### ISSUE TITLE
[1.12.2] Server crash when placing tile

### ISSUE THREAD

**Issue by SanAndreaP** [CreativeMD/LittleTiles#100]
Forge: 14.23.4.2739
CreativeCore: 1.9.9
LittleTiles: 1.5.0

Description:
Everytime I place a tile with the glove or a structure made with a recipe I get this error report crashing the server:
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at com.creativemd.littletiles.common.action.LittleAction.getIngredientsPreviews(LittleAction.java:710)
    at com.creativemd.littletiles.common.action.LittleAction.addTilesToInventoryOrDrop(LittleAction.java:719)
    at com.creativemd.littletiles.common.action.block.LittleActionPlaceRelative.placeTile(LittleActionPlaceRelative.java:194)
    at com.creativemd.littletiles.common.action.block.LittleActionPlaceRelative.action(LittleActionPlaceRelative.java:118)
    at com.creativemd.littletiles.common.action.LittleAction.executeServer(LittleAction.java:208)
    at com.creativemd.creativecore.common.packet.PacketReciever$2.run(PacketReciever.java:129)
```

Here's the crash log:
https://paste.dimdev.org/ugiqonucos.mccrash

Here's the latest.log:
https://gist.github.com/SanAndreasP/38eba114bd17b49723201b0457f0dcbf

**PS: I have VanillaFix installed, so I can keep playing even after such an error**

**Comment by CreativeMD** [comment]
Should be fixed in pre100, will be available soon. Make sure to update creativecore as well.

**Comment by SanAndreaP** [comment]
Thanks :)
