### ISSUE TITLE
Crash when closing door structure

### ISSUE THREAD

**Issue by SanAndreaP** [CreativeMD/LittleTiles#104]
Forge: 14.23.4.2739
CreativeCore: 1.9.25
LittleTiles: 1.5.0-pre100

Description:
I happen to get a crash when trying to closing one of my door structures:
```
java.lang.NullPointerException
    at com.creativemd.littletiles.common.entity.EntityAnimation.moveAndRotateAnimation(EntityAnimation.java:518)
    at com.creativemd.littletiles.common.entity.EntityAnimation.rotateAnimation(EntityAnimation.java:285)
    at com.creativemd.littletiles.common.entity.EntityAnimation.rotXTo(EntityAnimation.java:270)
    at com.creativemd.littletiles.common.utils.transformation.OrdinaryDoorTransformation.performTransformation(OrdinaryDoorTransformation.java:30)
    at com.creativemd.littletiles.common.entity.EntityDoorAnimation.onTick(EntityDoorAnimation.java:144)
    at com.creativemd.littletiles.common.entity.EntityAnimation.onUpdate(EntityAnimation.java:788)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1990)
    at net.minecraft.world.World.updateEntity(World.java:1952)
    at net.minecraft.world.World.redirect$updateEntity$zbk000(World.java:5114)
    at net.minecraft.world.World.updateEntities(World.java:1756)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1845)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1096)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3938)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Here's the crash log: https://paste.dimdev.org/iqarixilac.mccrash

And here's the latest.log: https://gist.githubusercontent.com/SanAndreasP/eb17f244dec0dde40e64f2b51f9c5980/raw/080b370baaf2dab5ff35a821498843897e28e0b9/latest.log

**Comment by CreativeMD** [comment]
Will be fixed in the upcoming version.

**Comment by CreativeMD** [comment]
New version is uploaded and should be available in a few minutes.
