### ISSUE TITLE
[1.21.1] Failed to process a synchronized task of the payload: creativecore:5c

### ISSUE THREAD

**Issue by Derek1256** [CreativeMD/LittleTiles#1041]
Very minor thing probably but thought id report it anyways as its every time any1 opens that menu.

doesnt crash or anything but does get quite annoying at times when you have to open it 30 times.

When opening the configure tool menu, console says this:
```
[18:50:42]` [Server thread/ERROR] [ne.ne.ne.ne.re.NetworkRegistry/]: Failed to process a synchronized task of the payload: creativecore:5c
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "team.creative.littletiles.common.placement.shape.ShapeSelection.countPositions()" because "team.creative.littletiles.common.item.ItemLittleChisel.selection" is null
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?] {re:mixin}
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?] {re:mixin}
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?] {}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.21.1-20240808.144430-srg.jar%23282!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:148) ~[server-1.21.1-20240808.144430-srg.jar%23282!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[server-1.21.1-20240808.144430-srg.jar%23282!/:?] {re:mixin,re:computing_frames,re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:872) ~[server-1.21.1-20240808.144430-srg.jar%23282!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin from mod modernfix,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:APP:kubejs.mixins.json:MinecraftServerMixin from mod kubejs,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin from mod ae2,pl:mixin:APP:littletiles.mixins.json:server.level.MinecraftServerAccessor from mod littletiles,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:170) ~[server-1.21.1-20240808.144430-srg.jar%23282!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin from mod modernfix,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:APP:kubejs.mixins.json:MinecraftServerMixin from mod kubejs,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin from mod ae2,pl:mixin:APP:littletiles.mixins.json:server.level.MinecraftServerAccessor from mod littletiles,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[server-1.21.1-20240808.144430-srg.jar%23282!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:855) ~[server-1.21.1-20240808.144430-srg.jar%23282!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin from mod modernfix,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:APP:kubejs.mixins.json:MinecraftServerMixin from mod kubejs,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin from mod ae2,pl:mixin:APP:littletiles.mixins.json:server.level.MinecraftServerAccessor from mod littletiles,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:849) ~[server-1.21.1-20240808.144430-srg.jar%23282!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin from mod modernfix,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:APP:kubejs.mixins.json:MinecraftServerMixin from mod kubejs,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin from mod ae2,pl:mixin:APP:littletiles.mixins.json:server.level.MinecraftServerAccessor from mod littletiles,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[server-1.21.1-20240808.144430-srg.jar%23282!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:821) ~[server-1.21.1-20240808.144430-srg.jar%23282!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin from mod modernfix,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:APP:kubejs.mixins.json:MinecraftServerMixin from mod kubejs,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin from mod ae2,pl:mixin:APP:littletiles.mixins.json:server.level.MinecraftServerAccessor from mod littletiles,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:826) ~[server-1.21.1-20240808.144430-srg.jar%23282!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin from mod modernfix,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:APP:kubejs.mixins.json:MinecraftServerMixin from mod kubejs,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin from mod ae2,pl:mixin:APP:littletiles.mixins.json:server.level.MinecraftServerAccessor from mod littletiles,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:712) ~[server-1.21.1-20240808.144430-srg.jar%23282!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin from mod modernfix,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:APP:kubejs.mixins.json:MinecraftServerMixin from mod kubejs,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin from mod ae2,pl:mixin:APP:littletiles.mixins.json:server.level.MinecraftServerAccessor from mod littletiles,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[server-1.21.1-20240808.144430-srg.jar%23282!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin from mod modernfix,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:APP:kubejs.mixins.json:MinecraftServerMixin from mod kubejs,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin from mod ae2,pl:mixin:APP:littletiles.mixins.json:server.level.MinecraftServerAccessor from mod littletiles,pl:mixin:A}
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {re:mixin}
Caused by: java.lang.NullPointerException: Cannot invoke "team.creative.littletiles.common.placement.shape.ShapeSelection.countPositions()" because "team.creative.littletiles.common.item.ItemLittleChisel.selection" is null
        at TRANSFORMER/littletiles@1.6.0-pre146/team.creative.littletiles.common.item.ItemLittleChisel.configured(ItemLittleChisel.java:202) ~[LittleTiles_ALPHA_v1.6.0-pre146_mc1.21.1.jar%23378!/:1.6.0-pre146] {re:classloading,pl:runtimedistcleaner:A}
        at TRANSFORMER/littletiles@1.6.0-pre146/team.creative.littletiles.common.gui.tool.GuiConfigure.lambda$new$0(GuiConfigure.java:15) ~[LittleTiles_ALPHA_v1.6.0-pre146_mc1.21.1.jar%23378!/:1.6.0-pre146] {re:classloading}
        at TRANSFORMER/creativecore@2.12.27/team.creative.creativecore.common.gui.sync.GuiSyncLocal.receive(GuiSyncLocal.java:22) ~[CreativeCore_NEOFORGE_v2.12.27_mc1.21.1.jar%23320!/:2.12.27] {re:classloading}
        at TRANSFORMER/creativecore@2.12.27/team.creative.creativecore.common.gui.sync.GuiSyncLocal.receive(GuiSyncLocal.java:11) ~[CreativeCore_NEOFORGE_v2.12.27_mc1.21.1.jar%23320!/:2.12.27] {re:classloading}
        at TRANSFORMER/creativecore@2.12.27/team.creative.creativecore.common.gui.packet.ControlSyncPacket.execute(ControlSyncPacket.java:30) ~[CreativeCore_NEOFORGE_v2.12.27_mc1.21.1.jar%23320!/:2.12.27] {re:classloading}
        at TRANSFORMER/creativecore@2.12.27/team.creative.creativecore.common.gui.packet.LayerPacket.executeServer(LayerPacket.java:24) ~[CreativeCore_NEOFORGE_v2.12.27_mc1.21.1.jar%23320!/:2.12.27] {re:classloading}
        at TRANSFORMER/creativecore@2.12.27/team.creative.creativecore.common.network.CreativePacket.execute(CreativePacket.java:17) ~[CreativeCore_NEOFORGE_v2.12.27_mc1.21.1.jar%23320!/:2.12.27] {re:classloading}
        at TRANSFORMER/creativecore@2.12.27/team.creative.creativecore.common.network.CreativeNetwork.lambda$registerType$0(CreativeNetwork.java:61) ~[CreativeCore_NEOFORGE_v2.12.27_mc1.21.1.jar%23320!/:2.12.27] {re:classloading}
        at TRANSFORMER/neoforge@21.1.90/net.neoforged.neoforge.network.handling.ServerPayloadContext.enqueueWork(ServerPayloadContext.java:32) ~[neoforge-21.1.90-universal.jar%23283!/:?] {re:classloading}
        at TRANSFORMER/creativecore@2.12.27/team.creative.creativecore.common.network.CreativeNetwork.lambda$registerType$1(CreativeNetwork.java:61) ~[CreativeCore_NEOFORGE_v2.12.27_mc1.21.1.jar%23320!/:2.12.27] {re:classloading}
        at TRANSFORMER/neoforge@21.1.90/net.neoforged.neoforge.network.handling.MainThreadPayloadHandler.lambda$handle$0(MainThreadPayloadHandler.java:16) ~[neoforge-21.1.90-universal.jar%23283!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:60) ~[server-1.21.1-20240808.144430-srg.jar%23282!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A}
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
        ... 14 more
```

**Comment by CreativeMD** [comment]
Fixed in the newest version.
