### ISSUE TITLE
Conflict with Minecolonies Pathfinding

### ISSUE THREAD

**Issue by WenXin20** [CreativeMD/LittleTiles#136]
**Forge** v14.23.5.2772-1.12.2
**Little Tiles** v1.5.0-pre122
**Creative Core** v1.9.35
**Minecolonies** v0.10.43-Alpha

#### Actual behaviour
- Colonists repeatedly run into pathing exceptions that can be seen in the log. The error in the logs seems to be related to this mod, although there were no Little Tiles blocks in the area.

- **Error Log** (This repeats until the build is canceled):
`
[08:37:20] [pool-13-thread-1/WARN]: Pathfinding Exception
java.lang.NullPointerException: null
	at com.creativemd.littletiles.common.blocks.BlockTile.isLadder(BlockTile.java:280) ~[BlockTile.class:?]
	at com.minecolonies.coremod.entity.pathfinding.AbstractPathJob.isLadder(AbstractPathJob.java:1015) ~[AbstractPathJob.class:?]
	at com.minecolonies.coremod.entity.pathfinding.AbstractPathJob.isLadder(AbstractPathJob.java:1020) ~[AbstractPathJob.class:?]
	at com.minecolonies.coremod.entity.pathfinding.AbstractPathJob.onLadderGoingDown(AbstractPathJob.java:510) ~[AbstractPathJob.class:?]
	at com.minecolonies.coremod.entity.pathfinding.AbstractPathJob.walkCurrentNode(AbstractPathJob.java:478) ~[AbstractPathJob.class:?]
	at com.minecolonies.coremod.entity.pathfinding.AbstractPathJob.search(AbstractPathJob.java:424) ~[AbstractPathJob.class:?]
	at com.minecolonies.coremod.entity.pathfinding.AbstractPathJob.call(AbstractPathJob.java:364) ~[AbstractPathJob.class:?]
	at com.minecolonies.coremod.entity.pathfinding.AbstractPathJob.call(AbstractPathJob.java:33) ~[AbstractPathJob.class:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
`

Also reported at ldtteam/minecolonies#3067

**Comment by CreativeMD** [comment]
I fixed it. There is either no entity or no bounding box for the entity, which caused this crash. It will be part of the upcoming pre-release, but unfortunately this may take some more time till its release. I hope this is not a major issue?

**Comment by WenXin20** [comment]
It's not a problem, and thanks!

**Comment by CreativeMD** [comment]
pre123 has been released
