### ISSUE TITLE
Server Creation Exception with OakNet-Link

### ISSUE THREAD

**Issue by WenXin20** [CreativeMD/LittleTiles#198]
Minecraft v1.12.2
Forge v14.23.5.2838
Little Tiles v1.5.0-pre146
Creative Core v1.9.52
[OakNet-Link](https://www.curseforge.com/minecraft/mc-mods/oaknetlink) v1.7.1

I get the following error with OakNet-Link whenever I try to create a server.
Here's the[ full log](https://gist.github.com/WenXin20/864917ad70214bd3f18a5cb0e49e22c4). In the previous version, pre135, I didn't get this error.

**Comment by CreativeMD** [comment]
This does not look like an issue of LT, Looks like millenaire is having some problems. I will close the issue for now, if you are sure it's LT just reopen the issue again.

**Comment by WenXin20** [comment]
I believe that you were viewing the truncated version of the file, the exception with LittleTiles is at the end, hidden by Gist.

**Comment by CreativeMD** [comment]
Can you send me the exception (can't find it)?

**Comment by WenXin20** [comment]
Here's the error:
```
[09:34:08] [Thread-27/INFO]: Minecraft Server: [09:34:08] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in LittleTiles_v1.5.0-pre146_mc1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[09:34:08] [Thread-27/INFO]: Minecraft Server: [09:34:08] [main/WARN] [FML]: The coremod com.creativemd.littletiles.LittlePatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[09:34:08] [Thread-27/INFO]: Minecraft Server: [09:34:08] [main/WARN] [FML]: The coremod LittlePatchingLoader (com.creativemd.littletiles.LittlePatchingLoader) is not signed!
[09:34:08] [Thread-27/INFO]: Minecraft Server: [09:34:08] [main/ERROR] [LaunchWrapper]: Unable to launch
[09:34:08] [Thread-27/INFO]: Minecraft Server: java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at C:\Users\newvi\Desktop\Curse\Minecraft\Instances\Cinnamon Pack 2\OakNetLinkServer\. for Forge Mod Loader
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:111) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupServer(FMLLaunchHandler.java:87) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForServerLaunch(FMLLaunchHandler.java:47) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraftforge.fml.common.launcher.FMLServerTweaker.injectIntoClassLoader(FMLServerTweaker.java:62) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70) [forge-1.12.2-14.23.5.2838-universal.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34) [forge-1.12.2-14.23.5.2838-universal.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: Caused by: java.lang.NoClassDefFoundError: com/creativemd/littletiles/LittleTilesAfterTransformer
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at com.creativemd.littletiles.LittlePatchingLoader.getAccessTransformerClass(LittlePatchingLoader.java:39) ~[LittleTiles_v1.5.0-pre146_mc1.12.2.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:595) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	... 11 more
[09:34:08] [Thread-27/INFO]: Minecraft Server: Caused by: java.lang.ClassNotFoundException: com.creativemd.littletiles.LittleTilesAfterTransformer
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at com.creativemd.littletiles.LittlePatchingLoader.getAccessTransformerClass(LittlePatchingLoader.java:39) ~[LittleTiles_v1.5.0-pre146_mc1.12.2.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:595) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	... 11 more
[09:34:08] [Thread-27/INFO]: Minecraft Server: Caused by: java.lang.NoClassDefFoundError: com/creativemd/creativecore/transformer/CreativeTransformer
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_51]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_51]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_51]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at com.creativemd.littletiles.LittlePatchingLoader.getAccessTransformerClass(LittlePatchingLoader.java:39) ~[LittleTiles_v1.5.0-pre146_mc1.12.2.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:595) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	... 11 more
[09:34:08] [Thread-27/INFO]: Minecraft Server: Caused by: java.lang.ClassNotFoundException: com.creativemd.creativecore.transformer.CreativeTransformer
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_51]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_51]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_51]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at com.creativemd.littletiles.LittlePatchingLoader.getAccessTransformerClass(LittlePatchingLoader.java:39) ~[LittleTiles_v1.5.0-pre146_mc1.12.2.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:595) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	... 11 more
[09:34:08] [Thread-27/INFO]: Minecraft Server: Caused by: java.lang.NullPointerException
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_51]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_51]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_51]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at com.creativemd.littletiles.LittlePatchingLoader.getAccessTransformerClass(LittlePatchingLoader.java:39) ~[LittleTiles_v1.5.0-pre146_mc1.12.2.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:595) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
[09:34:08] [Thread-27/INFO]: Minecraft Server: 	... 11 more
[09:34:08] [Thread-27/INFO]: Minecraft Server: [09:34:08] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: java.lang.reflect.InvocationTargetException
[09:34:08] [Thread-27/INFO]: Minecraft Server: [09:34:08] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:34:08] [Thread-27/INFO]: Minecraft Server: [09:34:08] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:34:08] [Thread-27/INFO]: Minecraft Server: [09:34:08] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:34:08] [Thread-27/INFO]: Minecraft Server: [09:34:08] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[09:34:08] [Thread-27/INFO]: Minecraft Server: [09:34:08] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
[09:34:08] [Thread-27/INFO]: Minecraft Server: [09:34:08] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
[09:34:08] [Thread-27/INFO]: Minecraft Server: [09:34:08] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[09:34:08] [Thread-27/INFO]: Minecraft Server: [09:34:08] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[09:34:08] [Thread-27/INFO]: Minecraft Server: [09:34:08] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[09:34:08] [Thread-27/INFO]: Minecraft Server: [09:34:08] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at java.lang.Runtime.exit(Runtime.java:107)
[09:34:08] [Thread-27/INFO]: Minecraft Server: [09:34:08] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at java.lang.System.exit(System.java:971)
[09:34:08] [Thread-27/INFO]: Minecraft Server: [09:34:08] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[09:34:08] [Thread-27/INFO]: Minecraft Server: [09:34:08] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[09:34:08] [Thread-27/INFO]: Minecraft Server: [09:34:08] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	... 6 more
[09:34:08] [Thread-28/ERROR]: Minecraft Server: A problem occurred running the Server launcher.
[09:34:09] [Client thread/ERROR]: Server is unable to start. Check your log and try again!
[09:58:18] [NetworkThread/ERROR]: Disconected from MasterServer: End of Stream
[09:58:20] [Ping Thread/ERROR]: Failed connection, disconnecting.3
[09:58:21] [Ping Thread/INFO]: [de.oaknetwork.OakNetLink.network.ClientHandler:sendPacketBack:169]: java.net.SocketException: Software caused connection abort: socket write error
[09:58:21] [Ping Thread/INFO]: [de.oaknetwork.OakNetLink.network.ClientHandler:sendPacketBack:169]: 	at java.net.SocketOutputStream.socketWrite0(Native Method)
[09:58:21] [Ping Thread/INFO]: [de.oaknetwork.OakNetLink.network.ClientHandler:sendPacketBack:169]: 	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
[09:58:21] [Ping Thread/INFO]: [de.oaknetwork.OakNetLink.network.ClientHandler:sendPacketBack:169]: 	at java.net.SocketOutputStream.write(SocketOutputStream.java:141)
[09:58:21] [Ping Thread/INFO]: [de.oaknetwork.OakNetLink.network.ClientHandler:sendPacketBack:169]: 	at de.oaknetwork.OakNetLink.network.ClientHandler.sendPacketBack(ClientHandler.java:165)
[09:58:21] [Ping Thread/INFO]: [de.oaknetwork.OakNetLink.network.ClientHandler:sendPacketBack:169]: 	at de.oaknetwork.OakNetLink.network.out.PacketOut.handlePacket(PacketOut.java:29)
[09:58:21] [Ping Thread/INFO]: [de.oaknetwork.OakNetLink.network.ClientHandler:sendPacketBack:169]: 	at de.oaknetwork.OakNetLink.network.out.PingPacketOut.handlePacket(PingPacketOut.java:15)
[09:58:21] [Ping Thread/INFO]: [de.oaknetwork.OakNetLink.network.ClientHandler:sendPacketBack:169]: 	at de.oaknetwork.OakNetLink.network.out.PacketOut.<init>(PacketOut.java:17)
[09:58:21] [Ping Thread/INFO]: [de.oaknetwork.OakNetLink.network.ClientHandler:sendPacketBack:169]: 	at de.oaknetwork.OakNetLink.network.out.PingPacketOut.<init>(PingPacketOut.java:8)
[09:58:21] [Ping Thread/INFO]: [de.oaknetwork.OakNetLink.network.ClientHandler:sendPacketBack:169]: 	at de.oaknetwork.OakNetLink.network.in.HandShakePacketIn$1.run(HandShakePacketIn.java:23)
[09:58:21] [Ping Thread/INFO]: [de.oaknetwork.OakNetLink.network.ClientHandler:sendPacketBack:169]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by CreativeMD** [comment]
This crash suggests that you forgot to install CreativeCore.

**Comment by WenXin20** [comment]
That's weird. I definitely have it installed. My single player world works fine.

**Comment by CreativeMD** [comment]
Maybe it's the wrong log file?

**Comment by WenXin20** [comment]
It's definitely the right one...

**Comment by CreativeMD** [comment]
Then you are definitely missing CreativeCore.

**Comment by WenXin20** [comment]
Maybe it's not being detected by the OakNet mod? Because I'm using the same instance for my single player world right now, which is working fine. I just tested it this morning, the server wouldn't start, so I continued on my single player world instead.

**Comment by WenXin20** [comment]
I'll try again though to make sure.

**Comment by WenXin20** [comment]
Nevermind, I just checked it again and it looks like I had somehow accidentally disabled it serverside... -_-
Thanks for the help though!

**Comment by CreativeMD** [comment]
No problem :D glad it is solved now!
