### ISSUE TITLE
Client log spam with v1.5.0-pre151

### ISSUE THREAD

**Issue by LemADEC** [CreativeMD/LittleTiles#215]
As of LittleTiles_v1.5.0-pre151_mc1.12.2 + CreativeCore_v1.9.55_mc1.12.2, a console spam is observed causing lots of client lag and what looks like a memory leak.
Upon inspection, latest.log reached 3.5GB within 6 mn.
We didn't place any little tiles, but we did use simple little tiles items for testing a duplication bug with Mechanism logistical pipes.

```
[01:55:11] [Thread-23/INFO] [STDERR]: [com.creativemd.littletiles.client.render.RenderingThread:run:330]: java.lang.RuntimeException: Could not create ambient occlusion face!
[01:55:11] [Thread-23/INFO] [STDERR]: [com.creativemd.littletiles.client.render.RenderingThread:run:330]: 	at com.creativemd.creativecore.client.rendering.model.CreativeModelPipeline.createAmbientOcclusionFace(CreativeModelPipeline.java:73)
[01:55:11] [Thread-23/INFO] [STDERR]: [com.creativemd.littletiles.client.render.RenderingThread:run:330]: 	at com.creativemd.littletiles.client.render.RenderingThread.run(RenderingThread.java:267)
[01:55:11] [Thread-24/INFO] [STDERR]: [com.creativemd.creativecore.client.rendering.model.CreativeModelPipeline:createAmbientOcclusionFace:71]: java.lang.IllegalAccessException: Class com.creativemd.creativecore.client.rendering.model.CreativeModelPipeline can not access a member of class net.minecraft.client.renderer.BlockModelRenderer$AmbientOcclusionFace with modifiers "public"
[01:55:11] [Thread-24/INFO] [STDERR]: [com.creativemd.creativecore.client.rendering.model.CreativeModelPipeline:createAmbientOcclusionFace:71]: 	at sun.reflect.Reflection.ensureMemberAccess(Unknown Source)
[01:55:11] [Thread-24/INFO] [STDERR]: [com.creativemd.creativecore.client.rendering.model.CreativeModelPipeline:createAmbientOcclusionFace:71]: 	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(Unknown Source)
[01:55:11] [Thread-24/INFO] [STDERR]: [com.creativemd.creativecore.client.rendering.model.CreativeModelPipeline:createAmbientOcclusionFace:71]: 	at java.lang.reflect.AccessibleObject.checkAccess(Unknown Source)
[01:55:11] [Thread-24/INFO] [STDERR]: [com.creativemd.creativecore.client.rendering.model.CreativeModelPipeline:createAmbientOcclusionFace:71]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[01:55:11] [Thread-24/INFO] [STDERR]: [com.creativemd.creativecore.client.rendering.model.CreativeModelPipeline:createAmbientOcclusionFace:71]: 	at com.creativemd.creativecore.client.rendering.model.CreativeModelPipeline.createAmbientOcclusionFace(CreativeModelPipeline.java:69)
[01:55:11] [Thread-24/INFO] [STDERR]: [com.creativemd.creativecore.client.rendering.model.CreativeModelPipeline:createAmbientOcclusionFace:71]: 	at com.creativemd.littletiles.client.render.RenderingThread.run(RenderingThread.java:267)
```

**Comment by CreativeMD** [comment]
Fixed in the newest pre-released.
