### ISSUE TITLE
Crash when changing dimensions.

### ISSUE THREAD

**Issue by TheRealGammer** [CreativeMD/LittleTiles#218]
Whenever I change dimensions it doesn't show up, but when I save and quit it crashes. I see in the crash report it's because little tiles is reluctant to unload the world. There's a null pointer on an even meaning you gave it the even but never populated it. This, along with the crash report is all the info I can give:

java.lang.NullPointerException: Updating screen events
	at com.creativemd.littletiles.common.events.LittleEvent.worldUnload(LittleEvent.java:300)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_70_LittleEvent_worldUnload_Unload.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2435)
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2430)
	at net.minecraft.client.gui.GuiIngameMenu.func_146284_a(GuiIngameMenu.java:52)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by TheRealGammer** [comment]
fyi when I rejoin the world after the crash, I pop back up in the correct dimension.

**Comment by CreativeMD** [comment]
Fixed in the newest pre-released.
