### ISSUE TITLE
Rotation support broken with pre155

### ISSUE THREAD

**Issue by LemADEC** [CreativeMD/LittleTiles#221]
As of LittleTiles_v1.5.0-pre155_mc1.12.2 + CreativeCore_v1.9.59_mc1.12.2 + WarpDrive-1.12.2-1.5.5.jar, an NPE is observed in the WarpDrive compatibility module:
```
[22:33:12] [Server thread/INFO] [STDERR]: [com.creativemd.littletiles.common.tiles.LittleTile:CreateandLoadTile:123]: java.lang.NullPointerException
[22:33:12] [Server thread/INFO] [STDERR]: [com.creativemd.littletiles.common.tiles.LittleTile:CreateandLoadTile:123]: 	at com.creativemd.creativecore.common.tileentity.TileEntityCreative.isClientSide(TileEntityCreative.java:20)
[22:33:12] [Server thread/INFO] [STDERR]: [com.creativemd.littletiles.common.tiles.LittleTile:CreateandLoadTile:123]: 	at com.creativemd.littletiles.common.tiles.LittleTileBlock.loadTileExtra(LittleTileBlock.java:146)
[22:33:12] [Server thread/INFO] [STDERR]: [com.creativemd.littletiles.common.tiles.LittleTile:CreateandLoadTile:123]: 	at com.creativemd.littletiles.common.tiles.LittleTileBlockColored.loadTileExtra(LittleTileBlockColored.java:69)
[22:33:12] [Server thread/INFO] [STDERR]: [com.creativemd.littletiles.common.tiles.LittleTile:CreateandLoadTile:123]: 	at com.creativemd.littletiles.common.tiles.LittleTile.loadTile(LittleTile.java:473)
[22:33:12] [Server thread/INFO] [STDERR]: [com.creativemd.littletiles.common.tiles.LittleTile:CreateandLoadTile:123]: 	at com.creativemd.littletiles.common.tiles.LittleTile.CreateandLoadTile(LittleTile.java:121)
[22:33:12] [Server thread/INFO] [STDERR]: [com.creativemd.littletiles.common.tiles.LittleTile:CreateandLoadTile:123]: 	at com.creativemd.littletiles.common.utils.compression.LittleNBTCompressionTools.readTiles(LittleNBTCompressionTools.java:77)
[22:33:12] [Server thread/INFO] [STDERR]: [com.creativemd.littletiles.common.tiles.LittleTile:CreateandLoadTile:123]: 	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.func_145839_a(TileEntityLittleTiles.java:668)
[22:33:12] [Server thread/INFO] [STDERR]: [com.creativemd.littletiles.common.tiles.LittleTile:CreateandLoadTile:123]: 	at com.creativemd.littletiles.common.mods.warpdrive.TileEntityLittleTilesTransformer.rotate(TileEntityLittleTilesTransformer.java:140)
[22:33:12] [Server thread/INFO] [STDERR]: [com.creativemd.littletiles.common.tiles.LittleTile:CreateandLoadTile:123]: 	at cr0s.warpdrive.data.JumpBlock.deploy(JumpBlock.java:296)
[22:33:12] [Server thread/INFO] [STDERR]: [com.creativemd.littletiles.common.tiles.LittleTile:CreateandLoadTile:123]: 	at cr0s.warpdrive.event.JumpSequencer.state_moveBlocks(JumpSequencer.java:1048)
[22:33:12] [Server thread/INFO] [STDERR]: [com.creativemd.littletiles.common.tiles.LittleTile:CreateandLoadTile:123]: 	at cr0s.warpdrive.event.JumpSequencer.onUpdate(JumpSequencer.java:319)
[22:33:12] [Server thread/INFO] [STDERR]: [com.creativemd.littletiles.common.tiles.LittleTile:CreateandLoadTile:123]: 	at cr0s.warpdrive.event.AbstractSequencer.updateTick(AbstractSequencer.java:24)
[22:33:12] [Server thread/INFO] [STDERR]: [com.creativemd.littletiles.common.tiles.LittleTile:CreateandLoadTile:123]: 	at cr0s.warpdrive.event.WorldHandler.onServerTick(WorldHandler.java:121)
[22:33:12] [Server thread/INFO] [STDERR]: [com.creativemd.littletiles.common.tiles.LittleTile:CreateandLoadTile:123]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_99_WorldHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
[22:33:12] [Server thread/INFO] [STDERR]: [com.creativemd.littletiles.common.tiles.LittleTile:CreateandLoadTile:123]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[22:33:12] [Server thread/INFO] [STDERR]: [com.creativemd.littletiles.common.tiles.LittleTile:CreateandLoadTile:123]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
[22:33:12] [Server thread/INFO] [STDERR]: [com.creativemd.littletiles.common.tiles.LittleTile:CreateandLoadTile:123]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
[22:33:12] [Server thread/INFO] [STDERR]: [com.creativemd.littletiles.common.tiles.LittleTile:CreateandLoadTile:123]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
[22:33:12] [Server thread/INFO] [STDERR]: [com.creativemd.littletiles.common.tiles.LittleTile:CreateandLoadTile:123]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
[22:33:12] [Server thread/INFO] [STDERR]: [com.creativemd.littletiles.common.tiles.LittleTile:CreateandLoadTile:123]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[22:33:12] [Server thread/INFO] [STDERR]: [com.creativemd.littletiles.common.tiles.LittleTile:CreateandLoadTile:123]: 	at java.lang.Thread.run(Unknown Source)
```

Issue isn't reproduced with CreativeCore_v1.9.58_mc1.12.2 + LittleTiles_v1.5.0-pre154_mc1.12.2.

**Comment by CreativeMD** [comment]
Does this version fixes it?
https://www.dropbox.com/s/mvgx1af2ntz28oj/LittleTiles_v1.5.0-pre156_mc1.12.2.jar?dl=1

**Comment by LemADEC** [comment]
Tested ok with CreativeCore_v1.9.59_mc1.12.2.

**Comment by CreativeMD** [comment]
It's released now.
