### ISSUE TITLE
NPE server side in CreativeCorePacket:writePacket

### ISSUE THREAD

**Issue by LemADEC** [CreativeMD/LittleTiles#235]
As of CreativeCore_v1.9.62_mc1.12.2 + LittleTiles_v1.5.0-pre158_mc1.12.2, NPE is reported intermittently in console, not sure what's triggering it.

```
05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]: java.lang.NullPointerException
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at com.creativemd.creativecore.common.packet.CreativeCorePacket.writePacket(CreativeCorePacket.java:157)
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at com.creativemd.littletiles.common.packet.LittleBlocksUpdatePacket.writeBytes(LittleBlocksUpdatePacket.java:55)
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at com.creativemd.creativecore.common.packet.CreativeMessageHandler.toBytes(CreativeMessageHandler.java:62)
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:30)
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:26)
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:81)
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67)
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88)
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032)
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296)
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250)
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at com.creativemd.creativecore.common.packet.PacketHandler.sendPacketToPlayer(PacketHandler.java:76)
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at com.creativemd.littletiles.common.action.LittleAction.sendBlockResetToClient(LittleAction.java:321)
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at com.creativemd.littletiles.common.action.LittleAction.sendBlockResetToClient(LittleAction.java:325)
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at com.creativemd.littletiles.common.packet.LittleDoorPacket.executeServer(LittleDoorPacket.java:104)
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at com.creativemd.creativecore.common.packet.PacketReciever$2.run(PacketReciever.java:115)
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at net.minecraft.util.Util.func_181617_a(SourceFile:46)
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:307)
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at net.minecraft.server.MinecraftServer.redirect$onRun$zjl000(MinecraftServer.java:4715)
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[05:52:39] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at java.lang.Thread.run(Thread.java:748)
...
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]: java.lang.NullPointerException
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at com.creativemd.creativecore.common.packet.CreativeCorePacket.writePacket(CreativeCorePacket.java:157)
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at com.creativemd.littletiles.common.packet.LittleBlocksUpdatePacket.writeBytes(LittleBlocksUpdatePacket.java:55)
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at com.creativemd.creativecore.common.packet.CreativeMessageHandler.toBytes(CreativeMessageHandler.java:62)
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:30)
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:26)
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:81)
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67)
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88)
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032)
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296)
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250)
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at com.creativemd.creativecore.common.packet.PacketHandler.sendPacketToPlayer(PacketHandler.java:76)
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at com.creativemd.littletiles.common.action.LittleAction.sendBlockResetToClient(LittleAction.java:321)
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at com.creativemd.littletiles.common.action.LittleAction.sendBlockResetToClient(LittleAction.java:325)
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at com.creativemd.littletiles.common.packet.LittleDoorPacket.executeServer(LittleDoorPacket.java:104)
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at com.creativemd.creativecore.common.packet.PacketReciever$2.run(PacketReciever.java:115)
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at net.minecraft.util.Util.func_181617_a(SourceFile:46)
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:307)
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at net.minecraft.server.MinecraftServer.redirect$onRun$zjl000(MinecraftServer.java:4715)
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[05:59:18] [Server thread/INFO] [STDERR]: [com.creativemd.creativecore.common.packet.CreativeCorePacket:writePacket:160]:       at java.lang.Thread.run(Thread.java:748)
```

**Comment by CreativeMD** [comment]
Will be fixed in the upcoming version.

**Comment by CreativeMD** [comment]
It's finally out!
