### ISSUE TITLE
Crash when Activating Door After Changing Recipe

### ISSUE THREAD

**Issue by FoxMcloud5655** [CreativeMD/LittleTiles#252]
In a single player world, I wanted to change how my double door recipe worked.  After changing an Advanced Recipe from Door Activator to None, I placed down the double doors contained within the recipe and attempted to activate a single door.  Unfortunately, this resulted in a crash.

Activating the door again after the world recovered from the crash resulted in the same thing happening.

Relevant part of the crash log:
```
java.lang.NullPointerException
    at com.creativemd.littletiles.common.structure.type.door.LittleDoor.activate(LittleDoor.java:62)
    at com.creativemd.littletiles.common.structure.type.door.LittleDoor.onBlockActivated(LittleDoor.java:84)
    at com.creativemd.littletiles.common.tiles.LittleTile.onBlockActivated(LittleTile.java:704)
    at com.creativemd.littletiles.common.tiles.LittleTileBlock.onBlockActivated(LittleTileBlock.java:246)
    at com.creativemd.littletiles.common.action.block.LittleActionActivated.action(LittleActionActivated.java:44)
    at com.creativemd.littletiles.common.action.LittleActionInteract.action(LittleActionInteract.java:109)
    at com.creativemd.littletiles.common.action.block.LittleActionActivated.action(LittleActionActivated.java:55)
    at com.creativemd.littletiles.common.action.LittleAction.execute(LittleAction.java:186)
    at com.creativemd.littletiles.common.blocks.BlockTile.onBlockActivatedClient(BlockTile.java:396)
    at com.creativemd.littletiles.common.blocks.BlockTile.onBlockActivated(BlockTile.java:388)
    at net.minecraft.client.multiplayer.PlayerControllerMP.processRightClickBlock(PlayerControllerMP.java:423)
    at net.minecraft.client.Minecraft.rightClickMouse(Minecraft.java:1579)
```

**Comment by CreativeMD** [comment]
This will be fixed in the upcoming pre-release. A none structure cannot have any children which will cause the crash. So if you set your recipe to none it will automatically (now) set the children to none as well.

**Comment by FoxMcloud5655** [comment]
Perfect.  That would allow users to edit structures after creation.  Thanks for the update!

**Comment by CreativeMD** [comment]
Finally it's out!
