### ISSUE TITLE
Game crash when placing tiles in survival

### ISSUE THREAD

**Issue by aprusik** [CreativeMD/LittleTiles#259]
**Summary**
When placing tiles in survival, the game crashes.

**Steps to reproduce**
1. Get a bag and put some blocks in it.
2. Attempt to place tiles with chisel.
3. Crash

**Other Relevant Mods Installed**
- Optifine

**Version**
LittleTiles 1.5.0-pre161
Creative Core 1.9.66

**Comments**
Using version 1.5.0-pre158 I do not encounter this issue.
Many actions in survival crash the game, not just placing tiles.
Crafting new objects in the bench also crashes the game.  None of these crashes occur in creative mode.

**Crash Log**
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore_v1.9.66_mc1.12.2.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre161_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 9/29/19 8:55 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.creativemd.littletiles.common.utils.ingredients.LittleIngredient.indexOf(LittleIngredient.java:34)
	at com.creativemd.littletiles.common.utils.ingredients.LittleIngredients.set(LittleIngredients.java:40)
	at com.creativemd.littletiles.common.utils.ingredients.LittleInventory.take(LittleInventory.java:164)
	at com.creativemd.littletiles.common.action.LittleAction.canTake(LittleAction.java:570)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.placeTile(LittleActionPlaceStack.java:167)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.action(LittleActionPlaceStack.java:117)
	at com.creativemd.littletiles.common.action.LittleAction.execute(LittleAction.java:183)
	at com.creativemd.littletiles.common.events.LittleEvent.onRightInteractClient(LittleEvent.java:322)
	at com.creativemd.littletiles.common.events.LittleEvent.onInteract(LittleEvent.java:274)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_24_LittleEvent_onInteract_RightClickBlock.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1137)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:398)
	at net.optifine.override.PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.creativemd.littletiles.common.utils.ingredients.LittleIngredient.indexOf(LittleIngredient.java:34)
	at com.creativemd.littletiles.common.utils.ingredients.LittleIngredients.set(LittleIngredients.java:40)
	at com.creativemd.littletiles.common.utils.ingredients.LittleInventory.take(LittleInventory.java:164)
	at com.creativemd.littletiles.common.action.LittleAction.canTake(LittleAction.java:570)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.placeTile(LittleActionPlaceStack.java:167)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.action(LittleActionPlaceStack.java:117)
	at com.creativemd.littletiles.common.action.LittleAction.execute(LittleAction.java:183)
	at com.creativemd.littletiles.common.events.LittleEvent.onRightInteractClient(LittleEvent.java:322)
	at com.creativemd.littletiles.common.events.LittleEvent.onInteract(LittleEvent.java:274)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_24_LittleEvent_onInteract_RightClickBlock.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1137)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:398)
	at net.optifine.override.PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['sageface55'/68, l='MpServer', x=-327.09, y=4.00, z=-718.29]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-325,4,-717), Chunk: (at 11,0,3 in -21,-45; contains blocks -336,0,-720 to -321,255,-705), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Level time: 8367 game time, 8367 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 31 total; [EntityChicken['Chicken'/0, l='MpServer', x=-402.92, y=4.00, z=-752.79], EntityHorse['Horse'/1, l='MpServer', x=-401.94, y=4.00, z=-761.85], EntityChicken['Chicken'/2, l='MpServer', x=-403.50, y=4.00, z=-747.50], EntitySheep['Sheep'/3, l='MpServer', x=-402.35, y=4.00, z=-705.21], EntitySheep['Sheep'/4, l='MpServer', x=-401.50, y=4.00, z=-690.50], EntityHorse['Horse'/5, l='MpServer', x=-386.50, y=4.00, z=-750.50], EntitySheep['Sheep'/6, l='MpServer', x=-393.80, y=4.00, z=-750.44], EntitySheep['Sheep'/7, l='MpServer', x=-390.37, y=4.00, z=-753.25], EntitySheep['Sheep'/8, l='MpServer', x=-394.60, y=4.00, z=-692.74], EntitySheep['Sheep'/9, l='MpServer', x=-397.50, y=4.00, z=-695.50], EntityHorse['Horse'/10, l='MpServer', x=-382.50, y=4.00, z=-746.50], EntityHorse['Horse'/11, l='MpServer', x=-381.50, y=4.00, z=-750.50], EntityPlayerSP['sageface55'/68, l='MpServer', x=-327.09, y=4.00, z=-718.29], EntityCow['Cow'/16, l='MpServer', x=-353.55, y=4.00, z=-765.36], EntityHorse['Horse'/17, l='MpServer', x=-356.50, y=4.00, z=-761.50], EntityHorse['Horse'/18, l='MpServer', x=-365.34, y=4.00, z=-766.34], EntitySheep['Sheep'/19, l='MpServer', x=-359.50, y=4.00, z=-758.50], EntityHorse['Horse'/20, l='MpServer', x=-348.04, y=4.00, z=-752.87], EntityPig['Pig'/21, l='MpServer', x=-325.26, y=4.00, z=-659.39], EntitySheep['Sheep'/22, l='MpServer', x=-310.50, y=4.00, z=-656.50], EntityPig['Pig'/23, l='MpServer', x=-316.19, y=4.00, z=-661.47], EntitySheep['Sheep'/24, l='MpServer', x=-301.77, y=4.00, z=-649.69], EntityCow['Cow'/25, l='MpServer', x=-264.14, y=4.00, z=-727.14], EntityCow['Cow'/26, l='MpServer', x=-266.19, y=4.00, z=-676.50], EntityCow['Cow'/27, l='MpServer', x=-260.15, y=4.00, z=-680.43], EntitySheep['Sheep'/28, l='MpServer', x=-265.50, y=4.00, z=-674.50], EntityPig['Pig'/29, l='MpServer', x=-260.54, y=4.00, z=-660.74], EntitySheep['Sheep'/30, l='MpServer', x=-255.50, y=4.00, z=-737.50], EntityPig['Pig'/32, l='MpServer', x=-247.17, y=4.00, z=-736.83], EntitySheep['Sheep'/34, l='MpServer', x=-253.73, y=4.00, z=-740.58], EntitySheep['Sheep'/35, l='MpServer', x=-251.65, y=4.00, z=-730.83]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1043209008 bytes (994 MB) / 1617952768 bytes (1543 MB) up to 7397179392 bytes (7054 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7936m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_E3 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version      | Source                                 | Signature |
	|:------ |:----------------- |:------------ |:-------------------------------------- |:--------- |
	| LCHIJA | minecraft         | 1.12.2       | minecraft.jar                          | None      |
	| LCHIJA | mcp               | 9.42         | minecraft.jar                          | None      |
	| LCHIJA | FML               | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar          | None      |
	| LCHIJA | forge             | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar          | None      |
	| LCHIJA | creativecoredummy | 1.0.0        | minecraft.jar                          | None      |
	| LCHIJA | littletilescore   | 1.0.0        | minecraft.jar                          | None      |
	| LCHIJA | creativecore      | 1.9.9        | CreativeCore_v1.9.66_mc1.12.2.jar      | None      |
	| LCHIJA | littletiles       | 1.5.0        | LittleTiles_v1.5.0-pre161_mc1.12.2.jar | None      |
	| LCHIJA | mineshot          | v1.71-1.12   | Mineshot-v1.71-1.12.jar                | None      |

	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore_v1.9.66_mc1.12.2.jar)
  
LittlePatchingLoader (LittleTiles_v1.5.0-pre161_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 436.30' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
	Launched Version: forge-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 436.30, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 1.14Bop+Quark.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL+v7.1.03.2.zip
	OpenGlVersion: 4.6.0 NVIDIA 436.30
	OpenGlRenderer: GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

**Comment by tolerus** [comment]
Also having this issue; many actions in survival causing crash. This one from using the little glove in replace mode but crash only occurs in survival

[https://paste.dimdev.org/razahopane.mccrash](url)

This mod is such a gamechanger!! :) Keep up the great work!

**Comment by CreativeMD** [comment]
Is fixed in the newest version. Thanks for reporting this issue!
