### ISSUE TITLE
NPE Batching chunks when disconnecting from server

### ISSUE THREAD

**Issue by LemADEC** [CreativeMD/LittleTiles#263]
As of LittleTiles_v1.5.0-pre158_mc1.12.2 + CreativeCore_v1.9.62_mc1.12.2, a client crash was observed when quickly disconnecting after connecting to a dedicated server in an area with little tiles.
```
java.lang.NullPointerException: Batching chunks
	at com.creativemd.littletiles.client.render.LittleChunkDispatcher.func_188245_a(LittleChunkDispatcher.java:166)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:126)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
	at java.lang.Thread.run(Thread.java:745)
```

https://gist.github.com/LemADEC/0eee8bd51f78806ac52c3a07c3313e1b

**Comment by CreativeMD** [comment]
Can you try out the new LT and CC versions and see if it still happens?

**Comment by CreativeMD** [comment]
I will close this issue for now. As it should be fixed anyway, otherwise reopen this issue.

**Comment by LemADEC** [comment]
Can't reproduce it anymore with CreativeCore_v1.9.68_mc1.12.2 + LittleTiles_v1.5.0-pre168_mc1.12.2.

**Comment by CreativeMD** [comment]
Good to hear that!
