### ISSUE TITLE
My Minecraft crashes when i try to place down the workbench

### ISSUE THREAD

**Issue by Monkey421** [CreativeMD/LittleTiles#301]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LittleLatePatchingLoader (LittleTilesCore-v1.0.0.jar)
  CreativePatchingLoader (CreativeCore_v1.9.74_mc1.12.2.jar)
  LittlePatchingLoader (LittleTiles-Mod-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 12/2/19 4:55 PM
Description: Unexpected error

java.lang.NoClassDefFoundError: Could not initialize class com.creativemd.littletiles.client.render.RenderingThread
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.addToRenderUpdate(TileEntityLittleTiles.java:388)
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.updateCustomRenderer(TileEntityLittleTiles.java:365)
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.updateTiles(TileEntityLittleTiles.java:351)
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.combineTiles(TileEntityLittleTiles.java:860)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.placeTiles(LittleActionPlaceStack.java:273)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.placeTiles(LittleActionPlaceStack.java:332)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.placeTile(LittleActionPlaceStack.java:164)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.action(LittleActionPlaceStack.java:113)
	at com.creativemd.littletiles.common.action.LittleAction.execute(LittleAction.java:179)
	at com.creativemd.littletiles.common.events.LittleEvent.onRightInteractClient(LittleEvent.java:275)
	at com.creativemd.littletiles.common.events.LittleEvent.onInteract(LittleEvent.java:259)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_76_LittleEvent_onInteract_RightClickBlock.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1132)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:398)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.addToRenderUpdate(TileEntityLittleTiles.java:388)
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.updateCustomRenderer(TileEntityLittleTiles.java:365)
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.updateTiles(TileEntityLittleTiles.java:351)
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.combineTiles(TileEntityLittleTiles.java:860)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.placeTiles(LittleActionPlaceStack.java:273)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.placeTiles(LittleActionPlaceStack.java:332)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.placeTile(LittleActionPlaceStack.java:164)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.action(LittleActionPlaceStack.java:113)
	at com.creativemd.littletiles.common.action.LittleAction.execute(LittleAction.java:179)
	at com.creativemd.littletiles.common.events.LittleEvent.onRightInteractClient(LittleEvent.java:275)
	at com.creativemd.littletiles.common.events.LittleEvent.onInteract(LittleEvent.java:259)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_76_LittleEvent_onInteract_RightClickBlock.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1132)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:398)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['monkeeeeee'/276, l='MpServer', x=167.56, y=65.00, z=255.15]]
	Chunk stats: MultiplayerChunkCache: 4032, 4032
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (168,64,256), Chunk: (at 8,4,0 in 10,16; contains blocks 160,0,256 to 175,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 5474 game time, 5474 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 86 total; [EntityBat['Bat'/2944, l='MpServer', x=225.47, y=17.17, z=196.80], EntityZombie['Zombie'/3715, l='MpServer', x=142.50, y=13.00, z=266.50], EntityBat['Bat'/2436, l='MpServer', x=107.60, y=18.92, z=239.94], EntityItem['item.item.LTRecipe'/138, l='MpServer', x=161.78, y=63.00, z=256.88], EntityItem['item.item.LTPremade.workbench'/139, l='MpServer', x=164.35, y=61.00, z=264.12], EntitySquid['Squid'/140, l='MpServer', x=155.60, y=62.00, z=274.60], EntitySkeleton['Skeleton'/2064, l='MpServer', x=138.50, y=26.00, z=252.50], EntityZombie['Zombie'/3344, l='MpServer', x=140.50, y=17.00, z=255.50], EntityBat['Bat'/3857, l='MpServer', x=147.50, y=55.27, z=230.63], EntityCreeper['Creeper'/2196, l='MpServer', x=114.16, y=17.00, z=239.41], EntityItem['item.item.seeds'/2455, l='MpServer', x=142.84, y=61.00, z=230.67], EntityBat['Bat'/153, l='MpServer', x=175.53, y=50.11, z=269.19], EntityPig['Pig'/154, l='MpServer', x=185.33, y=85.00, z=314.52], EntityCreeper['Creeper'/2842, l='MpServer', x=139.50, y=15.00, z=228.50], EntityPig['Pig'/155, l='MpServer', x=180.45, y=88.00, z=318.55], EntityPig['Pig'/156, l='MpServer', x=180.52, y=85.00, z=305.67], EntityPig['Pig'/157, l='MpServer', x=179.38, y=87.00, z=310.76], EntityPlayerSP['monkeeeeee'/276, l='MpServer', x=167.56, y=65.00, z=255.15], EntityBat['Bat'/2594, l='MpServer', x=186.76, y=60.10, z=184.02], EntityZombie['Zombie'/3365, l='MpServer', x=180.79, y=50.00, z=273.49], EntityCreeper['Creeper'/3110, l='MpServer', x=188.50, y=51.00, z=275.50], EntityPig['Pig'/168, l='MpServer', x=203.50, y=63.00, z=273.50], EntityPig['Pig'/169, l='MpServer', x=204.26, y=64.00, z=278.60], EntityPig['Pig'/170, l='MpServer', x=209.30, y=69.00, z=274.51], EntitySkeleton['Skeleton'/3243, l='MpServer', x=90.50, y=26.00, z=230.50], EntityCreeper['Creeper'/3884, l='MpServer', x=179.50, y=29.00, z=274.50], EntitySkeleton['Skeleton'/3885, l='MpServer', x=177.50, y=29.00, z=270.50], EntityCreeper['Creeper'/2863, l='MpServer', x=207.50, y=12.00, z=205.50], EntitySkeleton['Skeleton'/3766, l='MpServer', x=245.55, y=13.00, z=227.23], EntityBat['Bat'/3894, l='MpServer', x=115.30, y=21.49, z=251.40], EntitySkeleton['Skeleton'/3767, l='MpServer', x=247.50, y=13.00, z=222.50], EntityZombie['Zombie'/2365, l='MpServer', x=98.50, y=42.00, z=241.50], EntityPig['Pig'/191, l='MpServer', x=210.50, y=72.00, z=276.50], EntityBat['Bat'/3136, l='MpServer', x=185.87, y=12.00, z=185.80], EntityBat['Bat'/3904, l='MpServer', x=197.68, y=54.23, z=180.57], EntityBat['Bat'/3138, l='MpServer', x=184.29, y=14.10, z=181.75], EntityBat['Bat'/3139, l='MpServer', x=185.20, y=14.10, z=181.58], EntitySkeleton['Skeleton'/3396, l='MpServer', x=88.50, y=40.00, z=264.50], EntityCreeper['Creeper'/2760, l='MpServer', x=128.50, y=16.00, z=250.50], EntityCreeper['Creeper'/2121, l='MpServer', x=154.50, y=53.00, z=203.50], EntitySkeleton['Skeleton'/76, l='MpServer', x=103.50, y=42.00, z=235.50], EntityCreeper['Creeper'/3535, l='MpServer', x=247.50, y=16.00, z=207.50], EntityZombie['Zombie'/80, l='MpServer', x=105.50, y=21.00, z=244.50], EntityBat['Bat'/81, l='MpServer', x=130.32, y=16.55, z=240.00], EntitySheep['Sheep'/83, l='MpServer', x=104.79, y=63.00, z=271.35], EntityPig['Pig'/211, l='MpServer', x=244.77, y=73.00, z=248.49], EntityPig['Pig'/212, l='MpServer', x=245.51, y=73.00, z=240.79], EntityCreeper['Creeper'/3924, l='MpServer', x=142.50, y=17.00, z=235.50], EntityPig['Pig'/213, l='MpServer', x=245.66, y=67.00, z=267.49], EntityZombie['Zombie'/3289, l='MpServer', x=105.50, y=15.00, z=242.50], EntityZombie['Zombie'/3290, l='MpServer', x=96.57, y=17.00, z=236.75], EntitySkeleton['Skeleton'/3291, l='MpServer', x=99.79, y=16.00, z=240.50], EntityZombieVillager['Zombie Villager'/2396, l='MpServer', x=188.50, y=51.00, z=282.50], EntitySquid['Squid'/3036, l='MpServer', x=136.40, y=54.00, z=268.60], EntitySpider['Spider'/3292, l='MpServer', x=104.50, y=15.00, z=238.50], EntityBat['Bat'/93, l='MpServer', x=148.75, y=55.10, z=240.37], EntityZombieVillager['Zombie Villager'/2397, l='MpServer', x=177.77, y=51.00, z=275.50], EntitySheep['Sheep'/94, l='MpServer', x=113.49, y=66.00, z=255.73], EntitySheep['Sheep'/95, l='MpServer', x=113.50, y=63.00, z=266.50], EntitySquid['Squid'/2655, l='MpServer', x=126.93, y=61.00, z=266.44], EntitySheep['Sheep'/96, l='MpServer', x=116.52, y=64.00, z=265.77], EntitySkeleton['Skeleton'/3552, l='MpServer', x=129.50, y=55.00, z=306.50], EntityPig['Pig'/97, l='MpServer', x=121.50, y=63.00, z=287.50], EntityItem['item.tile.mushroom'/98, l='MpServer', x=127.15, y=61.00, z=299.61], EntityZombie['Zombie'/2147, l='MpServer', x=119.50, y=17.00, z=238.50], EntitySquid['Squid'/3300, l='MpServer', x=125.07, y=60.70, z=226.49], EntitySquid['Squid'/3301, l='MpServer', x=123.89, y=61.38, z=226.07], EntitySquid['Squid'/3302, l='MpServer', x=115.40, y=61.60, z=223.57], EntityCreeper['Creeper'/2790, l='MpServer', x=166.50, y=18.00, z=183.50], EntitySquid['Squid'/3303, l='MpServer', x=128.49, y=61.57, z=223.13], EntityZombie['Zombie'/3691, l='MpServer', x=89.50, y=20.00, z=224.50], EntitySkeleton['Skeleton'/3692, l='MpServer', x=89.50, y=20.00, z=222.50], EntityZombie['Zombie'/112, l='MpServer', x=134.59, y=17.00, z=239.76], EntityEnderman['Enderman'/3184, l='MpServer', x=132.45, y=30.00, z=238.28], EntityPig['Pig'/118, l='MpServer', x=128.55, y=60.00, z=295.77], EntitySkeleton['Skeleton'/3958, l='MpServer', x=103.50, y=28.00, z=258.50], EntityPig['Pig'/119, l='MpServer', x=128.55, y=59.00, z=290.39], EntityPig['Pig'/120, l='MpServer', x=127.50, y=59.00, z=288.75], EntitySkeleton['Skeleton'/3704, l='MpServer', x=201.50, y=53.00, z=177.50], EntityItem['item.tile.sapling.oak'/121, l='MpServer', x=130.12, y=76.00, z=319.06], EntityBat['Bat'/2938, l='MpServer', x=186.70, y=12.00, z=186.70], EntitySkeleton['Skeleton'/123, l='MpServer', x=147.71, y=53.00, z=242.47], EntitySkeleton['Skeleton'/124, l='MpServer', x=133.51, y=51.00, z=237.23], EntityZombie['Zombie'/125, l='MpServer', x=156.51, y=53.00, z=245.78], EntitySquid['Squid'/127, l='MpServer', x=141.94, y=61.21, z=266.26], EntityBat['Bat'/2943, l='MpServer', x=225.35, y=10.94, z=196.33]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 709666536 bytes (676 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2814 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version                      | Source                                                         | Signature                                |
	|:------ |:----------------- |:---------------------------- |:-------------------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft         | 1.12.2                       | minecraft.jar                                                  | None                                     |
	| LCHIJA | mcp               | 9.42                         | minecraft.jar                                                  | None                                     |
	| LCHIJA | FML               | 8.0.99.99                    | forge-1.12.2-14.23.5.2814.jar                                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge             | 14.23.5.2814                 | forge-1.12.2-14.23.5.2814.jar                                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy | 1.0.0                        | minecraft.jar                                                  | None                                     |
	| LCHIJA | littletilescore   | 1.0.0                        | minecraft.jar                                                  | None                                     |
	| LCHIJA | chiselsandbits    | 14.33                        | chiselsandbits-14.33.jar                                       | None                                     |
	| LCHIJA | creativecore      | 1.9.9                        | CreativeCore_v1.9.74_mc1.12.2.jar                              | None                                     |
	| LCHIJA | cfm               | 6.2.0                        | furniture-6.2.0-1.12.2.jar                                     | None                                     |
	| LCHIJA | littletiles       | 1.5.0                        | LittleTiles-Mod-1.12.2.jar                                     | None                                     |
	| LCHIJA | worldedit         | 6.1.10-SNAPSHOT              | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar              | None                                     |
	| LCHIJA | worldeditcuife2   | 2.2.0-mf-1.12.2-14.23.5.2768 | WorldEdit+CUI+Forge+Edition+2-2.2.0-mf-1.12.2-14.23.5.2768.jar | None                                     |

	Loaded coremods (and transformers): 
LittleLatePatchingLoader (LittleTilesCore-v1.0.0.jar)
  com.creativemd.littletiles.LittleTilesLateTransformer
CreativePatchingLoader (CreativeCore_v1.9.74_mc1.12.2.jar)
  
LittlePatchingLoader (LittleTiles-Mod-1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 441.41' Renderer: 'GeForce GTX 1060 3GB/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2814
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 441.41, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz

**Comment by CreativeMD** [comment]
Please only download minecraft mods from curseforge (or the official website of the author). Other websites do not have the permission. The modders don't earn anything from it and the versions are almost always outdated.
