### ISSUE TITLE
Game crashes as soon as I do anything

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#312]
Like the title says, as soon as I use stuff from the mod, the game crashes, I don't know if this also happens if I place the workbench for example, because I've only tried it with the chisel and the hammer.

The Error message is:
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  LittlePatchingLoader (LittleTiles_v1.5.0-pre135_mc1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  CreativePatchingLoader (CreativeCore_v1.9.80_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 12/20/19 8:34 PM
Description: Unexpected error

java.lang.NoClassDefFoundError: com/creativemd/creativecore/client/rendering/model/CreativeCubeConsumer
	at com.creativemd.littletiles.client.render.RenderingThread.<init>(RenderingThread.java:342)
	at com.creativemd.littletiles.client.render.RenderingThread.initThreads(RenderingThread.java:88)
	at com.creativemd.littletiles.client.render.RenderingThread.<clinit>(RenderingThread.java:128)
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.addToRenderUpdate(TileEntityLittleTiles.java:388)
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.updateCustomRenderer(TileEntityLittleTiles.java:365)
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.updateTiles(TileEntityLittleTiles.java:351)
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.addTile(TileEntityLittleTiles.java:291)
	at com.creativemd.littletiles.common.tiles.LittleTile.place(LittleTile.java:538)
	at com.creativemd.littletiles.common.tiles.LittleTileBlock.place(LittleTileBlock.java:263)
	at com.creativemd.littletiles.common.action.LittleAction.loadTe(LittleAction.java:256)
	at com.creativemd.littletiles.common.action.block.LittleActionDestroyBoxes.action(LittleActionDestroyBoxes.java:152)
	at com.creativemd.littletiles.common.action.block.LittleActionBoxes.action(LittleActionBoxes.java:67)
	at com.creativemd.littletiles.common.action.block.LittleActionDestroyBoxes.action(LittleActionDestroyBoxes.java:186)
	at com.creativemd.littletiles.common.action.LittleAction.execute(LittleAction.java:179)
	at com.creativemd.littletiles.common.items.ItemHammer.onClickBlock(ItemHammer.java:98)
	at com.creativemd.littletiles.common.events.LittleEvent.onLeftClick(LittleEvent.java:149)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_81_LittleEvent_onLeftClick_LeftClickBlock.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:1130)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_180511_b(PlayerControllerMP.java:222)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1518)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2249)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.creativemd.creativecore.client.rendering.model.CreativeCubeConsumer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 34 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.creativemd.littletiles.client.render.RenderingThread.<init>(RenderingThread.java:342)
	at com.creativemd.littletiles.client.render.RenderingThread.initThreads(RenderingThread.java:88)
	at com.creativemd.littletiles.client.render.RenderingThread.<clinit>(RenderingThread.java:128)
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.addToRenderUpdate(TileEntityLittleTiles.java:388)
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.updateCustomRenderer(TileEntityLittleTiles.java:365)
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.updateTiles(TileEntityLittleTiles.java:351)
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.addTile(TileEntityLittleTiles.java:291)
	at com.creativemd.littletiles.common.tiles.LittleTile.place(LittleTile.java:538)
	at com.creativemd.littletiles.common.tiles.LittleTileBlock.place(LittleTileBlock.java:263)
	at com.creativemd.littletiles.common.action.LittleAction.loadTe(LittleAction.java:256)
	at com.creativemd.littletiles.common.action.block.LittleActionDestroyBoxes.action(LittleActionDestroyBoxes.java:152)
	at com.creativemd.littletiles.common.action.block.LittleActionBoxes.action(LittleActionBoxes.java:67)
	at com.creativemd.littletiles.common.action.block.LittleActionDestroyBoxes.action(LittleActionDestroyBoxes.java:186)
	at com.creativemd.littletiles.common.action.LittleAction.execute(LittleAction.java:179)
	at com.creativemd.littletiles.common.items.ItemHammer.onClickBlock(ItemHammer.java:98)
	at com.creativemd.littletiles.common.events.LittleEvent.onLeftClick(LittleEvent.java:149)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_81_LittleEvent_onLeftClick_LeftClickBlock.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:1130)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_180511_b(PlayerControllerMP.java:222)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1518)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2249)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['_BooperDooper_'/250, l='MpServer', x=-114.77, y=63.00, z=254.14]]
	Chunk stats: MultiplayerChunkCache: 1088, 1088
	Level seed: 0
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-200,64,256), Chunk: (at 8,4,0 in -13,16; contains blocks -208,0,256 to -193,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 42965 game time, 7086 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 47 total; [EntitySheep['Sheep'/146, l='MpServer', x=-192.50, y=71.00, z=299.50], EntitySheep['Sheep'/147, l='MpServer', x=-187.20, y=71.00, z=309.45], EntitySheep['Sheep'/149, l='MpServer', x=-177.50, y=67.00, z=174.50], EntityChicken['Chicken'/150, l='MpServer', x=-177.50, y=69.00, z=227.84], EntityItem['item.item.egg'/151, l='MpServer', x=-177.94, y=69.00, z=226.99], EntityChicken['Chicken'/152, l='MpServer', x=-172.52, y=70.00, z=234.88], EntitySheep['Sheep'/153, l='MpServer', x=-179.52, y=77.00, z=279.23], EntitySheep['Sheep'/154, l='MpServer', x=-177.22, y=83.00, z=272.56], EntitySheep['Sheep'/155, l='MpServer', x=-177.26, y=104.00, z=292.41], EntitySheep['Sheep'/156, l='MpServer', x=-187.63, y=72.00, z=308.48], EntityItem['item.item.egg'/164, l='MpServer', x=-173.97, y=70.00, z=237.88], EntitySheep['Sheep'/165, l='MpServer', x=-166.74, y=84.00, z=268.51], EntitySheep['Sheep'/166, l='MpServer', x=-171.48, y=89.00, z=275.23], EntitySheep['Sheep'/167, l='MpServer', x=-172.50, y=101.00, z=285.55], EntitySheep['Sheep'/168, l='MpServer', x=-172.50, y=101.00, z=284.40], EntitySheep['Sheep'/169, l='MpServer', x=-173.26, y=103.00, z=292.47], EntitySheep['Sheep'/170, l='MpServer', x=-162.48, y=100.00, z=285.71], EntitySheep['Sheep'/171, l='MpServer', x=-160.77, y=103.00, z=300.52], EntitySheep['Sheep'/172, l='MpServer', x=-170.48, y=104.00, z=295.27], EntitySheep['Sheep'/173, l='MpServer', x=-167.51, y=103.00, z=291.33], EntityChicken['Chicken'/184, l='MpServer', x=-159.82, y=70.00, z=213.57], EntityChicken['Chicken'/185, l='MpServer', x=-154.83, y=70.00, z=239.47], EntityItem['item.item.egg'/186, l='MpServer', x=-155.55, y=70.00, z=239.69], EntitySheep['Sheep'/187, l='MpServer', x=-155.23, y=103.00, z=317.45], EntitySheep['Sheep'/188, l='MpServer', x=-145.55, y=100.00, z=315.45], EntitySheep['Sheep'/189, l='MpServer', x=-144.39, y=100.00, z=316.05], EntitySheep['Sheep'/190, l='MpServer', x=-147.50, y=99.00, z=321.73], EntityBat['Bat'/192, l='MpServer', x=-91.25, y=17.03, z=222.48], EntityBat['Bat'/193, l='MpServer', x=-115.54, y=28.08, z=223.52], EntityBat['Bat'/198, l='MpServer', x=-93.34, y=18.36, z=222.55], EntitySquid['Squid'/199, l='MpServer', x=-87.74, y=49.19, z=270.42], EntitySquid['Squid'/200, l='MpServer', x=-80.77, y=48.23, z=265.54], EntityPlayerSP['_BooperDooper_'/250, l='MpServer', x=-114.77, y=63.00, z=254.14], EntitySquid['Squid'/205, l='MpServer', x=-64.30, y=61.40, z=252.13], EntitySquid['Squid'/206, l='MpServer', x=-74.40, y=46.65, z=268.40], EntitySquid['Squid'/207, l='MpServer', x=-72.93, y=56.23, z=269.56], EntitySquid['Squid'/208, l='MpServer', x=-66.40, y=60.65, z=262.99], EntitySquid['Squid'/209, l='MpServer', x=-63.20, y=54.80, z=305.94], EntitySquid['Squid'/210, l='MpServer', x=-72.38, y=52.80, z=310.19], EntitySquid['Squid'/211, l='MpServer', x=-71.99, y=53.81, z=304.70], EntitySquid['Squid'/212, l='MpServer', x=-69.85, y=49.46, z=313.36], EntityBat['Bat'/224, l='MpServer', x=-51.91, y=38.99, z=189.42], EntityBat['Bat'/225, l='MpServer', x=-44.29, y=26.01, z=203.04], EntitySquid['Squid'/227, l='MpServer', x=-54.53, y=61.41, z=264.46], EntitySquid['Squid'/228, l='MpServer', x=-61.20, y=52.03, z=271.13], EntitySquid['Squid'/229, l='MpServer', x=-59.86, y=58.40, z=287.17], EntitySquid['Squid'/230, l='MpServer', x=-52.94, y=54.76, z=278.00]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 531963192 bytes (507 MB) / 1308622848 bytes (1248 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 98
	FML: MCP 9.42 Powered by Forge 14.23.5.2836 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version           | Source                                 | Signature                                |
	|:------ |:----------------- |:----------------- |:-------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft         | 1.12.2            | minecraft.jar                          | None                                     |
	| LCHIJA | mcp               | 9.42              | minecraft.jar                          | None                                     |
	| LCHIJA | FML               | 8.0.99.99         | forge-1.12.2-14.23.5.2836.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge             | 14.23.5.2836      | forge-1.12.2-14.23.5.2836.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy | 1.0.0             | minecraft.jar                          | None                                     |
	| LCHIJA | littletilescore   | 1.0.0             | minecraft.jar                          | None                                     |
	| LCHIJA | ctm               | MC1.12.2-1.0.1.30 | CTM-MC1.12.2-1.0.1.30.jar              | None                                     |
	| LCHIJA | chisel            | MC1.12.2-1.0.1.44 | Chisel-MC1.12.2-1.0.1.44.jar           | None                                     |
	| LCHIJA | creativecore      | 1.9.9             | CreativeCore_v1.9.80_mc1.12.2.jar      | None                                     |
	| LCHIJA | cfm               | 6.3.1             | furniture-6.3.1-1.12.2.jar             | None                                     |
	| LCHIJA | futureminecraf    | 1.2.2             | FutureVersionsV1.2.2.jar               | None                                     |
	| LCHIJA | ido               | 1.0.6             | ido-1.12.2-1.1.0.jar                   | None                                     |
	| LCHIJA | littletiles       | 1.5.0             | LittleTiles_v1.5.0-pre135_mc1.12.2.jar | None                                     |

	Loaded coremods (and transformers): 
LittlePatchingLoader (LittleTiles_v1.5.0-pre135_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  team.chisel.ctm.client.asm.CTMTransformer
CreativePatchingLoader (CreativeCore_v1.9.80_mc1.12.2.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13417 Compatibility Profile Context 15.301.1901.0' Renderer: 'AMD Mobility Radeon HD 5000 Series'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2836
	LWJGL: 2.9.4
	OpenGL: AMD Mobility Radeon HD 5000 Series GL version 4.5.13417 Compatibility Profile Context 15.301.1901.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x AMD Athlon(tm) II P320 Dual-Core Processor`

The other mods I have installed are
Chisel
Creative Core
Connected Textures
MrCrayfish' Furniture
Future Versions
and
Idō (Brings swimming and crawling into older versions)

Pls help, I want to build with smol blocks and Chisel and Bits doesn't have doors and stuff

**Comment by kirokadura** [comment]
The version of Little Tiles you're using is super outdated. Please use this one:

https://www.curseforge.com/minecraft/mc-mods/littletiles/files/2844843

**Comment by ghost** [comment]
Thanks for answering so quickly, it works now. I just went for the most downloaded version and didn't check if it was outdated.
