### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by TomberWolf** [CreativeMD/LittleTiles#32]
MC 1.7.10 on a Thermos Server 1.7.10

There's an untextured item. If you try to place it, the server crashes.

`java.lang.NullPointerException: Unexpected error
	at com.creativemd.littletiles.common.items.ItemRecipe.getPreview(ItemRecipe.java:166)
	at com.creativemd.littletiles.common.items.ItemMultiTiles.getLittlePreview(ItemMultiTiles.java:82)
	at com.creativemd.littletiles.common.utils.PlacementHelper.isLittleBlock(PlacementHelper.java:82)
	at com.creativemd.littletiles.common.events.LittleEvent.onInteract(LittleEvent.java:33)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_622_LittleEvent_onInteract_PlayerInteractEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:100)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1446)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**Comment by CreativeMD** [comment]
There is no support for 1.7.10 anymore sorry.
