### ISSUE TITLE
Problem with updateTranslucent appears again :(

### ISSUE THREAD

**Issue by hanspaerna** [CreativeMD/LittleTiles#325]
Hi, I'm getting this problem near my spawn area. Using Sponge 1.12.2 server with Forge. Unfortunately the latest build (190) did not help. I've noticed it appears when the second player joins the server near me.

[01:04:00] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:762) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NoSuchMethodError: net.minecraft.block.state.IBlockState.func_185895_e()Z
        at com.creativemd.littletiles.common.tiles.LittleTileBlock.updateTranslucent(LittleTileBlock.java:131) ~[LittleTileBlock.class:?]
        at com.creativemd.littletiles.common.tiles.LittleTileBlock.isTranslucent(LittleTileBlock.java:126) ~[LittleTileBlock.class:?]
        at com.creativemd.littletiles.common.tiles.LittleTileBlock.doesProvideSolidFace(LittleTileBlock.java:286) ~[LittleTileBlock.class:?]
        at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles$SideSolidCache.calculateState(TileEntityLittleTiles.java:934) ~[TileEntityLittleTiles$SideSolidCache.class:?]
        at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles$SideSolidCache.calculate(TileEntityLittleTiles.java:922) ~[TileEntityLittleTiles$SideSolidCache.class:?]
        at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles$SideSolidCache.get(TileEntityLittleTiles.java:978) ~[TileEntityLittleTiles$SideSolidCache.class:?]
        at com.creativemd.littletiles.common.blocks.BlockTile.isSideSolid(BlockTile.java:457) ~[BlockTile.class:?]
        at net.minecraft.block.Block.canCreatureSpawn(Block.java:1357) ~[aow.class:?]
        at net.minecraft.world.WorldEntitySpawner.canCreatureTypeSpawnBody(WorldEntitySpawner.java:244) ~[anb.class:?]
        at net.minecraft.entity.EntityLiving$SpawnPlacementType.canSpawnAt(EntityLiving.java:1463) ~[vq$a.class:?]
        at net.minecraft.world.WorldEntitySpawner.func_180267_a(WorldEntitySpawner.java:226) ~[anb.class:?]
        at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:754) ~[anb.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) ~[MinecraftServer.class:?]
        ... 4 more

**Comment by CreativeMD** [comment]
Oh right, I released another version which should fix it. Sorry overlooked that method as well. Hope it works now, if not just reopen the issue.

**Comment by artemantcev** [comment]
unfortunately it happens again, but with another error :c 

[03:25:41] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:762) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NoSuchMethodError: net.minecraft.block.Block.func_180664_k()Lnet/minecraft/util/BlockRenderLayer;
        at net.minecraft.block.Block.canRenderInLayer(Block.java:2159) ~[aow.class:?]
        at com.creativemd.littletiles.common.tiles.LittleTileBlock.updateTranslucent(LittleTileBlock.java:131) ~[LittleTileBlock.class:?]
        at com.creativemd.littletiles.common.tiles.LittleTileBlock.isTranslucent(LittleTileBlock.java:126) ~[LittleTileBlock.class:?]
        at com.creativemd.littletiles.common.tiles.LittleTileBlock.doesProvideSolidFace(LittleTileBlock.java:286) ~[LittleTileBlock.class:?]
        at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles$SideSolidCache.calculateState(TileEntityLittleTiles.java:934) ~[TileEntityLittleTiles$SideSolidCache.class:?]
        at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles$SideSolidCache.calculate(TileEntityLittleTiles.java:922) ~[TileEntityLittleTiles$SideSolidCache.class:?]
        at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles$SideSolidCache.get(TileEntityLittleTiles.java:978) ~[TileEntityLittleTiles$SideSolidCache.class:?]
        at com.creativemd.littletiles.common.blocks.BlockTile.isSideSolid(BlockTile.java:457) ~[BlockTile.class:?]
        at net.minecraft.block.Block.canCreatureSpawn(Block.java:1357) ~[aow.class:?]
        at net.minecraft.world.WorldEntitySpawner.canCreatureTypeSpawnBody(WorldEntitySpawner.java:244) ~[anb.class:?]
        at net.minecraft.entity.EntityLiving$SpawnPlacementType.canSpawnAt(EntityLiving.java:1463) ~[vq$a.class:?]
        at net.minecraft.world.WorldEntitySpawner.func_180267_a(WorldEntitySpawner.java:226) ~[anb.class:?]
        at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:754) ~[anb.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) ~[MinecraftServer.class:?]
        ... 4 more
[03:25:41] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: D:\katacraft\katabaserver-1.12.2\.\crash-reports\crash-2019-12-31_03.25.41-server.txt
