### ISSUE TITLE
Disabling VBOs cause game crash after animation

### ISSUE THREAD

**Issue by alexpado** [CreativeMD/LittleTiles#331]
Disabling VBOs cause game crash after an animation.

**Step To Reproduce :**

1. Build a simple structure
2. Configure an animation on it (tested with sliding)
3. Place your structure in the world
4. Right click it.

When the animation stop, the game will crash. With VBOs enabled, the game don't crash.

**Stacktrace**
```

java.lang.NullPointerException: Unexpected error
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
	at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38)
	at java.lang.reflect.Field.get(Field.java:393)
	at com.creativemd.littletiles.client.render.world.RenderUploader.uploadRenderData(RenderUploader.java:94)
	at com.creativemd.littletiles.common.entity.DoorController.place(DoorController.java:268)
	at com.creativemd.littletiles.common.entity.DoorController.endTransition(DoorController.java:191)
	at com.creativemd.littletiles.common.utils.animation.AnimationController.tick(AnimationController.java:155)
	at com.creativemd.littletiles.common.entity.DoorController.tick(DoorController.java:171)
	at com.creativemd.littletiles.common.entity.EntityAnimation.onTick(EntityAnimation.java:591)
	at com.creativemd.littletiles.common.entity.EntityAnimation.onUpdateForReal(EntityAnimation.java:641)
	at com.creativemd.littletiles.common.events.LittleDoorHandler.tickClient(LittleDoorHandler.java:282)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1352_LittleDoorHandler_tickClient_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1911)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

For now, I play with VBOs on, and I don't mind. But fixing it, or at least mention it in the original thread would certainly help many people.

**Comment by alexpado** [comment]
Just installed the update released yesterday, this bug doesn't occur anymore (singleplayer & multiplayer)
