### ISSUE TITLE
Opening Custom Doors

### ISSUE THREAD

**Issue by TomBombTom** [CreativeMD/LittleTiles#339]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore_v1.9.90_mc1.12.2.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre198_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 1/31/20 5:08 PM
Description: Unexpected error

java.lang.IllegalStateException: Function is not supported
	at org.lwjgl.BufferChecks.checkFunctionAddress(BufferChecks.java:58)
	at org.lwjgl.opengl.GL30.glMapBufferRange(GL30.java:998)
	at com.creativemd.littletiles.client.render.world.RenderUploader.glMapBufferRange(RenderUploader.java:143)
	at com.creativemd.littletiles.client.render.world.RenderUploader.uploadRenderData(RenderUploader.java:103)
	at com.creativemd.littletiles.common.entity.DoorController.place(DoorController.java:265)
	at com.creativemd.littletiles.common.entity.DoorController.endTransition(DoorController.java:190)
	at com.creativemd.littletiles.common.utils.animation.AnimationController.tick(AnimationController.java:155)
	at com.creativemd.littletiles.common.entity.DoorController.tick(DoorController.java:170)
	at com.creativemd.littletiles.common.entity.EntityAnimation.onTick(EntityAnimation.java:593)
	at com.creativemd.littletiles.common.entity.EntityAnimation.onUpdateForReal(EntityAnimation.java:643)
	at com.creativemd.littletiles.client.world.LittleAnimationHandlerClient.tickClient(LittleAnimationHandlerClient.java:500)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_49_LittleAnimationHandlerClient_tickClient_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1911)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.lwjgl.BufferChecks.checkFunctionAddress(BufferChecks.java:58)
	at org.lwjgl.opengl.GL30.glMapBufferRange(GL30.java:998)
	at com.creativemd.littletiles.client.render.world.RenderUploader.glMapBufferRange(RenderUploader.java:143)
	at com.creativemd.littletiles.client.render.world.RenderUploader.uploadRenderData(RenderUploader.java:103)
	at com.creativemd.littletiles.common.entity.DoorController.place(DoorController.java:265)
	at com.creativemd.littletiles.common.entity.DoorController.endTransition(DoorController.java:190)
	at com.creativemd.littletiles.common.utils.animation.AnimationController.tick(AnimationController.java:155)
	at com.creativemd.littletiles.common.entity.DoorController.tick(DoorController.java:170)
	at com.creativemd.littletiles.common.entity.EntityAnimation.onTick(EntityAnimation.java:593)
	at com.creativemd.littletiles.common.entity.EntityAnimation.onUpdateForReal(EntityAnimation.java:643)
	at com.creativemd.littletiles.client.world.LittleAnimationHandlerClient.tickClient(LittleAnimationHandlerClient.java:500)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_49_LittleAnimationHandlerClient_tickClient_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Fortnite_Gamer12'/0, l='MpServer', x=725.96, y=4.00, z=-1095.50]]
	Chunk stats: MultiplayerChunkCache: 4032, 4032
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (721,4,-1106), Chunk: (at 1,0,14 in 45,-70; contains blocks 720,0,-1120 to 735,255,-1105), Region: (1,-3; contains chunks 32,-96 to 63,-65, blocks 512,0,-1536 to 1023,255,-1025)
	Level time: 12160 game time, 12160 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 27 total; [EntityItem['item.item.LTRecipe'/1207192, l='MpServer', x=722.35, y=4.00, z=-1097.94], EntityPig['Pig'/51151, l='MpServer', x=664.50, y=4.00, z=-1140.50], EntityDonkey['Donkey'/51152, l='MpServer', x=670.50, y=4.00, z=-1144.50], EntityDonkey['Donkey'/51153, l='MpServer', x=668.86, y=4.00, z=-1141.44], EntityPig['Pig'/51155, l='MpServer', x=668.50, y=4.00, z=-1145.50], EntityChicken['Chicken'/51156, l='MpServer', x=752.09, y=4.00, z=-1047.16], EntityDonkey['Donkey'/51157, l='MpServer', x=742.50, y=4.00, z=-1045.50], EntityDonkey['Donkey'/51158, l='MpServer', x=741.50, y=4.00, z=-1042.50], EntityItem['item.item.egg'/1028757, l='MpServer', x=763.04, y=4.00, z=-1094.93], EntityPig['Pig'/51168, l='MpServer', x=749.50, y=4.00, z=-1174.50], EntityPig['Pig'/51169, l='MpServer', x=756.30, y=4.00, z=-1173.57], EntityChicken['Chicken'/51170, l='MpServer', x=747.50, y=4.00, z=-1173.50], EntityChicken['Chicken'/51171, l='MpServer', x=738.87, y=4.00, z=-1169.68], EntityPlayerSP['Fortnite_Gamer12'/0, l='MpServer', x=725.96, y=4.00, z=-1095.50], EntityItem['item.item.egg'/1219002, l='MpServer', x=752.21, y=4.00, z=-1046.32], EntityChicken['Chicken'/51180, l='MpServer', x=762.50, y=4.00, z=-1095.50], EntityChicken['Chicken'/51181, l='MpServer', x=762.50, y=4.00, z=-1097.50], EntityAnimation['entity.animation.name'/1240000, l='MpServer', x=724.00, y=3.00, z=-1098.00], EntityChicken['Chicken'/51182, l='MpServer', x=759.50, y=4.00, z=-1094.50], EntityChicken['Chicken'/51183, l='MpServer', x=761.43, y=4.00, z=-1099.17], EntityChicken['Chicken'/51184, l='MpServer', x=691.50, y=4.00, z=-1166.50], EntityCow['Cow'/51185, l='MpServer', x=696.50, y=4.00, z=-1162.50], EntityCow['Cow'/51186, l='MpServer', x=696.50, y=4.00, z=-1164.50], EntityItem['item.item.egg'/976956, l='MpServer', x=761.07, y=4.00, z=-1100.00], EntityCow['Cow'/51188, l='MpServer', x=703.17, y=4.00, z=-1171.31], EntityItem['item.item.egg'/839865, l='MpServer', x=758.99, y=4.00, z=-1095.09], EntityItem['item.item.egg'/783091, l='MpServer', x=762.48, y=4.00, z=-1096.64]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.13.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 486776768 bytes (464 MB) / 1577058304 bytes (1504 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version      | Source                                 | Signature |
	|:------ |:----------------- |:------------ |:-------------------------------------- |:--------- |
	| LCHIJA | minecraft         | 1.12.2       | minecraft.jar                          | None      |
	| LCHIJA | mcp               | 9.42         | minecraft.jar                          | None      |
	| LCHIJA | FML               | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar          | None      |
	| LCHIJA | forge             | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar          | None      |
	| LCHIJA | creativecoredummy | 1.0.0        | minecraft.jar                          | None      |
	| LCHIJA | littletilescore   | 1.0.0        | minecraft.jar                          | None      |
	| LCHIJA | creativecore      | 1.9.9        | CreativeCore_v1.9.90_mc1.12.2.jar      | None      |
	| LCHIJA | littletiles       | 1.5.0        | LittleTiles_v1.5.0-pre198_mc1.12.2.jar | None      |

	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore_v1.9.90_mc1.12.2.jar)
  
LittlePatchingLoader (LittleTiles_v1.5.0-pre198_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '2.1 NVIDIA-10.4.14 310.90.30.05b27' Renderer: 'NVIDIA GeForce 9400M OpenGL Engine'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.2
	OpenGL: NVIDIA GeForce 9400M OpenGL Engine GL version 2.1 NVIDIA-10.4.14 310.90.30.05b27, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Core(TM)2 Duo CPU P7550 @ 2.26GHz

**Comment by CreativeMD** [comment]
Either you have a very old graphic card or you haven't updated your driver. You can disable the option `uploadToVBODirectly` in `Rendering` which should fix the crash.
