### ISSUE TITLE
Game crashes when I search blocks from this mod in JEI

### ISSUE THREAD

**Issue by Devilofether** [CreativeMD/LittleTiles#34]
**Game crashes when I search blocks from this mod in JEI**

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LittlePatchingLoader ([Content] Little Tiles 1.11.2.jar)
  MMFMLCorePlugin ([Feature] MultiMine 1.11.2.jar)
  BetterAutoJumpCore ([Misc] Better Auto Jump 1.11.2.jar)
  CreativePatchingLoader ([Dependancy] Creative Core (Little Tiles) 1.11.2.jar)
  LoadingPlugin ([Content] Quark 1.11.2.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 2/20/17 2:08 PM
Description: Unexpected error

java.lang.IllegalStateException: Already building!
	at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:291)
	at net.minecraft.client.renderer.RenderGlobal.func_174976_a(RenderGlobal.java:1958)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1640)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1569)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1346)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:291)
	at net.minecraft.client.renderer.RenderGlobal.func_174976_a(RenderGlobal.java:1958)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1640)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1569)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Devilofether'/1, l='MpServer', x=1.84, y=56.00, z=2.10]]
	Chunk stats: MultiplayerChunkCache: 530, 530
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (667,4,-535), Chunk: (at 11,0,9 in 41,-34; contains blocks 656,0,-544 to 671,255,-529), Region: (1,-2; contains chunks 32,-64 to 63,-33, blocks 512,0,-1024 to 1023,255,-513)
	Level time: 28687 game time, 57687 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['Devilofether'/1, l='MpServer', x=1.84, y=56.00, z=2.10]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:401)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 351608176 bytes (335 MB) / 861335552 bytes (821 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2233 Optifine OptiFine_1.11.2_HD_U_B5 33 mods loaded, 33 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2233.jar) 
	UCHIJAAAA	forge{13.20.0.2233} [Minecraft Forge] (forge-1.11.2-13.20.0.2233.jar) 
	UCHIJAAAA	littletilescore{1.0.0} [LittleTilesCore] (minecraft.jar) 
	UCHIJAAAA	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.jar) 
	UCHIJAAAA	betterfoliage{2.1.3} [Better Foliage] ([Aesthetic] Better Foliage 1.11.x.jar) 
	UCHIJAAAA	justenoughbuttons{1.11.2-1.4.2} [Just Enough Buttons] ([Cheat] Just Enough Buttons 1.11.2.jar) 
	UCHIJAAAA	jei{4.2.2.215} [Just Enough Items] ([Cheat] Just Enough Items 1.11.2.jar) 
	UCHIJAAAA	blockdispenser{1.0} [BlockDispenser] ([Content] Block Dispenser 1.1.2.jar) 
	UCHIJAAAA	chiselsandbits{13.10} [Chisels & Bits] ([Content] Chisels And Bits 1.11.2.jar) 
	UCHIJAAAA	extrabitmanipulation{1.11.2-3.0.4} [Extra Bit Manipulation] ([Content] Extra Bit Manipulation 1.11.2.jar) 
	UCHIJAAAA	hopperducts{1.4.9} [Hopper Ducts] ([Content] Hopper Ducts 1.11.2.jar) 
	UCHIJAAAA	littletiles{1.3.0} [LittleTiles] ([Content] Little Tiles 1.11.2.jar) 
	UCHIJAAAA	morphtool{1.1-13} [Morph-o-Tool] ([Content] Morph-o-Tool 1.11.2.jar) 
	UCHIJAAAA	notenoughwands{1.5.4} [Not Enough Wands] ([Content] Not Enough Wands 1.11.2.jar) 
	UCHIJAAAA	quark{r1.2-81} [Quark] ([Content] Quark 1.11.2.jar) 
	UCHIJAAAA	chameleon{1.11-3.0.2} [Chameleon] ([Dependancy] Chameleon (Drawers) 1.11.x.jar) 
	UCHIJAAAA	storagedrawers{1.11-4.0.3} [Storage Drawers] ([Content] Storage Drawers 1.11.x.jar) 
	UCHIJAAAA	autoreglib{1.1-4} [AutoRegLib] ([Dependancy] Auto Reg Lib (Quark)1.11.x.jar) 
	UCHIJAAAA	creativecore{1.5.0} [CreativeCore] ([Dependancy] Creative Core (Little Tiles) 1.11.2.jar) 
	UCHIJAAAA	fastleafdecay{v12} [Fast Leaf Decay] ([Feature] Fast Leaf Decay 1.11.x.jar) 
	UCHIJAAAA	mousetweaks{2.7} [Mouse Tweaks] ([Feature] Mouse Tweaks 1.11.2.jar) 
	UCHIJAAAA	multimine{1.5.6} [Multi Mine] ([Feature] MultiMine 1.11.2.jar) 
	UCHIJAAAA	simulatednights{1.11.2-1.1.2} [Simulated Nights] ([Feature] Simulated Nights 1.11.2.jar) 
	UCHIJAAAA	treechopper{1.1.1a} [Tree Chopper] ([Feature] Tree Chopper 1.11.x.jar) 
	UCHIJAAAA	veinminer{0.35.3} [Vein Miner] ([Feature] Vein Miner 1.11.x.jar) 
	UCHIJAAAA	veinminermodsupport{0.35.3} [Mod Support] ([Feature] Vein Miner 1.11.x.jar) 
	UCHIJAAAA	appleskin{1.0.5} [AppleSkin] ([Misc] Apple Skin 1.11.x.jar) 
	UCHIJAAAA	betterautojump{1.1.0-mc1.11.2} [Better Auto Jump] ([Misc] Better Auto Jump 1.11.2.jar) 
	UCHIJAAAA	waila{1.8.6} [Waila] ([Misc] Hwyla 1.11.x.jar) 
	UCHIJAAAA	multihotbar{1.0} [Multi-Hotbar] ([Misc] Multi Hotbar 1.11.2.jar) 
	Loaded coremods (and transformers): 
LittlePatchingLoader ([Content] Little Tiles 1.11.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
MMFMLCorePlugin ([Feature] MultiMine 1.11.2.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
BetterAutoJumpCore ([Misc] Better Auto Jump 1.11.2.jar)
  com.mmyzd.betterautojump.asm.ClassTransformer
CreativePatchingLoader ([Dependancy] Creative Core (Little Tiles) 1.11.2.jar)
  
LoadingPlugin ([Content] Quark 1.11.2.jar)
  vazkii.quark.base.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 358.91' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
	Launched Version: 1.11.2-forge1.11.2-13.20.0.2233
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 358.91, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x AMD FX(tm)-6300 Six-Core Processor 
	OptiFine Version: OptiFine_1.11.2_HD_U_B5
	Render Distance Chunks: 12
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 358.91
	OpenGlRenderer: GeForce GTX 750 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 6

**Comment by CreativeMD** [comment]
Unfortunately i can't see which version you are using
`([Content] Little Tiles 1.11.2.jar)`
it is hidden by `[Content]`, so could you please provide me the version of CreativeCore and LittleTiles?

**Comment by WenXin20** [comment]
I got the same crash in 1.10.2.
**Mods**:
LittleTiles v1.3.10
CreativeCore v1.6.21
JEI v3.14.6.411.
**[Crash Report](http://pastebin.com/1RpA60kQ)**

**Comment by CreativeMD** [comment]
I could not reproduce this crash using
CreativeCore v1.6.21 mc1.10.2.jar
InGameInfoXML-1.10.2-2.8.1.89
JEI 1.10.2-3.14.6.411
JustEnoughButtons-1.10.2-1.7
LittleTiles v1.3.10 mc1.10.2
Waila-1.7.0-B3_1.9.4
Optifine 1.10.2 HD U D6
Maybe you can find the crash report from jei? Should be in your minecraft folder somewhere.

**Comment by WenXin20** [comment]
Maybe try with Forge MultiPart CBE and Code Chicken Core, I see these mods mentioned in the log when ever I search Multipart or other phrases, like oak.
[Lastest log](https://github.com/UniversalLP/JustEnoughButtons/files/769648/fml-client-latest.txt)
I originally thought it was Just Enough Buttonz, so I reported it at UniversalLP/JustEnoughButtons#20

**Comment by CreativeMD** [comment]
This seems to be the crash, which breaks the renderer:
`[15:10:55] [Client thread/ERROR] [JEI/]: Rendering ingredient crashed: 1xitem.microblock@1 microblockcbe:microblock nbt:{mat:"minecraft:bookshelf"}
net.minecraft.util.ReportedException: Rendering item
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:261) ~[CCRenderItem.class:?]
	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.render(ItemStackRenderer.java:27) ~[ItemStackRenderer.class:?]
	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.render(ItemStackRenderer.java:21) ~[ItemStackRenderer.class:?]
	at mezz.jei.gui.ingredients.GuiIngredientFast.renderSlow(GuiIngredientFast.java:181) [GuiIngredientFast.class:?]
	at mezz.jei.gui.ingredients.GuiIngredientFast.renderSlow(GuiIngredientFast.java:170) [GuiIngredientFast.class:?]
	at mezz.jei.gui.ingredients.GuiIngredientFastList.render(GuiIngredientFastList.java:194) [GuiIngredientFastList.class:?]
	at mezz.jei.gui.ItemListOverlayInternal.drawScreen(ItemListOverlayInternal.java:305) [ItemListOverlayInternal.class:?]
	at mezz.jei.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:89) [GuiEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_718_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:590) [bft.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:73) [bgl.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382) [ForgeHooksClient.class:?]
	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at Reflector.callVoid(Reflector.java:512) [Reflector.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1398) [bnz.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at codechicken.lib.render.pipeline.CCRenderPipeline.rebuild(CCRenderPipeline.java:120) ~[CCRenderPipeline.class:?]
	at codechicken.lib.render.pipeline.CCRenderPipeline.setPipeline(CCRenderPipeline.java:78) ~[CCRenderPipeline.class:?]
	at codechicken.lib.render.CCRenderState.setPipeline(CCRenderState.java:120) ~[CCRenderState.class:?]
	at codechicken.lib.render.CCRenderState.render(CCRenderState.java:161) ~[CCRenderState.class:?]
	at codechicken.microblock.MicroblockRender$$anonfun$renderCuboid$2$$anonfun$apply$mcVI$sp$1.apply(MicroblockRender.scala:63) ~[MicroblockRender$$anonfun$renderCuboid$2$$anonfun$apply$mcVI$sp$1.class:?]
	at codechicken.microblock.MicroblockRender$$anonfun$renderCuboid$2$$anonfun$apply$mcVI$sp$1.apply(MicroblockRender.scala:62) ~[MicroblockRender$$anonfun$renderCuboid$2$$anonfun$apply$mcVI$sp$1.class:?]
	at scala.collection.immutable.List.foreach(List.scala:383) ~[List.class:?]
	at codechicken.microblock.MicroblockRender$$anonfun$renderCuboid$2.apply$mcVI$sp(MicroblockRender.scala:62) ~[MicroblockRender$$anonfun$renderCuboid$2.class:?]
	at codechicken.microblock.MicroblockRender$$anonfun$renderCuboid$2.apply(MicroblockRender.scala:59) ~[MicroblockRender$$anonfun$renderCuboid$2.class:?]
	at codechicken.microblock.MicroblockRender$$anonfun$renderCuboid$2.apply(MicroblockRender.scala:59) ~[MicroblockRender$$anonfun$renderCuboid$2.class:?]
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778) ~[TraversableLike$WithFilter$$anonfun$foreach$1.class:?]
	at scala.collection.immutable.Range.foreach(Range.scala:160) ~[Range.class:?]
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777) ~[TraversableLike$WithFilter.class:?]
	at codechicken.microblock.MicroblockRender$.renderCuboid(MicroblockRender.scala:59) ~[MicroblockRender$.class:?]
	at codechicken.microblock.FaceMicroblockClient$class.render(FaceMicroblock.scala:55) ~[FaceMicroblockClient$class.class:?]
	at Microblock_cmp$$0.render(Unknown Source) ~[?:?]
	at codechicken.microblock.ItemMicroPartRenderer$.renderItem(ItemMicroPart.scala:191) ~[ItemMicroPartRenderer$.class:?]
	at codechicken.lib.render.item.CCRenderItem.func_180454_a(CCRenderItem.java:86) ~[CCRenderItem.class:?]
	at codechicken.lib.render.item.CCRenderItem.func_184390_a(CCRenderItem.java:167) ~[CCRenderItem.class:?]
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:231) ~[CCRenderItem.class:?]
	... 27 more`

It's definitely not an issue of mine. As you said looks like it's either caused by CodeChickenCore or ForgeMultipart. Maybe try to update both, if it still occurs report it to their authors.
