### ISSUE TITLE
Crashing everytime i use any little tiles tool

### ISSUE THREAD

**Issue by Codysang** [CreativeMD/LittleTiles#350]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LittlePatchingLoader (LittleTiles_v1.5.0-pre135_mc1.12.2.jar)
  CreativePatchingLoader (CreativeCore-1.12.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 3/4/20 12:12 AM
Description: Unexpected error

java.lang.NoClassDefFoundError: com/creativemd/creativecore/client/rendering/model/CreativeCubeConsumer
	at com.creativemd.littletiles.client.render.RenderingThread.<init>(RenderingThread.java:342)
	at com.creativemd.littletiles.client.render.RenderingThread.initThreads(RenderingThread.java:88)
	at com.creativemd.littletiles.client.render.RenderingThread.<clinit>(RenderingThread.java:128)
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.addToRenderUpdate(TileEntityLittleTiles.java:388)
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.updateCustomRenderer(TileEntityLittleTiles.java:365)
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.updateTiles(TileEntityLittleTiles.java:351)
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.combineTiles(TileEntityLittleTiles.java:876)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.placeTiles(LittleActionPlaceStack.java:275)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.placeTiles(LittleActionPlaceStack.java:332)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.placeTile(LittleActionPlaceStack.java:164)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.action(LittleActionPlaceStack.java:113)
	at com.creativemd.littletiles.common.action.LittleAction.execute(LittleAction.java:179)
	at com.creativemd.littletiles.common.events.LittleEvent.onRightInteractClient(LittleEvent.java:279)
	at com.creativemd.littletiles.common.events.LittleEvent.onInteract(LittleEvent.java:263)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_185_LittleEvent_onInteract_RightClickBlock.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1137)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:398)
	at net.optifine.override.PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.creativemd.creativecore.client.rendering.model.CreativeCubeConsumer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 33 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.creativemd.littletiles.client.render.RenderingThread.<init>(RenderingThread.java:342)
	at com.creativemd.littletiles.client.render.RenderingThread.initThreads(RenderingThread.java:88)
	at com.creativemd.littletiles.client.render.RenderingThread.<clinit>(RenderingThread.java:128)
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.addToRenderUpdate(TileEntityLittleTiles.java:388)
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.updateCustomRenderer(TileEntityLittleTiles.java:365)
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.updateTiles(TileEntityLittleTiles.java:351)
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.combineTiles(TileEntityLittleTiles.java:876)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.placeTiles(LittleActionPlaceStack.java:275)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.placeTiles(LittleActionPlaceStack.java:332)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.placeTile(LittleActionPlaceStack.java:164)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.action(LittleActionPlaceStack.java:113)
	at com.creativemd.littletiles.common.action.LittleAction.execute(LittleAction.java:179)
	at com.creativemd.littletiles.common.events.LittleEvent.onRightInteractClient(LittleEvent.java:279)
	at com.creativemd.littletiles.common.events.LittleEvent.onInteract(LittleEvent.java:263)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_185_LittleEvent_onInteract_RightClickBlock.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1137)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:398)
	at net.optifine.override.PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['codysan327'/395, l='MpServer', x=-3689.10, y=71.00, z=-2331.93]]
	Chunk stats: MultiplayerChunkCache: 1089, 1089
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (208,64,256), Chunk: (at 0,4,0 in 13,16; contains blocks 208,0,256 to 223,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 160873 game time, 97341 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 38 total; [EntityBat['Bat'/448, l='MpServer', x=-3723.08, y=42.01, z=-2384.80], EntityBat['Bat'/461, l='MpServer', x=-3718.39, y=53.53, z=-2276.36], EntitySheep['Sheep'/462, l='MpServer', x=-3713.85, y=70.00, z=-2305.83], EntitySheep['Sheep'/463, l='MpServer', x=-3732.21, y=67.00, z=-2311.47], EntityBat['Bat'/464, l='MpServer', x=-3715.73, y=29.03, z=-2353.88], EntityMinecartChest['Minecart with Chest'/465, l='MpServer', x=-3721.50, y=32.06, z=-2342.50], EntityMinecartChest['Minecart with Chest'/466, l='MpServer', x=-3719.50, y=32.06, z=-2335.50], EntitySheep['Sheep'/471, l='MpServer', x=-3699.45, y=70.00, z=-2289.79], EntitySheep['Sheep'/472, l='MpServer', x=-3707.82, y=70.00, z=-2294.76], EntityBat['Bat'/536, l='MpServer', x=-3620.43, y=23.15, z=-2309.12], EntitySheep['Sheep'/473, l='MpServer', x=-3706.21, y=70.00, z=-2295.46], EntitySheep['Sheep'/474, l='MpServer', x=-3701.31, y=70.00, z=-2302.67], EntitySheep['Sheep'/475, l='MpServer', x=-3703.22, y=70.00, z=-2302.83], EntityMinecartChest['Minecart with Chest'/415, l='MpServer', x=-3757.51, y=31.00, z=-2381.89], EntityMinecartChest['Minecart with Chest'/481, l='MpServer', x=-3693.50, y=37.06, z=-2402.50], EntityPlayerSP['codysan327'/395, l='MpServer', x=-3689.10, y=71.00, z=-2331.93], EntityMinecartChest['Minecart with Chest'/425, l='MpServer', x=-3747.50, y=25.06, z=-2321.50], EntityBat['Bat'/489, l='MpServer', x=-3666.91, y=39.17, z=-2401.38], EntitySquid['Squid'/426, l='MpServer', x=-3754.67, y=62.13, z=-2332.84], EntityChicken['Chicken'/490, l='MpServer', x=-3656.50, y=88.00, z=-2324.50], EntityChicken['Chicken'/491, l='MpServer', x=-3655.77, y=87.00, z=-2320.83], EntityMinecartChest['Minecart with Chest'/428, l='MpServer', x=-3747.50, y=31.06, z=-2291.50], EntityChicken['Chicken'/492, l='MpServer', x=-3657.50, y=87.00, z=-2322.50], EntityBat['Bat'/429, l='MpServer', x=-3735.95, y=35.87, z=-2373.22], EntityChicken['Chicken'/493, l='MpServer', x=-3657.50, y=87.00, z=-2320.50], EntityMinecartChest['Minecart with Chest'/430, l='MpServer', x=-3741.50, y=30.06, z=-2387.50], EntitySquid['Squid'/494, l='MpServer', x=-3657.77, y=60.13, z=-2385.06], EntitySheep['Sheep'/436, l='MpServer', x=-3735.53, y=65.00, z=-2255.29], EntitySheep['Sheep'/501, l='MpServer', x=-3669.49, y=65.00, z=-2257.48], EntitySheep['Sheep'/441, l='MpServer', x=-3741.50, y=63.00, z=-2253.50], EntitySquid['Squid'/505, l='MpServer', x=-3637.31, y=62.58, z=-2376.02], EntitySquid['Squid'/506, l='MpServer', x=-3637.93, y=61.30, z=-2385.06], EntityItem['item.item.rustic.chili_pepper_seeds'/507, l='MpServer', x=-3642.84, y=61.00, z=-2365.76], EntityBat['Bat'/444, l='MpServer', x=-3746.93, y=31.75, z=-2294.08], EntitySheep['Sheep'/508, l='MpServer', x=-3619.24, y=64.00, z=-2335.50], EntitySheep['Sheep'/445, l='MpServer', x=-3738.50, y=63.00, z=-2341.50], EntityBat['Bat'/446, l='MpServer', x=-3728.13, y=30.05, z=-2305.47], EntitySheep['Sheep'/447, l='MpServer', x=-3736.43, y=68.00, z=-2318.80]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 993812176 bytes (947 MB) / 2013265920 bytes (1920 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 20 mods loaded, 20 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version               | Source                                        | Signature |
	|:------ |:----------------- |:--------------------- |:--------------------------------------------- |:--------- |
	| LCHIJA | minecraft         | 1.12.2                | minecraft.jar                                 | None      |
	| LCHIJA | mcp               | 9.42                  | minecraft.jar                                 | None      |
	| LCHIJA | FML               | 8.0.99.99             | forge-1.12.2-14.23.5.2847.jar                 | None      |
	| LCHIJA | forge             | 14.23.5.2847          | forge-1.12.2-14.23.5.2847.jar                 | None      |
	| LCHIJA | creativecoredummy | 1.0.0                 | minecraft.jar                                 | None      |
	| LCHIJA | littletilescore   | 1.0.0                 | minecraft.jar                                 | None      |
	| LCHIJA | architecturecraft | @VERSION@             | architecturecraft-1.12-3.98.jar               | None      |
	| LCHIJA | bibliocraft       | 2.4.5                 | BiblioCraft[v2.4.5][MC1.12.2].jar             | None      |
	| LCHIJA | biomesoplenty     | 7.0.1.2441            | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar | None      |
	| LCHIJA | blockcraftery     | 1.12.2-1.3.1          | blockcraftery-1.12.2-1.3.1.jar                | None      |
	| LCHIJA | chiselsandbits    | 14.33                 | chiselsandbits-14.33.jar                      | None      |
	| LCHIJA | creativecore      | 1.9.9                 | CreativeCore-1.12.2.jar                       | None      |
	| LCHIJA | cfm               | 6.3.1                 | furniture-6.3.1-1.12.2.jar                    | None      |
	| LCHIJA | jei               | 4.15.0.291            | jei_1.12.2-4.15.0.291.jar                     | None      |
	| LCHIJA | journeymap        | 1.12.2-5.5.9          | journeymap-1.12.2-5.5.9.jar                   | None      |
	| LCHIJA | littletiles       | 1.5.0                 | LittleTiles_v1.5.0-pre135_mc1.12.2.jar        | None      |
	| LCHIJA | malisiscore       | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                  | None      |
	| LCHIJA | malisisdoors      | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                 | None      |
	| LCHIJA | rustic            | 1.1.2                 | rustic-1.1.2.jar                              | None      |
	| LCHIJA | mysticallib       | 1.12.2-1.3.1          | mysticallib-1.12.2-1.3.1.jar                  | None      |

	Loaded coremods (and transformers): 
LittlePatchingLoader (LittleTiles_v1.5.0-pre135_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
CreativePatchingLoader (CreativeCore-1.12.2.jar)
  
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13586 Compatibility Profile Context 20.1.3 26.20.15015.1007' Renderer: 'AMD Radeon(TM) Vega 3 Graphics'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: AMD Radeon(TM) Vega 3 Graphics GL version 4.6.13586 Compatibility Profile Context 20.1.3 26.20.15015.1007, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx 
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13586 Compatibility Profile Context 20.1.3 26.20.15015.1007
	OpenGlRenderer: AMD Radeon(TM) Vega 3 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by CreativeMD** [comment]
Please don't download mods from 9minecraft, use curseforge instead.
https://www.curseforge.com/minecraft/mc-mods/creativecore
https://www.curseforge.com/minecraft/mc-mods/littletiles
