### ISSUE TITLE
Client crush on placing item with wrong NBT

### ISSUE THREAD

**Issue by Krutoy242** [CreativeMD/LittleTiles#364]
I created item with CraftTweaker command
`/ct give <littletiles:premade>.withTag({structure: {id: "workbench"}})`
and got invisible item in hand. When i try to place it, client crushed
```
java.lang.NullPointerException: Unexpected error
	at com.creativemd.littletiles.common.tile.preview.LittlePreviewsStructure.getStructure(LittlePreviewsStructure.java:45)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.placeTile(LittleActionPlaceStack.java:156)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.action(LittleActionPlaceStack.java:122)
```

**LittleTiles Version:** LittleTiles_v1.5.0-pre199_19_mc1.12.2

[Debug.log](https://mega.nz/#!Ml1XjbDC!B1SJscAzLlwph66V7oYF3G40O33n_yQcOKw6aF7sM7c)

**Comment by CreativeMD** [comment]
You can't do that. You have to include the tiles itself in the preview as well. You can find the proper nbt tag in the mod jar (in assets/littletiles/premade).
