### ISSUE TITLE
Crash on rendering chunk

### ISSUE THREAD

**Issue by WillisShek** [CreativeMD/LittleTiles#386]
crash report: https://paste.dimdev.org/apalisoboh.mccrash

Not sure what caused it. Some smaller crashes happened before but they didn't crash the client with VanillaFix. However, the above crash successfully crashed the client. I am not sure whether they are related.

For your reference, those smaller crashes are like the follows.

```
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 2020-04-19 22:54:06 AEST
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
    at com.creativemd.littletiles.common.packet.LittlePlacedAnimationPacket.executeClient(LittlePlacedAnimationPacket.java:80)
    at com.creativemd.creativecore.common.packet.PacketReciever$1.run(PacketReciever.java:86)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(SourceFile:529)
```

Thanks for your great mod.

**Comment by CreativeMD** [comment]
First issue will be fixed in the next pre-release
Second issue has been already fixed and will also be part of the next pre-release.

**Comment by CreativeMD** [comment]
New release is out now!
