### ISSUE TITLE
When I clicked the pivot door, game crashed

### ISSUE THREAD

**Issue by LuZWCHA** [CreativeMD/LittleTiles#387]
Game crashed when I tried to click the door with item(a stack of snow may be) in my main hand, I'm sure the following error log will be useful .The Replay mod may cause this issue.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CorePlugin ([字体修复]SmoothFont-mc1.12.2-2.0.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre199_15_mc1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.10.3_mc1.12.2.jar)
  LoadingPlugin (replaymod-1.12.2-2.1.4.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 4/20/20 4:38 PM
Description: Unexpected error

java.lang.ClassCastException: net.minecraft.client.entity.EntityPlayerSP cannot be cast to net.minecraft.entity.player.EntityPlayerMP
	at com.creativemd.littletiles.common.action.LittleActionInteract.action(LittleActionInteract.java:99)
	at com.creativemd.littletiles.common.action.block.LittleActionActivated.action(LittleActionActivated.java:57)
	at com.creativemd.littletiles.common.action.LittleAction.execute(LittleAction.java:243)
	at com.creativemd.littletiles.common.block.BlockTile.onBlockActivatedClient(BlockTile.java:415)
	at com.creativemd.littletiles.common.block.BlockTile.func_180639_a(BlockTile.java:407)
	at com.creativemd.littletiles.common.entity.EntityAnimation.onRightClick(EntityAnimation.java:789)
	at com.creativemd.littletiles.client.world.LittleAnimationHandlerClient.rightClick(LittleAnimationHandlerClient.java:174)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_185_LittleAnimationHandlerClient_rightClick_PlayerInteractEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1137)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:398)
	at net.optifine.override.PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.creativemd.littletiles.common.action.LittleActionInteract.action(LittleActionInteract.java:99)
	at com.creativemd.littletiles.common.action.block.LittleActionActivated.action(LittleActionActivated.java:57)
	at com.creativemd.littletiles.common.action.LittleAction.execute(LittleAction.java:243)
	at com.creativemd.littletiles.common.block.BlockTile.onBlockActivatedClient(BlockTile.java:415)
	at com.creativemd.littletiles.common.block.BlockTile.func_180639_a(BlockTile.java:407)
	at com.creativemd.littletiles.common.entity.EntityAnimation.onRightClick(EntityAnimation.java:789)
	at com.creativemd.littletiles.client.world.LittleAnimationHandlerClient.rightClick(LittleAnimationHandlerClient.java:174)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_185_LittleAnimationHandlerClient_rightClick_PlayerInteractEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1137)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:398)
	at net.optifine.override.PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['O___Q'/34, l='MpServer', x=-884.96, y=13.31, z=874.30]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-704,4,827), Chunk: (at 0,0,11 in -44,51; contains blocks -704,0,816 to -689,255,831), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Level time: 8019785 game time, 6000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: spectator (ID 3). Hardcore: false. Cheats: false
	Forced entities: 32 total; [EntityAnimation['entity.animation.name'/0, l='MpServer', x=-885.00, y=12.00, z=873.00], EntityPainting['画'/1, l='MpServer', x=-884.00, y=23.00, z=882.97], EntityPig['pig_car_black'/2, l='MpServer', x=-864.94, y=12.00, z=872.57], EntityPainting['画'/3, l='MpServer', x=-867.50, y=22.00, z=871.03], EntityItemFrame['entity.ItemFrame.name'/4, l='MpServer', x=-874.50, y=15.50, z=888.97], EntityItemFrame['entity.ItemFrame.name'/5, l='MpServer', x=-876.50, y=15.50, z=888.97], EntityItemFrame['entity.ItemFrame.name'/6, l='MpServer', x=-878.50, y=15.50, z=888.97], EntityPainting['画'/7, l='MpServer', x=-867.00, y=15.50, z=887.97], EntityPainting['画'/8, l='MpServer', x=-863.50, y=22.00, z=871.03], EntityItemFrame['entity.ItemFrame.name'/9, l='MpServer', x=-841.97, y=24.50, z=802.50], EntityPainting['画'/10, l='MpServer', x=-834.03, y=24.50, z=803.00], EntityPainting['画'/11, l='MpServer', x=-831.50, y=23.00, z=795.03], EntityItemFrame['entity.ItemFrame.name'/12, l='MpServer', x=-830.50, y=22.50, z=800.03], EntityItemFrame['entity.ItemFrame.name'/13, l='MpServer', x=-828.50, y=22.50, z=800.03], EntityPig['pig_car_white'/14, l='MpServer', x=-818.92, y=12.00, z=859.06], EntityItemFrame['entity.ItemFrame.name'/15, l='MpServer', x=-826.97, y=15.50, z=882.50], EntityItemFrame['entity.ItemFrame.name'/16, l='MpServer', x=-826.97, y=15.50, z=880.50], EntityItemFrame['entity.ItemFrame.name'/18, l='MpServer', x=-787.50, y=23.50, z=806.97], EntityPainting['画'/19, l='MpServer', x=-796.50, y=14.00, z=878.03], EntityItemFrame['entity.ItemFrame.name'/20, l='MpServer', x=-797.50, y=15.50, z=876.97], EntityPainting['画'/21, l='MpServer', x=-771.00, y=15.50, z=802.03], EntityItemFrame['entity.ItemFrame.name'/22, l='MpServer', x=-781.50, y=15.50, z=813.97], EntityItemFrame['entity.ItemFrame.name'/23, l='MpServer', x=-783.50, y=15.50, z=813.97], EntityPainting['画'/24, l='MpServer', x=-770.03, y=22.00, z=805.50], EntityPainting['画'/25, l='MpServer', x=-776.97, y=23.00, z=805.00], EntityItemFrame['entity.ItemFrame.name'/27, l='MpServer', x=-764.50, y=15.50, z=809.03], EntityPainting['画'/28, l='MpServer', x=-765.50, y=15.50, z=807.97], EntityPainting['画'/29, l='MpServer', x=-738.50, y=22.00, z=809.97], EntityPainting['画'/30, l='MpServer', x=-743.97, y=23.00, z=878.50], EntityItemFrame['entity.ItemFrame.name'/31, l='MpServer', x=-739.50, y=23.50, z=873.97], EntityPainting['画'/33, l='MpServer', x=-733.50, y=23.00, z=879.97], EntityPlayerSP['O___Q'/34, l='MpServer', x=-884.96, y=13.31, z=874.30]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7212042704 bytes (6877 MB) / 10200547328 bytes (9728 MB) up to 10485760000 bytes (10000 MB)
	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx10000m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F4 30 mods loaded, 30 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                      | Version                    | Source                                                            | Signature                                |
	|:------ |:----------------------- |:-------------------------- |:----------------------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft               | 1.12.2                     | minecraft.jar                                                     | None                                     |
	| LCHIJA | mcp                     | 9.42                       | minecraft.jar                                                     | None                                     |
	| LCHIJA | FML                     | 8.0.99.99                  | forge-1.12.2-14.23.5.2847.jar                                     | None                                     |
	| LCHIJA | forge                   | 14.23.5.2847               | forge-1.12.2-14.23.5.2847.jar                                     | None                                     |
	| LCHIJA | smoothfontcore          | mc1.12.2-2.0               | minecraft.jar                                                     | None                                     |
	| LCHIJA | creativecoredummy       | 1.0.0                      | minecraft.jar                                                     | None                                     |
	| LCHIJA | littletilescore         | 1.0.0                      | minecraft.jar                                                     | None                                     |
	| LCHIJA | smoothfont              | mc1.12.2-2.0               | [字体修复]SmoothFont-mc1.12.2-2.0.jar                                 | None                                     |
	| LCHIJA | replaymod-compat        | 1.12.2-2.1.4               | replaymod-1.12.2-2.1.4.jar                                        | None                                     |
	| LCHIJA | replaymod               | 1.12.2-2.1.4               | replaymod-1.12.2-2.1.4.jar                                        | None                                     |
	| LCHIJA | replaymod-editor        | 1.12.2-2.1.4               | replaymod-1.12.2-2.1.4.jar                                        | None                                     |
	| LCHIJA | replaymod-extras        | 1.12.2-2.1.4               | replaymod-1.12.2-2.1.4.jar                                        | None                                     |
	| LCHIJA | replaymod-online        | 1.12.2-2.1.4               | replaymod-1.12.2-2.1.4.jar                                        | None                                     |
	| LCHIJA | replaymod-recording     | 1.12.2-2.1.4               | replaymod-1.12.2-2.1.4.jar                                        | None                                     |
	| LCHIJA | replaymod-render        | 1.12.2-2.1.4               | replaymod-1.12.2-2.1.4.jar                                        | None                                     |
	| LCHIJA | replaymod-replay        | 1.12.2-2.1.4               | replaymod-1.12.2-2.1.4.jar                                        | None                                     |
	| LCHIJA | replaymod-simplepathing | 1.12.2-2.1.4               | replaymod-1.12.2-2.1.4.jar                                        | None                                     |
	| LCHIJA | customstuff4            | 0.5.3                      | [ITP模组]customstuff4-1.12.2-0.5.3.jar                              | None                                     |
	| LCHIJA | itproject               | 0.0.1                      | [ITP模组]itproject-1.0.20200308.jar                                 | None                                     |
	| LCHIJA | worldedit               | 6.1.8                      | [小木斧]worldedit-forge-mc1.12-6.1.8-dist.jar                        | None                                     |
	| LCHIJA | worldeditcuife2         | 2.1.2-mf-1.12-14.21.0.2373 | [小木斧]WorldEdit CUI Forge Edition 2-2.1.2-mf-1.12-14.21.0.2373.jar | None                                     |
	| LCHIJA | journeymap              | 1.12.2-5.5.2               | [旅行地图]journeymap-1.12.2-5.5.2.jar                                 | None                                     |
	| LCHIJA | jei                     | 4.15.0.268                 | [物品管理]jei_1.12.2-4.15.0.268.jar                                   | None                                     |
	| LCHIJA | codechickenlib          | 3.2.2.354                  | CodeChickenLib-1.12.2-3.2.2.354-universal.jar                     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | creativecore            | 1.10.0                     | CreativeCore_v1.10.3_mc1.12.2.jar                                 | None                                     |
	| LCHIJA | forgemultipartcbe       | 2.6.1.81                   | ForgeMultipart-1.12.2-2.6.1.81-universal.jar                      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | microblockcbe           | 2.6.1.81                   | ForgeMultipart-1.12.2-2.6.1.81-universal.jar                      | None                                     |
	| LCHIJA | minecraftmultipartcbe   | 2.6.1.81                   | ForgeMultipart-1.12.2-2.6.1.81-universal.jar                      | None                                     |
	| LCHIJA | littletiles             | 1.5.0                      | LittleTiles_v1.5.0-pre199_15_mc1.12.2.jar                         | None                                     |
	| LCHIJA | mrtjpcore               | 2.1.3.35                   | MrTJPCore-1.12.2-2.1.3.35-universal.jar                           | None                                     |

	Loaded coremods (and transformers): 
CorePlugin ([字体修复]SmoothFont-mc1.12.2-2.0.jar)
  bre.smoothfont.asm.Transformer
LittlePatchingLoader (LittleTiles_v1.5.0-pre199_15_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
CreativePatchingLoader (CreativeCore_v1.10.3_mc1.12.2.jar)
  
LoadingPlugin (replaymod-1.12.2-2.1.4.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 436.30' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Launched Version: HMCL 3.2.130
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 436.30, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: IT-Project 128x V3, IT-Project 128x V3 CS4 Mod, IT-Project 128x V3 BumpMappingPack, IT-Project HQ-Plants V3
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A8-7650K Radeon R7, 10 Compute Cores 4C+6G 
	OptiFine Version: OptiFine_1.12.2_HD_U_F4
	OptiFine Build: 20191023-234904
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: SEUS PTGI E6
	OpenGlVersion: 4.6.0 NVIDIA 436.30
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
```

**Comment by CreativeMD** [comment]
Update to the newest version of CreativeCore and LittleTiles it should fix your issue.
