### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by MrRedstoneA1** [CreativeMD/LittleTiles#424]
Crashes on startup. Using MultiMC, no crash report provided by minecraft. Unfortunately I can't give much info here, but here's the crash report MultiMC produced. It should have everything like forge version, mod version and minecraft version as well as all the mods I'm using. Game loads fine without the mod.

MultiMC version: 0.6.11-1430

Minecraft folder is:
D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/instances/1.12.2/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_251, using 64-bit architecture.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/instances/1.12.2/natives

Libraries:
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2826/forge-1.12.2-14.23.5.2826-universal.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  [✔️] [1.12.2] SecurityCraft v1.8.17
  [✔️] [1.12]bspkrsCore-universal-7.6.0.1
  [✔️] __rzi_3384
  [✔️] backpack-3.0.2-1.12.2
  [✔️] betterinvisibility-1.12-1.0
  [✔️] Blur-1.0.4-14
  [✔️] CodeChickenLib-1.12.2-3.2.2.353-universal
  [📁] config (folder)
  [✔️] Decoration-Mega-Pack-Mod-1.12.2
  [✔️] DevicesMod-0.4.1-mc1.12.2
  [✔️] DynamicLights-1.12.2
  [✔️] DynamicSurroundings-1.12.2-3.6.0.2
  [✔️] ElevatorMod-1.12.2-1.3.13
  [✔️] Embassy_5.0-b19
  [✔️] filteredhopper-2.1.1
  [✔️] Flan.s.Mod-1.12.2-5.6
  [✔️] grapplemod-v11.1-1.12.2
  [✔️] iChunUtil-1.12.2-7.2.2
  [✔️] incontrol-1.12-3.9.16
  [✔️] jei_1.12.2-4.13.1.220
  [✔️] journeymap-1.12.2-5.7.1
  [✔️] LittleTiles_v1.5.0-pre199_34_mc1.12.2
  [✔️] lostcities-1.12-2.0.22
  [📁] memory_repo (folder)
  [✔️] ModularPowersuits-1.12.2
  [✔️] mw-Modern Warfare-1.11.7.7-1.12.2
  [✔️] MyChunkloader-1.12.2-01
  [✔️] NotEnoughItems-1.12.2-2.4.2.240-universal
  [✔️] Numina-1.12.2-1.0.38
  [✔️] omlib-1.12.2-3.1.3-246
  [✔️] openmodularturrets-1.12.2-3.1.4-356
  [✔️] OptiFine_1.12.2_HD_U_F5
  [✔️] OreLib-1.12.2-3.6.0.1
  [✔️] Realistic-Terrain-Generation-Mod-1.12.2
  [✔️] RoguelikeDungeons-1.12.2-1.8.0
  [✔️] Shatter-1.12.2-7.0.1
  [✔️] twilightforest-1.12.2-3.10.1013-universal

Params:
  --username  --version MultiMC5 --gameDir D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/instances/1.12.2/.minecraft --assetsDir D:/Program Files/MultiMC/mmc-stable-win32/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-Xmn768m, -XX:+DisableExplicitGC, -XX:+UseConcMarkSweepGC, -XX:+UseParNewGC, -XX:+UseNUMA, -XX:+CMSParallelRemarkEnabled, -XX:MaxTenuringThreshold=15, -XX:MaxGCPauseMillis=30, -XX:GCPauseIntervalMillis=150, -XX:+UseAdaptiveGCBoundary, -XX:-UseGCOverheadLimit, -XX:+UseBiasedLocking, -XX:SurvivorRatio=8, -XX:TargetSurvivorRatio=90, -XX:MaxTenuringThreshold=15, -Dfml.ignorePatchDiscrepancies=true, -Dfml.ignoreInvalidMinecraftCertificates=true, -XX:+UseFastAccessorMethods, -XX:+UseCompressedOops, -XX:+OptimizeStringConcat, -XX:+AggressiveOpts, -XX:ReservedCodeCacheSize=2048m, -XX:+UseCodeCacheFlushing, -XX:SoftRefLRUPolicyMSPerMB=10000, -XX:ParallelGCThreads=10, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2000m, -Xmx4000m, -Duser.language=en]

Minecraft process ID: 13996

Using onesix launcher.

[00:51:57] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[00:51:57] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[00:51:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[00:51:57] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2826 for Minecraft 1.12.2 loading
[00:51:57] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_251, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_251
[00:51:59] [main/INFO] [FML]: Searching D:\Program Files\MultiMC\mmc-stable-win32\MultiMC\instances\1.12.2\.minecraft\mods for mods
[00:51:59] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Blur-1.0.4-14.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:51:59] [main/WARN] [FML]: The coremod com.tterrag.blur.BlurPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[00:51:59] [main/WARN] [FML]: The coremod BlurPlugin (com.tterrag.blur.BlurPlugin) is not signed!
[00:51:59] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in DynamicLights-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:51:59] [main/WARN] [FML]: The coremod atomicstryker.dynamiclights.common.DLFMLCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[00:51:59] [main/WARN] [FML]: The coremod DLFMLCorePlugin (atomicstryker.dynamiclights.common.DLFMLCorePlugin) is not signed!
[00:51:59] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from DynamicSurroundings-1.12.2-3.6.0.2.jar
[00:51:59] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in LittleTiles_v1.5.0-pre199_34_mc1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:51:59] [main/WARN] [FML]: The coremod com.creativemd.littletiles.LittlePatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[00:51:59] [main/WARN] [FML]: The coremod LittlePatchingLoader (com.creativemd.littletiles.LittlePatchingLoader) is not signed!
[00:52:00] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at D:\Program Files\MultiMC\mmc-stable-win32\MultiMC\instances\1.12.2\.minecraft for Forge Mod Loader
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:111) ~[forge-1.12.2-14.23.5.2826-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:81) ~[forge-1.12.2-14.23.5.2826-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42) ~[forge-1.12.2-14.23.5.2826-universal.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:141) ~[forge-1.12.2-14.23.5.2826-universal.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: com/creativemd/littletiles/LittleTilesAfterTransformer
	at com.creativemd.littletiles.LittlePatchingLoader.getAccessTransformerClass(LittlePatchingLoader.java:39) ~[LittleTiles_v1.5.0-pre199_34_mc1.12.2.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:595) ~[forge-1.12.2-14.23.5.2826-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2826-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2826-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2826-universal.jar:?]
	... 13 more
Caused by: java.lang.ClassNotFoundException: com.creativemd.littletiles.LittleTilesAfterTransformer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at com.creativemd.littletiles.LittlePatchingLoader.getAccessTransformerClass(LittlePatchingLoader.java:39) ~[LittleTiles_v1.5.0-pre199_34_mc1.12.2.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:595) ~[forge-1.12.2-14.23.5.2826-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2826-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2826-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2826-universal.jar:?]
	... 13 more
Caused by: java.lang.NoClassDefFoundError: com/creativemd/creativecore/transformer/CreativeTransformer
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_251]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_251]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at com.creativemd.littletiles.LittlePatchingLoader.getAccessTransformerClass(LittlePatchingLoader.java:39) ~[LittleTiles_v1.5.0-pre199_34_mc1.12.2.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:595) ~[forge-1.12.2-14.23.5.2826-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2826-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2826-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2826-universal.jar:?]
	... 13 more
Caused by: java.lang.ClassNotFoundException: com.creativemd.creativecore.transformer.CreativeTransformer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_251]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_251]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at com.creativemd.littletiles.LittlePatchingLoader.getAccessTransformerClass(LittlePatchingLoader.java:39) ~[LittleTiles_v1.5.0-pre199_34_mc1.12.2.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:595) ~[forge-1.12.2-14.23.5.2826-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2826-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2826-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2826-universal.jar:?]
	... 13 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_251]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_251]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at com.creativemd.littletiles.LittlePatchingLoader.getAccessTransformerClass(LittlePatchingLoader.java:39) ~[LittleTiles_v1.5.0-pre199_34_mc1.12.2.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:595) ~[forge-1.12.2-14.23.5.2826-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2826-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2826-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2826-universal.jar:?]
	... 13 more
[00:52:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:199]: Failed to start Minecraft:
[00:52:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: java.lang.reflect.InvocationTargetException
[00:52:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:52:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[00:52:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[00:52:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[00:52:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[00:52:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[00:52:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[00:52:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[00:52:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[00:52:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[00:52:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[00:52:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.Runtime.exit(Unknown Source)
[00:52:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.System.exit(Unknown Source)
[00:52:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[00:52:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[00:52:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	... 8 more
[00:52:00] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[00:52:00] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[00:52:00] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[00:52:00] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[00:52:00] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[00:52:00] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[00:52:00] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)
Exception in thread "main" 
Process exited with code 1.

**Comment by MrRedstoneA1** [comment]
Problem solved. Accidentally put CreativeCore inside another mod archive. After putting it back inside the mods folder it started up. Sorry for the confusion.
