### ISSUE TITLE
my world will crash or a backup would bug my world by mixing the blocks

### ISSUE THREAD

**Issue by BnedysGmer324** [CreativeMD/LittleTiles#427]
crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (EluLib-1.12.2.jar)
  OpenEyePlugin (OpenEye-1.12.2-0.8.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre177_mc1.12.2.jar)
  ObfuscatePlugin (obfuscate-0.2.7-1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.10.16_mc1.12.2.jar)
  McLib core mod (mclib-1.0.4-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
  Techguns Core (techguns-1.12.2-2.0.1.2_1.jar)
  IGCMPatchingLoader (IGCM_v1.2.8_mc1.12.2.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
  BlockbusterCore (blockbuster-1.6.6-1.12.2.jar)
  ColorUtilityCorePlugin (ColorUtility-universal-1.0.4.jar)
  TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 6/19/20 7:14 PM
Description: Initializing game

java.lang.NoClassDefFoundError: com/creativemd/opf/OPFrame$1
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.creativemd.opf.OPFrame$1
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 38 more
Caused by: java.lang.NoClassDefFoundError: com/creativemd/littletiles/common/gui/handler/LittleGuiHandler
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 40 more
Caused by: java.lang.ClassNotFoundException: com.creativemd.littletiles.common.gui.handler.LittleGuiHandler
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 98555064 bytes (93 MB) / 405835776 bytes (387 MB) up to 12798132224 bytes (12205 MB)
	JVM Flags: 3 total; -Xmn128M -Xmx12217M -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F4 72 mods loaded, 70 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                           | Version               | Source                                   | Signature                                |
	|:----- |:-------------------------------------------- |:--------------------- |:---------------------------------------- |:---------------------------------------- |
	| LC    | minecraft                                    | 1.12.2                | minecraft.jar                            | None                                     |
	| LC    | mcp                                          | 9.42                  | minecraft.jar                            | None                                     |
	| LC    | FML                                          | 8.0.99.99             | forge-1.12.2-14.23.5.2847.jar            | None                                     |
	| LC    | forge                                        | 14.23.5.2847          | forge-1.12.2-14.23.5.2847.jar            | None                                     |
	| LC    | ColorUtility                                 | 1.0.4                 | minecraft.jar                            | None                                     |
	| LC    | creativecoredummy                            | 1.0.0                 | minecraft.jar                            | None                                     |
	| LC    | littletilescore                              | 1.0.0                 | minecraft.jar                            | None                                     |
	| LC    | OpenEye                                      | 0.8                   | OpenEye-1.12.2-0.8.jar                   | None                                     |
	| LC    | com.elytradev.movingworld.common.asm.coremod |                       | minecraft.jar                            | None                                     |
	| LC    | obfuscate                                    | 0.2.7                 | minecraft.jar                            | None                                     |
	| LC    | elucore                                      | 1.0                   | minecraft.jar                            | None                                     |
	| LC    | techguns_core                                | 1.12.2-1.0            | minecraft.jar                            | None                                     |
	| LC    | architecturecraft                            | @VERSION@             | architecturecraft-1.12-3.98.jar          | None                                     |
	| LC    | bibliocraft                                  | 2.4.5                 | BiblioCraft[v2.4.5][MC1.12.2].jar        | None                                     |
	| LC    | mclib                                        | 1.0.4                 | mclib-1.0.4-1.12.2.jar                   | None                                     |
	| LC    | moreplayermodels                             | 1.12.2                | More-Player-Models-Mod-1.12.2.jar        | None                                     |
	| LC    | metamorph                                    | 1.1.10                | metamorph-1.1.10-1.12.2.jar              | None                                     |
	| LC    | blockbuster                                  | 1.6.6                 | blockbuster-1.6.6-1.12.2.jar             | None                                     |
	| LC    | blockcraftery                                | 1.12.2-1.3.1          | blockcraftery-1.12.2-1.3.1.jar           | None                                     |
	| LC    | bnedysmod                                    | 1.0.0                 | BnedysMod v3.1.jar                       | None                                     |
	| LC    | bookworm                                     | 1.12.2-2.3.0          | bookworm-1.12.2-2.3.0.jar                | None                                     |
	| LC    | cdm                                          | 0.4.1                 | cdm-0.4.1-mc1.12.2.jar                   | None                                     |
	| LC    | cfm                                          | 6.2.0                 | cfm-6.2.0-mc1.12.2.jar                   | None                                     |
	| LC    | chameleon                                    | 1.12-4.1.3            | Chameleon-1.12-4.1.3.jar                 | None                                     |
	| LC    | ctm                                          | MC1.12.2-0.3.3.22     | CTM-MC1.12.2-0.3.3.22.jar                | None                                     |
	| LC    | chisel                                       | MC1.12.2-0.2.1.35     | Chisel-MC1.12.2-0.2.1.35.jar             | None                                     |
	| LC    | chiselsandbits                               | 14.26                 | Chisels-and-Bits-1.12.jar                | None                                     |
	| LC    | colored_water                                | 1.12.2-b37            | ColoredWater-1.12.2-b37.jar              | None                                     |
	| LC    | cookingforblockheads                         | 6.4.71                | CookingForBlockheads_1.12.2-6.4.71.jar   | None                                     |
	| LC    | igcm                                         | 1.2.2                 | IGCM_v1.2.8_mc1.12.2.jar                 | None                                     |
	| LC    | creativecore                                 | 1.10.0                | CreativeCore_v1.10.16_mc1.12.2.jar       | None                                     |
	| LC    | modcurrency                                  | 1.12-1.3.11           | Currency-1.12.0-1.3.11.jar               | None                                     |
	| LC    | customnpcs                                   | 1.12                  | CustomNPCs_1.12.2-(01Oct19).jar          | None                                     |
	| LC    | ptrmodellib                                  | 1.0.4                 | PTRLib-1.0.4.jar                         | None                                     |
	| LC    | props                                        | 2.6.3                 | Decocraft-2.6.3_1.12.2.jar               | None                                     |
	| LC    | doggytalents                                 | 1.15.1.4              | Doggy-Talents-Mod-1.12.2.jar             | None                                     |
	| LC    | fairylights                                  | 2.1.10                | fairylights-2.1.10-1.12.2.jar            | None                                     |
	| LC    | fcl                                          | 1.XII.48              | Fexcraft+Common+Library-1.XII.48.jar     | None                                     |
	| LC    | famm                                         | 3.2.2                 | FAMM-3.2.2.jar                           | None                                     |
	| LC    | fencejumper                                  | 1.0.5                 | fencejumper-1.12-1.0.5.jar               | None                                     |
	| LC    | tmt                                          | 1.4                   | Fexcraft+Common+Library-1.XII.48.jar     | None                                     |
	| LC    | flansmod                                     | 5.5.2                 | Flan's Mod-1.12.2-5.5.2.jar              | None                                     |
	| LC    | flansmodapocalypse                           | 1.0                   | Flan's Mod-1.12.2-5.5.2.jar              | None                                     |
	| LC    | foodexpansion                                | 1.3                   | FoodExpansion1.3.3-1.12.2.jar            | None                                     |
	| LC    | fvtm                                         | 3.2.40b               | FVTM-3.2.40b-1.12.2.jar                  | None                                     |
	| LC    | ichunutil                                    | 7.2.2                 | iChunUtil-1.12.2-7.2.2.jar               | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | littlelooter                                 | 1.1.5                 | LittleLooter-1.1.5.jar                   | None                                     |
	| LC    | littletiles                                  | 1.5.0                 | LittleTiles_v1.5.0-pre177_mc1.12.2.jar   | None                                     |
	| LC    | longerdays                                   | 1.0.4                 | longerdays-1.0.4.jar                     | None                                     |
	| LC    | lootoverhaul                                 | 1.2                   | LootOverhaul-1.2.jar                     | None                                     |
	| LC    | malisiscore                                  | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar             | None                                     |
	| LC    | malisisdoors                                 | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar            | None                                     |
	| LC    | movingworld                                  | 1.12-6.342            | movingworld-1.12-6.342-full.jar          | None                                     |
	| LC    | nifty                                        | 1.20.1                | NiftyBlocks-1.20.1.jar                   | None                                     |
	| L     | opframe                                      | 1.4.0                 | OnlinePicFrame_v1.4.26_mc1.12.2.jar      | None                                     |
	| L     | phonesalpha                                  | v1.10                 | pa1.9.10r.jar                            | None                                     |
	| L     | prefab                                       | 1.3.0.26              | prefab-1.3.0.26.jar                      | None                                     |
	| L     | scm                                          | 0.3.03                | SCM-v1.12.2-0.3.03.jar                   | None                                     |
	| L     | securitycraft                                | v1.8.9                | SecurityCraft-1.12.2.jar                 | None                                     |
	| L     | surge                                        | 2.0.77                | Surge-1.12.2-2.0.77.jar                  | None                                     |
	| L     | tails                                        | 1.12-1.10.0           | Tails-1.12-1.10.0.jar                    | None                                     |
	| L     | techguns                                     | 2.0.1.2               | techguns-1.12.2-2.0.1.2_1.jar            | None                                     |
	| L     | tlauncher_custom_cape_skin                   | 1.4                   | tlskincape_1.12.2-1.4.jar                | None                                     |
	| L     | travellersbackpack                           | 1.0.20.20             | TravellersBackpack-1.12.2-1.0.20.20.jar  | None                                     |
	| L     | variedcommodities                            | 1.12.2                | VariedCommodities_1.12.2(27oct19).jar    | None                                     |
	| L     | vehicle                                      | 0.43.4                | vehicle-mod-0.43.4-1.12.2.jar            | None                                     |
	| L     | worldedit                                    | 6.1.10                | worldedit-forge-mc1.12.2-6.1.10-dist.jar | None                                     |
	| L     | additions                                    | 0.5.1                 | Additions-0.5.1.jar                      | None                                     |
	| L     | elulib                                       | 0.1.12                | EluLib-1.12.2.jar                        | None                                     |
	| L     | mysticallib                                  | 1.12.2-1.3.2          | mysticallib-1.12.2-1.3.2.jar             | None                                     |
	| UD    | blockbuster_core                             | 1.6.6                 | minecraft.jar                            | None                                     |
	| UD    | mclib_core                                   | 1.0.4                 | minecraft.jar                            | None                                     |

	Loaded coremods (and transformers): 
FMLPlugin (EluLib-1.12.2.jar)
  elucent.elulib.asm.ASMTransformer
OpenEyePlugin (OpenEye-1.12.2-0.8.jar)
  openeye.asm.MultiTransformer
LittlePatchingLoader (LittleTiles_v1.5.0-pre177_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
ObfuscatePlugin (obfuscate-0.2.7-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
CreativePatchingLoader (CreativeCore_v1.10.16_mc1.12.2.jar)
  
McLib core mod (mclib-1.0.4-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
  
Techguns Core (techguns-1.12.2-2.0.1.2_1.jar)
  techguns.core.TechgunsASMTransformer
IGCMPatchingLoader (IGCM_v1.2.8_mc1.12.2.jar)
  com.creativemd.igcm.core.IGCMTransformer
MovingWorldCore (movingworld-1.12-6.342-full.jar)
  
BlockbusterCore (blockbuster-1.6.6-1.12.2.jar)
  mchorse.blockbuster.core.BBCoreClassTransformer
ColorUtilityCorePlugin (ColorUtility-universal-1.0.4.jar)
  com.Axeryok.ColorUtility.ColorUtilityTransformer
TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.15.4279' Renderer: 'Intel(R) HD Graphics 4400'
	Launched Version: ForgeOptiFine 1.12.2
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 10.18.15.4279, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (Canada)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F4
	OptiFine Build: 20191023-234904
	Render Distance Chunks: 7
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.3.0 - Build 10.18.15.4279
	OpenGlRenderer: Intel(R) HD Graphics 4400
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by CreativeMD** [comment]
Update LittleTiles and OnlinePictureFrame.
