### ISSUE TITLE
Crash upon loading minecraft

### ISSUE THREAD

**Issue by Luckyradkid1** [CreativeMD/LittleTiles#429]
i crash when i load up minecraft. i am using multiMC
here is crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.247.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.7.0-209-universal.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 4/25/20 10:54 AM
Description: Updating screen events

com.google.common.util.concurrent.ExecutionError: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2215)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.bake(ModelLoader.java:419)
	at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.bake(ModelLoader.java:719)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:180)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:808)
	at net.minecraftforge.fml.client.FMLClientHandler.refreshResources(FMLClientHandler.java:1128)
	at net.minecraftforge.fml.client.FMLClientHandler.lambda$scheduleResourcesRefresh$0(FMLClientHandler.java:1139)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at net.minecraft.client.Minecraft.func_152343_a(Minecraft.java:3146)
	at net.minecraft.client.Minecraft.func_152344_a(Minecraft.java:3168)
	at net.minecraftforge.fml.client.FMLClientHandler.scheduleResourcesRefresh(FMLClientHandler.java:1139)
	at net.minecraftforge.fml.client.FMLClientHandler.scheduleResourcesRefresh(FMLClientHandler.java:1134)
	at net.minecraft.client.settings.GameSettings.onGuiClosed(GameSettings.java:1480)
	at net.minecraft.client.gui.GuiVideoSettings.func_146281_b(GuiVideoSettings.java:126)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:989)
	at net.minecraft.client.gui.GuiVideoSettings.func_146284_a(GuiVideoSettings.java:78)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.GuiVideoSettings.func_73864_a(GuiVideoSettings.java:86)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiVideoSettings.func_146274_d(GuiVideoSettings.java:57)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at javax.vecmath.Matrix4f.clone(Matrix4f.java:3255)
	at net.minecraftforge.common.model.TRSRTransformation.getMatrix(TRSRTransformation.java:577)
	at net.minecraft.client.renderer.block.model.FaceBakery.rotateVertex(FaceBakery.java:220)
	at net.minecraft.client.renderer.block.model.FaceBakery.fillVertexData(FaceBakery.java:148)
	at net.minecraft.client.renderer.block.model.FaceBakery.makeQuadVertexData(FaceBakery.java:92)
	at net.minecraft.client.renderer.block.model.FaceBakery.makeBakedQuad(FaceBakery.java:64)
	at net.minecraft.client.renderer.block.model.ModelBakery.makeBakedQuad(ModelBakery.java:715)
	at net.minecraftforge.client.model.ModelLoader.access$600(ModelLoader.java:115)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.bakeNormal(ModelLoader.java:478)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.bakeImpl(ModelLoader.java:449)
	at net.minecraftforge.client.model.ModelLoader$VanillaLoader$1.load(ModelLoader.java:822)
	at net.minecraftforge.client.model.ModelLoader$VanillaLoader$1.load(ModelLoader.java:818)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.bake(ModelLoader.java:419)
	at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.bake(ModelLoader.java:719)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:180)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:808)
	at net.minecraftforge.fml.client.FMLClientHandler.refreshResources(FMLClientHandler.java:1128)
	at net.minecraftforge.fml.client.FMLClientHandler.lambda$scheduleResourcesRefresh$0(FMLClientHandler.java:1139)
	at net.minecraftforge.fml.client.FMLClientHandler$$Lambda$760/239561000.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at net.minecraft.client.Minecraft.func_152343_a(Minecraft.java:3146)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2215)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.bake(ModelLoader.java:419)
	at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.bake(ModelLoader.java:719)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:180)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:808)
	at net.minecraftforge.fml.client.FMLClientHandler.refreshResources(FMLClientHandler.java:1128)
	at net.minecraftforge.fml.client.FMLClientHandler.lambda$scheduleResourcesRefresh$0(FMLClientHandler.java:1139)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at net.minecraft.client.Minecraft.func_152343_a(Minecraft.java:3146)
	at net.minecraft.client.Minecraft.func_152344_a(Minecraft.java:3168)
	at net.minecraftforge.fml.client.FMLClientHandler.scheduleResourcesRefresh(FMLClientHandler.java:1139)
	at net.minecraftforge.fml.client.FMLClientHandler.scheduleResourcesRefresh(FMLClientHandler.java:1134)
	at net.minecraft.client.settings.GameSettings.onGuiClosed(GameSettings.java:1480)
	at net.minecraft.client.gui.GuiVideoSettings.func_146281_b(GuiVideoSettings.java:126)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:989)
	at net.minecraft.client.gui.GuiVideoSettings.func_146284_a(GuiVideoSettings.java:78)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.GuiVideoSettings.func_73864_a(GuiVideoSettings.java:86)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiVideoSettings.func_146274_d(GuiVideoSettings.java:57)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiVideoSettings

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['LuckyRad'/241, l='MpServer', x=-1595.53, y=82.00, z=-1565.13]]
	Chunk stats: MultiplayerChunkCache: 49, 49
	Level seed: 0
	Level generator: ID 07 - PlanetGen, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-97,64,217), Chunk: (at 15,4,9 in -7,13; contains blocks -112,0,208 to -97,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 5141938 game time, 1000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 7 total; [EntityBat['Bat'/23312, l='MpServer', x=-1591.29, y=47.37, z=-1571.00], EntityBat['Bat'/23282, l='MpServer', x=-1583.54, y=34.02, z=-1553.45], EntityBat['Bat'/23285, l='MpServer', x=-1593.62, y=32.15, z=-1569.23], EntityBat['Bat'/23286, l='MpServer', x=-1593.57, y=33.09, z=-1562.79], GCEntityClientPlayerMP['LuckyRad'/241, l='MpServer', x=-1595.53, y=82.00, z=-1565.13], EntitySquid['Squid'/23273, l='MpServer', x=-1606.77, y=31.16, z=-1580.36], EntityBat['Bat'/23419, l='MpServer', x=-1583.77, y=12.81, z=-1558.28]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 5.3.0-24-generic
	Java Version: 1.8.0_242, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 148977368 bytes (142 MB) / 970981376 bytes (926 MB) up to 970981376 bytes (926 MB)
	JVM Flags: 2 total; -Xms512m -Xmx1024m
	IntCache: cache: 0, tcache: 19, allocated: 5, tallocated: 47
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 32 mods loaded, 32 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                         | Version         | Source                                             | Signature                                |
	|:------ |:-------------------------- |:--------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                  | 1.12.2          | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp                        | 9.42            | minecraft.jar                                      | None                                     |
	| LCHIJA | FML                        | 8.0.99.99       | forge-1.12.2-14.23.5.2854-universal.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                      | 14.23.5.2854    | forge-1.12.2-14.23.5.2854-universal.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | advancedrocketrycore       | 1               | minecraft.jar                                      | None                                     |
	| LCHIJA | micdoodlecore              |                 | minecraft.jar                                      | None                                     |
	| LCHIJA | opencomputers|core         | 1.7.4.153       | minecraft.jar                                      | None                                     |
	| LCHIJA | redstoneflux               | 2.1.1           | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
	| LCHIJA | cofhcore                   | 4.6.6           | CoFHCore-1.12.2-4.6.6.1-universal.jar              | None                                     |
	| LCHIJA | libvulpes                  | 0.4.2.-74       | LibVulpes-1.12.2-0.4.2-74-universal.jar            | None                                     |
	| LCHIJA | advancedrocketry           | 1.7.0.-209      | AdvancedRocketry-1.12.2-1.7.0-209-universal.jar    | None                                     |
	| LCHIJA | opencomputers              | 1.7.4.153       | OpenComputers-MC1.12.2-1.7.4.153.jar               | None                                     |
	| LCHIJA | aunis                      | 1.9.5-beta      | aunis-1.12.2-1.9.5-beta.jar                        | None                                     |
	| LCHIJA | codechickenlib             | 3.2.3.358       | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | brandonscore               | 2.4.18          | BrandonsCore-1.12.2-2.4.18.210-universal.jar       | None                                     |
	| LCHIJA | cofhworld                  | 1.4.0           | CoFHWorld-1.12.2-1.4.0.1-universal.jar             | None                                     |
	| LCHIJA | thermalfoundation          | 2.6.7           | ThermalFoundation-1.12.2-2.6.7.1-universal.jar     | None                                     |
	| LCHIJA | draconicevolution          | 2.3.25          | Draconic-Evolution-1.12.2-2.3.25.351-universal.jar | None                                     |
	| LCHIJA | extrautils2                | 1.0             | extrautils2-1.12-1.9.9.jar                         | None                                     |
	| LCHIJA | forgemultipartcbe          | 2.6.2.83        | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | microblockcbe              | 2.6.2.83        | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | None                                     |
	| LCHIJA | minecraftmultipartcbe      | 2.6.2.83        | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | None                                     |
	| LCHIJA | galacticraftcore           | 4.0.2.247       | GalacticraftCore-1.12.2-4.0.2.247.jar              | None                                     |
	| LCHIJA | galacticraftplanets        | 4.0.2.247       | Galacticraft-Planets-1.12.2-4.0.2.247.jar          | None                                     |
	| LCHIJA | jei                        | 4.15.0.291      | jei_1.12.2-4.15.0.291.jar                          | None                                     |
	| LCHIJA | projectintelligence        | 1.0.9           | ProjectIntelligence-1.12.2-1.0.9.28-universal.jar  | None                                     |
	| LCHIJA | raumships                  | 1.3.4           | raumships-1.3.4.jar                                | None                                     |
	| LCHIJA | ruins                      | 17.1            | Ruins-1.12.2.jar                                   | None                                     |
	| LCHIJA | thermalexpansion           | 5.5.7           | ThermalExpansion-1.12.2-5.5.7.1-universal.jar      | None                                     |
	| LCHIJA | tlauncher_custom_cape_skin | 1.4             | tlskincape_1.12.2-1.4.jar                          | None                                     |
	| LCHIJA | translocators              | 2.5.2.81        | Translocators-1.12.2-2.5.2.81-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | worldedit                  | 6.1.10-SNAPSHOT | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar  | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.247.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.7.0-209-universal.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  li.cil.oc.common.asm.ClassTransformer
TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
	GL info: ' Vendor: 'X.Org' Version: '3.1 Mesa 19.0.8' Renderer: 'AMD TURKS (DRM 2.50.0 / 5.3.0-24-generic, LLVM 8.0.0)'
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: AMD TURKS (DRM 2.50.0 / 5.3.0-24-generic, LLVM 8.0.0) GL version 3.1 Mesa 19.0.8, X.Org
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-3540M CPU @ 3.00GHz
I know it is little tiles because when i take it out it runs fine

**Comment by kirokadura** [comment]
There's no mention of any of our mods in the crash report. It doesn't even mention it on the mod list. Furthermore, if you install LittleTiles, you gotta install CreativeCore as well, both downloaded from Curseforge.

**Comment by Luckyradkid1** [comment]
creativecore? oohhhh xD im so sorry i forgot xD

**Comment by Luckyradkid1** [comment]
ok its not crashing thank u!

**Comment by Luckyradkid1** [comment]
oh um when i go to the little tiles tab in crative mode it crashes, ill make a new issue for this because its not related to it crashing, i can go to search one and look up somehting from little tiles and it works

**Comment by FreezePhoenix** [comment]
You need to allocate more memory to the instance of MC.
