### ISSUE TITLE
Crash when opening the Little tiles tab in creative mode

### ISSUE THREAD

**Issue by Luckyradkid1** [CreativeMD/LittleTiles#431]
self explanitory, i am able to go to search bar and get like a hammer or something and no crash but the tab crashes here is crash log:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LittlePatchingLoader (LittleTiles_v1.5.0-pre199_25_mc1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.10.10_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 6/27/20 11:30 AM
Description: Rendering item

java.lang.NoSuchMethodError: com.creativemd.creativecore.client.rendering.RenderCubeObject.setKeepUV(Z)Lcom/creativemd/creativecore/client/rendering/RenderCubeObject;
	at com.creativemd.littletiles.common.structure.type.premade.signal.LittleSignalCable$LittleStructureTypeCable.getRenderingCubes(LittleSignalCable.java:54)
	at com.creativemd.littletiles.common.item.ItemPremadeStructure.getRenderingCubes(ItemPremadeStructure.java:53)
	at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.getBlockQuads(CreativeBakedModel.java:155)
	at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.func_188616_a(CreativeBakedModel.java:75)
	at net.minecraftforge.client.ForgeHooksClient.renderLitItem(ForgeHooksClient.java:653)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:118)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:106)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:149)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:308)
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:347)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.creativemd.littletiles.common.structure.type.premade.signal.LittleSignalCable$LittleStructureTypeCable.getRenderingCubes(LittleSignalCable.java:54)
	at com.creativemd.littletiles.common.item.ItemPremadeStructure.getRenderingCubes(ItemPremadeStructure.java:53)
	at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.getBlockQuads(CreativeBakedModel.java:155)
	at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.func_188616_a(CreativeBakedModel.java:75)
	at net.minecraftforge.client.ForgeHooksClient.renderLitItem(ForgeHooksClient.java:653)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:118)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:106)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:149)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:308)

-- Item being rendered --
Details:
	Item Type: com.creativemd.littletiles.common.item.ItemPremadeStructure@692c8530
	Registry Name: littletiles:premade
	Item Aux: 0
	Item NBT: {structure:{id:"single_cable1"}}
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:347)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (222, 56). Absolute: (668, 679)
	Screen size: Scaled: (534, 283). Absolute: (1600, 849). Scale factor of 3

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['LuckyRad'/757, l='MpServer', x=221.50, y=67.00, z=226.50]]
	Chunk stats: MultiplayerChunkCache: 121, 121
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (224,64,224), Chunk: (at 0,4,0 in 14,14; contains blocks 224,0,224 to 239,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 56 game time, 56 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 57 total; [EntityVillager['Villager'/8, l='MpServer', x=177.50, y=64.00, z=188.50], EntityVillager['Villager'/9, l='MpServer', x=178.50, y=64.00, z=188.50], EntityVillager['Villager'/10, l='MpServer', x=174.50, y=64.00, z=196.50], EntityVillager['Villager'/11, l='MpServer', x=181.50, y=64.00, z=196.50], EntityItem['item.item.seeds'/12, l='MpServer', x=174.37, y=17.00, z=239.13], EntityVillager['Villager'/18, l='MpServer', x=189.50, y=64.00, z=188.50], EntitySkeleton['Skeleton'/2066, l='MpServer', x=169.50, y=29.00, z=242.50], EntityVillager['Villager'/19, l='MpServer', x=192.50, y=64.00, z=196.50], EntityVillager['Villager'/22, l='MpServer', x=209.47, y=63.00, z=167.03], EntityVillager['Villager'/23, l='MpServer', x=202.44, y=65.00, z=172.66], EntityVillager['Villager'/24, l='MpServer', x=204.50, y=64.00, z=175.50], EntityVillager['Villager'/25, l='MpServer', x=212.50, y=64.00, z=173.50], EntityVillager['Villager'/26, l='MpServer', x=204.29, y=64.00, z=187.49], EntityVillager['Villager'/27, l='MpServer', x=203.95, y=64.00, z=188.62], EntityVillager['Villager'/30, l='MpServer', x=219.43, y=63.84, z=165.50], EntitySkeleton['Skeleton'/2078, l='MpServer', x=234.50, y=18.00, z=229.50], EntityVillager['Villager'/31, l='MpServer', x=224.53, y=64.00, z=170.46], EntityZombie['Zombie'/2079, l='MpServer', x=233.50, y=18.00, z=228.50], EntitySkeleton['Skeleton'/2080, l='MpServer', x=208.50, y=33.00, z=247.50], EntitySheep['Sheep'/34, l='MpServer', x=238.50, y=71.00, z=202.50], EntitySheep['Sheep'/35, l='MpServer', x=239.50, y=71.00, z=203.50], EntitySheep['Sheep'/36, l='MpServer', x=239.48, y=70.26, z=198.23], EntitySheep['Sheep'/37, l='MpServer', x=240.50, y=71.00, z=204.50], EntityItem['item.tile.mushroom'/39, l='MpServer', x=255.90, y=22.00, z=164.41], EntityItem['item.tile.mushroom'/40, l='MpServer', x=258.71, y=22.00, z=163.13], EntityItem['item.tile.mushroom'/41, l='MpServer', x=257.22, y=23.00, z=167.20], EntityItem['item.tile.mushroom'/42, l='MpServer', x=253.53, y=23.00, z=171.46], EntitySheep['Sheep'/43, l='MpServer', x=267.50, y=71.00, z=167.50], EntitySheep['Sheep'/44, l='MpServer', x=269.50, y=71.00, z=162.50], EntitySheep['Sheep'/45, l='MpServer', x=271.50, y=71.00, z=166.50], EntitySheep['Sheep'/46, l='MpServer', x=264.50, y=71.00, z=167.50], EntityZombie['Zombie'/2094, l='MpServer', x=283.50, y=30.00, z=222.50], EntitySkeleton['Skeleton'/2095, l='MpServer', x=282.50, y=30.00, z=221.50], EntitySkeleton['Skeleton'/2096, l='MpServer', x=285.50, y=30.00, z=223.50], EntityPlayerSP['LuckyRad'/757, l='MpServer', x=221.50, y=67.00, z=226.50], EntityCreeper['Creeper'/2115, l='MpServer', x=258.50, y=22.00, z=189.50], EntitySkeleton['Skeleton'/2121, l='MpServer', x=214.50, y=15.00, z=279.50], EntityBat['Bat'/2164, l='MpServer', x=259.87, y=21.13, z=232.87], EntityCreeper['Creeper'/2169, l='MpServer', x=161.50, y=17.00, z=222.50], EntitySkeleton['Skeleton'/2181, l='MpServer', x=214.50, y=33.00, z=229.50], EntitySquid['Squid'/1210, l='MpServer', x=156.09, y=60.53, z=271.91], EntitySquid['Squid'/1220, l='MpServer', x=176.40, y=51.74, z=282.54], EntitySquid['Squid'/1226, l='MpServer', x=176.18, y=52.70, z=224.16], EntitySquid['Squid'/1227, l='MpServer', x=171.22, y=51.31, z=224.75], EntitySquid['Squid'/1228, l='MpServer', x=171.21, y=52.00, z=226.60], EntitySquid['Squid'/1229, l='MpServer', x=175.64, y=50.88, z=220.76], EntityCreeper['Creeper'/1405, l='MpServer', x=265.50, y=20.00, z=192.50], EntityBat['Bat'/1964, l='MpServer', x=277.50, y=30.10, z=226.75], EntityBat['Bat'/1966, l='MpServer', x=275.32, y=29.88, z=224.68], EntityBat['Bat'/1974, l='MpServer', x=246.11, y=21.81, z=225.53], EntitySkeleton['Skeleton'/1998, l='MpServer', x=232.50, y=17.00, z=211.50], EntityCreeper['Creeper'/1999, l='MpServer', x=276.50, y=14.00, z=220.50], EntitySkeleton['Skeleton'/1503, l='MpServer', x=194.50, y=44.00, z=266.50], EntityWitch['Witch'/1504, l='MpServer', x=191.50, y=44.00, z=264.50], EntityBat['Bat'/2017, l='MpServer', x=208.83, y=34.02, z=220.45], EntityBat['Bat'/2029, l='MpServer', x=258.51, y=16.04, z=216.78], EntityBat['Bat'/2040, l='MpServer', x=190.08, y=44.03, z=263.90]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 5.3.0-24-generic
	Java Version: 1.8.0_242, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 3128760072 bytes (2983 MB) / 4123525120 bytes (3932 MB) up to 4123525120 bytes (3932 MB)
	JVM Flags: 2 total; -Xms4096m -Xmx4096m
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version      | Source                                    | Signature                                |
	|:------ |:----------------- |:------------ |:----------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft         | 1.12.2       | minecraft.jar                             | None                                     |
	| LCHIJA | mcp               | 9.42         | minecraft.jar                             | None                                     |
	| LCHIJA | FML               | 8.0.99.99    | forge-1.12.2-14.23.5.2854-universal.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge             | 14.23.5.2854 | forge-1.12.2-14.23.5.2854-universal.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy | 1.0.0        | minecraft.jar                             | None                                     |
	| LCHIJA | littletilescore   | 1.0.0        | minecraft.jar                             | None                                     |
	| LCHIJA | redstoneflux      | 2.1.0        | RedstoneFlux-1.12-2.1.0.6-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | cofhcore          | 4.6.3        | CoFHCore-1.12.2-4.6.3.27-universal.jar    | None                                     |
	| LCHIJA | aunis             | 1.9.9-beta   | aunis-1.12.2-1.9.9-beta.jar               | None                                     |
	| LCHIJA | creativecore      | 1.10.0       | CreativeCore_v1.10.10_mc1.12.2.jar        | None                                     |
	| LCHIJA | littletiles       | 1.5.0        | LittleTiles_v1.5.0-pre199_25_mc1.12.2.jar | None                                     |

	Loaded coremods (and transformers): 
LittlePatchingLoader (LittleTiles_v1.5.0-pre199_25_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
CreativePatchingLoader (CreativeCore_v1.10.10_mc1.12.2.jar)
  
	GL info: ' Vendor: 'X.Org' Version: '3.1 Mesa 19.0.8' Renderer: 'AMD TURKS (DRM 2.50.0 / 5.3.0-24-generic, LLVM 8.0.0)'
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: AMD TURKS (DRM 2.50.0 / 5.3.0-24-generic, LLVM 8.0.0) GL version 3.1 Mesa 19.0.8, X.Org
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Ressourcepack+moddé+V3.3+for+1.12.2+for+Aunis+v1.9.8.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-3540M CPU @ 3.00GHz

**Comment by kirokadura** [comment]
Update LittleTiles and CreativeCore.

**Comment by CreativeMD** [comment]
Yep that should fix your issue.
