### ISSUE TITLE
Better Foliage Mod Crash

### ISSUE THREAD

**Issue by RinseWernik420** [CreativeMD/LittleTiles#441]
Hey CreativeMD

I just downloaded your mod, and its awsome, but when i instal the Better Foliage mod, my game crashes. 
I downloaded the newest version of Tiny Tiles and CreativeCore.
LittleTiles_v1.5.0-pre199_34_mc1.12.2.jar
CreativeCore_v1.10.16_mc1.12.2.jar

On your Curse Forge page description, you said that deleting the LittleTilesCore v1.0.0.jar will fix the issue, but i cant find the LittleTilesCore v1.0.0.jar file. 

Here is my latest crash report,

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LittlePatchingLoader (LittleTiles_v1.5.0-pre199_34_mc1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.10.16_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 7/7/20 12:41 PM
Description: Updating screen events

java.lang.NoSuchFieldError: field_191308_b
	at net.optifine.config.ConnectedParser.parseEntities(ConnectedParser.java:1248)
	at net.optifine.shaders.EntityAliases.loadEntityAliases(EntityAliases.java:164)
	at net.optifine.shaders.EntityAliases.update(EntityAliases.java:89)
	at net.optifine.shaders.Shaders.loadShaderPackProperties(Shaders.java:1086)
	at net.optifine.shaders.Shaders.loadShaderPack(Shaders.java:948)
	at net.optifine.shaders.Shaders.setShaderPack(Shaders.java:871)
	at net.optifine.shaders.gui.GuiSlotShaders.selectIndex(GuiSlotShaders.java:91)
	at net.optifine.shaders.gui.GuiSlotShaders.func_148144_a(GuiSlotShaders.java:81)
	at net.minecraft.client.gui.GuiSlot.func_178039_p(GuiSlot.java:323)
	at net.optifine.shaders.gui.GuiShaders.func_146274_d(GuiShaders.java:117)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.optifine.config.ConnectedParser.parseEntities(ConnectedParser.java:1248)
	at net.optifine.shaders.EntityAliases.loadEntityAliases(EntityAliases.java:164)
	at net.optifine.shaders.EntityAliases.update(EntityAliases.java:89)
	at net.optifine.shaders.Shaders.loadShaderPackProperties(Shaders.java:1086)
	at net.optifine.shaders.Shaders.loadShaderPack(Shaders.java:948)
	at net.optifine.shaders.Shaders.setShaderPack(Shaders.java:871)
	at net.optifine.shaders.gui.GuiSlotShaders.selectIndex(GuiSlotShaders.java:91)
	at net.optifine.shaders.gui.GuiSlotShaders.func_148144_a(GuiSlotShaders.java:81)
	at net.minecraft.client.gui.GuiSlot.func_178039_p(GuiSlot.java:323)
	at net.optifine.shaders.gui.GuiShaders.func_146274_d(GuiShaders.java:117)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: net.optifine.shaders.gui.GuiShaders
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 360027944 bytes (343 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version      | Source                                    | Signature                                |
	|:------ |:----------------- |:------------ |:----------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft         | 1.12.2       | minecraft.jar                             | None                                     |
	| LCHIJA | mcp               | 9.42         | minecraft.jar                             | None                                     |
	| LCHIJA | FML               | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge             | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy | 1.0.0        | minecraft.jar                             | None                                     |
	| LCHIJA | littletilescore   | 1.0.0        | minecraft.jar                             | None                                     |
	| LCHIJA | creativecore      | 1.10.0       | CreativeCore_v1.10.16_mc1.12.2.jar        | None                                     |
	| LCHIJA | littletiles       | 1.5.0        | LittleTiles_v1.5.0-pre199_34_mc1.12.2.jar | None                                     |
	| LCHIJA | worldedit         | 6.1.10       | worldedit-forge-mc1.12.2-6.1.10-dist.jar  | None                                     |

	Loaded coremods (and transformers): 
LittlePatchingLoader (LittleTiles_v1.5.0-pre199_34_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
CreativePatchingLoader (CreativeCore_v1.10.16_mc1.12.2.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 445.75' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.75, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.27 Lite
	OpenGlVersion: 4.6.0 NVIDIA 445.75
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by CreativeMD** [comment]
This is an issue of Optifine, not related to LittleTiles.

**Comment by RinseWernik420** [comment]
i deleted optifine but is still crashes :(

**Comment by CreativeMD** [comment]
Than it must be a different crash. Can you send it?

**Comment by RinseWernik420** [comment]
I dont know how, but every time my minecraft crashes, i wont get a new crash report. i reinstalled minecraft but it still doesn't work, still wont give me a new crash report :|

**Comment by RinseWernik420** [comment]
And it only crashes with the Better Foliage mod

**Comment by CreativeMD** [comment]
Then send me the log file (it always generates). If it even crashes without LT installed you should rather contact the author of Better Foliage mod.

**Comment by RinseWernik420** [comment]
Yo mann, after 4 days i got it working XD. My Java version was outdated. Better Foliage mod needs Java 8, and the mod needs the Forgelin mod. Dont tell my way but it works :)
