### ISSUE TITLE
Game Crashes on start.

### ISSUE THREAD

**Issue by Jodoyledragon** [CreativeMD/LittleTiles#448]
I've been messing around alittle to see what the problem could be. I've started up forge normaly and it workes, I've started forge with other mods and have it work, I've redownloaded both forge and the mod but nothing works.

Here's the startup log if that helps.
21:17:59.208
at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2854.jar:?]
21:17:59.208
at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2854.jar:?]
21:17:59.230
at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2854.jar:?]
21:17:59.230
... 5 more
21:17:59.230
Exception in thread "main" [21:17:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
21:17:59.230
[21:17:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
21:17:59.230
[21:17:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
21:17:59.230
[21:17:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
21:17:59.230
[21:17:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
21:17:59.230
[21:17:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
21:17:59.230
[21:17:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
21:17:59.259
Process crashed with exit code 1

If there is a simple fix for this I would be delighted because this mod looks amazing and I would love to play it.

**Comment by kirokadura** [comment]
This doesn't help much. We'll need the full crash report before we can do anything.

**Comment by Jodoyledragon** [comment]
14:12:28.273
game
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
14:12:28.273
game
at com.creativemd.littletiles.LittlePatchingLoader.getAccessTransformerClass(LittlePatchingLoader.java:42) ~[LittleTiles+v1.5.0-pre31+mc1.12.2.jar:?]
14:12:28.273
game
at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:595) ~[forge-1.12.2-14.23.5.2854.jar:?]
14:12:28.273
game
at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2854.jar:?]
14:12:28.273
game
at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2854.jar:?]
14:12:28.273
game
at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2854.jar:?]
14:12:28.273
game
... 5 more
14:12:28.273
game
Exception in thread "main" [14:12:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
14:12:28.273
game
[14:12:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
14:12:28.273
game
[14:12:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
14:12:28.273
game
[14:12:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
14:12:28.273
game
[14:12:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
14:12:28.273
game
[14:12:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
14:12:28.273
game
[14:12:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
14:12:28.299
monitor
Process Monitor
Process crashed with exit code 1

I'm nor compleatly sure what ypou mean with a full crash report but I think you mean this.

**Comment by kirokadura** [comment]
Download the latest version of LittleTiles and CreativeCore from Curseforge.

**Comment by Jodoyledragon** [comment]
thank you.
