### ISSUE TITLE
A crash little tiles

### ISSUE THREAD

**Issue by BogdanHack** [CreativeMD/LittleTiles#480]
-- Head --
Thread: Client thread
Stacktrace:
	at com.creativemd.littletiles.client.LittleTilesClient.loadSide(LittleTilesClient.java:252)
	at com.creativemd.littletiles.LittleTiles.registerItems(LittleTiles.java:265)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_6_LittleTiles_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 144284608 bytes (137 MB) / 369098752 bytes (352 MB) up to 7616856064 bytes (7264 MB)
	JVM Flags: 8 total; -Xmn128M -Xmx7234M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                         | Version      | Source                             | Signature                                |
	|:----- |:-------------------------- |:------------ |:---------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                  | 1.12.2       | minecraft.jar                      | None                                     |
	| LCH   | mcp                        | 9.42         | minecraft.jar                      | None                                     |
	| LCH   | FML                        | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                      | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | creativecoredummy          | 1.0.0        | minecraft.jar                      | None                                     |
	| LCH   | littletilescore            | 1.0.0        | minecraft.jar                      | None                                     |
	| LCH   | creativecore               | 1.10.0       | CreativeCore_v1.10.20_mc1.12.2.jar | None                                     |
	| LCH   | littletiles                | 1.5.0        | LittleTiles-Mod-1.12.2.jar         | None                                     |
	| LCH   | tlauncher_custom_cape_skin | 1.4          | tlskincape_1.12.2-1.4.jar          | None                                     |

	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore_v1.10.20_mc1.12.2.jar)
  
TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
LittlePatchingLoader (LittleTiles-Mod-1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13587 Compatibility Profile Context 20.4.2 26.20.15029.27017' Renderer: 'AMD Radeon R7 200 Series'
	Launched Version: Forge 1.12.2
	LWJGL: 2.9.4
	OpenGL: AMD Radeon R7 200 Series GL version 4.6.13587 Compatibility Profile Context 20.4.2 26.20.15029.27017, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/?lDefault?r..?l3D?r..High?0?o (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD Athlon(tm) X4 840 Quad Core Processor 
[12:15:48] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Administrator\AppData\Roaming\.minecraft\crash-reports\crash-2020-09-05_12.15.48-client.txt
Here I am!
[VersionManager] Refreshing versions locally...
[VersionManager] Versions has been refreshed (37 ms)
[Launcher] Launcher exited.
[Launcher] Minecraft closed with exit code: -1
flush now
[Launcher] [Crash] Found crash report file: C:\Users\Administrator\AppData\Roaming\.minecraft\crash-reports\crash-2020-09-05_12.08.59-client.txt
[Crash] Found crash report file: C:\Users\Administrator\AppData\Roaming\.minecraft\crash-reports\crash-2020-09-05_12.08.59-client.txt
[Launcher] [Crash] Found crash report file: C:\Users\Administrator\AppData\Roaming\.minecraft\crash-reports\crash-2020-09-05_12.15.48-client.txt
[Crash] Found crash report file: C:\Users\Administrator\AppData\Roaming\.minecraft\crash-reports\crash-2020-09-05_12.15.48-client.txt
[OS] Trying to open folder: C:\Users\Administrator\AppData\Roaming\.minecraft\
flush now
Showing error:
java.io.IOException: Error writing to server
at sun.net.www.protocol.http.HttpURLConnection.writeRequests(Unknown Source)
at sun.net.www.protocol.http.HttpURLConnection.writeRequests(Unknown Source)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
at net.minecraft.launcher.Http.performPost(Http.java:127)
at net.minecraft.launcher.Http.performPost(Http.java:141)
at net.minecraft.launcher.Http.performPost(Http.java:39)
at org.tlauncher.util.pastebin.Paste.doPaste(Paste.java:114)
at org.tlauncher.util.pastebin.Paste.paste(Paste.java:84)
at org.tlauncher.tlauncher.ui.console.Console$4.run(Console.java:195)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at org.tlauncher.util.async.RunnableThread.run(RunnableThread.java:15)
Thread called by: org.tlauncher.util.async.ExtendedThread$ExtendedThreadCaller
at org.tlauncher.util.async.ExtendedThread.<init>(ExtendedThread.java:17)
at org.tlauncher.util.async.ExtendedThread.<init>(ExtendedThread.java:21)
at org.tlauncher.util.async.RunnableThread.<init>(RunnableThread.java:7)
at org.tlauncher.util.async.AsyncThread$1.newThread(AsyncThread.java:12)
at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.addWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
at org.tlauncher.util.async.AsyncThread.execute(AsyncThread.java:17)
at org.tlauncher.tlauncher.ui.console.Console.sendPaste(Console.java:187)
at org.tlauncher.tlauncher.ui.console.ConsoleFrameBottom.lambda$new$1(ConsoleFrameBottom.java:38)
at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
at java.awt.Component.processMouseEvent(Unknown Source)
at javax.swing.JComponent.processMouseEvent(Unknown Source)
at java.awt.Component.processEvent(Unknown Source)
at java.awt.Container.processEvent(Unknown Source)
at java.awt.Component.dispatchEventImpl(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Window.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.awt.EventQueue.access$500(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue.dispatchEvent(Unknown Source)
at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by kirokadura** [comment]
Judging my the name of your LittleTiles mod file ("LittleTiles-Mod-1.12.2.jar"), I'll assume you didn't download it from Curseforge. Only download our mods from Curse.
