### ISSUE TITLE
Game keeps crashing when i try to join a server

### ISSUE THREAD

**Issue by SpicySauseSaig** [CreativeMD/LittleTiles#482]
I tried to import a item with the importer in a server with littletiles, and it keeps crashing when i try to rejoin. Any way to fix this? also, forge crash report.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre199_34_mc1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.10.16_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 9/10/20 7:21 PM
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: 1
	at com.creativemd.littletiles.common.tile.preview.LittlePreview.getBlockName(LittlePreview.java:109)
	at com.creativemd.littletiles.common.tile.preview.LittlePreview.getBlock(LittlePreview.java:113)
	at com.creativemd.littletiles.common.tile.preview.LittlePreview.getCubeBlock(LittlePreview.java:148)
	at com.creativemd.littletiles.common.tile.preview.LittlePreview.getCubes(LittlePreview.java:491)
	at com.creativemd.littletiles.common.tile.preview.LittlePreview.getCubes(LittlePreview.java:465)
	at com.creativemd.littletiles.common.item.ItemRecipeAdvanced.getRenderingCubes(ItemRecipeAdvanced.java:119)
	at com.creativemd.littletiles.common.item.ItemRecipeAdvanced.getRenderingCubes(ItemRecipeAdvanced.java:52)
	at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.getBlockQuads(CreativeBakedModel.java:155)
	at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.func_188616_a(CreativeBakedModel.java:75)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:168)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:136)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:216)
	at net.minecraft.client.renderer.RenderItem.func_184394_a(RenderItem.java:463)
	at net.minecraft.client.renderer.RenderItem.func_184392_a(RenderItem.java:426)
	at net.minecraft.client.renderer.ItemRenderer.func_187462_a(ItemRenderer.java:84)
	at net.minecraft.client.renderer.ItemRenderer.func_187457_a(ItemRenderer.java:472)
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:359)
	at net.minecraft.client.renderer.EntityRenderer.renderHand(EntityRenderer.java:1057)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:1001)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1973)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1384)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.creativemd.littletiles.common.tile.preview.LittlePreview.getBlockName(LittlePreview.java:109)
	at com.creativemd.littletiles.common.tile.preview.LittlePreview.getBlock(LittlePreview.java:113)
	at com.creativemd.littletiles.common.tile.preview.LittlePreview.getCubeBlock(LittlePreview.java:148)
	at com.creativemd.littletiles.common.tile.preview.LittlePreview.getCubes(LittlePreview.java:491)
	at com.creativemd.littletiles.common.tile.preview.LittlePreview.getCubes(LittlePreview.java:465)
	at com.creativemd.littletiles.common.item.ItemRecipeAdvanced.getRenderingCubes(ItemRecipeAdvanced.java:119)
	at com.creativemd.littletiles.common.item.ItemRecipeAdvanced.getRenderingCubes(ItemRecipeAdvanced.java:52)
	at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.getBlockQuads(CreativeBakedModel.java:155)
	at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.func_188616_a(CreativeBakedModel.java:75)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:168)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:136)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:216)
	at net.minecraft.client.renderer.RenderItem.func_184394_a(RenderItem.java:463)
	at net.minecraft.client.renderer.RenderItem.func_184392_a(RenderItem.java:426)
	at net.minecraft.client.renderer.ItemRenderer.func_187462_a(ItemRenderer.java:84)
	at net.minecraft.client.renderer.ItemRenderer.func_187457_a(ItemRenderer.java:472)
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:359)
	at net.minecraft.client.renderer.EntityRenderer.renderHand(EntityRenderer.java:1057)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:1001)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1973)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)

-- Affected level --
Details:
	Level name: MpServer
	All players: 3 total; [EntityPlayerSP['Spicy_SauseSaig'/274125, l='MpServer', x=-33895.91, y=65.00, z=322.55], EntityOtherPlayerMP['Skyscoot'/257886, l='MpServer', x=-34061.00, y=66.76, z=316.52], EntityOtherPlayerMP['Gooblet77'/271667, l='MpServer', x=-33896.71, y=65.00, z=317.16]]
	Chunk stats: MultiplayerChunkCache: 841, 841
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (1064,96,138), Chunk: (at 8,6,10 in 66,8; contains blocks 1056,0,128 to 1071,255,143), Region: (2,0; contains chunks 64,0 to 95,31, blocks 1024,0,0 to 1535,255,511)
	Level time: 273192946 game time, 570854 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: false
	Forced entities: 50 total; [EntityPlayerSP['Spicy_SauseSaig'/274125, l='MpServer', x=-33895.91, y=65.00, z=322.55], EntityOtherPlayerMP['Skyscoot'/257886, l='MpServer', x=-34061.00, y=66.76, z=316.52], EntityItem['item.item.porkchopRaw'/272654, l='MpServer', x=-33839.37, y=65.00, z=366.72], EntityItem['item.tile.sapling.birch'/272655, l='MpServer', x=-33832.13, y=65.00, z=306.38], EntityItem['item.item.feather'/272660, l='MpServer', x=-33853.19, y=65.00, z=307.62], EntityOtherPlayerMP['Gooblet77'/271667, l='MpServer', x=-33896.71, y=65.00, z=317.16], EntityItem['item.item.apple'/272661, l='MpServer', x=-33849.99, y=65.00, z=305.13], EntityChicken['Chicken'/272662, l='MpServer', x=-33845.50, y=76.00, z=287.50], EntityChicken['Chicken'/272663, l='MpServer', x=-33845.69, y=77.00, z=283.21], EntityChicken['Chicken'/272657, l='MpServer', x=-33844.40, y=76.00, z=288.24], EntityChicken['Chicken'/272658, l='MpServer', x=-33850.51, y=64.00, z=301.14], EntityChicken['Chicken'/272659, l='MpServer', x=-33851.81, y=64.00, z=301.59], EntityItem['item.item.porkchopRaw'/272668, l='MpServer', x=-33850.20, y=65.00, z=351.23], EntityChicken['Chicken'/272664, l='MpServer', x=-33846.20, y=77.00, z=283.88], EntityItem['item.item.porkchopRaw'/272665, l='MpServer', x=-33841.52, y=65.00, z=362.92], EntityItem['item.item.porkchopRaw'/272666, l='MpServer', x=-33849.38, y=65.00, z=376.46], EntityItem['item.tile.sapling.oak'/272667, l='MpServer', x=-33846.88, y=65.00, z=337.91], EntityItem['item.item.egg'/272676, l='MpServer', x=-33863.89, y=69.00, z=298.04], EntityChicken['Chicken'/272677, l='MpServer', x=-33864.64, y=70.00, z=283.74], EntitySheep['Sheep'/272678, l='MpServer', x=-33861.90, y=64.00, z=349.60], EntityItem['item.item.porkchopRaw'/272679, l='MpServer', x=-33859.11, y=65.00, z=343.90], EntityItem['item.item.chickenRaw'/272674, l='MpServer', x=-33856.12, y=65.00, z=307.34], EntityChicken['Chicken'/272675, l='MpServer', x=-33856.50, y=64.00, z=302.50], EntityItem['item.item.porkchopRaw'/272680, l='MpServer', x=-33863.12, y=65.00, z=351.30], EntitySheep['Sheep'/272681, l='MpServer', x=-33862.50, y=64.00, z=355.74], EntitySheep['Sheep'/272682, l='MpServer', x=-33857.62, y=64.00, z=361.55], EntitySheep['Sheep'/272683, l='MpServer', x=-33861.45, y=64.00, z=354.45], EntityChicken['Chicken'/272692, l='MpServer', x=-33877.50, y=71.00, z=283.86], EntityChicken['Chicken'/272688, l='MpServer', x=-33873.43, y=70.00, z=292.13], EntityItem['item.item.egg'/272689, l='MpServer', x=-33872.86, y=70.00, z=292.52], EntityItem['item.item.egg'/272690, l='MpServer', x=-33875.15, y=71.00, z=293.64], EntityOtherPlayerMP['Gooblet77'/271667, l='MpServer', x=-33896.71, y=65.00, z=317.16], EntityChicken['Chicken'/272691, l='MpServer', x=-33881.71, y=71.00, z=289.58], EntityPig['Pig'/272852, l='MpServer', x=-33969.50, y=71.00, z=269.50], EntityPig['Pig'/272853, l='MpServer', x=-33971.50, y=71.00, z=267.50], EntityPig['Pig'/272854, l='MpServer', x=-33975.50, y=70.00, z=268.84], EntityPig['Pig'/272855, l='MpServer', x=-33974.50, y=70.00, z=269.50], EntityItem['item.item.egg'/273488, l='MpServer', x=-33876.95, y=71.00, z=293.58], EntityOtherPlayerMP['Skyscoot'/257886, l='MpServer', x=-34061.00, y=66.76, z=316.52], EntityPig['Pig'/272857, l='MpServer', x=-33952.49, y=72.00, z=246.51], EntityPig['Pig'/272858, l='MpServer', x=-33953.31, y=72.00, z=247.58], EntityPig['Pig'/272877, l='MpServer', x=-33951.30, y=72.00, z=245.30], EntityPig['Pig'/272878, l='MpServer', x=-33950.50, y=72.00, z=246.50], EntityItem['item.item.porkchopRaw'/272879, l='MpServer', x=-33943.36, y=65.00, z=348.30], EntityItem['item.item.porkchopRaw'/272885, l='MpServer', x=-33942.55, y=65.00, z=353.58], EntityItem['item.item.porkchopRaw'/272886, l='MpServer', x=-33945.20, y=65.00, z=360.40], EntityItem['item.item.porkchopRaw'/272887, l='MpServer', x=-33941.39, y=65.00, z=378.37], EntityItem['item.item.porkchopRaw'/272880, l='MpServer', x=-33935.43, y=65.00, z=380.30], EntityItem['item.item.reeds'/272883, l='MpServer', x=-33954.26, y=65.00, z=381.37], EntityItem['item.item.porkchopRaw'/272888, l='MpServer', x=-33935.14, y=65.00, z=358.56]]
	Retry entities: 0 total; []
	Server brand: fml,forge,sponge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1078079768 bytes (1028 MB) / 3120562176 bytes (2976 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2844 Optifine OptiFine_1.12.2_HD_U_E3 23 mods loaded, 23 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version      | Source                                           | Signature                                |
	|:------ |:----------------- |:------------ |:------------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft         | 1.12.2       | minecraft.jar                                    | None                                     |
	| LCHIJA | mcp               | 9.42         | minecraft.jar                                    | None                                     |
	| LCHIJA | FML               | 8.0.99.99    | forge-1.12.2-14.23.5.2844.jar                    | None                                     |
	| LCHIJA | forge             | 14.23.5.2844 | forge-1.12.2-14.23.5.2844.jar                    | None                                     |
	| LCHIJA | creativecoredummy | 1.0.0        | minecraft.jar                                    | None                                     |
	| LCHIJA | littletilescore   | 1.0.0        | minecraft.jar                                    | None                                     |
	| LCHIJA | securitycraft     | v1.8.19.3    | 1.12.2SecurityCraftv1.8.19.3.jar                 | None                                     |
	| LCHIJA | craftpresence     | v1.7.0       | CraftPresence-Forge-1.12.2-Beta-1.7.0.jar        | eca02c6a597321ad22340897683951ba5c76720a |
	| LCHIJA | opframe           | 1.4.0        | OnlinePicFrame_v1.4.40_mc1.12.2.jar              | None                                     |
	| LCHIJA | creativecore      | 1.10.0       | CreativeCore_v1.10.16_mc1.12.2.jar               | None                                     |
	| LCHIJA | mts               | 18.5.0       | Immersive+Vehicles-1.12.2-18.5.0.jar             | None                                     |
	| LCHIJA | mtsofficialpack   | 16.0.0       | MTS_Official_Pack_V16.jar                        | None                                     |
	| LCHIJA | dwtmtspack        | 2.0.1        | DWTPack_V2.0.1.jar                               | None                                     |
	| LCHIJA | floodlights       | 1.4.4-22     | FloodLights-1.12.2-1.4.4-22.jar                  | None                                     |
	| LCHIJA | furenikusroads    | 1.1.6        | FurenikusRoads-1.1.6.jar                         | None                                     |
	| LCHIJA | ivairlinerpack    | 1.0.0        | Golden_Airport_Pack_Immersive_Vehicles_2.2.3.jar | None                                     |
	| LCHIJA | helicopterpack    | 0.1.0        | Helicopter_Pack-1.4.0.jar                        | None                                     |
	| LCHIJA | iv_tcp            | 1.0.0        | IV_Trin_Civil_Pack_(compact)_2.5.2.jar           | None                                     |
	| LCHIJA | journeymap        | 1.12.2-5.7.1 | journeymap-1.12.2-5.7.1.jar                      | None                                     |
	| LCHIJA | littletiles       | 1.5.0        | LittleTiles_v1.5.0-pre199_34_mc1.12.2.jar        | None                                     |
	| LCHIJA | sereneseasons     | 1.2.18       | SereneSeasons-1.12.2-1.2.18-universal.jar        | None                                     |
	| LCHIJA | unuparts          | 3.5.0        | UNU+Parts+Pack+[MTS]+1.12.2-18.0.0-3.5.0.jar     | None                                     |
	| LCHIJA | worldedit         | 6.1.10       | worldedit-forge-mc1.12.2-6.1.10-dist.jar         | None                                     |

	Loaded coremods (and transformers): 
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
LittlePatchingLoader (LittleTiles_v1.5.0-pre199_34_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
CreativePatchingLoader (CreativeCore_v1.10.16_mc1.12.2.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14736 Compatibility Profile Context 20.8.2 27.20.2001.16003' Renderer: 'AMD Radeon R9 200 Series'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2844
	LWJGL: 2.9.4
	OpenGL: AMD Radeon R9 200 Series GL version 4.6.14736 Compatibility Profile Context 20.8.2 27.20.2001.16003, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz

**Comment by CreativeMD** [comment]
Update to the newest version of CreativeCore and LittleTiles. If it still crashes just post it here and I will reopen it again.
