### ISSUE TITLE
Crash using JEI on opening inventory 

### ISSUE THREAD

**Issue by drhaber** [CreativeMD/LittleTiles#492]
---- Minecraft Crash Report ----
// Oops.

Time: 2020-09-21 16:43:25 EDT
Description: Rendering ingredient

java.lang.ClassCastException: com.creativemd.littletiles.client.render.tile.LittleRenderingCube cannot be cast to com.creativemd.creativecore.client.rendering.RenderBox
    at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.getBlockQuads(CreativeBakedModel.java:80)
    at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.getBlockQuads(CreativeBakedModel.java:159)
    at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.getQuads(CreativeBakedModel.java:75)
    at net.minecraftforge.client.ForgeHooksClient.renderLitItem(ForgeHooksClient.java:653)
    at net.minecraft.client.renderer.RenderItem.renderModel(RenderItem.java:118)
    at net.minecraft.client.renderer.RenderItem.renderModel(RenderItem.java:106)
    at mezz.jei.render.ItemStackFastRenderer.uncheckedRenderItemAndEffectIntoGUI(ItemStackFastRenderer.java:63)
    at mezz.jei.render.ItemStackFastRenderer.renderItemAndEffectIntoGUI(ItemStackFastRenderer.java:32)
    at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:157)
    at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:99)
    at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:97)
    at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:161)
    at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:72)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3244_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraft.client.gui.GuiScreen.drawDefaultBackground(GuiScreen.java:575)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.drawScreen(GuiContainerCreative.java:615)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1124)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)

[Full Log](https://pastebin.com/xwMLA6ri)

**Comment by CreativeMD** [comment]
Update CreativeCore and LittleTiles (download the newest version from curseforge).
