### ISSUE TITLE
Crash with littletiles batching chunks

### ISSUE THREAD

**Issue by darthvader45** [CreativeMD/LittleTiles#51]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  NEICorePlugin (NotEnoughItems-1.11.2-2.3.0.223-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.11.2-2.7.0.268-universal.jar)
  BetterFoliageLoader (BetterFoliage-MC1.11.2-2.1.5.jar)
  ForgelinPlugin (Forgelin-1.5.0.jar)
  CreativePatchingLoader (CreativeCore v1.7.4 mc1.11.2.jar)
  llibrary (llibrary-1.7.6-1.11.2.jar)
  LittlePatchingLoader (LittleTiles v1.4.12 mc1.11.2.jar)
  LittleLatePatchingLoader (LittleTilesCore-v1.0.0.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.4.5.6.jar)
  BIFLoader (BowInfinityFix-1.11.x-rv4.jar)
  BookshelfLoadingPlugin (Bookshelf-1.11.2-1.5.0.371.jar)
  MicdoodlePlugin (MicdoodleCore-1.11.2-4.0.0.106.jar)
  literalascension (literalascension-1.11.2-1.0.2.2.jar)
  BetterFontsCore (TTFR-1.11.2-1.7.4.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.7.0-beta1-anarchy.jar)
  MalisisCorePlugin (malisiscore-1.11.2-5.2.1.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 6/23/17 9:50 PM
Description: Batching chunks

java.lang.NullPointerException: Batching chunks
	at com.creativemd.littletiles.client.render.TileEntityTilesRenderer.isGlobalRenderer(TileEntityTilesRenderer.java:51)
	at com.creativemd.littletiles.client.render.TileEntityTilesRenderer.func_188185_a(TileEntityTilesRenderer.java:40)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:234)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.creativemd.littletiles.client.render.TileEntityTilesRenderer.isGlobalRenderer(TileEntityTilesRenderer.java:51)
	at com.creativemd.littletiles.client.render.TileEntityTilesRenderer.func_188185_a(TileEntityTilesRenderer.java:40)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['<PROFILE NAME>'/32437, l='MpServer', x=-105.69, y=84.50, z=250.01]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-16,64,248), Chunk: (at 0,4,8 in -1,15; contains blocks -16,0,240 to -1,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 2084271 game time, 2113840 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 63 total; [EntitySkeletonHorse['Skeleton Horse'/52738, l='MpServer', x=-181.98, y=66.00, z=294.12], EntityHamster['Hamster'/51469, l='MpServer', x=-378.61, y=63.00, z=217.17], EntityPlayerDummy['entity.PlayerDummy.name'/53010, l='MpServer', x=-123.58, y=55.00, z=260.10], EntityPlayerDummy['entity.PlayerDummy.name'/53016, l='MpServer', x=-126.46, y=55.00, z=262.70], EntitySkeletonHorse['Skeleton Horse'/52763, l='MpServer', x=-155.61, y=64.00, z=294.52], EntityToad['Toad'/32287, l='MpServer', x=-80.85, y=64.00, z=199.85], EntityPlayerDummy['entity.PlayerDummy.name'/54048, l='MpServer', x=-105.63, y=45.00, z=272.66], EntityPlayerDummy['entity.PlayerDummy.name'/53794, l='MpServer', x=-102.20, y=50.00, z=267.40], EntityPlayerDummy['entity.PlayerDummy.name'/54050, l='MpServer', x=-110.80, y=45.00, z=272.70], EntityPlayerDummy['entity.PlayerDummy.name'/53796, l='MpServer', x=-97.61, y=50.00, z=267.63], EntityPlayerDummy['entity.PlayerDummy.name'/52774, l='MpServer', x=-106.47, y=63.00, z=262.41], EntityPlayerDummy['entity.PlayerDummy.name'/52779, l='MpServer', x=-114.16, y=60.00, z=257.60], EntityPlayerDummy['entity.PlayerDummy.name'/53294, l='MpServer', x=-104.70, y=50.00, z=265.19], EntityPlayerDummy['entity.PlayerDummy.name'/52783, l='MpServer', x=-110.60, y=55.00, z=262.00], EntityPlayerDummy['entity.PlayerDummy.name'/53039, l='MpServer', x=-126.68, y=55.00, z=264.59], EntityPlayerDummy['entity.PlayerDummy.name'/53807, l='MpServer', x=-95.66, y=50.00, z=264.17], EntityPlayerDummy['entity.PlayerDummy.name'/53300, l='MpServer', x=-104.66, y=50.00, z=267.25], EntityPlayerDummy['entity.PlayerDummy.name'/53053, l='MpServer', x=-126.63, y=55.00, z=262.30], EntityPlayerDummy['entity.PlayerDummy.name'/53824, l='MpServer', x=-95.54, y=48.00, z=263.07], EntityPlayerDummy['entity.PlayerDummy.name'/52807, l='MpServer', x=-110.64, y=55.00, z=265.35], EntityPlayerDummy['entity.PlayerDummy.name'/52810, l='MpServer', x=-105.76, y=55.00, z=262.47], EntityPlayerDummy['entity.PlayerDummy.name'/52812, l='MpServer', x=-100.35, y=55.00, z=262.40], EntityPlayerDummy['entity.PlayerDummy.name'/53838, l='MpServer', x=-95.30, y=50.00, z=263.70], EntityPlayerDummy['entity.PlayerDummy.name'/52815, l='MpServer', x=-95.57, y=55.00, z=262.56], EntityPlayerDummy['entity.PlayerDummy.name'/54103, l='MpServer', x=-104.73, y=45.00, z=272.36], EntityPlayerDummy['entity.PlayerDummy.name'/52824, l='MpServer', x=-108.81, y=55.00, z=262.52], EntityPlayerDummy['entity.PlayerDummy.name'/54104, l='MpServer', x=-107.70, y=45.00, z=275.89], EntityPlayerDummy['entity.PlayerDummy.name'/53850, l='MpServer', x=-94.60, y=49.00, z=267.30], EntityPlayerDummy['entity.PlayerDummy.name'/53852, l='MpServer', x=-101.26, y=50.00, z=267.30], EntityPlayerDummy['entity.PlayerDummy.name'/52832, l='MpServer', x=-124.49, y=55.00, z=262.32], EntityPlayerDummy['entity.PlayerDummy.name'/53600, l='MpServer', x=-104.70, y=50.00, z=272.04], EntityPlayerDummy['entity.PlayerDummy.name'/53091, l='MpServer', x=-126.49, y=55.00, z=261.79], EntityPlayerDummy['entity.PlayerDummy.name'/52843, l='MpServer', x=-129.51, y=55.00, z=262.70], EntityPlayerDummy['entity.PlayerDummy.name'/53100, l='MpServer', x=-129.56, y=55.00, z=262.32], EntityPlayerDummy['entity.PlayerDummy.name'/52847, l='MpServer', x=-118.98, y=55.00, z=262.70], EntityPlayerDummy['entity.PlayerDummy.name'/54136, l='MpServer', x=-104.70, y=45.00, z=269.57], EntityPlayerDummy['entity.PlayerDummy.name'/53882, l='MpServer', x=-113.70, y=50.00, z=267.78], EntityPlayerDummy['entity.PlayerDummy.name'/54139, l='MpServer', x=-101.34, y=45.00, z=271.95], EntityPlayerDummy['entity.PlayerDummy.name'/53884, l='MpServer', x=-110.64, y=45.00, z=272.65], EntityPlayerDummy['entity.PlayerDummy.name'/53629, l='MpServer', x=-104.70, y=45.00, z=272.62], EntityPlayerDummy['entity.PlayerDummy.name'/54141, l='MpServer', x=-95.70, y=45.00, z=271.22], EntityPlayerDummy['entity.PlayerDummy.name'/53119, l='MpServer', x=-129.70, y=55.00, z=266.49], EntityPlayerDummy['entity.PlayerDummy.name'/54144, l='MpServer', x=-105.69, y=84.50, z=250.01], EntityPlayerDummy['entity.PlayerDummy.name'/52880, l='MpServer', x=-117.39, y=55.00, z=262.70], EntityPlayerDummy['entity.PlayerDummy.name'/52897, l='MpServer', x=-120.43, y=55.00, z=262.70], EntityPlayerDummy['entity.PlayerDummy.name'/53163, l='MpServer', x=-129.36, y=55.00, z=259.30], EntityPlayerDummy['entity.PlayerDummy.name'/53165, l='MpServer', x=-122.94, y=55.00, z=262.46], EntityHamster['Hamster'/51648, l='MpServer', x=-376.77, y=70.00, z=159.43], EntityPlayerDummy['entity.PlayerDummy.name'/53185, l='MpServer', x=-113.67, y=54.04, z=263.79], GCEntityClientPlayerMP['<PROFILE NAME>'/32437, l='MpServer', x=-105.69, y=84.50, z=250.01], EntityPlayerDummy['entity.PlayerDummy.name'/53188, l='MpServer', x=-110.49, y=50.00, z=267.74], EntityPlayerDummy['entity.PlayerDummy.name'/53191, l='MpServer', x=-107.62, y=50.00, z=266.99], EntityPlayerDummy['entity.PlayerDummy.name'/52940, l='MpServer', x=-120.46, y=55.00, z=263.89], EntityPlayerDummy['entity.PlayerDummy.name'/53202, l='MpServer', x=-107.70, y=50.00, z=263.14], EntityPlayerDummy['entity.PlayerDummy.name'/52961, l='MpServer', x=-120.55, y=55.00, z=258.44], EntityPlayerDummy['entity.PlayerDummy.name'/52968, l='MpServer', x=-123.50, y=55.00, z=262.70], EntityItem['item.item.feather'/64239, l='MpServer', x=-103.28, y=63.50, z=266.05], EntityHenLeghorn['Leghorn Hen'/52723, l='MpServer', x=-101.30, y=68.00, z=264.50], EntityPlayerDummy['entity.PlayerDummy.name'/53750, l='MpServer', x=-104.70, y=50.00, z=271.76], EntityPlayerDummy['entity.PlayerDummy.name'/53751, l='MpServer', x=-104.70, y=50.00, z=269.96], EntityMareDraftHorse['Draft Horse Mare'/52727, l='MpServer', x=-163.97, y=63.09, z=201.05], EntityPlayerDummy['entity.PlayerDummy.name'/52987, l='MpServer', x=-123.45, y=55.00, z=263.84], EntityMareDraftHorse['Draft Horse Mare'/52735, l='MpServer', x=-154.93, y=62.00, z=230.35]]
	Retry entities: 74 total; [EntityHamster['Hamster'/51469, l='MpServer', x=-378.61, y=63.00, z=217.17], EntityHamster['Hamster'/51470, l='MpServer', x=-382.50, y=63.00, z=214.50], EntityPlayerDummy['entity.PlayerDummy.name'/52880, l='MpServer', x=-117.39, y=55.00, z=262.70], EntityFrogs['Frog'/52242, l='MpServer', x=-292.50, y=63.00, z=148.50], EntityPlayerDummy['entity.PlayerDummy.name'/53010, l='MpServer', x=-123.58, y=55.00, z=260.10], EntityFrogs['Frog'/52243, l='MpServer', x=-291.50, y=63.00, z=147.50], EntityToad['Toad'/52120, l='MpServer', x=-304.50, y=68.00, z=120.50], EntityPlayerDummy['entity.PlayerDummy.name'/53016, l='MpServer', x=-126.46, y=55.00, z=262.70], EntityPlayerDummy['entity.PlayerDummy.name'/54048, l='MpServer', x=-105.63, y=45.00, z=272.66], EntityPlayerDummy['entity.PlayerDummy.name'/52897, l='MpServer', x=-120.43, y=55.00, z=262.70], EntityPlayerDummy['entity.PlayerDummy.name'/53794, l='MpServer', x=-102.20, y=50.00, z=267.40], EntityPlayerDummy['entity.PlayerDummy.name'/54050, l='MpServer', x=-110.80, y=45.00, z=272.70], EntityPlayerDummy['entity.PlayerDummy.name'/53796, l='MpServer', x=-97.61, y=50.00, z=267.63], EntityPlayerDummy['entity.PlayerDummy.name'/52774, l='MpServer', x=-106.47, y=63.00, z=262.41], EntityPlayerDummy['entity.PlayerDummy.name'/52779, l='MpServer', x=-114.16, y=60.00, z=257.60], EntityPlayerDummy['entity.PlayerDummy.name'/53163, l='MpServer', x=-129.36, y=55.00, z=259.30], EntityPlayerDummy['entity.PlayerDummy.name'/53165, l='MpServer', x=-122.94, y=55.00, z=262.46], EntityPlayerDummy['entity.PlayerDummy.name'/53294, l='MpServer', x=-104.70, y=50.00, z=265.19], EntityCowAngus['Angus Cow'/51759, l='MpServer', x=-406.50, y=68.00, z=131.83], EntityPlayerDummy['entity.PlayerDummy.name'/52783, l='MpServer', x=-110.60, y=55.00, z=262.00], EntityPlayerDummy['entity.PlayerDummy.name'/53039, l='MpServer', x=-126.68, y=55.00, z=264.59], EntityPlayerDummy['entity.PlayerDummy.name'/53807, l='MpServer', x=-95.66, y=50.00, z=264.17], EntityPlayerDummy['entity.PlayerDummy.name'/53300, l='MpServer', x=-104.66, y=50.00, z=267.25], EntityCowAngus['Angus Cow'/51638, l='MpServer', x=-398.16, y=64.00, z=171.75], EntityCalfAngus['Angus Calf'/51639, l='MpServer', x=-410.50, y=66.00, z=156.70], EntityItem['item.tile.mushroom'/51642, l='MpServer', x=-405.13, y=66.00, z=205.88], EntityItem['item.tile.mushroom'/51643, l='MpServer', x=-410.88, y=66.00, z=204.88], EntityPlayerDummy['entity.PlayerDummy.name'/53053, l='MpServer', x=-126.63, y=55.00, z=262.30], EntityHamster['Hamster'/51646, l='MpServer', x=-369.74, y=72.00, z=157.46], EntityHamster['Hamster'/51647, l='MpServer', x=-366.25, y=68.00, z=139.05], EntityHamster['Hamster'/51648, l='MpServer', x=-376.77, y=70.00, z=159.43], EntityPlayerDummy['entity.PlayerDummy.name'/53824, l='MpServer', x=-95.54, y=48.00, z=263.07], EntityHamster['Hamster'/51649, l='MpServer', x=-371.62, y=70.00, z=166.20], EntityPlayerDummy['entity.PlayerDummy.name'/53185, l='MpServer', x=-113.67, y=54.04, z=263.79], EntityPlayerDummy['entity.PlayerDummy.name'/53188, l='MpServer', x=-110.49, y=50.00, z=267.74], EntityPlayerDummy['entity.PlayerDummy.name'/52807, l='MpServer', x=-110.64, y=55.00, z=265.35], EntityPlayerDummy['entity.PlayerDummy.name'/53191, l='MpServer', x=-107.62, y=50.00, z=266.99], EntityPlayerDummy['entity.PlayerDummy.name'/52810, l='MpServer', x=-105.76, y=55.00, z=262.47], EntityPlayerDummy['entity.PlayerDummy.name'/52812, l='MpServer', x=-100.35, y=55.00, z=262.40], EntityPlayerDummy['entity.PlayerDummy.name'/52940, l='MpServer', x=-120.46, y=55.00, z=263.89], EntityPlayerDummy['entity.PlayerDummy.name'/53838, l='MpServer', x=-95.30, y=50.00, z=263.70], EntityPlayerDummy['entity.PlayerDummy.name'/52815, l='MpServer', x=-95.57, y=55.00, z=262.56], EntityPlayerDummy['entity.PlayerDummy.name'/53202, l='MpServer', x=-107.70, y=50.00, z=263.14], EntityToad['Toad'/52437, l='MpServer', x=-324.50, y=72.00, z=113.50], EntityFrogs['Frog'/52438, l='MpServer', x=-325.50, y=72.00, z=115.50], EntityPlayerDummy['entity.PlayerDummy.name'/54103, l='MpServer', x=-104.73, y=45.00, z=272.36], EntityPlayerDummy['entity.PlayerDummy.name'/52824, l='MpServer', x=-108.81, y=55.00, z=262.52], EntityPlayerDummy['entity.PlayerDummy.name'/54104, l='MpServer', x=-107.70, y=45.00, z=275.89], EntityPlayerDummy['entity.PlayerDummy.name'/53850, l='MpServer', x=-94.60, y=49.00, z=267.30], EntityPlayerDummy['entity.PlayerDummy.name'/53852, l='MpServer', x=-101.26, y=50.00, z=267.30], EntityPlayerDummy['entity.PlayerDummy.name'/52832, l='MpServer', x=-124.49, y=55.00, z=262.32], EntityPlayerDummy['entity.PlayerDummy.name'/53600, l='MpServer', x=-104.70, y=50.00, z=272.04], EntityPlayerDummy['entity.PlayerDummy.name'/52961, l='MpServer', x=-120.55, y=55.00, z=258.44], EntityPlayerDummy['entity.PlayerDummy.name'/53091, l='MpServer', x=-126.49, y=55.00, z=261.79], EntityPeafowlWhite['White Peafowl'/51684, l='MpServer', x=-304.46, y=67.00, z=122.12], EntityCowAngus['Angus Cow'/51686, l='MpServer', x=-403.81, y=64.00, z=178.17], EntityCalfAngus['Angus Calf'/51687, l='MpServer', x=-405.51, y=63.00, z=178.45], EntityPlayerDummy['entity.PlayerDummy.name'/52968, l='MpServer', x=-123.50, y=55.00, z=262.70], EntityPlayerDummy['entity.PlayerDummy.name'/52843, l='MpServer', x=-129.51, y=55.00, z=262.70], EntityPlayerDummy['entity.PlayerDummy.name'/53100, l='MpServer', x=-129.56, y=55.00, z=262.32], EntityPlayerDummy['entity.PlayerDummy.name'/52847, l='MpServer', x=-118.98, y=55.00, z=262.70], EntityPlayerDummy['entity.PlayerDummy.name'/53750, l='MpServer', x=-104.70, y=50.00, z=271.76], EntityPlayerDummy['entity.PlayerDummy.name'/53751, l='MpServer', x=-104.70, y=50.00, z=269.96], EntityPlayerDummy['entity.PlayerDummy.name'/54136, l='MpServer', x=-104.70, y=45.00, z=269.57], EntityFrogs['Frog'/52217, l='MpServer', x=-291.50, y=73.00, z=124.50], EntityPlayerDummy['entity.PlayerDummy.name'/53882, l='MpServer', x=-113.70, y=50.00, z=267.78], EntityPlayerDummy['entity.PlayerDummy.name'/52987, l='MpServer', x=-123.45, y=55.00, z=263.84], EntityPlayerDummy['entity.PlayerDummy.name'/54139, l='MpServer', x=-101.34, y=45.00, z=271.95], EntityRoosterLeghorn['Leghorn Rooster'/51708, l='MpServer', x=-332.50, y=64.55, z=127.71], EntityPlayerDummy['entity.PlayerDummy.name'/53884, l='MpServer', x=-110.64, y=45.00, z=272.65], EntityHenLeghorn['Leghorn Hen'/51709, l='MpServer', x=-335.50, y=65.00, z=135.50], EntityPlayerDummy['entity.PlayerDummy.name'/53629, l='MpServer', x=-104.70, y=45.00, z=272.62], EntityPlayerDummy['entity.PlayerDummy.name'/54141, l='MpServer', x=-95.70, y=45.00, z=271.22], EntityPlayerDummy['entity.PlayerDummy.name'/53119, l='MpServer', x=-129.70, y=55.00, z=266.49]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:57)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 949206664 bytes (905 MB) / 2581069824 bytes (2461 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx8192m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.38 Powered by Forge 13.20.0.2345 Optifine OptiFine_1.11.2_HD_U_C2 46 mods loaded, 46 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAAAAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2345-universal.jar) 
	UCHIJAAAAAAAAA	forge{13.20.0.2345} [Minecraft Forge] (forge-1.11.2-13.20.0.2345-universal.jar) 
	UCHIJAAAAAAAAA	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UCHIJAAAAAAAAA	littletilescore{1.0.0} [LittleTilesCore] (minecraft.jar) 
	UCHIJAAAAAAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAAAAAAA	betterfonts{1.7.4} [BetterFonts] (minecraft.jar) 
	UCHIJAAAAAAAAA	bowinfinityfix{rv4} [Bow Infinity Fix] (minecraft.jar) 
	UCHIJAAAAAAAAA	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHIJAAAAAAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.11.2-2.7.0.268-universal.jar) 
	UCHIJAAAAAAAAA	bspkrscore{7.5.2.1} [bspkrsCore] ([1.11.2]bspkrsCore-universal-7.5.2.1.jar) 
	UCHIJAAAAAAAAA	treecapitator{1.42.1} [TreeCapitator] ([1.11.2]TreeCapitator-client-1.42.1.jar) 
	UCHIJAAAAAAAAA	animania{1.1.5} [Animania] (animania-1.11.2-1.1.5.jar) 
	UCHIJAAAAAAAAA	betterfoliage{2.1.5} [Better Foliage] (BetterFoliage-MC1.11.2-2.1.5.jar) 
	UCHIJAAAAAAAAA	bibliocraft{2.3.2} [BiblioCraft] (BiblioCraft[v2.3.2][MC1.11.2].jar) 
	UCHIJAAAAAAAAA	bookshelf{1.5.0.371} [Bookshelf] (Bookshelf-1.11.2-1.5.0.371.jar) 
	UCHIJAAAAAAAAA	chiselsandbits{13.10} [Chisels & Bits] (chiselsandbits-13.10.jar) 
	UCHIJAAAAAAAAA	codechickenlib{2.7.0.268} [CodeChicken Lib] (CodeChickenLib-1.11.2-2.7.0.268-universal.jar) 
	UCHIJAAAAAAAAA	cookingforblockheads{5.3.20} [Cooking for Blockheads] (CookingForBlockheads_1.11.2-5.3.20.jar) 
	UCHIJAAAAAAAAA	creativecore{1.7.4} [CreativeCore] (CreativeCore v1.7.4 mc1.11.2.jar) 
	UCHIJAAAAAAAAA	cyberware{alpha-0.2.9} [Cyberware] (cyberware-1.11.2-alpha-0.2.9.jar) 
	UCHIJAAAAAAAAA	jei{4.5.0.287} [Just Enough Items] (jei_1.11.2-4.5.0.287.jar) 
	UCHIJAAAAAAAAA	cyclicmagic{1.5.7} [Cyclic] (Cyclic-1.11.2-1.5.7.jar) 
	UCHIJAAAAAAAAA	darkutils{1.2.0.126} [Dark Utilities] (DarkUtilities-1.11.2-1.2.0.126.jar) 
	UCHIJAAAAAAAAA	galacticraftcore{4.0.0} [Galacticraft Core] (GalacticraftCore-1.11.2-4.0.0.106.jar) 
	UCHIJAAAAAAAAA	dsurround{3.4.5.6} [§3Dynamic Surroundings] (DynamicSurroundings-1.11.2-3.4.5.6.jar) 
	UCHIJAAAAAAAAA	presets{3.4.5.6} [§3Presets!] (DynamicSurroundings-1.11.2-3.4.5.6.jar) 
	UCHIJAAAAAAAAA	csb_ench_table{1.1} [Lapis Stays in the Enchanting Table] (EnchantingTable-1.11-1.1.jar) 
	UCHIJAAAAAAAAA	fbp{2.2.1} [Fancy Block Particles] (FancyBlockParticles-1.11.2-2.2.1.jar) 
	UCHIJAAAAAAAAA	foamfix{@VERSION@} [FoamFix] (foamfix-0.7.0-beta1-anarchy.jar) 
	UCHIJAAAAAAAAA	forgelin{1.4.2} [Shadowfacts' Forgelin] (Forgelin-1.5.0.jar) 
	UCHIJAAAAAAAAA	galacticraftplanets{4.0.0} [Galacticraft Planets] (Galacticraft-Planets-1.11.2-4.0.0.106.jar) 
	UCHIJAAAAAAAAA	immersiveengineering{0.11-62} [Immersive Engineering] (ImmersiveEngineering-0.11-62.jar) 
	UCHIJAAAAAAAAA	immersivepetroleum{1.0.6} [Immersive Petroleum] (immersivepetroleum-1.11.2-1.0.6.jar) 
	UCHIJAAAAAAAAA	llibrary{1.7.6} [LLibrary] (llibrary-1.7.6-1.11.2.jar) 
	UCHIJAAAAAAAAA	literalascension{1.11.2-1.0.2.2} [Literal Ascension] (literalascension-1.11.2-1.0.2.2.jar) 
	UCHIJAAAAAAAAA	littletiles{1.4.8} [LittleTiles] (LittleTiles v1.4.12 mc1.11.2.jar) 
	UCHIJAAAAAAAAA	malisiscore{1.11.2-5.2.1} [MalisisCore] (malisiscore-1.11.2-5.2.1.jar) 
	UCHIJAAAAAAAAA	malisisblocks{1.11.2-5.1.0} [Malisis Blocks] (malisisblocks-1.11.2-5.1.0.jar) 
	UCHIJAAAAAAAAA	malisisdoors{1.11.2-6.1.1} [MalisisDoors] (malisisdoors-1.11.2-6.1.1.jar) 
	UCHIJAAAAAAAAA	nei{${mod_version}} [Not Enough Items] (NotEnoughItems-1.11.2-2.3.0.223-universal.jar) 
	UCHIJAAAAAAAAA	rfpr{8.1.1} [Real First-Person Render] (Real First-Person Render-1.11.2-8.1.1.jar) 
	UCHIJAAAAAAAAA	scenter{1.11.2-3.10.1} [Scenter] (scenter-1.11.2-3.10.1.jar) 
	UCHIJAAAAAAAAA	waila{1.7.1} [waila] (Waila-1.7.1_1.11.2.jar) 
	UCHIJAAAAAAAAA	wawla{2.4.0.231} [What Are We Looking At] (Wawla-1.11.2-2.4.0.231.jar) 
	Loaded coremods (and transformers): 
NEICorePlugin (NotEnoughItems-1.11.2-2.3.0.223-universal.jar)
  codechicken.nei.asm.NEITransformer
CCLCorePlugin (CodeChickenLib-1.11.2-2.7.0.268-universal.jar)
  codechicken.lib.asm.ClassHierarchyManager
  codechicken.lib.asm.CCL_ASMTransformer
BetterFoliageLoader (BetterFoliage-MC1.11.2-2.1.5.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
ForgelinPlugin (Forgelin-1.5.0.jar)
  
CreativePatchingLoader (CreativeCore v1.7.4 mc1.11.2.jar)
  
llibrary (llibrary-1.7.6-1.11.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
LittlePatchingLoader (LittleTiles v1.4.12 mc1.11.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
LittleLatePatchingLoader (LittleTilesCore-v1.0.0.jar)
  com.creativemd.littletiles.LittleTilesLateTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.4.5.6.jar)
  org.blockartistry.DynSurround.asm.Transformer
BIFLoader (BowInfinityFix-1.11.x-rv4.jar)
  com.github.parker8283.bif.Transformer
BookshelfLoadingPlugin (Bookshelf-1.11.2-1.5.0.371.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
MicdoodlePlugin (MicdoodleCore-1.11.2-4.0.0.106.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
literalascension (literalascension-1.11.2-1.0.2.2.jar)
  com.jamieswhiteshirt.literalascension.core.patcher.LiteralAscensionRuntimePatcher
BetterFontsCore (TTFR-1.11.2-1.7.4.jar)
  cubex2.ttfr.BFClassTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.7.0-beta1-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
MalisisCorePlugin (malisiscore-1.11.2-5.2.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	codechickenlib Invalid Fingerprint Reports: - No invalid fingerprints.: 
	nei Invalid Fingerprint Reports: - No invalid fingerprints.: 
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: F32-1.10.2.zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz
	OptiFine Version: OptiFine_1.11.2_HD_U_C2
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 382.05
	OpenGlRenderer: GeForce GT 750M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
```

**Comment by CreativeMD** [comment]
This looks like a weird threading issue, it will be fixed with the 1.5.0 Update. Thanks for reporting!

**Comment by darthvader45** [comment]
No problem.  Love this mod.

**Comment by CreativeMD** [comment]
A beta version for 1.5.0 is out.
