### ISSUE TITLE
Halp please

### ISSUE THREAD

**Issue by blackwarrior3** [CreativeMD/LittleTiles#545]
So I was building a door and got the recipe like normal (first time btw) and when I opened the little bench it crashed my game immediately

**Comment by blackwarrior3** [comment]
Please hall

**Comment by CreativeMD** [comment]
Please post the crash report.

**Comment by blackwarrior3** [comment]
I'm a bit dumb on this side of stuff how to I copy a crash report

**Comment by CreativeMD** [comment]
Your issue is most likely an outdated version of CreativeCore and LittleTiles ...

**Comment by blackwarrior3** [comment]
Does it come in 1.16.2 or what is the latest version,?

**Comment by blackwarrior3** [comment]
I'm using 1.12.2 creative core and forge  and little tiles

**Comment by CreativeMD** [comment]
No it's not updated yet and I wasn't talking about the minecraft version ...

**Comment by blackwarrior3** [comment]
so use 1.16.4 forge ?
or what im a bit confused'
and i can get the crash log if you need me to

**Comment by blackwarrior3** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore_v1.9.54_mc1.12.2.jar)
  LittlePatchingLoader (LittleTiles-Mod-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 12/27/20 4:36 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at com.creativemd.creativecore.common.gui.GuiControl.isMouseOver(GuiControl.java:110)
	at com.creativemd.creativecore.common.gui.client.style.Style.getBackground(Style.java:40)
	at com.creativemd.creativecore.common.gui.GuiControl.renderBackground(GuiControl.java:244)
	at com.creativemd.creativecore.common.gui.GuiControl.renderControl(GuiControl.java:287)
	at com.creativemd.creativecore.common.gui.container.GuiParent.renderContent(GuiParent.java:122)
	at com.creativemd.creativecore.common.gui.GuiControl.renderControl(GuiControl.java:300)
	at com.creativemd.creativecore.common.gui.mc.GuiContainerSub.func_146979_b(GuiContainerSub.java:169)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:117)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.creativemd.creativecore.common.gui.GuiControl.isMouseOver(GuiControl.java:110)
	at com.creativemd.creativecore.common.gui.client.style.Style.getBackground(Style.java:40)
	at com.creativemd.creativecore.common.gui.GuiControl.renderBackground(GuiControl.java:244)
	at com.creativemd.creativecore.common.gui.GuiControl.renderControl(GuiControl.java:287)
	at com.creativemd.creativecore.common.gui.container.GuiParent.renderContent(GuiParent.java:122)
	at com.creativemd.creativecore.common.gui.GuiControl.renderControl(GuiControl.java:300)
	at com.creativemd.creativecore.common.gui.mc.GuiContainerSub.func_146979_b(GuiContainerSub.java:169)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:117)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)

-- Screen render details --
Details:
	Screen name: com.creativemd.creativecore.common.gui.mc.GuiContainerSub
	Mouse location: Scaled: (213, 119). Absolute: (427, 240)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['D0peTomato'/15, l='MpServer', x=1405.25, y=32.00, z=148.16]]
	Chunk stats: MultiplayerChunkCache: 841, 841
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (1377,4,166), Chunk: (at 1,0,6 in 86,10; contains blocks 1376,0,160 to 1391,255,175), Region: (2,0; contains chunks 64,0 to 95,31, blocks 1024,0,0 to 1535,255,511)
	Level time: 239947 game time, 1127 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 11 total; [EntityLlama['Llama'/5, l='MpServer', x=1325.08, y=32.00, z=145.80], EntityChicken['Chicken'/6, l='MpServer', x=1336.77, y=32.00, z=177.91], EntityItem['item.item.egg'/7, l='MpServer', x=1343.14, y=32.00, z=186.63], EntityChicken['Chicken'/8, l='MpServer', x=1353.24, y=32.00, z=117.14], EntityItem['item.item.egg'/9, l='MpServer', x=1350.61, y=32.00, z=112.22], EntitySheep['Sheep'/10, l='MpServer', x=1351.57, y=32.00, z=202.28], EntityPig['Pig'/11, l='MpServer', x=1365.62, y=32.00, z=204.73], EntityPig['Pig'/12, l='MpServer', x=1387.23, y=32.00, z=106.38], EntityPig['Pig'/13, l='MpServer', x=1384.45, y=23.00, z=132.57], EntitySheep['Sheep'/14, l='MpServer', x=1418.38, y=32.00, z=120.77], EntityPlayerSP['D0peTomato'/15, l='MpServer', x=1405.25, y=32.00, z=148.16]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 923072168 bytes (880 MB) / 1577058304 bytes (1504 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version      | Source                            | Signature                                |
	|:------ |:----------------- |:------------ |:--------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft         | 1.12.2       | minecraft.jar                     | None                                     |
	| LCHIJA | mcp               | 9.42         | minecraft.jar                     | None                                     |
	| LCHIJA | FML               | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge             | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy | 1.0.0        | minecraft.jar                     | None                                     |
	| LCHIJA | littletilescore   | 1.0.0        | minecraft.jar                     | None                                     |
	| LCHIJA | creativecore      | 1.9.9        | CreativeCore_v1.9.54_mc1.12.2.jar | None                                     |
	| LCHIJA | littletiles       | 1.5.0        | LittleTiles-Mod-1.12.2.jar        | None                                     |

	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore_v1.9.54_mc1.12.2.jar)
  
LittlePatchingLoader (LittleTiles-Mod-1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 27.20.100.8280' Renderer: 'Intel(R) UHD Graphics'
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics GL version 4.6.0 - Build 27.20.100.8280, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz

**Comment by blackwarrior3** [comment]
what version do i use like u said minecraft version u cant have a mod open with a reg minecraft version so its gotta be forge and what forge u talking about u gotta tell me more detailed

**Comment by CreativeMD** [comment]
Please just download the newest version of CreativeCore and LittleTiles from curseforge.

**Comment by blackwarrior3** [comment]
ok

**Comment by blackwarrior3** [comment]
if u see this what version of forge is my isue please

**Comment by CreativeMD** [comment]
Just use the latest ...
