### ISSUE TITLE
so i accully need detail

### ISSUE THREAD

**Issue by blackwarrior3** [CreativeMD/LittleTiles#547]
last issue got closed whats the latest version what version of forge do i need what version of creative ccore and now i cant even luanch my mc anymore i need detail D E T A I L

**Comment by blackwarrior3** [comment]
pleeeeeeeeeeeeeeease

**Comment by blackwarrior3** [comment]
![Screenshot (83)](https://user-images.githubusercontent.com/76650652/103181224-f8a28380-486c-11eb-8788-87525f517526.png)

**Comment by blackwarrior3** [comment]
tell me whats wrong 
so i can accually u this mod

**Comment by CreativeMD** [comment]
http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.12.2.html
https://www.curseforge.com/minecraft/mc-mods/creativecore
https://www.curseforge.com/minecraft/mc-mods/littletiles
If you have no idea how to install Forge this is not the right place to ask. I highly recommend to watch a tutorial on how to install Forge + Mods.

**Comment by blackwarrior3** [comment]
I KNOW HOW TO DDOWNLOAD FORGEE4
WHATS THE FUDGEING VERSIONNNNNNNNNNNNNNNNNNNNNNN

**Comment by blackwarrior3** [comment]
alright i have this  AND IT STILLL FREACK CRASHES 
BRUH NO FREAKING HELP HERE

**Comment by CreativeMD** [comment]
as I said latest ...

**Comment by blackwarrior3** [comment]
![Uploading Screenshot (84).png…]()

**Comment by blackwarrior3** [comment]
this is the latest creative core and it doesent work

**Comment by blackwarrior3** [comment]
![Screenshot (84)](https://user-images.githubusercontent.com/76650652/103181310-ce9d9100-486d-11eb-8f75-968b426bebc3.png)

**Comment by blackwarrior3** [comment]
so do i downlaod 1.12.2 creative core?

**Comment by blackwarrior3** [comment]
just tell me  what version my creative core needs to be

**Comment by blackwarrior3** [comment]
u thoguht i ment forge no i ment creative core
\

**Comment by CreativeMD** [comment]
Everything is outdated and don't use the download button on curseforge. Go to files and search for the newest version for 1.12 obviously.

**Comment by blackwarrior3** [comment]
ik u seen this

**Comment by blackwarrior3** [comment]
just tell me what version creative core needs and ill leave u aloonne if theres no issues

**Comment by blackwarrior3** [comment]
![Uploading Screenshot (84).png…]()

**Comment by blackwarrior3** [comment]
![Screenshot (84)](https://user-images.githubusercontent.com/76650652/103181410-b417e780-486e-11eb-856f-6c2c471b60e8.png)

**Comment by CreativeMD** [comment]
I said the newest for 1.12

**Comment by blackwarrior3** [comment]
so 1.12.2

**Comment by blackwarrior3** [comment]
thank you have a nice dday im sorry for being mad i get agrevated easly gday

**Comment by blackwarrior3** [comment]
soryr again but uhm little tiles wont turn on  do i got the right version

**Comment by blackwarrior3** [comment]
![Screenshot (85)](https://user-images.githubusercontent.com/76650652/103181494-972fe400-486f-11eb-8cee-27c426635db1.png)

**Comment by blackwarrior3** [comment]
thats my last thing if my game crashes again i will just ask somone who will give me actual detail

**Comment by blackwarrior3** [comment]
is this the right version ??????????

**Comment by blackwarrior3** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LittlePatchingLoader (LittleTiles_v1.5.0-pre199_73_mc1.12.2 (1).jar)
  CreativePatchingLoader (CreativeCore_v1.9.54_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 12/27/20 6:30 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from LittleTiles (littletiles)
Caused by: java.lang.NoClassDefFoundError: com/creativemd/creativecore/common/config/holder/CreativeConfigRegistry
	at com.creativemd.littletiles.LittleTiles.PreInit(LittleTiles.java:228)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.creativemd.creativecore.common.config.holder.CreativeConfigRegistry
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 418216920 bytes (398 MB) / 771751936 bytes (736 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version      | Source                                        | Signature                                |
	|:----- |:----------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft         | 1.12.2       | minecraft.jar                                 | None                                     |
	| LCH   | mcp               | 9.42         | minecraft.jar                                 | None                                     |
	| LCH   | FML               | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge             | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | creativecoredummy | 1.0.0        | minecraft.jar                                 | None                                     |
	| LCH   | littletilescore   | 1.0.0        | minecraft.jar                                 | None                                     |
	| LCH   | creativecore      | 1.9.9        | CreativeCore_v1.9.54_mc1.12.2.jar             | None                                     |
	| LCE   | littletiles       | 1.5.0        | LittleTiles_v1.5.0-pre199_73_mc1.12.2 (1).jar | None                                     |

	Loaded coremods (and transformers): 
LittlePatchingLoader (LittleTiles_v1.5.0-pre199_73_mc1.12.2 (1).jar)
  com.creativemd.littletiles.LittleTilesTransformer
CreativePatchingLoader (CreativeCore_v1.9.54_mc1.12.2.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 27.20.100.8280' Renderer: 'Intel(R) UHD Graphics'

**Comment by CreativeMD** [comment]
You still haven't updated CreativeCore just download this version: https://www.curseforge.com/minecraft/mc-mods/creativecore/files/3097498

**Comment by blackwarrior3** [comment]
if it doesent work

**Comment by blackwarrior3** [comment]
OMG TY
IM HAPPPY 
 BRO WE HAVE BEEN GOING AT THIS SINCE 7 AM BRO  TY
