### ISSUE TITLE
Client Crash when using Overwrite Mode

### ISSUE THREAD

**Issue by knobsam** [CreativeMD/LittleTiles#557]
Hi,

I had several crashes lately when trying to replace a bunch of tiles with e.g. other material (using Chisel) or with content of an Advanced Recipe. Please find my crash log (full log [here](https://pastebin.com/5KqKK3ch)) below (server is running fine).
I'm using both the latest versions of LittleTiles and CreativeCore for MC 1.12.2 with Forge 14.23.5.2854.

Thanks for having a look,

Samuel

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BetterFoliageLoader (BetterFoliage-MC1.12-2.3.1.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  RandomPatches (randompatches-1.12.2-1.22.1.7.jar)
  CreativePatchingLoader (CreativeCore_v1.10.34_mc1.12.2.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre199_73_mc1.12.2.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.2.1.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.150.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 1/5/21 3:15 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.creativemd.littletiles.common.util.place.Placement$PlacementBlock.lambda$canPlace$0(Placement.java:368)
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.isSpaceForLittleTile(TileEntityLittleTiles.java:389)
	at com.creativemd.littletiles.common.util.place.Placement$PlacementBlock.canPlace(Placement.java:368)
	at com.creativemd.littletiles.common.util.place.Placement.canPlace(Placement.java:119)
	at com.creativemd.littletiles.common.util.place.Placement.place(Placement.java:159)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.placeTile(LittleActionPlaceStack.java:148)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.action(LittleActionPlaceStack.java:99)
	at com.creativemd.littletiles.common.action.LittleAction.execute(LittleAction.java:248)
	at com.creativemd.littletiles.common.event.LittleEventHandler.onRightInteractClient(LittleEventHandler.java:339)
	at com.creativemd.littletiles.common.event.LittleEventHandler.onInteract(LittleEventHandler.java:291)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_384_LittleEventHandler_onInteract_RightClickBlock.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1137)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:398)
	at net.optifine.override.PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.creativemd.littletiles.common.util.place.Placement$PlacementBlock.lambda$canPlace$0(Placement.java:368)
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.isSpaceForLittleTile(TileEntityLittleTiles.java:389)
	at com.creativemd.littletiles.common.util.place.Placement$PlacementBlock.canPlace(Placement.java:368)
	at com.creativemd.littletiles.common.util.place.Placement.canPlace(Placement.java:119)
	at com.creativemd.littletiles.common.util.place.Placement.place(Placement.java:159)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.placeTile(LittleActionPlaceStack.java:148)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.action(LittleActionPlaceStack.java:99)
	at com.creativemd.littletiles.common.action.LittleAction.execute(LittleAction.java:248)
	at com.creativemd.littletiles.common.event.LittleEventHandler.onRightInteractClient(LittleEventHandler.java:339)
	at com.creativemd.littletiles.common.event.LittleEventHandler.onInteract(LittleEventHandler.java:291)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_384_LittleEventHandler_onInteract_RightClickBlock.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1137)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:398)
	at net.optifine.override.PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
```

**Comment by knobsam** [comment]
While scrolling the commit history it may be that this is already fixed... Is there a chance to get an intermediate version for testing (or a build instruction)?

**Comment by CreativeMD** [comment]
Does this still occur in the newest version released on curseforge (don't forget to update CreativeCore as well)?

**Comment by knobsam** [comment]
I just found out yesterday about your beta releases on Discord and wanted to test with the latest version (pre295 or so) today.
I'll give you an update as soon as possible.

If I understood your Discord announcement correctly I should delete my cfg/json config files before updating, right?

**Comment by CreativeMD** [comment]
Just get the newest from curseforge and there is no need to delete your config (it's only necessary if you downloaded pre293).

**Comment by knobsam** [comment]
**Update**

I just upgraded to pre303 from Curseforge. Sadly the crash is still there (line has changed to L375, same file).

How to reproduce:
- Copy a LT block (I have a 8x8x22 [scale 1/16] log beam here) with Middle Mouse button
- Hit Ctrl+C, go into Overwrite Mode
- Hit M, place the copied block into the existing (full replace or partially - same result)
- Try to add/place the block

Result is
```The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error
Exit Code: 255
```

and the crash log above.

Fun fact: Sometimes is seems to work fine (2 out of 10 I would say). So I cannot tell why exactly the crash happens.

**Comment by CreativeMD** [comment]
Should be fixed in the newest version, at least I hope so.

**Comment by knobsam** [comment]
Thanks for the quick response and fix, the crash is gone.
Placing copied LT items works as well as inserting structures with an advanced recipe.

Thanks for your work!

**Comment by CreativeMD** [comment]
Perfect!
