### ISSUE TITLE
Weird bug with signals and doors. 

### ISSUE THREAD

**Issue by djhatt0204** [CreativeMD/LittleTiles#574]
I took a tree and turned it into a sliding door and added an input tile. When it isn't connected to a wire it works fine with right clicking but when attached to wires right clicking it causes it to appear as if it works but it also duplicates itself as an invisible version and after messing with it i received a crash. Here is my crash log

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LittlePatchingLoader (LittleTiles_v1.5.0-pre310_mc1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.10.42_mc1.12.2 (1).jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 1/17/21 6:38 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.creativemd.littletiles.common.structure.signal.logic.SignalTarget.getState(SignalTarget.java:98)
	at com.creativemd.littletiles.common.structure.signal.logic.SignalTarget.getState(SignalTarget.java:91)
	at com.creativemd.littletiles.common.structure.signal.input.SignalInputVariable.test(SignalInputVariable.java:81)
	at com.creativemd.littletiles.common.structure.signal.output.InternalSignalOutput.update(InternalSignalOutput.java:89)
	at com.creativemd.littletiles.common.structure.LittleStructure.processSignalChanges(LittleStructure.java:691)
	at com.creativemd.littletiles.common.structure.LittleStructure.notifyChange(LittleStructure.java:682)
	at com.creativemd.littletiles.common.structure.type.door.LittleDoor.completeAnimation(LittleDoor.java:182)
	at com.creativemd.littletiles.common.entity.DoorController.place(DoorController.java:232)
	at com.creativemd.littletiles.common.entity.DoorController.endTransition(DoorController.java:197)
	at com.creativemd.littletiles.common.structure.animation.AnimationController.tick(AnimationController.java:155)
	at com.creativemd.littletiles.common.entity.DoorController.tick(DoorController.java:176)
	at com.creativemd.littletiles.common.entity.EntityAnimation.onTick(EntityAnimation.java:590)
	at com.creativemd.littletiles.common.entity.EntityAnimation.onUpdateForReal(EntityAnimation.java:646)
	at com.creativemd.littletiles.server.world.LittleAnimationHandlerServer.tick(LittleAnimationHandlerServer.java:24)
	at com.creativemd.littletiles.common.world.WorldAnimationHandler.tick(WorldAnimationHandler.java:144)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_61_WorldAnimationHandler_tick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:274)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 444474736 bytes (423 MB) / 973078528 bytes (928 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version      | Source                                 | Signature                                |
	|:------ |:----------------- |:------------ |:-------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft         | 1.12.2       | minecraft.jar                          | None                                     |
	| LCHIJA | mcp               | 9.42         | minecraft.jar                          | None                                     |
	| LCHIJA | FML               | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge             | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy | 1.0.0        | minecraft.jar                          | None                                     |
	| LCHIJA | littletilescore   | 1.0.0        | minecraft.jar                          | None                                     |
	| LCHIJA | creativecore      | 1.10.0       | CreativeCore_v1.10.42_mc1.12.2 (1).jar | None                                     |
	| LCHIJA | littletiles       | 1.5.0        | LittleTiles_v1.5.0-pre310_mc1.12.2.jar | None                                     |
	| LCHIJA | alet              | 1.0          | A+Little+Extra+Tiles-1.0.14.jar        | None                                     |
	| LCHIJA | artemislib        | 1.0.6        | ArtemisLib-1.12.2-v1.0.6 (1).jar       | None                                     |
	| LCHIJA | gulliverreborn    | 1.10         | Gulliver+Reborn+mc1.12.2+v1.10 (1).jar | None                                     |
	| LCHIJA | kirosblocks       | 1.1          | kirosblocks-1.1 (1).jar                | None                                     |
	| LCHIJA | littleframes      | 1.0.0        | LittleFrames_v1.0.2_mc1.12.2 (1).jar   | None                                     |

	Loaded coremods (and transformers): 
LittlePatchingLoader (LittleTiles_v1.5.0-pre310_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
CreativePatchingLoader (CreativeCore_v1.10.42_mc1.12.2 (1).jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['djhatt0204'/1963, l='tiny poyo', x=-230.97, y=70.53, z=225.49]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by CreativeMD** [comment]
Should also be fixed. Just want to say that signal connections only work if the animation has stopped.
