### ISSUE TITLE
Game Crashes when using little recipe (Info Included)

### ISSUE THREAD

**Issue by HelloitsRoFi** [CreativeMD/LittleTiles#594]
Hi, I had build something then right clicked each corner while holding a little recipe, and then i tried to open the recipe by right clicking point to the air (this is my first time using this mod let me know if im doing anything wrong) but then the game freezes for like 5 seconds, screen goes white, then crashes. 

I am using Forge 1.12.2-forge-14.23.5.2855 
the only mods i have are optifine 1.12.2, little tiles_v1.5.0-pre199_68_mc1.12.2, and creativecore_v1.10.44_mc1.12.2

here is the crash report

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore_v1.10.44_mc1.12.2.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre199_68_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 2/7/21 3:29 AM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at com.creativemd.creativecore.common.gui.GuiControl.isMouseOver(GuiControl.java:123)
	at com.creativemd.creativecore.common.gui.client.style.Style.getBackground(Style.java:39)
	at com.creativemd.creativecore.common.gui.GuiControl.renderBackground(GuiControl.java:261)
	at com.creativemd.creativecore.common.gui.GuiControl.renderControl(GuiControl.java:304)
	at com.creativemd.creativecore.common.gui.container.GuiParent.renderContent(GuiParent.java:129)
	at com.creativemd.creativecore.common.gui.GuiControl.renderControl(GuiControl.java:317)
	at com.creativemd.creativecore.common.gui.mc.GuiContainerSub.func_146979_b(GuiContainerSub.java:216)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:117)
	at com.creativemd.creativecore.common.gui.mc.GuiContainerSub.func_73863_a(GuiContainerSub.java:158)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1457)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.creativemd.creativecore.common.gui.GuiControl.isMouseOver(GuiControl.java:123)
	at com.creativemd.creativecore.common.gui.client.style.Style.getBackground(Style.java:39)
	at com.creativemd.creativecore.common.gui.GuiControl.renderBackground(GuiControl.java:261)
	at com.creativemd.creativecore.common.gui.GuiControl.renderControl(GuiControl.java:304)
	at com.creativemd.creativecore.common.gui.container.GuiParent.renderContent(GuiParent.java:129)
	at com.creativemd.creativecore.common.gui.GuiControl.renderControl(GuiControl.java:317)
	at com.creativemd.creativecore.common.gui.mc.GuiContainerSub.func_146979_b(GuiContainerSub.java:216)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:117)
	at com.creativemd.creativecore.common.gui.mc.GuiContainerSub.func_73863_a(GuiContainerSub.java:158)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)

-- Screen render details --
Details:
	Screen name: com.creativemd.creativecore.common.gui.mc.GuiContainerSub
	Mouse location: Scaled: (480, 269). Absolute: (960, 540)
	Screen size: Scaled: (960, 540). Absolute: (1920, 1080). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['HelloitsRoFi'/12, l='MpServer', x=158.38, y=4.00, z=1099.46]]
	Chunk stats: MultiplayerChunkCache: 575, 575
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (156,4,1085), Chunk: (at 12,0,13 in 9,67; contains blocks 144,0,1072 to 159,255,1087), Region: (0,2; contains chunks 0,64 to 31,95, blocks 0,0,1024 to 511,255,1535)
	Level time: 6815 game time, 6815 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 14 total; [EntitySheep['Sheep'/0, l='MpServer', x=94.50, y=4.00, z=1103.50], EntitySheep['Sheep'/1, l='MpServer', x=88.57, y=4.00, z=1095.73], EntityHorse['Horse'/2, l='MpServer', x=96.50, y=4.00, z=1097.50], EntityHorse['Horse'/3, l='MpServer', x=96.50, y=4.00, z=1095.50], EntityItem['item.item.egg'/35, l='MpServer', x=204.54, y=4.00, z=1134.25], EntitySheep['Sheep'/4, l='MpServer', x=184.80, y=4.00, z=1131.54], EntitySheep['Sheep'/5, l='MpServer', x=208.46, y=4.00, z=1050.23], EntityChicken['Chicken'/6, l='MpServer', x=196.47, y=4.00, z=1135.44], EntitySheep['Sheep'/7, l='MpServer', x=200.50, y=4.00, z=1129.50], EntityChicken['Chicken'/8, l='MpServer', x=204.19, y=4.00, z=1133.60], EntitySheep['Sheep'/9, l='MpServer', x=210.57, y=4.00, z=1043.11], EntitySheep['Sheep'/10, l='MpServer', x=211.50, y=4.00, z=1040.50], EntitySheep['Sheep'/11, l='MpServer', x=212.77, y=4.00, z=1044.62], EntityPlayerSP['HelloitsRoFi'/12, l='MpServer', x=158.38, y=4.00, z=1099.46]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 419288760 bytes (399 MB) / 738197504 bytes (704 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_F5 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version      | Source                                    | Signature                                |
	|:------ |:----------------- |:------------ |:----------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft         | 1.12.2       | minecraft.jar                             | None                                     |
	| LCHIJA | mcp               | 9.42         | minecraft.jar                             | None                                     |
	| LCHIJA | FML               | 8.0.99.99    | forge-1.12.2-14.23.5.2855.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge             | 14.23.5.2855 | forge-1.12.2-14.23.5.2855.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy | 1.0.0        | minecraft.jar                             | None                                     |
	| LCHIJA | littletilescore   | 1.0.0        | minecraft.jar                             | None                                     |
	| LCHIJA | creativecore      | 1.10.0       | CreativeCore_v1.10.44_mc1.12.2.jar        | None                                     |
	| LCHIJA | littletiles       | 1.5.0        | LittleTiles_v1.5.0-pre199_68_mc1.12.2.jar | None                                     |

	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore_v1.10.44_mc1.12.2.jar)
  
LittlePatchingLoader (LittleTiles_v1.5.0-pre199_68_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13506 Compatibility Profile Context 23.20.15016.15' Renderer: 'AMD Radeon(TM) R4 Graphics'
	Launched Version: 1.12.2-forge-14.23.5.2855
	LWJGL: 2.9.4
	OpenGL: AMD Radeon(TM) R4 Graphics GL version 4.5.13506 Compatibility Profile Context 23.20.15016.15, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: VanillaTweaks_r638597.zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A6-7310 APU with AMD Radeon R4 Graphics 
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13506 Compatibility Profile Context 23.20.15016.15
	OpenGlRenderer: AMD Radeon(TM) R4 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by CreativeMD** [comment]
Update LittleTiles.

**Comment by HelloitsRoFi** [comment]
i have downloaded the latest one from curseforge? where can i find an update

**Comment by CreativeMD** [comment]
Pre199_68 is not the newest version

**Comment by HelloitsRoFi** [comment]
lol sorry my bad i just went and checked and your right thank you so much
