### ISSUE TITLE
On launch, LittleTiles causes crash with code 1.

### ISSUE THREAD

**Issue by Valarisgames** [CreativeMD/LittleTiles#601]
I recently downloaded LittleTiles for some Minecraft projects I have in mind using it's capabilities, and I'm having some trouble. Namely, whenever I launch with it using a MultiMC install of Forge, it crashes with exit code 1. I've tested all the other mods I had installed, and they all work fine, both together and on their own; LittleTiles causes me to crash, both on it's own and with other mods.

Save is in C:/New folder/ because I moved it there after the issue started happening, in order to get a log; my file path MultiMC is kept in contains personal info.

`MultiMC version: 0.6.11-1430

Minecraft folder is:
C:/New folder/MultiMC/instances/Valiance/.minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_281/bin/javaw.exe

Java is version 1.8.0_281, using 64-bit architecture.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/New folder/MultiMC/instances/Valiance/natives

Libraries:
  C:/New folder/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/New folder/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/New folder/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/New folder/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/New folder/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/New folder/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/New folder/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/New folder/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/New folder/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/New folder/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/New folder/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/New folder/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/New folder/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/New folder/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/New folder/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/New folder/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/New folder/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/New folder/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/New folder/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/New folder/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/New folder/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/New folder/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/New folder/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  C:/New folder/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/New folder/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/New folder/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/New folder/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/New folder/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/New folder/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/New folder/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/New folder/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/New folder/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2854/forge-1.12.2-14.23.5.2854-universal.jar
  C:/New folder/MultiMC/libraries/org/ow2/asm/asm-debug-all/5.2/asm-debug-all-5.2.jar
  C:/New folder/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/New folder/MultiMC/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  C:/New folder/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/New folder/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/New folder/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/New folder/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/New folder/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2_mc/scala-continuations-library_2.11-1.0.2_mc.jar
  C:/New folder/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2_mc/scala-continuations-plugin_2.11.1-1.0.2_mc.jar
  C:/New folder/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/New folder/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/New folder/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/New folder/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/New folder/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/New folder/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/New folder/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/New folder/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/New folder/MultiMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  C:/New folder/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  C:/New folder/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/New folder/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/New folder/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  [✔️] LittleTiles_v1.5.0-pre324_mc1.12.2

Params:
  --username  --version MultiMC5 --gameDir C:/New folder/MultiMC/instances/Valiance/.minecraft --assetsDir C:/New folder/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx10024m, -Duser.language=en]

Minecraft process ID: 96000

Using onesix launcher.

[23:52:44] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[23:52:44] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[23:52:44] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[23:52:45] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2854 for Minecraft 1.12.2 loading
[23:52:45] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_281, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_281
[23:52:45] [main/INFO] [FML]: Searching C:\New folder\MultiMC\instances\Valiance\.minecraft\mods for mods
[23:52:45] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in LittleTiles_v1.5.0-pre324_mc1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[23:52:45] [main/WARN] [FML]: The coremod com.creativemd.littletiles.LittlePatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:52:45] [main/WARN] [FML]: The coremod LittlePatchingLoader (com.creativemd.littletiles.LittlePatchingLoader) is not signed!
[23:52:45] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at C:\New folder\MultiMC\instances\Valiance\.minecraft for Forge Mod Loader
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:111) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:81) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:141) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: com/creativemd/littletiles/LittleTilesAfterTransformer
	at com.creativemd.littletiles.LittlePatchingLoader.getAccessTransformerClass(LittlePatchingLoader.java:39) ~[LittleTiles_v1.5.0-pre324_mc1.12.2.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:595) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
	... 13 more
Caused by: java.lang.ClassNotFoundException: com.creativemd.littletiles.LittleTilesAfterTransformer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at com.creativemd.littletiles.LittlePatchingLoader.getAccessTransformerClass(LittlePatchingLoader.java:39) ~[LittleTiles_v1.5.0-pre324_mc1.12.2.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:595) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
	... 13 more
Caused by: java.lang.NoClassDefFoundError: com/creativemd/creativecore/transformer/CreativeTransformer
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_281]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_281]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at com.creativemd.littletiles.LittlePatchingLoader.getAccessTransformerClass(LittlePatchingLoader.java:39) ~[LittleTiles_v1.5.0-pre324_mc1.12.2.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:595) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
	... 13 more
Caused by: java.lang.ClassNotFoundException: com.creativemd.creativecore.transformer.CreativeTransformer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_281]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_281]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at com.creativemd.littletiles.LittlePatchingLoader.getAccessTransformerClass(LittlePatchingLoader.java:39) ~[LittleTiles_v1.5.0-pre324_mc1.12.2.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:595) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
	... 13 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_281]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_281]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at com.creativemd.littletiles.LittlePatchingLoader.getAccessTransformerClass(LittlePatchingLoader.java:39) ~[LittleTiles_v1.5.0-pre324_mc1.12.2.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:595) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
	... 13 more
[23:52:45] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:199]: Failed to start Minecraft:
[23:52:45] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: java.lang.reflect.InvocationTargetException
[23:52:45] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:52:45] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[23:52:45] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[23:52:45] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[23:52:45] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[23:52:45] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[23:52:45] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[23:52:45] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[23:52:45] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[23:52:45] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[23:52:45] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[23:52:45] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.Runtime.exit(Unknown Source)
[23:52:45] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.System.exit(Unknown Source)
[23:52:45] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[23:52:45] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[23:52:45] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	... 8 more
[23:52:45] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[23:52:45] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[23:52:45] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[23:52:45] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[23:52:45] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[23:52:45] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[23:52:45] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)
Exception in thread "main" 
Process exited with code 1.`

**Comment by CreativeMD** [comment]
You forgot to install CreativeCore.
