### ISSUE TITLE
Little Tiles Crashes when I try to open a recipe 

### ISSUE THREAD

**Issue by MidKnightOnyxFury** [CreativeMD/LittleTiles#606]
So, im able to launch the game just fine, and I can do pretty much everything else. But the issue comes whenever I try to use the Little Recipe item to actually make something function. When I do, the screen first goes to a blue grey color, then back to the game screen, after which, it crashes. 

this is my crash report. 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  McLib core mod (mclib-2.2.2-1.12.2.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre199_71_mc1.12.2.jar)
  BlockbusterCore (blockbuster-2.2.2-1.12.2.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  CreativePatchingLoader (CreativeCore_v1.10.47_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 3/14/21 9:28 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at com.creativemd.creativecore.common.gui.GuiControl.isMouseOver(GuiControl.java:123)
	at com.creativemd.creativecore.common.gui.client.style.Style.getBackground(Style.java:39)
	at com.creativemd.creativecore.common.gui.GuiControl.renderBackground(GuiControl.java:261)
	at com.creativemd.creativecore.common.gui.GuiControl.renderControl(GuiControl.java:304)
	at com.creativemd.creativecore.common.gui.container.GuiParent.renderContent(GuiParent.java:130)
	at com.creativemd.creativecore.common.gui.GuiControl.renderControl(GuiControl.java:317)
	at com.creativemd.creativecore.common.gui.mc.GuiContainerSub.func_146979_b(GuiContainerSub.java:216)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:117)
	at com.creativemd.creativecore.common.gui.mc.GuiContainerSub.func_73863_a(GuiContainerSub.java:158)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.creativemd.creativecore.common.gui.GuiControl.isMouseOver(GuiControl.java:123)
	at com.creativemd.creativecore.common.gui.client.style.Style.getBackground(Style.java:39)
	at com.creativemd.creativecore.common.gui.GuiControl.renderBackground(GuiControl.java:261)
	at com.creativemd.creativecore.common.gui.GuiControl.renderControl(GuiControl.java:304)
	at com.creativemd.creativecore.common.gui.container.GuiParent.renderContent(GuiParent.java:130)
	at com.creativemd.creativecore.common.gui.GuiControl.renderControl(GuiControl.java:317)
	at com.creativemd.creativecore.common.gui.mc.GuiContainerSub.func_146979_b(GuiContainerSub.java:216)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:117)
	at com.creativemd.creativecore.common.gui.mc.GuiContainerSub.func_73863_a(GuiContainerSub.java:158)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)

-- Screen render details --
Details:
	Screen name: com.creativemd.creativecore.common.gui.mc.GuiContainerSub
	Mouse location: Scaled: (213, 119). Absolute: (640, 360)
	Screen size: Scaled: (427, 240). Absolute: (1280, 720). Scale factor of 3

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['doubleanonbithor'/214, l='MpServer', x=-167.37, y=70.00, z=-500.77]]
	Chunk stats: MultiplayerChunkCache: 48, 48
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-20,64,256), Chunk: (at 12,4,0 in -2,16; contains blocks -32,0,256 to -17,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 46150 game time, 28549 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 12 total; [EntityZombieVillager['Zombie Villager'/354, l='MpServer', x=-154.88, y=55.00, z=-487.48], EntitySheep['Sheep'/259, l='MpServer', x=-178.63, y=69.00, z=-494.53], EntitySheep['Sheep'/260, l='MpServer', x=-178.66, y=69.00, z=-512.21], EntityCreeper['Creeper'/308, l='MpServer', x=-171.82, y=53.00, z=-488.58], EntityVillagerMCA['Grazyna'/309, l='MpServer', x=-162.72, y=68.00, z=-485.58], EntityVillagerMCA['Zach'/310, l='MpServer', x=-168.26, y=69.00, z=-495.61], EntityBat['Bat'/278, l='MpServer', x=-164.73, y=55.07, z=-485.52], EntityCreeper['Creeper'/215, l='MpServer', x=-176.18, y=70.00, z=-502.41], EntityPlayerSP['doubleanonbithor'/214, l='MpServer', x=-167.37, y=70.00, z=-500.77], EntityZombieVillager['Zombie Villager'/217, l='MpServer', x=-182.62, y=53.00, z=-496.14], EntitySheep['Sheep'/314, l='MpServer', x=-161.25, y=69.00, z=-509.50], EntityZombie['Zombie'/219, l='MpServer', x=-174.22, y=48.00, z=-514.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 156990072 bytes (149 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 24 mods loaded, 22 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version      | Source                                    | Signature                                |
	|:------ |:----------------- |:------------ |:----------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft         | 1.12.2       | minecraft.jar                             | None                                     |
	| LCHIJA | mcp               | 9.42         | minecraft.jar                             | None                                     |
	| LCHIJA | FML               | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge             | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy | 1.0.0        | minecraft.jar                             | None                                     |
	| LCHIJA | littletilescore   | 1.0.0        | minecraft.jar                             | None                                     |
	| LCHIJA | jei               | 4.14.4.264   | jei_1.12.2-4.14.4.264.jar                 | None                                     |
	| LCHIJA | quark             | r1.6-179     | Quark-r1.6-179.jar                        | None                                     |
	| LCHIJA | autoreglib        | 1.3-32       | AutoRegLib-1.3-32.jar                     | None                                     |
	| LCHIJA | bibliocraft       | 2.4.5        | BiblioCraft-Mod-1.12.2.jar                | None                                     |
	| LCHIJA | mclib             | 2.2.2        | mclib-2.2.2-1.12.2.jar                    | None                                     |
	| LCHIJA | moreplayermodels  | 1.12.2       | More-Player-Models-Mod-1.12.2.jar         | None                                     |
	| LCHIJA | metamorph         | 1.2.6        | metamorph-1.2.6-1.12.2.jar                | None                                     |
	| LCHIJA | blockbuster       | 2.2.2        | blockbuster-2.2.2-1.12.2.jar              | None                                     |
	| LCHIJA | cfm               | 6.2.0        | cfm-6.2.0-mc1.12.2.jar                    | None                                     |
	| LCHIJA | chiselsandbits    | 14.33        | chiselsandbits-14.33.jar                  | None                                     |
	| LCHIJA | creativecore      | 1.10.0       | CreativeCore_v1.10.47_mc1.12.2.jar        | None                                     |
	| LCHIJA | ptrmodellib       | 1.0.4        | PTRLib-1.0.4.jar                          | None                                     |
	| LCHIJA | props             | 2.6.3        | Decocraft-2.6.3_1.12.2.jar                | None                                     |
	| LCHIJA | littletiles       | 1.5.0        | LittleTiles_v1.5.0-pre199_71_mc1.12.2.jar | None                                     |
	| LCHIJA | radixcore         | 1.12.x-2.2.1 | RadixCore-1.12.2.jar                      | None                                     |
	| LCHIJA | mca               | 1.12.2-5.3.1 | Minecraft-Comes-Alive-Mod-1.12.2.jar      | None                                     |
	| UD     | blockbuster_core  | 2.2.2        | minecraft.jar                             | None                                     |
	| UD     | mclib_core        | 2.2.2        | minecraft.jar                             | None                                     |

	Loaded coremods (and transformers): 
McLib core mod (mclib-2.2.2-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
LittlePatchingLoader (LittleTiles_v1.5.0-pre199_71_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
BlockbusterCore (blockbuster-2.2.2-1.12.2.jar)
  mchorse.blockbuster.core.BBCoreClassTransformer
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
CreativePatchingLoader (CreativeCore_v1.10.47_mc1.12.2.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 22.20.16.4836' Renderer: 'Intel(R) HD Graphics 620'
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 620 GL version 4.5.0 - Build 22.20.16.4836, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: PureBDcraft 128x MC17.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz

**Comment by Doc-1** [comment]
It looks like you need to update LittleTiles. You have pre199; Little Tiles is at pre327. Also, pre327 no longer has the little recipe; it just has what is now called the blueprint. If you ever used the advanced recipe, the blueprint is the same thing.

**Comment by CreativeMD** [comment]
Yep your LT version is way outdated.
