### ISSUE TITLE
Littletiles blocks rendering slowly on mc eternal

### ISSUE THREAD

**Issue by Zatzou** [CreativeMD/LittleTiles#625]
Im having an issue on mc eternal where the blocks are rendering really slowly. They are invisible and then just appear slowly chunk by chunk here are some screenshots of how it looks.
![2021-04-10_01 07 14](https://user-images.githubusercontent.com/12207527/114245510-4ca72300-9999-11eb-8d9f-1ac266ff128a.png)
![2021-04-10_01 07 23](https://user-images.githubusercontent.com/12207527/114245516-4f097d00-9999-11eb-9e14-000d36aacbe3.png)

This also causes vanilla blocks to lag until all of the littletiles blocks have rendered.
Im running mc eternal 1.4.3 and I have already tried all kinds of combination of using different mipmap levels and stuff.

**Comment by Zatzou** [comment]
This happens generally when loading in the area so basically every time i join or come to the area

**Comment by CreativeMD** [comment]
LittleTiles blocks render separately otherwise it there would be horrible lag. You could increase the thread count in the littletiles configuration to speed it up, but if it's that slow you might not have enough RAM. Is there anything in the logs?

**Comment by Zatzou** [comment]
For some reason the log files are gigabytes in size.
It seems to be spamming this just over and over in the log files.

```
[01:06:56] [Thread-62/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at net.minecraft.world.World.handler$zch000$preGetCombinedLight(World.java:5161)
[01:06:56] [Thread-62/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at net.minecraft.world.World.func_175626_b(World.java)
[01:06:56] [Thread-62/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at net.minecraft.block.Block.func_185484_c(Block.java:378)
[01:06:56] [Thread-62/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185889_a(BlockStateContainer.java:362)
[01:06:56] [Thread-62/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at net.minecraftforge.client.model.pipeline.BlockInfo.updateLightMatrix(BlockInfo.java:127)
[01:06:56] [Thread-62/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at net.minecraftforge.client.model.pipeline.VertexLighterSmoothAo.updateBlockInfo(VertexLighterSmoothAo.java:183)
[01:06:56] [Thread-62/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at com.creativemd.creativecore.client.rendering.model.CreativeModelPipeline.renderBlockFaceSmooth(CreativeModelPipeline.java:132)
[01:06:56] [Thread-62/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at com.creativemd.littletiles.client.render.cache.RenderingThread.run(RenderingThread.java:293)
[01:06:56] [Thread-62/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5208]: Something just went wrong here, getting default light value instead!
[01:06:56] [Thread-61/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]: org.valkyrienskies.mod.common.util.multithreaded.CalledFromWrongThreadException: Wrong thread calling code: Thread[Thread-61,5,main]
[01:06:56] [Thread-61/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at org.valkyrienskies.mod.common.ships.ship_world.WorldClientShipManager.enforceGameThread(WorldClientShipManager.java:38)
[01:06:56] [Thread-61/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at org.valkyrienskies.mod.common.ships.ship_world.WorldClientShipManager.getPhysObjectsInAABB(WorldClientShipManager.java:113)
[01:06:56] [Thread-61/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at net.minecraft.world.World.handler$zch000$preGetCombinedLight(World.java:5161)
[01:06:56] [Thread-61/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at net.minecraft.world.World.func_175626_b(World.java)
[01:06:56] [Thread-61/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at net.minecraft.block.Block.func_185484_c(Block.java:378)
[01:06:56] [Thread-61/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185889_a(BlockStateContainer.java:362)
[01:06:56] [Thread-61/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at net.minecraftforge.client.model.pipeline.BlockInfo.updateLightMatrix(BlockInfo.java:127)
[01:06:56] [Thread-61/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at net.minecraftforge.client.model.pipeline.VertexLighterSmoothAo.updateBlockInfo(VertexLighterSmoothAo.java:183)
[01:06:56] [Thread-61/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at com.creativemd.creativecore.client.rendering.model.CreativeModelPipeline.renderBlockFaceSmooth(CreativeModelPipeline.java:132)
[01:06:56] [Thread-61/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at com.creativemd.littletiles.client.render.cache.RenderingThread.run(RenderingThread.java:293)
[01:06:56] [Thread-61/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5208]: Something just went wrong here, getting default light value instead!
[01:06:56] [Thread-62/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]: org.valkyrienskies.mod.common.util.multithreaded.CalledFromWrongThreadException: Wrong thread calling code: Thread[Thread-62,5,main]
[01:06:56] [Thread-62/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at org.valkyrienskies.mod.common.ships.ship_world.WorldClientShipManager.enforceGameThread(WorldClientShipManager.java:38)
[01:06:56] [Thread-62/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at org.valkyrienskies.mod.common.ships.ship_world.WorldClientShipManager.getPhysObjectsInAABB(WorldClientShipManager.java:113)
[01:06:56] [Thread-62/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at net.minecraft.world.World.handler$zch000$preGetCombinedLight(World.java:5161)
[01:06:56] [Thread-62/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at net.minecraft.world.World.func_175626_b(World.java)
[01:06:56] [Thread-62/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at net.minecraft.block.Block.func_185484_c(Block.java:378)
[01:06:56] [Thread-62/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185889_a(BlockStateContainer.java:362)
[01:06:56] [Thread-62/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at net.minecraftforge.client.model.pipeline.BlockInfo.updateLightMatrix(BlockInfo.java:127)
[01:06:56] [Thread-62/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at net.minecraftforge.client.model.pipeline.VertexLighterSmoothAo.updateBlockInfo(VertexLighterSmoothAo.java:183)
[01:06:56] [Thread-62/INFO] [STDERR]: [net.minecraft.world.World:handler$zch000$preGetCombinedLight:5209]:      at com.creativemd.creativecore.client.rendering.model.CreativeModelPipeline.renderBlockFaceSmooth(CreativeModelPipeline.java:132)
```

It appears to mention littletiles so that might be an incompatibility between some mods. It could also be that there is lag just caused by the fact that my memory usage is at very high levels constantly in this pack.

Looks like valkyrien skies messes with the rendering in some way which makes littletiles not work even when there are no valkyrien skies ships in the world.

**Comment by Zatzou** [comment]
I removed valkyrien skies and littletiles seem to render correctly now. This is probably a bug with valkyrien skies.
