### ISSUE TITLE
[Server thread/FATAL]: Error executing task

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#633]
[22:36:08] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/creativemd/creativecore/common/gui/container/SubGui
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_252]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_252]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:836) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:773) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.NoClassDefFoundError: com/creativemd/creativecore/common/gui/container/SubGui
        at com.creativemd.littletiles.common.item.ItemLittleChisel.rotate(ItemLittleChisel.java:250) ~[ItemLittleChisel.class:?]
        at com.creativemd.littletiles.common.packet.LittleRotatePacket.execute(LittleRotatePacket.java:42) ~[LittleRotatePacket.class:?]
        at com.creativemd.littletiles.common.packet.LittleRotatePacket.executeServer(LittleRotatePacket.java:47) ~[LittleRotatePacket.class:?]
        at com.creativemd.creativecore.common.packet.PacketReciever$2.run(PacketReciever.java:117) ~[PacketReciever$2.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_252]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_252]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
Caused by: java.lang.ClassNotFoundException: com.creativemd.creativecore.common.gui.container.SubGui
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_252]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_252]
        at com.creativemd.littletiles.common.item.ItemLittleChisel.rotate(ItemLittleChisel.java:250) ~[ItemLittleChisel.class:?]
        at com.creativemd.littletiles.common.packet.LittleRotatePacket.execute(LittleRotatePacket.java:42) ~[LittleRotatePacket.class:?]
        at com.creativemd.littletiles.common.packet.LittleRotatePacket.executeServer(LittleRotatePacket.java:47) ~[LittleRotatePacket.class:?]
        at com.creativemd.creativecore.common.packet.PacketReciever$2.run(PacketReciever.java:117) ~[PacketReciever$2.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_252]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_252]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
Caused by: java.lang.NoClassDefFoundError: com/creativemd/creativecore/common/gui/container/GuiParent
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_252]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_252]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_252]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_252]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_252]
        at com.creativemd.littletiles.common.item.ItemLittleChisel.rotate(ItemLittleChisel.java:250) ~[ItemLittleChisel.class:?]
        at com.creativemd.littletiles.common.packet.LittleRotatePacket.execute(LittleRotatePacket.java:42) ~[LittleRotatePacket.class:?]
        at com.creativemd.littletiles.common.packet.LittleRotatePacket.executeServer(LittleRotatePacket.java:47) ~[LittleRotatePacket.class:?]
        at com.creativemd.creativecore.common.packet.PacketReciever$2.run(PacketReciever.java:117) ~[PacketReciever$2.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_252]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_252]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
Caused by: java.lang.ClassNotFoundException: com.creativemd.creativecore.common.gui.container.GuiParent
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_252]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_252]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_252]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_252]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_252]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_252]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_252]
        at com.creativemd.littletiles.common.item.ItemLittleChisel.rotate(ItemLittleChisel.java:250) ~[ItemLittleChisel.class:?]
        at com.creativemd.littletiles.common.packet.LittleRotatePacket.execute(LittleRotatePacket.java:42) ~[LittleRotatePacket.class:?]
        at com.creativemd.littletiles.common.packet.LittleRotatePacket.executeServer(LittleRotatePacket.java:47) ~[LittleRotatePacket.class:?]
        at com.creativemd.creativecore.common.packet.PacketReciever$2.run(PacketReciever.java:117) ~[PacketReciever$2.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_252]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_252]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more

it happens in the console when i rotate corners

**Comment by CreativeMD** [comment]
Fixed in the newest version.
