### ISSUE TITLE
java.lang.NullPointerException: Unexpected error

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#635]
at com.creativemd.littletiles.common.util.shape.ShapeSelection.<init>(ShapeSelection.java:65)
	at com.creativemd.littletiles.common.item.ItemLittleHammer.getBoxes(ItemLittleHammer.java:94)
	at com.creativemd.littletiles.client.render.overlay.PreviewRenderer.drawHighlight(PreviewRenderer.java:301)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_357_PreviewRenderer_drawHighlight_DrawBlockHighlightEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:191)
	at sun.reflect.GeneratedMethodAccessor96.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.callBoolean(Reflector.java:689)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1827)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1621)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1390)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Latest Little Tiles 1.5.2 when i choose  little hammer

**Comment by Desoroxxx** [comment]
Did you tried with a new hammer ?

Like destroying the current one, and then giving/crafting a new one ?

**Comment by ghost** [comment]
yes

**Comment by CreativeMD** [comment]
Fixed in the newest version!
