### ISSUE TITLE
Saving entity NBT

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#658]
java.lang.AbstractMethodError: com.creativemd.creativecore.common.world.SaveHandlerFake.getUUID()Ljava/util/UUID;
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1885)
	at net.minecraft.entity.Entity.func_184198_c(Entity.java:1809)
	at com.creativemd.littletiles.common.entity.EntityAnimation.func_70014_b(EntityAnimation.java:949)
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1934)
	at com.creativemd.littletiles.common.world.WorldAnimationHandler.trackEntity(WorldAnimationHandler.java:135)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_193_WorldAnimationHandler_trackEntity_StartTracking.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:96)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186)
	at net.minecraftforge.event.ForgeEventFactory.onStartEntityTracking(ForgeEventFactory.java:398)
	at net.minecraft.entity.EntityTrackerEntry.func_73117_b(EntityTrackerEntry.java:515)
	at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:318)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:916)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630)
	at java.lang.Thread.run(Thread.java:748)

Habe das Windrad von Tacco platziert und dann nach einer Weile kam es zu dem Crash.

**Comment by CreativeMD** [comment]
Was für einen Server benutzt ihr? Ich bräuchte die gesamte Modliste.

**Comment by ghost** [comment]
Wir nutzen Mohist. Hier ist unsere Modlist.

https://gyazo.com/2f754955474d13c5db3e6611ec022633

Ich kann aber nochmal versuchen wie sich das ganze auf nem Forge only Server verhält.

**Comment by Desoroxxx** [comment]
Hayho
versuch es nochmal auf einem forge only server mal schauen ob sich was ändert
mit freundlichen grüßen ^^

**Comment by CreativeMD** [comment]
Leider unterstützt LittleTiles Mohist nicht.
