### ISSUE TITLE
Crash when starting minecraft with your sources

### ISSUE THREAD

**Issue by Protoxy22** [CreativeMD/LittleTiles#659]
I have this crash when I place something from LittleTiles, or when the world load LittleTiles blocks.

I'm in the IntelliJ dev environement and I correctly set the Manifest and -Dfml.coreMods.load=com.creativemd.littletiles.LittlePatchingLoader 

```
[16:51:12] [Client thread/FATAL] [minecraft/Minecraft]: Unreported exception thrown!
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at com.creativemd.littletiles.client.render.world.LittleChunkDispatcher.uploadChunk(LittleChunkDispatcher.java:158) ~[LittleChunkDispatcher.class:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.uploadChunk(ChunkRenderDispatcher.java) ~[ChunkRenderDispatcher.class:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.processTask(ChunkRenderWorker.java:160) ~[ChunkRenderWorker.class:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.updateChunkNow(ChunkRenderDispatcher.java:172) ~[ChunkRenderDispatcher.class:?]
	at net.minecraft.client.renderer.RenderGlobal.setupTerrain(RenderGlobal.java:976) ~[RenderGlobal.class:?]
	at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1316) ~[EntityRenderer.class:?]
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1259) ~[EntityRenderer.class:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1062) ~[EntityRenderer.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119) ~[Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:398) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_211]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_211]
	at net.minecraftforge.legacydev.Main.start(Main.java:86) [legacydev-0.2.3.1-fatjar.jar:0.2.3.1+4+372be23]
	at net.minecraftforge.legacydev.MainClient.main(MainClient.java:29) [legacydev-0.2.3.1-fatjar.jar:0.2.3.1+4+372be23]
[16:51:12] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:553]: ---- Minecraft Crash Report ----
// My bad.

Time: 5/1/21 4:51 PM
Description: Unexpected error

java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at com.creativemd.littletiles.client.render.world.LittleChunkDispatcher.uploadChunk(LittleChunkDispatcher.java:158)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.uploadChunk(ChunkRenderDispatcher.java)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.processTask(ChunkRenderWorker.java:160)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.updateChunkNow(ChunkRenderDispatcher.java:172)
	at net.minecraft.client.renderer.RenderGlobal.setupTerrain(RenderGlobal.java:976)
	at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1316)
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.run(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.legacydev.Main.start(Main.java:86)
	at net.minecraftforge.legacydev.MainClient.main(MainClient.java:29)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.creativemd.littletiles.client.render.world.LittleChunkDispatcher.uploadChunk(LittleChunkDispatcher.java:158)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.uploadChunk(ChunkRenderDispatcher.java)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.processTask(ChunkRenderWorker.java:160)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.updateChunkNow(ChunkRenderDispatcher.java:172)
	at net.minecraft.client.renderer.RenderGlobal.setupTerrain(RenderGlobal.java:976)
	at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1316)
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1259)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Player513'/1461, l='MpServer', x=-4.75, y=66.00, z=230.30]]
	Chunk stats: MultiplayerChunkCache: 552, 552
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-9,64,222), Chunk: (at 7,4,14 in -1,13; contains blocks -16,0,208 to -1,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 365 game time, 365 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 99 total; [EntitySquid['Squid'/1536, l='MpServer', x=-11.17, y=59.07, z=252.43], EntitySquid['Squid'/1537, l='MpServer', x=-14.32, y=56.13, z=252.50], EntitySquid['Squid'/1538, l='MpServer', x=-13.25, y=58.17, z=251.02], EntityCreeper['Creeper'/2052, l='MpServer', x=-13.20, y=44.00, z=269.48], EntityZombie['Zombie'/2066, l='MpServer', x=-18.50, y=35.00, z=285.50], EntitySquid['Squid'/1557, l='MpServer', x=-48.08, y=60.71, z=239.80], EntitySquid['Squid'/1558, l='MpServer', x=-57.38, y=57.31, z=233.64], EntitySquid['Squid'/1559, l='MpServer', x=-50.21, y=60.49, z=236.58], EntitySquid['Squid'/1560, l='MpServer', x=-53.82, y=60.38, z=241.21], EntitySquid['Squid'/1561, l='MpServer', x=18.83, y=62.43, z=216.12], EntityBat['Bat'/1817, l='MpServer', x=9.11, y=32.08, z=219.62], EntitySquid['Squid'/1562, l='MpServer', x=25.85, y=62.19, z=214.36], EntityBat['Bat'/1818, l='MpServer', x=-9.12, y=27.02, z=216.59], EntitySquid['Squid'/1563, l='MpServer', x=8.57, y=59.22, z=200.59], EntitySquid['Squid'/1564, l='MpServer', x=13.40, y=59.19, z=211.59], EntityZombie['Zombie'/1828, l='MpServer', x=15.72, y=15.00, z=247.48], EntityCreeper['Creeper'/2086, l='MpServer', x=-56.50, y=15.00, z=224.50], EntityCreeper['Creeper'/2087, l='MpServer', x=-58.50, y=15.00, z=228.50], EntityCreeper['Creeper'/2094, l='MpServer', x=-3.50, y=35.00, z=284.50], EntitySkeleton['Skeleton'/1583, l='MpServer', x=24.50, y=19.00, z=273.50], EntitySkeleton['Skeleton'/1584, l='MpServer', x=21.50, y=19.00, z=273.50], EntityPlayerSP['Player513'/1461, l='MpServer', x=-4.75, y=66.00, z=230.30], EntitySkeleton['Skeleton'/1851, l='MpServer', x=67.50, y=40.00, z=300.50], EntityZombie['Zombie'/2117, l='MpServer', x=24.50, y=21.00, z=276.50], EntityBat['Bat'/1863, l='MpServer', x=-37.33, y=43.10, z=304.51], EntityBat['Bat'/1864, l='MpServer', x=50.25, y=22.10, z=227.49], EntityBat['Bat'/1865, l='MpServer', x=50.39, y=20.98, z=222.25], EntityMinecartChest['Minecart with Chest'/73, l='MpServer', x=-86.89, y=19.00, z=194.49], EntityMinecartChest['Minecart with Chest'/75, l='MpServer', x=-86.50, y=30.06, z=253.50], EntityMinecartChest['Minecart with Chest'/76, l='MpServer', x=-81.50, y=34.06, z=253.50], EntityBat['Bat'/1871, l='MpServer', x=-82.28, y=34.04, z=279.70], EntityZombie['Zombie'/1877, l='MpServer', x=9.50, y=13.00, z=241.50], EntityBat['Bat'/1889, l='MpServer', x=-0.29, y=22.60, z=242.55], EntitySheep['Sheep'/98, l='MpServer', x=-58.50, y=70.00, z=306.50], EntitySheep['Sheep'/99, l='MpServer', x=-59.50, y=70.00, z=306.50], EntityBat['Bat'/1891, l='MpServer', x=50.45, y=20.57, z=227.08], EntitySheep['Sheep'/100, l='MpServer', x=-62.50, y=71.00, z=307.50], EntitySheep['Sheep'/101, l='MpServer', x=-64.50, y=71.00, z=306.50], EntitySpider['Spider'/2161, l='MpServer', x=64.50, y=30.00, z=275.50], EntityZombie['Zombie'/1906, l='MpServer', x=-37.50, y=30.00, z=306.50], EntityBat['Bat'/1907, l='MpServer', x=-30.49, y=41.75, z=241.44], EntityBat['Bat'/1908, l='MpServer', x=-31.34, y=43.08, z=237.57], EntityZombie['Zombie'/2169, l='MpServer', x=47.69, y=47.00, z=240.53], EntitySheep['Sheep'/122, l='MpServer', x=66.50, y=64.00, z=307.50], EntitySheep['Sheep'/124, l='MpServer', x=62.49, y=64.00, z=302.53], EntityZombie['Zombie'/1918, l='MpServer', x=47.70, y=19.00, z=184.63], EntityZombie['Zombie'/1919, l='MpServer', x=48.53, y=16.00, z=176.75], EntitySkeleton['Skeleton'/1927, l='MpServer', x=-7.50, y=27.00, z=257.50], EntityBat['Bat'/1680, l='MpServer', x=39.25, y=16.91, z=268.25], EntitySkeleton['Skeleton'/2194, l='MpServer', x=-37.50, y=40.00, z=255.67], EntitySkeleton['Skeleton'/2195, l='MpServer', x=-34.50, y=40.00, z=267.50], EntitySkeleton['Skeleton'/2196, l='MpServer', x=-35.50, y=40.00, z=265.50], EntityZombie['Zombie'/1941, l='MpServer', x=50.50, y=37.00, z=213.50], EntityZombie['Zombie'/1942, l='MpServer', x=58.50, y=37.00, z=212.50], EntitySkeleton['Skeleton'/2199, l='MpServer', x=57.50, y=26.00, z=229.50], EntitySkeleton['Skeleton'/1692, l='MpServer', x=16.50, y=9.00, z=177.50], EntitySpider['Spider'/2206, l='MpServer', x=50.50, y=37.00, z=212.50], EntityZombie['Zombie'/2207, l='MpServer', x=-21.50, y=27.00, z=263.50], EntityZombie['Zombie'/1696, l='MpServer', x=51.50, y=24.00, z=226.50], EntityZombie['Zombie'/2208, l='MpServer', x=-19.50, y=27.00, z=263.50], EntitySkeleton['Skeleton'/1954, l='MpServer', x=67.50, y=28.00, z=290.27], EntitySkeleton['Skeleton'/1955, l='MpServer', x=51.50, y=24.00, z=292.50], EntityBat['Bat'/1700, l='MpServer', x=-12.38, y=35.59, z=287.36], EntityCreeper['Creeper'/1956, l='MpServer', x=48.80, y=24.00, z=288.45], EntityCreeper['Creeper'/1957, l='MpServer', x=50.50, y=24.00, z=289.50], EntitySkeleton['Skeleton'/1704, l='MpServer', x=0.50, y=23.00, z=238.50], EntityZombie['Zombie'/1962, l='MpServer', x=-67.50, y=15.00, z=172.50], EntitySpider['Spider'/1969, l='MpServer', x=54.50, y=27.00, z=229.50], EntityEnderman['Enderman'/1716, l='MpServer', x=-13.50, y=25.00, z=262.50], EntitySkeleton['Skeleton'/1717, l='MpServer', x=-17.50, y=25.00, z=264.50], EntitySpider['Spider'/1973, l='MpServer', x=32.50, y=14.00, z=154.50], EntitySkeleton['Skeleton'/1718, l='MpServer', x=-18.50, y=25.00, z=262.50], EntitySpider['Spider'/2235, l='MpServer', x=54.50, y=34.00, z=221.50], EntitySkeleton['Skeleton'/2239, l='MpServer', x=-33.50, y=26.00, z=274.50], EntityZombie['Zombie'/2241, l='MpServer', x=40.50, y=45.00, z=219.50], EntitySquid['Squid'/1478, l='MpServer', x=-36.79, y=60.29, z=238.34], EntitySquid['Squid'/1479, l='MpServer', x=-36.22, y=59.28, z=247.25], EntitySquid['Squid'/1480, l='MpServer', x=-42.57, y=58.87, z=240.05], EntitySquid['Squid'/1481, l='MpServer', x=-39.73, y=59.55, z=242.20], EntitySkeleton['Skeleton'/2251, l='MpServer', x=40.50, y=21.00, z=252.50], EntitySquid['Squid'/1486, l='MpServer', x=6.91, y=49.90, z=180.14], EntitySquid['Squid'/1487, l='MpServer', x=4.60, y=47.00, z=176.06], EntitySquid['Squid'/1492, l='MpServer', x=-41.99, y=53.30, z=250.79], EntitySkeleton['Skeleton'/2004, l='MpServer', x=42.50, y=47.00, z=252.50], EntitySquid['Squid'/1493, l='MpServer', x=-47.53, y=54.77, z=250.87], EntitySquid['Squid'/1494, l='MpServer', x=-47.53, y=53.80, z=251.60], EntitySkeleton['Skeleton'/1750, l='MpServer', x=-45.51, y=15.00, z=249.79], EntityZombie['Zombie'/2262, l='MpServer', x=64.50, y=32.00, z=281.50], EntitySkeleton['Skeleton'/2008, l='MpServer', x=54.73, y=32.00, z=220.49], EntityZombieVillager['Zombie Villager'/2276, l='MpServer', x=-25.50, y=43.00, z=289.50], EntitySquid['Squid'/1515, l='MpServer', x=37.40, y=51.06, z=194.40], EntitySquid['Squid'/1516, l='MpServer', x=45.17, y=51.38, z=205.25], EntitySquid['Squid'/1517, l='MpServer', x=47.43, y=54.98, z=199.45], EntitySquid['Squid'/1518, l='MpServer', x=41.94, y=54.41, z=202.78], EntitySquid['Squid'/1531, l='MpServer', x=-16.48, y=53.73, z=257.86], EntitySquid['Squid'/1532, l='MpServer', x=-23.67, y=53.52, z=260.96], EntitySquid['Squid'/1533, l='MpServer', x=-11.40, y=51.91, z=260.55], EntitySquid['Squid'/1534, l='MpServer', x=-13.51, y=51.63, z=266.41], EntitySquid['Squid'/1535, l='MpServer', x=-14.87, y=56.00, z=249.57]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:420)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.run(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.legacydev.Main.start(Main.java:86)
	at net.minecraftforge.legacydev.MainClient.main(MainClient.java:29)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 878860848 bytes (838 MB) / 1214775296 bytes (1158 MB) up to 3806855168 bytes (3630 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID              | Version      | Source                                                             | Signature |
	|:------ |:--------------- |:------------ |:------------------------------------------------------------------ |:--------- |
	| LCHIJA | minecraft       | 1.12.2       | minecraft.jar                                                      | None      |
	| LCHIJA | mcp             | 9.42         | minecraft.jar                                                      | None      |
	| LCHIJA | FML             | 8.0.99.99    | forge-1.12.2-14.23.5.2854_mapped_snapshot_20171003-1.12-recomp.jar | None      |
	| LCHIJA | forge           | 14.23.5.2854 | forge-1.12.2-14.23.5.2854_mapped_snapshot_20171003-1.12-recomp.jar | None      |
	| LCHIJA | littletilescore | 1.0.0        | minecraft.jar                                                      | None      |
	| LCHIJA | creativecore    | 1.10.0       | CreativeCore_v1.10.57_mc1.12.2.jar                                 | None      |
	| LCHIJA | littletiles     | 1.5.0        | main                                                               | None      |

	Loaded coremods (and transformers): 
LittlePatchingLoader (unknown)
  com.creativemd.littletiles.LittleTilesTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 461.09' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: ${MC_VERSION}
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 461.09, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor 
```

**Comment by Protoxy22** [comment]
You can always give the link of your blurry 2017 video, we see nothing on it
Could you make real explanations on the setup of your mod ? And why is it necessary to make a double project (CreativeCore & LittleTiles) ?

Your mod mod is incredible, but it drives me crazy. Nobody can build your mod dude, your old video has no utility,
there is absolutely no explanations, just tasks to follow without explaining why you do it

**Comment by Protoxy22** [comment]
Dude, I just want to disable the rightClicks activation of doors in function of the state of my game (Lobby, InGame)
It is buggy asfuck, the door animation is played on rightClick but still closed

**Comment by CreativeMD** [comment]
Hey, sorry for not responding earlier. I highly recommend to use eclipse because I have no idea how to do this for IntelliJ. So I can't really help you. The video is still the best explanation (https://www.youtube.com/watch?v=7Ahshi_QjM4), if you follow each step it will definitely work.

A few important things that might help you:
- CreativeCore has a core mod which has to be loaded before LT ones
- I use mod files in the mod folder to activate the core mods not a command line

Things will look different in 1.16, but I can guarantee you it's still a mess. I'm not very good at these things and the solutions I got from other people just don't suit my way of working. But at least the core mods should work a lot easier.

I will close this issue for now. You can also contact me over discord (I will respond sooner there).
