### ISSUE TITLE
Error executing task on  the server

### ISSUE THREAD

**Issue by KopieSlime** [CreativeMD/LittleTiles#703]
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_291]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_291]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_291]
Caused by: java.lang.NullPointerException
        at net.minecraft.world.World.handler$zzf000$checkLightFor(World.java:4636) ~[amu.class:?]
        at net.minecraft.world.World.func_180500_c(World.java) ~[amu.class:?]
        at net.minecraft.world.World.func_175664_x(World.java:3222) ~[amu.class:?]
        at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.updateLighting(TileEntityLittleTiles.java:178) ~[TileEntityLittleTiles.class:?]
        at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.updateTiles(TileEntityLittleTiles.java:261) ~[TileEntityLittleTiles.class:?]
        at com.creativemd.littletiles.common.util.place.Placement.placeTiles(Placement.java:237) ~[Placement.class:?]
        at com.creativemd.littletiles.common.util.place.Placement.place(Placement.java:178) ~[Placement.class:?]
        at com.creativemd.littletiles.common.util.place.Placement.tryPlace(Placement.java:189) ~[Placement.class:?]
        at com.creativemd.littletiles.common.structure.type.door.LittleDoorBase.place(LittleDoorBase.java:206) ~[LittleDoorBase.class:?]
        at com.creativemd.littletiles.common.structure.type.door.LittleDoorBase.openDoor(LittleDoorBase.java:265) ~[LittleDoorBase.class:?]
        at com.creativemd.littletiles.common.structure.type.door.LittleDoor.activate(LittleDoor.java:106) ~[LittleDoor.class:?]
        at com.creativemd.littletiles.common.packet.LittleActivateDoorPacket.executeServer(LittleActivateDoorPacket.java:87) ~[LittleActivateDoorPacket.class:?]
        at com.creativemd.creativecore.common.packet.PacketReciever$2.run(PacketReciever.java:117) ~[PacketReciever$2.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_291]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_291]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
        
        door after opening stop working and become non existing block 
        
        mods: archaicguns@0.3.1,ctgui@1.0.0,cgm@0.15.3,creativecoredummy@1.0.0,jei@4.15.0.268,nei@2.4.3,scarper@1.1,uppers@0.0.6,mcp@9.42,ctm@MC1.12.2-1.0.2.31,harvestcraft@1.12.2zb,athenaeum@1.12.2-1.19.2,pyrotech@1.12.2-1.5.7,imvoice@0.7.0,tlauncher_custom_cape_skin@1.4,superhot@1.1,crafttweaker@4.1.20,firstaid@1.6.15,forge@14.23.5.2855,absentbydesign@1.12.2-1.0.4,phosphor-lighting@1.12.2-0.2.7,konkrete@1.1.5,corpse@1.12.2-1.0.8,variedcommodities@1.12.2,minecraft@1.12.2,ambientsounds@3.0,crafttweakerjei@2.0.3,mtlib@3.0.6,blur@1.0.4-14,creativecore@1.10.0,modtweaker@4.0.18,futureminecraf@1.3.1,astikorcarts@1.12.2-0.1.2.7,dropt@1.12.2-1.18.0,resourceloader@1.5.3,littletilescore@1.0.0,patchouli@1.0-22,securitycraft@v1.8.21,cathedral@1.12.2-1.9.9,doubleslabs@0.10.0,toughasnails@3.1.0.140,dawnoftimebuilder@1.0.6,FML@8.0.99.99,obfuscate@0.2.6,customnpcs@1.12,spartanweaponry@beta 1.3.8,chisel@MC1.12.2-1.0.2.45,hardcoredarkness@1.9,recipehandler@0.13,codechickenlib@3.2.3.358,playerrevive@1.0,littletiles@1.5.0,unlimitedchiselworks@0.3.4

**Comment by CreativeMD** [comment]
Can you send me your entire log file?

**Comment by KopieSlime** [comment]
[2021-06-07-1.log](https://github.com/CreativeMD/LittleTiles/files/6617135/2021-06-07-1.log)

**Comment by CreativeMD** [comment]
LittleTiles does not support Mohist. The issue is very likely to come from that. You could report it to them, maybe the can fix it or already have fixed it in an update.
