### ISSUE TITLE
Error when breaking a door in combination with Special AI

### ISSUE THREAD

**Issue by juraj-hrivnak** [CreativeMD/LittleTiles#709]
- **latest.log**
https://paste.ee/p/Spbds

Probably it's Special AI fault?
```less
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
    at fathertoast.specialai.village.ReputationHandler.onBlockBreak(ReputationHandler.java:181)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2717_ReputationHandler_onBlockBreak_BreakEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at com.creativemd.littletiles.common.action.LittleAction.fireBlockBreakEvent(LittleAction.java:419)
    at com.creativemd.littletiles.common.action.LittleActionInteract.action(LittleActionInteract.java:129)
    at com.creativemd.littletiles.common.action.LittleAction.executeServer(LittleAction.java:307)
    at com.creativemd.creativecore.common.packet.PacketReciever$2.run(PacketReciever.java:117)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 5 more
```

**Comment by CreativeMD** [comment]
Not sure if I can do something about it. Have you reported the issue to them?

**Comment by juraj-hrivnak** [comment]
Hmm, yeah, but it's not a major issue, at least.
Yes, I reported it to the mod author just right now :D
https://www.curseforge.com/minecraft/mc-mods/special-ai?comment=103

**Comment by CreativeMD** [comment]
Sorry but I will close this issue for now. Special AI hasn't updated in quite in some time and it's not an issue of LittleTiles itself either.

**Comment by juraj-hrivnak** [comment]
No problem! Thanks for your time!
