### ISSUE TITLE
I am using other mods that seem like they would be compatiable but i'm having issues

### ISSUE THREAD

**Issue by Problemswithmods** [CreativeMD/LittleTiles#727]
So I have
BiomesOPlenty-1.12.2-7.0.1.2444-universal
chiselsandbits-14.33
Decocraft-2.6.3_1.12.2 (3)
fairylights-2.2.0-1.12.2
jei_1.12.2-4.16.1.301
JustEnoughIDs-1.0.3-55 (1)
PTRLib-1.0.5 (1)
I am also using the cocricot resource pack but not the mod, my screen keeps going black and then has the menue in the very left lower corner of the screen

**Comment by CreativeMD** [comment]
I need the crash-report in order to help you. But also make sure to install the newest version of CreativeCore and LittleTiles from curseforge.

**Comment by Problemswithmods** [comment]
There is no crash report but it makes the game unplayable as no menus are
displayed and the only non-black part of the screen is in the far left
corner, would you like a picture?

**Comment by CreativeMD** [comment]
There has to be an error in the log file at least.

**Comment by Problemswithmods** [comment]
[16:08:45] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:08:45] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:08:45] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[16:08:45] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2854 for Minecraft 1.12.2 loading
[16:08:45] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 7:amd64:6.1, installed at C:\Program Files (x86)\Minecraft\runtime\jre-legacy\windows-x64\jre-legacy
[16:08:47] [main/INFO] [FML]: Searching C:\Users\pc\AppData\Roaming\.minecraft\mods for mods
[16:08:47] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from JustEnoughIDs-1.0.3-55 (1).jar
[16:08:47] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_F5 (1).jar
[16:08:47] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:08:47] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[16:08:47] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/pc/AppData/Roaming/.minecraft/mods/JustEnoughIDs-1.0.3-55%20(1).jar Service=LaunchWrapper Env=CLIENT
[16:08:51] [main/WARN] [FML]: The coremod JustEnoughIDs Extension Plugin (org.dimdev.jeid.JEIDLoadingPlugin) is not signed!
[16:08:51] [main/INFO] [JustEnoughIDs]: Initializing JustEnoughIDs core mixins
[16:08:51] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[16:08:51] [main/INFO] [JustEnoughIDs]: Initializing JustEnoughIDs initialization mixins
[16:08:51] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[16:08:51] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[16:08:51] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:08:51] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:08:51] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[16:08:51] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[16:08:51] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[16:08:51] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ClassTransformer
[16:08:51] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ZIP file: C:\Users\pc\AppData\Roaming\.minecraft\mods\OptiFine_1.12.2_HD_U_F5 (1).jar
[16:08:51] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:08:54] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[16:08:54] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[16:08:54] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:08:54] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[16:08:54] [main/INFO] [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@44cb460e
[16:08:54] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[16:08:55] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[16:08:55] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[16:08:55] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[16:08:55] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[16:08:55] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
[16:08:56] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[16:08:57] [Client thread/INFO] [net.minecraft.client.Minecraft]: Setting user:
[16:09:04] [Client thread/INFO] [Config]: [OptiFine] *** Reflector Forge ***
[16:09:04] [Client thread/INFO] [Config]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient
[16:09:06] [Client thread/INFO] [Config]: [OptiFine] *** Reflector Vanilla ***
[16:09:07] [Client thread/INFO] [net.minecraft.client.Minecraft]: LWJGL Version: 2.9.4
[16:09:08] [Client thread/INFO] [Config]: [OptiFine] 
[16:09:08] [Client thread/INFO] [Config]: [OptiFine] OptiFine_1.12.2_HD_U_F5
[16:09:08] [Client thread/INFO] [Config]: [OptiFine] Build: 20191204-141934
[16:09:08] [Client thread/INFO] [Config]: [OptiFine] OS: Windows 7 (amd64) version 6.1
[16:09:08] [Client thread/INFO] [Config]: [OptiFine] Java: 1.8.0_51, Oracle Corporation
[16:09:08] [Client thread/INFO] [Config]: [OptiFine] VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[16:09:08] [Client thread/INFO] [Config]: [OptiFine] LWJGL: 2.9.4
[16:09:08] [Client thread/INFO] [Config]: [OptiFine] OpenGL: Intel(R) Q45/Q43 Express Chipset, version 2.1.0 - Build 8.15.10.2302, Intel
[16:09:08] [Client thread/INFO] [Config]: [OptiFine] OpenGL Version: 2.1.0
[16:09:08] [Client thread/INFO] [Config]: [OptiFine] OpenGL Fancy fog: Not available (GL_NV_fog_distance)
[16:09:08] [Client thread/INFO] [Config]: [OptiFine] Maximum texture size: 4096x4096
[16:09:08] [VersionCheck/INFO] [Config]: [OptiFine] Checking for new version
[16:09:08] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] OpenGL Version: 2.1.0 - Build 8.15.10.2302
[16:09:08] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Vendor:  Intel
[16:09:08] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Renderer: Intel(R) Q45/Q43 Express Chipset
[16:09:08] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Capabilities:  2.0  2.1  -  -  - 
[16:09:08] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] GL_MAX_DRAW_BUFFERS: 8
[16:09:08] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] GL_MAX_COLOR_ATTACHMENTS_EXT: 8
[16:09:08] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] GL_MAX_TEXTURE_IMAGE_UNITS: 16
[16:09:08] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Load shaders configuration.
[16:09:08] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Loaded shaderpack: (internal)
[16:09:09] [Client thread/INFO] [Config]: [OptiFine] [Shaders] Delayed loading of block mappings after resources are loaded
[16:09:09] [Client thread/INFO] [Config]: [OptiFine] [Shaders] Delayed loading of item mappings after resources are loaded
[16:09:09] [Client thread/INFO] [Config]: [OptiFine] [Shaders] Delayed loading of entity mappings after resources are loaded
[16:09:09] [Client thread/INFO] [Config]: [OptiFine] VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
[16:09:09] [VersionCheck/INFO] [Config]: [OptiFine] Version found: G5
[16:09:09] [Client thread/INFO] [FML]: Forge Mod Loader has detected optifine OptiFine_1.12.2_HD_U_F5, enabling compatibility features
[16:09:09] [Client thread/INFO] [FML]: MinecraftForge v14.23.5.2854 Initialized
[16:09:09] [Client thread/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[16:09:09] [Client thread/INFO] [FML]: Invalid recipe found with multiple oredict ingredients in the same ingredient...
[16:09:09] [Client thread/INFO] [FML]: Replaced 1227 ore ingredients
[16:09:10] [Client thread/INFO] [FML]: Searching C:\Users\pc\AppData\Roaming\.minecraft\mods for mods
[16:09:23] [Client thread/WARN] [FML]: Mod jeid is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.0.3-55
[16:09:26] [Client thread/INFO] [FML]: Forge Mod Loader has identified 12 mods to load
[16:09:26] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod props (Decocraft) requires [ptrmodellib@[1.0.3,)]
[16:09:26] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod jehc (Just Enough HarvestCraft) requires [jei@[4.15,)]
[16:09:26] [Client thread/ERROR] [FML]: An exception was thrown, the game will display an error screen and halt.
net.minecraftforge.fml.common.MultipleModsErrored: 
Missing Mods:
	unknown : need [1.0.3,): have missing

Missing Mods:
	unknown : need [4.15,): have missing


	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:300) ~[Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:572) ~[Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[16:09:26] [Client thread/WARN] [FML]: EventBus 0 shutting down - future events will not be posted.
[16:09:26] [Client thread/INFO] [net.minecraft.client.resources.SimpleReloadableResourceManager]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Biomes O' Plenty, FMLFileResourcePack:cocricot Mod, FMLFileResourcePack:Decocraft, FMLFileResourcePack:Fairy Lights, FMLFileResourcePack:Just Enough HarvestCraft, FMLFileResourcePack:JustEnoughIDs, FMLFileResourcePack:GachaShroom, FMLFileResourcePack:Pam's HarvestCraft, cocricot for 1.12.2 v1.10.3.zip
[16:09:27] [Client thread/WARN] [FML]: There were errors previously. Not beginning mod initialization phase
[16:09:27] [Client thread/INFO] [Config]: [OptiFine] *** Reloading textures ***
[16:09:27] [Client thread/INFO] [Config]: [OptiFine] Resource packs: cocricot for 1.12.2 v1.10.3.zip
[16:09:29] [Sound Library Loader/INFO] [net.minecraft.client.audio.SoundManager]: Starting up SoundSystem...
[16:09:30] [Thread-3/INFO] [net.minecraft.client.audio.SoundManager]: Initializing LWJGL OpenAL
[16:09:30] [Thread-3/INFO] [net.minecraft.client.audio.SoundManager]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[16:09:31] [Client thread/INFO] [com.mojang.text2speech.NarratorWindows]: Narrator library for x64 successfully loaded
[16:09:33] [Client thread/INFO] [Config]: [OptiFine] *** Reloading custom textures ***
[16:09:33] [Client thread/INFO] [Config]: [OptiFine] CustomColors: Colormap mcpatcher/colormap/sky0.png
[16:09:33] [Client thread/INFO] [Config]: [OptiFine] CustomColors: Non-standard palette size: 1x1, should be: 256x256, path: mcpatcher/colormap/sky0.png
[16:09:33] [Client thread/INFO] [Config]: [OptiFine] CustomColors: Colormap mcpatcher/colormap/fog0.png
[16:09:33] [Client thread/INFO] [Config]: [OptiFine] CustomColors: Non-standard palette size: 1x1, should be: 256x256, path: mcpatcher/colormap/fog0.png
[16:09:33] [Client thread/INFO] [Config]: [OptiFine] CustomColors: Colormap mcpatcher/colormap/underlava.png
[16:09:33] [Client thread/INFO] [Config]: [OptiFine] CustomColors: Non-standard palette size: 1x1, should be: 256x256, path: mcpatcher/colormap/underlava.png
[16:09:33] [Client thread/INFO] [Config]: [OptiFine] CustomColors: Colormap mcpatcher/lightmap/world-1.png
[16:09:33] [Client thread/INFO] [Config]: [OptiFine] CustomColors: Loading mcpatcher/color.properties
[16:09:33] [Client thread/INFO] [Config]: [OptiFine] CustomColors: lilypad = 7db732
[16:09:33] [Client thread/INFO] [Config]: [OptiFine] CustomColors: text.sign = ffffff
[16:09:33] [Client thread/INFO] [Config]: [OptiFine] CustomColors: fog.nether = fffafa
[16:09:33] [Client thread/INFO] [Config]: [OptiFine] CustomColors: Block palette: palette.block./colormap/color.png = 83 106 111 161:2 161:6 161:14 161:3 161:7 161:15
[16:09:33] [Client thread/WARN] [Config]: [OptiFine] CustomColors: Colormap not found: mcpatcher/colormap/color.png
[16:09:33] [Client thread/INFO] [Config]: [OptiFine] CustomColors: Block palette: palette.block./colormap/color2.png = 30:15 389 65
[16:09:33] [Client thread/WARN] [Config]: [OptiFine] CustomColors: Colormap not found: mcpatcher/colormap/color2.png
[16:09:33] [Client thread/INFO] [Config]: [OptiFine] CustomColors: Block palette: palette.block.~/colormap/color_grass.png = cocricotmod:color_grass
[16:09:33] [Client thread/WARN] [Config]: [OptiFine] CustomColors: Colormap not found: mcpatcher/colormap/color_grass.png
[16:09:33] [Client thread/INFO] [Config]: [OptiFine] CustomSky properties: mcpatcher/sky/world0/sky1.properties
[16:09:36] [Client thread/INFO] [Config]: [OptiFine] CustomSky properties: mcpatcher/sky/world0/sky2.properties
[16:09:40] [Thread-3/INFO] [net.minecraft.client.audio.SoundManager]: OpenAL initialized.
[16:09:40] [Sound Library Loader/INFO] [net.minecraft.client.audio.SoundManager]: Sound engine started
[16:09:50] [Client thread/ERROR] [net.minecraft.client.Minecraft]: ########## GL ERROR ##########
[16:09:50] [Client thread/ERROR] [net.minecraft.client.Minecraft]: @ Post render
[16:09:50] [Client thread/ERROR] [net.minecraft.client.Minecraft]: 1286: Invalid framebuffer operation
[16:09:50] [Client thread/ERROR] [net.minecraft.client.Minecraft]: ########## GL ERROR ###

**Comment by Problemswithmods** [comment]
I believe that this is the correct log?

**Comment by CreativeMD** [comment]
Nope in that log LittleTiles is not even installed.

**Comment by Problemswithmods** [comment]
My apologies ^^; I’m new to this sorry is this it?

**Comment by CreativeMD** [comment]
There are a few options either you have installed the wrong versions and you cannot find the crash-report. Or java itself crashes. If that is the case there should be a hs*******.log file in your .minecraft folder, which is most likely caused by an old graphic card or an outdated graphic card driver.

**Comment by Problemswithmods** [comment]
There is a log like that in my Minecraft folder, is there something I can
do to fix that?

**Comment by CreativeMD** [comment]
You can send the newest one to me. You can update your graphic card driver. Most likely this is an issue with the stencil feature CreativeCore uses. You can disable that in the config folder in the creativecore-client.json file. Just set useStencil to false. Unfortunately this will cause some rendering glitches in the gui.

**Comment by Problemswithmods** [comment]
Thank you, I will try that and get back to you

**Comment by Problemswithmods** [comment]
Is it in the .Minecraft folder?

**Comment by CreativeMD** [comment]
Yes
