### ISSUE TITLE
Fatal error on server joining

### ISSUE THREAD

**Issue by yusuf72100** [CreativeMD/LittleTiles#738]
I have again this problem:

Caused by: java.lang.IndexOutOfBoundsException: readerIndex(9) + length(4) exceeds writerIndex(10): UnpooledSlicedByteBuf(ridx: 9, widx: 10, cap: 10/10, unwrapped: PooledUnsafeDirectByteBuf(ridx: 0, widx: 11, cap: 11))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1396) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.buffer.AbstractByteBuf.readInt(AbstractByteBuf.java:766) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at com.creativemd.creativecore.common.packet.CreativeCorePacket.readPos(CreativeCorePacket.java:77) ~[CreativeCorePacket.class:?]
	at com.creativemd.littletiles.common.packet.LittleBlockPacket.readBytes(LittleBlockPacket.java:191) ~[LittleBlockPacket.class:?]
	at com.creativemd.creativecore.common.packet.CreativeMessageHandler.fromBytes(CreativeMessageHandler.java:46) ~[CreativeMessageHandler.class:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:36) ~[SimpleIndexedCodec.class:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:26) ~[SimpleIndexedCodec.class:?]
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:111) ~[FMLIndexedMessageToMessageCodec.class:?]
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:41) ~[FMLIndexedMessageToMessageCodec.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	... 57 more
[11:31:02] [Netty Client IO #3/ERROR] [FML]: Network Disconnect: A fatal error has occurred, this connection is terminated

**Comment by CreativeMD** [comment]
What mods are installed on server and what mods are installed on the client? EnhancedVisuals for example also needs to be installed on both ends.

**Comment by yusuf72100** [comment]
I have so many mods, 

- security craft
- alchemistery
- alib
- betterfps
- cdm
- cocricot
- codechickenlib
- coocking for blockHeads
- creativecore
- CTM
- customNPCS
- psychedelicraft
- ecologymod
- effortlessbuildings
-  ekimod
- emoticons 
- fairylights
- firstaid
- fixRTM
- foamfix
- forgelin
- forgeMultipart
- Furenuki's roads
- furniture
- hideNames
- ICBM
- ichunUtil
- IvToolkit
- Jei
- little frames
- little tittles
- locks
- malisisdoorcore
- malisisdoors
- mclib
- mc paint
- MCTE
- Mekanism
- modular voicechat
- mrtjpcore
- ngtlib
- nifty
- nostalgien
- noIDS
- noItems
- obfuscate
- optifine 
- playerApi
- playerRevive
- projectRed base
- projectRed immigration
- redstone remote
- rojiuramod
- rtm
- scp
- secretsdoor
- shadowMC
- signalController 
- SignPicture
- staminaplus 
- the Rc  Mod
- tonaBlock Plus 
- tonaMod v2
- tonationRP Phone mod 
- tough as nails 
-  traffic control
- u team core
- usefull backpacks 
- vehicle 
- wireless redstone 
- z radio


And the server which I have has the old version of Little Tilles.

**Comment by CreativeMD** [comment]
And what is installed on the server? Pretty sure the issue is caused by either different versions on server and client or a mod is installed on client side but not in on server side.

**Comment by yusuf72100** [comment]
All of this mod is installed on the server side but they are not optifine and better fps as well.

I have also the same versions for the differents mods on the server and client side.

**Comment by CreativeMD** [comment]
That is definitely not the case, because otherwise it would work. Send me the latest.log from server and client.

**Comment by yusuf72100** [comment]
Holly Jesus IT WOOORKS. 

I don't know what i have touched but i don't have a fatal error!

**Comment by yusuf72100** [comment]
I have copy/paste the client mod file into the fre***y server mod file and it work perfectly!

Thanks for you're help!

**Comment by CreativeMD** [comment]
Glad it works now.
