### ISSUE TITLE
Server crashes whenever people join it

### ISSUE THREAD

**Issue by cadergator10** [CreativeMD/LittleTiles#749]
[crash-2021-09-22_10.42.26-server.txt](https://github.com/CreativeMD/LittleTiles/files/7211792/crash-2021-09-22_10.42.26-server.txt)
Nobody is able to join it anymore, and I can't backup because somebody put in 10 hours of work into it yesterday

**Comment by cadergator10** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (OpenComputers-MC1.12.2-1.7.5.216.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  weaponlib (mw_2.0-0.4.6.2_mc1.12.2 (1).jar)
  Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2.jar)
  SoundUnpack (OpenSecurity-1.12.2-1.0-71.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  CreativePatchingLoader (CreativeCore_v1.10.57_mc1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  LittlePatchingLoader (LittleTiles_v1.5.6_mc1.12.2.jar)
  RandomPatches (randompatches-1.12.2-1.22.1.6.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 9/22/21 10:42 AM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.creativemd.littletiles.common.structure.LittleStructure.isClient(LittleStructure.java:139)
	at com.creativemd.littletiles.common.structure.type.door.LittleDoor.completeAnimation(LittleDoor.java:180)
	at com.creativemd.littletiles.common.entity.DoorController.place(DoorController.java:240)
	at com.creativemd.littletiles.common.entity.DoorController.endTransition(DoorController.java:198)
	at com.creativemd.littletiles.common.structure.animation.AnimationController.tick(AnimationController.java:155)
	at com.creativemd.littletiles.common.entity.DoorController.tick(DoorController.java:177)
	at com.creativemd.littletiles.common.entity.EntityAnimation.onTick(EntityAnimation.java:590)
	at com.creativemd.littletiles.common.entity.EntityAnimation.onUpdateForReal(EntityAnimation.java:646)
	at com.creativemd.littletiles.server.world.LittleAnimationHandlerServer.tick(LittleAnimationHandlerServer.java:24)
	at com.creativemd.littletiles.common.world.WorldAnimationHandler.tick(WorldAnimationHandler.java:144)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_472_WorldAnimationHandler_tick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:274)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:776)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.19-ovh-xxxx-std-ipv6-64
	Java Version: 1.8.0_292, Red Hat, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Red Hat, Inc.
	Memory: 1991078568 bytes (1898 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 20 total; -Xmx6144M -Xms6144M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 65 mods loaded, 65 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                      | Version               | Source                                                       | Signature                                |
	|:------ |:----------------------- |:--------------------- |:------------------------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft               | 1.12.2                | minecraft.jar                                                | None                                     |
	| LCHIJA | mcp                     | 9.42                  | minecraft.jar                                                | None                                     |
	| LCHIJA | FML                     | 8.0.99.99             | forge-1.12.2.jar                                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                   | 14.23.5.2854          | forge-1.12.2.jar                                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy       | 1.0.0                 | minecraft.jar                                                | None                                     |
	| LCHIJA | littletilescore         | 1.0.0                 | minecraft.jar                                                | None                                     |
	| LCHIJA | opencomputers|core      | 1.7.5.216             | minecraft.jar                                                | None                                     |
	| LCHIJA | randompatches           | 1.12.2-1.22.1.6       | randompatches-1.12.2-1.22.1.6.jar                            | None                                     |
	| LCHIJA | techguns_core           | 1.12.2-1.0            | minecraft.jar                                                | None                                     |
	| LCHIJA | jei                     | 4.16.1.302            | jei_1.12.2-4.16.1.302.jar                                    | None                                     |
	| LCHIJA | appleskin               | 1.0.14                | AppleSkin-mc1.12-1.0.14.jar                                  | None                                     |
	| LCHIJA | bibliocraft             | 2.4.5                 | BiblioCraft[v2.4.5][MC1.12.2].jar                            | None                                     |
	| LCHIJA | chisel                  | MC1.12.2-1.0.2.45     | Chisel-MC1.12.2-1.0.2.45.jar                                 | None                                     |
	| LCHIJA | chiselsandbits          | 14.33                 | chiselsandbits-14.33.jar                                     | None                                     |
	| LCHIJA | codechickenlib          | 3.2.3.358             | CodeChickenLib-1.12.2-3.2.3.358-universal.jar                | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | asielib                 | 1.0.0                 | Computronics-1.12.2-1.6.6 (1).jar                            | None                                     |
	| LCHIJA | opencomputers           | 1.7.5.216             | OpenComputers-MC1.12.2-1.7.5.216.jar                         | None                                     |
	| LCHIJA | computronics            | 1.6.6                 | Computronics-1.12.2-1.6.6 (1).jar                            | None                                     |
	| LCHIJA | creativecore            | 1.10.0                | CreativeCore_v1.10.57_mc1.12.2.jar                           | None                                     |
	| LCHIJA | cubsalarams             | 1.0.0                 | Cubs_Alarms_1.12.2.jar                                       | None                                     |
	| LCHIJA | props                   | 2.6.3.7               | Decocraft-2.6.3.7_1.12.2.jar                                 | None                                     |
	| LCHIJA | dynmap                  | 3.2-beta-3-514        | Dynmap-3.2-beta-3-forge-1.12.2.jar                           | None                                     |
	| LCHIJA | exactspawn              | 1.12-1.2.3.17         | ExactSpawn-1.12-1.2.3.17.jar                                 | None                                     |
	| LCHIJA | extrautils2             | 1.0                   | extrautils2-1.12-1.9.9.jar                                   | None                                     |
	| LCHIJA | fakename                | 1.2                   | Fakename+MC1.12.2+v1.2 (1).jar                               | None                                     |
	| LCHIJA | com.boydti.fawe         | 3.5.1                 | FastAsyncWorldEdit-forge112-19.11.13-5505943-1282-22.3.5.jar | None                                     |
	| LCHIJA | firstaid                | 1.6.16                | firstaid-1.6.16.jar                                          | 7904c4e13947c8a616c5f39b26bdeba796500722 |
	| LCHIJA | forgelin                | 1.8.4                 | Forgelin-1.8.4.jar                                           | None                                     |
	| LCHIJA | forgemultipartcbe       | 2.6.2.83              | ForgeMultipart-1.12.2-2.6.2.83-universal.jar                 | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | microblockcbe           | 2.6.2.83              | ForgeMultipart-1.12.2-2.6.2.83-universal.jar                 | None                                     |
	| LCHIJA | minecraftmultipartcbe   | 2.6.2.83              | ForgeMultipart-1.12.2-2.6.2.83-universal.jar                 | None                                     |
	| LCHIJA | furenikusroads          | 1.0.3                 | Fureniku's+Roads-1.0.2.1.jar                                 | None                                     |
	| LCHIJA | cfm                     | 6.3.1                 | furniture-6.3.1-1.12.2.jar                                   | None                                     |
	| LCHIJA | h2os_scps               | 1.0.0                 | H2Os+SCPs+1.8.4+[Secure+And+Contain+Update].jar              | None                                     |
	| LCHIJA | icbmclassic             | 1.12.2-4.0.1.75       | ICBM-classic-1.12.2-4.0.1b75.jar                             | None                                     |
	| LCHIJA | kirosblocks             | 1.1                   | kirosblocks-1.1.jar                                          | None                                     |
	| LCHIJA | littletiles             | 1.5.0                 | LittleTiles_v1.5.6_mc1.12.2.jar                              | None                                     |
	| LCHIJA | malisiscore             | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                                 | None                                     |
	| LCHIJA | malisisblocks           | 1.12.2-6.1.0          | malisisblocks-1.12.2-6.1.0.jar                               | None                                     |
	| LCHIJA | malisisdoors            | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                                | None                                     |
	| LCHIJA | moarsigns               | 6.0.0.11              | MoarSigns-1.12.2-6.0.0.11.jar                                | 5a57c7d1420cf4c58f53ea2a298ebef8215ede63 |
	| LCHIJA | mrtjpcore               | 2.1.4.43              | MrTJPCore-1.12.2-2.1.4.43-universal.jar                      | None                                     |
	| LCHIJA | mw                      | 0.4.6.2               | mw_2.0-0.4.6.2_mc1.12.2 (1).jar                              | None                                     |
	| LCHIJA | openscreens             | 1.0.1                 | openscreens-1.12.2-1.0.1.jar                                 | None                                     |
	| LCHIJA | opensecurity            | 1.0-71                | OpenSecurity-1.12.2-1.0-71.jar                               | None                                     |
	| LCHIJA | harvestcraft            | 1.12.2zb              | Pam's+HarvestCraft+1.12.2zg.jar                              | None                                     |
	| LCHIJA | scpfanmattys_scp_mod    | 1.0.0                 | Project+Facility+Final+Update.jar                            | None                                     |
	| LCHIJA | projectred-core         | 4.9.4.120             | ProjectRed-1.12.2-4.9.4.120-Base.jar                         | None                                     |
	| LCHIJA | projectred-compat       | 1.0                   | ProjectRed-1.12.2-4.9.4.120-compat.jar                       | None                                     |
	| LCHIJA | projectred-integration  | 4.9.4.120             | ProjectRed-1.12.2-4.9.4.120-integration.jar                  | None                                     |
	| LCHIJA | projectred-transmission | 4.9.4.120             | ProjectRed-1.12.2-4.9.4.120-integration.jar                  | None                                     |
	| LCHIJA | projectred-illumination | 4.9.4.120             | ProjectRed-1.12.2-4.9.4.120-lighting.jar                     | None                                     |
	| LCHIJA | rsgauges                | 1.2.5                 | rsgauges-1.12.2-1.2.5.jar                                    | ed58ed655893ced6280650866985abcae2bf7559 |
	| LCHIJA | scpsarmor20             | 2.0                   | SCP's+Armor+2.0.jar                                          | None                                     |
	| LCHIJA | scootys_scp_mod         | 1.5                   | SCP+Lockdown+Heavy+Expansion+1.5.1.jar                       | None                                     |
	| LCHIJA | scp                     | 2.4.0                 | SCP_Lockdown-1.12.2-2.4.0-hotfix.jar                         | None                                     |
	| LCHIJA | scpua                   | 1.7.7                 | SCPL-xk-unity-1.7.7.jar                                      | None                                     |
	| LCHIJA | scple                   | 1.0                   | scple-1.0.jar                                                | None                                     |
	| LCHIJA | servertabinfo           | 1.2.6                 | ServerTabInfo-1.12.2-1.2.6.jar                               | None                                     |
	| LCHIJA | spartanshields          | 1.5.4                 | SpartanShields-1.12.2-1.5.4.jar                              | None                                     |
	| LCHIJA | techguns                | 2.0.2.0               | techguns-1.12.2-2.0.2.0_pre3.2.jar                           | None                                     |
	| LCHIJA | gvc                     | 1.2.0                 | Voice+Chat+Reloaded-1.2.4.jar                                | None                                     |
	| LCHIJA | worldedit               | 6.1.10                | worldedit-forge-mc1.12.2-6.1.10-dist.jar                     | None                                     |
	| LCHIJA | wrcbe                   | 2.3.2                 | WR-CBE-1.12.2-2.3.2.33-universal.jar                         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | dcintegration           | 2.2.0                 | dcintegration-forge-2.2.0-1.12.jar                           | None                                     |

	Loaded coremods (and transformers): 
TransformerLoader (OpenComputers-MC1.12.2-1.7.5.216.jar)
  li.cil.oc.common.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
weaponlib (mw_2.0-0.4.6.2_mc1.12.2 (1).jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2.jar)
  techguns.core.TechgunsASMTransformer
SoundUnpack (OpenSecurity-1.12.2-1.0-71.jar)
  
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
CreativePatchingLoader (CreativeCore_v1.10.57_mc1.12.2.jar)
  
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LittlePatchingLoader (LittleTiles_v1.5.6_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
RandomPatches (randompatches-1.12.2-1.22.1.6.jar)
  com.therandomlabs.randompatches.core.RPTransformer
	Profiler Position: N/A (disabled)
	Player Count: 1 / 72; [EntityPlayerMP['cadergator10'/7, l='NewSite', x=2770.04, y=25.18, z=1481.30]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by cadergator10** [comment]
Fixed it by updating to newest version
