### ISSUE TITLE
Crash bei Undo nicht immer reproduzierbar

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#750]
java.lang.NullPointerException: Unexpected error
	at com.creativemd.littletiles.common.tile.place.PlacePreviewRelative.placeTile(PlacePreviewRelative.java:56)
	at com.creativemd.littletiles.common.util.place.Placement$PlacementBlock.placeLate(Placement.java:570)
	at com.creativemd.littletiles.common.util.place.Placement.placeTiles(Placement.java:228)
	at com.creativemd.littletiles.common.util.place.Placement.place(Placement.java:192)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceAbsolute.action(LittleActionPlaceAbsolute.java:82)
	at com.creativemd.littletiles.common.action.LittleAction.undo(LittleAction.java:143)
	at com.creativemd.littletiles.client.render.overlay.PreviewRenderer.handleUndoAndRedo(PreviewRenderer.java:79)
	at com.creativemd.littletiles.client.render.overlay.PreviewRenderer.tick(PreviewRenderer.java:111)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_411_PreviewRenderer_tick_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:196)
	at sun.reflect.GeneratedMethodAccessor99.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:669)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1959)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1621)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1390)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by CreativeMD** [comment]
I need more information. That is not very helpful.

**Comment by CreativeMD** [comment]
Will close it for now. If there are more information just post them here.
