### ISSUE TITLE
littletiles and creative core crashes on launch with exit code 1

### ISSUE THREAD

**Issue by AgelessOlive** [CreativeMD/LittleTiles#815]
i have downloaded little tiles and creative core from many different versions on curseforge but they all crash giving me exit code one or "java.lang.ClassNotFoundException: com.creativemd.creativecore.gui.opener.CustomGuiHandler"i have used many different version of these mods and forge client but they don't work. if i take littletiles out of my mods folder it will load just fine but it crashes with littletiles in it.
here's the crash log

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Controllable (controllable-0.11.2-1.12.2.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  LittlePatchingLoader (LittleTiles-Mod-1.12.1.jar)
  CreativePatchingLoader (CreativeCore_v1.10.70_mc1.12.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  SecurityCraftLoadingPlugin ([1.12.2] SecurityCraft v1.9.2.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 7/4/22 1:51 PM
Description: Initializing game

java.lang.NoClassDefFoundError: com/creativemd/creativecore/gui/opener/CustomGuiHandler
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.creativemd.creativecore.gui.opener.CustomGuiHandler
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 483949624 bytes (461 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 35 mods loaded, 35 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version               | Source                                           | Signature                                |
	|:----- |:-------------------- |:--------------------- |:------------------------------------------------ |:---------------------------------------- |
	| LC    | minecraft            | 1.12.2                | minecraft.jar                                    | None                                     |
	| LC    | mcp                  | 9.42                  | minecraft.jar                                    | None                                     |
	| LC    | FML                  | 8.0.99.99             | forge-1.12.2-14.23.5.2859.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                | 14.23.5.2859          | forge-1.12.2-14.23.5.2859.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | creativecoredummy    | 1.0.0                 | minecraft.jar                                    | None                                     |
	| LC    | littletilescore      | 1.0.0                 | minecraft.jar                                    | None                                     |
	| LC    | controllable         | 0.11.2                | controllable-0.11.2-1.12.2.jar                   | None                                     |
	| LC    | obfuscate            | 0.4.2                 | minecraft.jar                                    | None                                     |
	| LC    | securitycraft        | v1.9.2                | [1.12.2] SecurityCraft v1.9.2.jar                | None                                     |
	| LC    | creativecore         | 1.10.0                | CreativeCore_v1.10.70_mc1.12.2.jar               | None                                     |
	| LC    | customnpcs           | 1.12                  | CustomNPCs_1.12.2-(05Jul20).jar                  | None                                     |
	| LC    | cdm                  | 0.4.1                 | device-mod-0.4.1-1.12.2.jar                      | None                                     |
	| LC    | cfm                  | 6.3.1                 | furniture-6.3.1-1.12.2.jar                       | None                                     |
	| LC    | modcurrency          | 1.12-1.3.11           | good-o-Currency-1_12_2.jar                       | None                                     |
	| LC    | hbm                  | hbm-1.6.5Av2-1.12.2   | hbm-1.6.5a-Gv2.jar                               | None                                     |
	| LC    | mts                  | 21.2.0                | Immersive+Vehicles-1.12.2-21.2.0.jar             | None                                     |
	| LC    | trackapi             | 1.2                   | TrackAPI-1.2.jar                                 | None                                     |
	| LC    | universalmodcore     | 1.1.4                 | UniversalModCore-1.12.2-forge-1.1.4-2b81e7.jar   | None                                     |
	| LC    | immersiverailroading | 1.9.1                 | ImmersiveRailroading-1.12.2-forge-1.9.1.jar      | None                                     |
	| LC    | jei                  | 4.16.1.301            | jei_1.12.2-4.16.1.301.jar                        | None                                     |
	| L     | littletiles          | 1.5.0                 | LittleTiles-Mod-1.12.1.jar                       | None                                     |
	| L     | malisiscore          | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                     | None                                     |
	| L     | malisisdoors         | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                    | None                                     |
	| L     | shetiphiancore       | 3.5.9                 | ShetiPhianCore-1.12.2.jar                        | None                                     |
	| L     | multistorage         | 1.4.14                | multistorage-1.12.0-1.4.14.jar                   | None                                     |
	| L     | alarms               | 1.6                   | Orvnge+Alarms+Mod+1.6+1.12.2.jar                 | None                                     |
	| L     | thutcore             | 5.21.0                | thutcore-mc1.12.2-v5.21.0.jar                    | None                                     |
	| L     | thutcore_compat      | 1.0                   | thutcore-mc1.12.2-v5.21.0.jar                    | None                                     |
	| L     | thuttech             | 6.1.6                 | thuttech-mc1.12.2-v6.1.6.jar                     | None                                     |
	| L     | trafficcontrol       | 0.4.1                 | trafficcontrol-0.4.1.jar                         | None                                     |
	| L     | unuparts             | 5.1.2                 | UNU+Parts+Pack+[MTS]+1.12.2-21.1.0-5.1.2.jar     | None                                     |
	| L     | unucivil             | 5.3.0                 | UNU+Civilian+Pack+[MTS]+1.12.2-21.1.0-5.3.0.jar  | None                                     |
	| L     | unumilitary          | 4.0.2                 | UNU+Military+Pack+[MTS]+1.12.2-19.15.5-4.0.2.jar | None                                     |
	| L     | vehicle              | 0.44.1                | vehicle-mod-0.44.1-1.12.2.jar                    | None                                     |
	| L     | worldedit            | 6.1.10                | worldedit-forge-mc1.12.2-6.1.10-dist.jar         | None                                     |

	Loaded coremods (and transformers): 
Controllable (controllable-0.11.2-1.12.2.jar)
  
ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  shetiphian.asm.ClassTransformer
LittlePatchingLoader (LittleTiles-Mod-1.12.1.jar)
  com.creativemd.littletiles.LittleTilesTransformer
CreativePatchingLoader (CreativeCore_v1.10.70_mc1.12.2.jar)
  
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
SecurityCraftLoadingPlugin ([1.12.2] SecurityCraft v1.9.2.jar)
  
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14761 Compatibility Profile Context FireGL 20.45.40.15 27.20.14540.15002' Renderer: 'AMD Radeon Pro 455'
	Launched Version: 1.12.2-forge-14.23.5.2859
	LWJGL: 2.9.4
	OpenGL: AMD Radeon Pro 455 GL version 4.6.14761 Compatibility Profile Context FireGL 20.45.40.15 27.20.14540.15002, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz

**Comment by CreativeMD** [comment]
Please download LittleTiles from curseforge and not any other website. Then things will work just fine.
