### ISSUE TITLE
Doors do not open on server

### ISSUE THREAD

**Issue by S1mpleM0use** [CreativeMD/LittleTiles#820]
Server core: CatServer-6eb82ffe-universal
When opening a door, this message gets displayed in console while doors remains still:
[21:28:04] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_312]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_312]
        at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:910) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:475) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:834) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.NullPointerException
Do I need to provide full modlist? We are playing on a pretty big modpack

**Comment by CreativeMD** [comment]
You only posted half of the error, if you send the second half I might be able to figure out what is the issue.

**Comment by S1mpleM0use** [comment]
aah... eeh... what? that's the full error
like...
![image](https://user-images.githubusercontent.com/58431737/184637242-82af58c1-3fe4-42a1-ba1f-35f09e0c78d6.png)
There's no crash-report, so the log file is the only place I can see the error in

**Comment by CreativeMD** [comment]
Again you only showed half of it, I need to see the lines after `Caused by: java.lang.NullPointerException`.

**Comment by S1mpleM0use** [comment]
there are none
![image](https://user-images.githubusercontent.com/58431737/184638621-fe19e6c0-8a49-4302-8612-9ec7564b458f.png)

**Comment by CreativeMD** [comment]
Can you send me the log file?

**Comment by S1mpleM0use** [comment]
[2022-08-14-2.log.gz](https://github.com/CreativeMD/LittleTiles/files/9337566/2022-08-14-2.log.gz)

**Comment by CreativeMD** [comment]
I have looked through the log file. No idea what is going on. I don't think I can help you. The only way to figure out what mod is causing the issue is to remove some and see if the issue still persists. LittleTiles works with Forge and SpongeForge as the server architecture, all the others might work but there is no guarantee. Sorry for the inconvenience.
