### ISSUE TITLE
latest version error when loading on the server side client I do not know 

### ISSUE THREAD

**Issue by Sarocesch** [CreativeMD/LittleTiles#882]
[13:15:39] [Server thread/ERROR] [FML]: The mcmod.info file in LittleTiles_v1.5.79_mc1.12.2.jar cannot be parsed as valid JSON. It will be ignored
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 11 column 73 path $[0].credits
	at com.google.gson.internal.Streams.parse(Streams.java:60) ~[Streams.class:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:84) ~[JsonParser.class:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:59) ~[JsonParser.class:?]
	at net.minecraftforge.fml.common.MetadataCollection.from(MetadataCollection.java:60) [MetadataCollection.class:?]
	at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:61) [JarDiscoverer.class:?]
	at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:46) [ContainerType.class:?]
	at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:72) [ModCandidate.class:?]
	at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:92) [ModDiscoverer.class:?]
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:443) [Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:583) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:101) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:331) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:167) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 11 column 73 path $[0].credits
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414) ~[JsonReader.class:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:738) ~[TypeAdapters$29.class:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:731) ~[TypeAdapters$29.class:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714) ~[TypeAdapters$29.class:?]
	at com.google.gson.internal.Streams.parse(Streams.java:48) ~[Streams.class:?]
	... 14 more

**Comment by CreativeMD** [comment]
Can you try out the newest version 1.5.80? This issue should not occur anymore.

**Comment by Sarocesch** [comment]
ahh bin auf einer version drunter werde das update machen und mich dann nochmal melden

**Comment by Sarocesch** [comment]
sorry have only now seen that my translator has given up 

am still one version below will update and then report may take a little time

**Comment by Sarocesch** [comment]
is no longer in the latest
