### ISSUE TITLE
Not compatible with new versions of rubidium?

### ISSUE THREAD

**Issue by Xing-C** [CreativeMD/LittleTiles#897]
Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |ENQUEUE_IM|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		LittleFrames_FORGE_v1.2.2_mc1.20.1.jar   |LittleFrames                  |littleframes                  |1.2.2               |ENQUEUE_IM|Manifest: NOSIGNATURE
		rubidium_extras-1.20.1_v1.4.3.jar        |Rubidium Extras               |rubidium_extras               |1.20.1_v1.4.3       |ENQUEUE_IM|Manifest: NOSIGNATURE
		TextruesRubidiumOptions-1.0.3+mc1.|TexTrue's Rubidium Options    |reeses_sodium_options         |1.0.3+mc1.20.1      |ENQUEUE_IM|Manifest: NOSIGNATURE
		forge-1.20.1-47.1.70-universal.jar                |NeoForge                      |forge                         |47.1.70             |ENQUEUE_IM|Manifest: 5c:77:18:4b:07:f2:c9:01:60:c8:5d:d0:92:b4:aa:c0:ac:6d:8f:b0:a9:fa:62:5e:2e:0a:b9:6f:1c:d6:b4:05
		rubidium-mc1.20.1-0.7.1.jar                   |Rubidium                      |rubidium                      |0.7.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		flywheel-forge-1.20.1-0.6.10-7.jar                |Flywheel                      |flywheel                      |0.6.10-7            |ENQUEUE_IM|Manifest: NOSIGNATURE
		create-1.20.1-0.5.1.e.jar             |Create                        |create                        |0.5.1.e             |ENQUEUE_IM|Manifest: NOSIGNATURE
		watermedia-1.3.35.jar                 |WaterMedia                    |watermedia                    |1.3.35              |ENQUEUE_IM|Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.11.1_mc1.20.1.j|CreativeCore                  |creativecore                  |2.11.1              |ENQUEUE_IM|Manifest: NOSIGNATURE
		LittleTiles_ALPHA_v1.6.0-pre062_mc1.20|LittleTiles                   |littletiles                   |1.6.0-pre062        |ERROR     |Manifest: NOSIGNATURE

```
Time: 2023-10-01 13:05:07
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.1.70-universal.jar%23177!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:143) ~[forge-1.20.1-47.1.70-universal.jar%23177!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$4(Minecraft.java:571) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:rubidium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:littletiles.mixins.json:client.MinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:421) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:564) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:rubidium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:littletiles.mixins.json:client.MinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_88315_(LoadingOverlay.java:138) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:954) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:rubidium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:littletiles.mixins.json:client.MinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:rubidium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:littletiles.mixins.json:client.MinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:126) ~[loader-47.1.47.jar:47.1] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:114) ~[loader-47.1.47.jar:47.1] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-47.1.47.jar:47.1] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:108) ~[loader-47.1.47.jar:47.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) ~[?:?] {}
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) ~[?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {}
-- MOD littletiles --
Details:
	Mod File: LittleTiles_ALPHA_v1.6.0-pre062_mc1.20.1.jar
	Failure message: LittleTiles (littletiles) encountered an error during the sided_setup event phase
		java.lang.IncompatibleClassChangeError: class team.creative.littletiles.client.mod.rubidium.level.LittleWorldSlice cannot inherit from final class me.jellysquid.mods.sodium.client.world.WorldSlice
	Mod Version: 1.6.0-pre062
	Mod Issue URL: https://github.com/CreativeMD/LittleTiles/issues
	Exception message: java.lang.IncompatibleClassChangeError: class team.creative.littletiles.client.mod.rubidium.level.LittleWorldSlice cannot inherit from final class me.jellysquid.mods.sodium.client.world.WorldSlice
Stacktrace:
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {}
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:119) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at team.creative.littletiles.client.mod.rubidium.pipeline.LittleRenderPipelineTypeRubidium.<init>(LittleRenderPipelineTypeRubidium.java:8) ~[LittleTiles_ALPHA_v1.6.0-pre062_mc1.20.1.jar%23165!/:1.6.0-pre062] {re:classloading}
	at team.creative.littletiles.client.mod.rubidium.RubidiumInteractor.<clinit>(RubidiumInteractor.java:8) ~[LittleTiles_ALPHA_v1.6.0-pre062_mc1.20.1.jar%23165!/:1.6.0-pre062] {re:classloading}
	at team.creative.littletiles.client.mod.rubidium.RubidiumManager.init(RubidiumManager.java:24) ~[LittleTiles_ALPHA_v1.6.0-pre062_mc1.20.1.jar%23165!/:1.6.0-pre062] {re:classloading}
	at team.creative.littletiles.client.LittleTilesClient.setup(LittleTilesClient.java:237) ~[LittleTiles_ALPHA_v1.6.0-pre062_mc1.20.1.jar%23165!/:1.6.0-pre062] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%23139!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%23139!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23139!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23139!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[language-java-47.1.47.jar%23174!/:47.1] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:124) ~[core-47.1.47.jar%23173!/:47.1] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
```

**Comment by Xing-C** [comment]
only if:
rubidium-mc1.20.1-0.7.1.jar
LittleTiles_ALPHA_v1.6.0-pre062_mc1.20.1.jar
CreativeCore_FORGE_v2.11.1_mc1.20.1.jar

```
[0110��2023 14:15:34.171] [Worker-Main-11/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: class team.creative.littletiles.client.mod.rubidium.level.LittleWorldSlice cannot inherit from final class me.jellysquid.mods.sodium.client.world.WorldSlice
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$4666/0x00000008017877f8@61697a43
java.lang.IncompatibleClassChangeError: class team.creative.littletiles.client.mod.rubidium.level.LittleWorldSlice cannot inherit from final class me.jellysquid.mods.sodium.client.world.WorldSlice
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:119)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at TRANSFORMER/littletiles@1.6.0-pre062/team.creative.littletiles.client.mod.rubidium.pipeline.LittleRenderPipelineTypeRubidium.<init>(LittleRenderPipelineTypeRubidium.java:8)
	at TRANSFORMER/littletiles@1.6.0-pre062/team.creative.littletiles.client.mod.rubidium.RubidiumInteractor.<clinit>(RubidiumInteractor.java:8)
	at TRANSFORMER/littletiles@1.6.0-pre062/team.creative.littletiles.client.mod.rubidium.RubidiumManager.init(RubidiumManager.java:24)
	at TRANSFORMER/littletiles@1.6.0-pre062/team.creative.littletiles.client.LittleTilesClient.setup(LittleTilesClient.java:237)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at LAYER PLUGIN/fml_language_java@47.1.47/net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107)
	at LAYER PLUGIN/fml_core@47.1.47/net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:124)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

[0110��2023 14:15:34.172] [Worker-Main-11/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event FMLClientSetupEvent dispatch for modid littletiles
java.lang.IncompatibleClassChangeError: class team.creative.littletiles.client.mod.rubidium.level.LittleWorldSlice cannot inherit from final class me.jellysquid.mods.sodium.client.world.WorldSlice
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:119) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at team.creative.littletiles.client.mod.rubidium.pipeline.LittleRenderPipelineTypeRubidium.<init>(LittleRenderPipelineTypeRubidium.java:8) ~[%5B1-1%5D%5BLTС����%5DLittleTiles_ALPHA_v1.6.0-pre062_mc1.20.1.jar%23159!/:1.6.0-pre062]
	at team.creative.littletiles.client.mod.rubidium.RubidiumInteractor.<clinit>(RubidiumInteractor.java:8) ~[%5B1-1%5D%5BLTС����%5DLittleTiles_ALPHA_v1.6.0-pre062_mc1.20.1.jar%23159!/:1.6.0-pre062]
	at team.creative.littletiles.client.mod.rubidium.RubidiumManager.init(RubidiumManager.java:24) ~[%5B1-1%5D%5BLTС����%5DLittleTiles_ALPHA_v1.6.0-pre062_mc1.20.1.jar%23159!/:1.6.0-pre062]
	at team.creative.littletiles.client.LittleTilesClient.setup(LittleTilesClient.java:237) ~[%5B1-1%5D%5BLTС����%5DLittleTiles_ALPHA_v1.6.0-pre062_mc1.20.1.jar%23159!/:1.6.0-pre062]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%23139!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%23139!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23139!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23139!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[language-java-47.1.47.jar%23164!/:47.1]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:124) ~[core-47.1.47.jar%23163!/:47.1]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

**Comment by agentwolf88** [comment]
Same problem.

**Comment by Xiarno** [comment]
Please use [Embeddium](https://www.curseforge.com/minecraft/mc-mods/embeddium) instead. #895 

Also, currently, it is incompatible with Flywheel. #896

**Comment by Xing-C** [comment]
> Please use [Embeddium](https://www.curseforge.com/minecraft/mc-mods/embeddium) instead. #895
> 
> Also, currently, it is incompatible with Flywheel. #896

But the real situation still crashes and cannot run

embeddium-0.1.13+mc1.20.1
create-1.20.1-0.5.1.e
CreativeCore_FORGE_v2.11.1_mc1.20.1
LittleTiles_ALPHA_v1.6.0-pre062_mc1.20.1

**Comment by Xing-C** [comment]
> Please use [Embeddium](https://www.curseforge.com/minecraft/mc-mods/embeddium) instead. #895
> 
> Also, currently, it is incompatible with Flywheel. #896

```
-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar:10.0.9+10.0.9+main.dcd20f30] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.initRenderer(SodiumWorldRenderer.java:252) ~[embeddium-0.1.13+mc1.20.1.jar%23163!/:?] {re:mixin,re:classloading,pl:mixin:APP:littletiles.mixins.json:rubidium.SodiumWorldRendererAccessor,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.loadWorld(SodiumWorldRenderer.java:103) ~[embeddium-0.1.13+mc1.20.1.jar%23163!/:?] {re:mixin,re:classloading,pl:mixin:APP:littletiles.mixins.json:rubidium.SodiumWorldRendererAccessor,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.setWorld(SodiumWorldRenderer.java:95) ~[embeddium-0.1.13+mc1.20.1.jar%23163!/:?] {re:mixin,re:classloading,pl:mixin:APP:littletiles.mixins.json:rubidium.SodiumWorldRendererAccessor,pl:mixin:A}
	at net.minecraft.client.renderer.LevelRenderer.handler$zbl000$onWorldChanged(LevelRenderer.java:5147) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109701_(LevelRenderer.java:685) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91324_(Minecraft.java:2153) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:rubidium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:littletiles.mixins.json:client.MinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91156_(Minecraft.java:2078) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:rubidium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:littletiles.mixins.json:client.MinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5998_(ClientPacketListener.java:404) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.network.protocol.game.ClientboundLoginPacket.m_5797_(ClientboundLoginPacket.java:95) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundLoginPacket.m_5797_(ClientboundLoginPacket.java:25) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
-- Affected level --
```

**Comment by Xiarno** [comment]
> > Please use [Embeddium](https://www.curseforge.com/minecraft/mc-mods/embeddium) instead. #895
> > Also, currently, it is incompatible with Flywheel. #896
> 
> But the real situation still crashes and cannot run
> 
> embeddium-0.1.13+mc1.20.1 create-1.20.1-0.5.1.e CreativeCore_FORGE_v2.11.1_mc1.20.1 LittleTiles_ALPHA_v1.6.0-pre062_mc1.20.1

Yes, because Create is in it. Create includes Flywheel. Thus the incompatibility with Flywheel.

**Comment by Xing-C** [comment]
> > > Please use [Embeddium](https://www.curseforge.com/minecraft/mc-mods/embeddium) instead. #895
> > > Also, currently, it is incompatible with Flywheel. #896
> > 
> > 
> > But the real situation still crashes and cannot run
> > embeddium-0.1.13+mc1.20.1 create-1.20.1-0.5.1.e CreativeCore_FORGE_v2.11.1_mc1.20.1 LittleTiles_ALPHA_v1.6.0-pre062_mc1.20.1
> 
> Yes, because Create is in it. Create includes Flywheel. Thus the incompatibility with Flywheel.

Looking forward to the author solving this bugs

**Comment by CreativeMD** [comment]
Tested it using the newest version of Embeddium, CreativeCore and LittleTiles for 1.20.2 and it all worked fine. Will look at the Flywheel issue soon, but close this issue.

**Comment by Xiarno** [comment]
> Tested it using the newest version of Embeddium, CreativeCore and LittleTiles for 1.20.2 and it all worked fine. Will look at the Flywheel issue soon, but close this issue.

Yes, Embeddium, CreativesCore & LittleTiles now work fine. It's Flywheel that is the issue currently :/
