### ISSUE TITLE
Chisels and bits integration [pre-87 - pre97]

### ISSUE THREAD

**Issue by BasieBrinkie** [CreativeMD/LittleTiles#90]
I saw you made an attempt to fix the chisels and bits integration. I wanted to compile it for myself and saw you didn't include the gradle files. Could be that i'am missing something. Sorry first time doing this sort of thing (compiling and reporting a issue)

I have tested quite some versions
It seemed that version 1.5.0-pre83 was the last one with fully working integration

Kind regards,
Bas

**Comment by Dushess** [comment]
LGS messed up something, fo 1.11.2 84th build may also work.

**Comment by CreativeMD** [comment]
Are you talking about converting LT stuff to C&B or the other way around?

**Comment by BasieBrinkie** [comment]
C&B to Littletiles

**Comment by CreativeMD** [comment]
So what does happen? Simply doesn't work or will it mess up the block? Maybe share a screenshot?

**Comment by BasieBrinkie** [comment]
Minecraft Version:1.12.2
Forge: 1.12.2-14.23.4.2703
LittleTiles: v1.5.0-pre97
CreativeCore: 1.9.22
Both Little recipe and wrench aren't working. I clicked two times left with the recipe and until version pre83 it still worked.

Gif:
![chisels and bits integration](https://user-images.githubusercontent.com/20798788/40734859-e8c8ce66-6439-11e8-8385-3e94d6854a2e.gif)

Error from the debug file:

[18:26:21] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] First position: x=-157,y=78,z=77
[18:26:21] [main/FATAL] [net.minecraft.client.Minecraft]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at com.creativemd.littletiles.common.items.ItemMultiTiles.getLTStructure(ItemMultiTiles.java:112) ~[ItemMultiTiles.class:?]
	at com.creativemd.littletiles.common.gui.SubGuiStructure.createControls(SubGuiStructure.java:36) ~[SubGuiStructure.class:?]
	at com.creativemd.creativecore.gui.container.SubGui.onOpened(SubGui.java:258) ~[SubGui.class:?]
	at com.creativemd.creativecore.gui.mc.GuiContainerSub.func_73866_w_(GuiContainerSub.java:63) ~[GuiContainerSub.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478) ~[blk.class:?]
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1016) ~[bib.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:494) ~[FMLClientHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.showGuiScreen(FMLCommonHandler.java:321) ~[FMLCommonHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:112) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550) ~[aed.class:?]
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.process(OpenGuiHandler.java:50) ~[OpenGuiHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.lambda$channelRead0$0(OpenGuiHandler.java:43) ~[OpenGuiHandler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more

**Comment by CreativeMD** [comment]
It is fixed! It will be included in the upcoming pre-release. Thanks for reporting this issue. Unfortunately I can't release it right away as there are things which need to be finished first, I will try to do it as soon as possible.
