### ISSUE TITLE
Doors do not work in 1.12.2 anymore

### ISSUE THREAD

**Issue by Sarocesch** [CreativeMD/LittleTiles#900]
Doors extended doors somehow no longer work in 1.12.2 
right click does not trigger them but only the hand moves

**Comment by CreativeMD** [comment]
I need more contest. I need to see what you configure in the recipe gui. What version you are using. If you are on a server. Maybe include a log file (it might show an error which prevents the door from opening).

**Comment by Sarocesch** [comment]
ahh sorry I am stupid 
it works on servers not single player it works
additionally the gui of the block to store structures does not work and crashes the server
when you click on doors also on levers etc so animations don't work anymore so nothing happens except the hand movement comes up 
LittleTiles_v1.5.82_mc1.12.2
I will send you a log in a moment
i have several mods on my server so i try to keep them small and at the end i will open the gui again that crashes it hope then there are enough infos in it

**Comment by Sarocesch** [comment]
do you perhaps also understand german and may you then continue to write in tiket german ?

**Comment by Sarocesch** [comment]
[Uploading latest.log…]()

**Comment by Sarocesch** [comment]
[latest.log](https://github.com/CreativeMD/LittleTiles/files/12837736/latest.3.log)

**Comment by Sarocesch** [comment]
Here again a log without other mods 
[latest.log](https://github.com/CreativeMD/LittleTiles/files/12885902/latest.log)

**Comment by Sarocesch** [comment]
java.util.concurrent.ExecutionException: java.lang.ClassCastException: com.creativemd.creativecore.common.world.SubWorldServer cannot be cast to net.minecraft.world.WorldServer
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_381]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_381]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) ~[h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:861) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:800) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:672) ~[MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_381]
Caused by: java.lang.ClassCastException: com.creativemd.creativecore.common.world.SubWorldServer cannot be cast to net.minecraft.world.WorldServer
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:486) ~[awu$a.class:?]
        at com.creativemd.creativecore.common.world.NeighborUpdateCollector.processPosition(NeighborUpdateCollector.java:45) ~[NeighborUpdateCollector.class:?]
        at com.creativemd.littletiles.common.world.LittleNeighborUpdateCollector.processPosition(LittleNeighborUpdateCollector.java:46) ~[LittleNeighborUpdateCollector.class:?]
        at com.creativemd.creativecore.common.world.NeighborUpdateCollector.process(NeighborUpdateCollector.java:54) ~[NeighborUpdateCollector.class:?]
        at com.creativemd.littletiles.common.util.place.Placement.placeTiles(Placement.java:247) ~[Placement.class:?]
        at com.creativemd.littletiles.common.util.place.Placement.place(Placement.java:198) ~[Placement.class:?]
        at com.creativemd.littletiles.common.util.place.Placement.tryPlace(Placement.java:209) ~[Placement.class:?]
        at com.creativemd.littletiles.common.structure.type.door.LittleDoorBase.place(LittleDoorBase.java:209) ~[LittleDoorBase.class:?]
        at com.creativemd.littletiles.common.structure.type.door.LittleDoorBase.openDoor(LittleDoorBase.java:270) ~[LittleDoorBase.class:?]
        at com.creativemd.littletiles.common.structure.type.door.LittleDoor.activate(LittleDoor.java:103) ~[LittleDoor.class:?]
        at com.creativemd.littletiles.common.packet.LittleActivateDoorPacket.executeServer(LittleActivateDoorPacket.java:65) ~[LittleActivateDoorPacket.class:?]
        at com.creativemd.creativecore.common.packet.PacketReciever$2.run(PacketReciever.java:117) ~[PacketReciever$2.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_381]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_381]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
>

**Comment by Sarocesch** [comment]
this is in the console 

When i open a custom door

**Comment by CreativeMD** [comment]
Looks like you are using magma. Unfortunately it does not really work. Use mohist instead.

**Comment by Sarocesch** [comment]
ok thanks
