### ISSUE TITLE
Crash during start up when using Rubidium (1.20.1)

### ISSUE THREAD

**Issue by DN2048** [CreativeMD/LittleTiles#912]
I added Rubidium to my mod list (so I could use shaders) but LittleTiles crashes when loading the game.

Minecraft 1.20.1
LittleTiles ALPHA_v1.6.0-pre067_mc1.20.1
Rubidium-mc 1.20.1-0.7.1
Forge 47.2.0

Crash log:

```
Time: 2023-11-14 23:17:55
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.2.0-universal.jar%23217!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:143) ~[forge-1.20.1-47.2.0-universal.jar%23217!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$4(Minecraft.java:571) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:mixin:APP:physicsmod.mixins.json:MixinMinecraft,pl:mixin:APP:physicsmod.mixins.json:cloth.MixinMinecraft,pl:mixin:APP:physicsmod.mixins.json:fabricapi.MixinMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:mixins/common/nochatreports.mixins.json:client.MixinMinecraft,pl:mixin:APP:rubidium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:worldeditcui.mixins.json:MinecraftAccess,pl:mixin:APP:worldeditcui.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:azurelib.mixins.json:MinecraftMixin,pl:mixin:APP:carryon.mixins.json:MinecraftMixin,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:421) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?] {re:classloading,re:mixin}
	at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:564) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:mixin:APP:physicsmod.mixins.json:MixinMinecraft,pl:mixin:APP:physicsmod.mixins.json:cloth.MixinMinecraft,pl:mixin:APP:physicsmod.mixins.json:fabricapi.MixinMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:mixins/common/nochatreports.mixins.json:client.MixinMinecraft,pl:mixin:APP:rubidium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:worldeditcui.mixins.json:MinecraftAccess,pl:mixin:APP:worldeditcui.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:azurelib.mixins.json:MinecraftMixin,pl:mixin:APP:carryon.mixins.json:MinecraftMixin,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ForgeLoadingOverlay.m_88315_(ForgeLoadingOverlay.java:146) ~[forge-1.20.1-47.2.0-universal.jar%23217!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:954) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:mixin:APP:physicsmod.mixins.json:MixinMinecraft,pl:mixin:APP:physicsmod.mixins.json:cloth.MixinMinecraft,pl:mixin:APP:physicsmod.mixins.json:fabricapi.MixinMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:mixins/common/nochatreports.mixins.json:client.MixinMinecraft,pl:mixin:APP:rubidium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:worldeditcui.mixins.json:MinecraftAccess,pl:mixin:APP:worldeditcui.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:azurelib.mixins.json:MinecraftMixin,pl:mixin:APP:carryon.mixins.json:MinecraftMixin,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:mixin:APP:physicsmod.mixins.json:MixinMinecraft,pl:mixin:APP:physicsmod.mixins.json:cloth.MixinMinecraft,pl:mixin:APP:physicsmod.mixins.json:fabricapi.MixinMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:mixins/common/nochatreports.mixins.json:client.MixinMinecraft,pl:mixin:APP:rubidium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:worldeditcui.mixins.json:MinecraftAccess,pl:mixin:APP:worldeditcui.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:azurelib.mixins.json:MinecraftMixin,pl:mixin:APP:carryon.mixins.json:MinecraftMixin,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:physicsmod.mixins.json:MixinMain,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) ~[?:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) ~[?:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[?:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {}
-- MOD littletiles --
Details:
	Mod File: /X/.minecraft/mods/LittleTiles_ALPHA_v1.6.0-pre067_mc1.20.1.jar
	Failure message: LittleTiles (littletiles) encountered an error during the sided_setup event phase
		java.lang.IncompatibleClassChangeError: class team.creative.littletiles.client.mod.rubidium.level.LittleWorldSlice cannot inherit from final class me.jellysquid.mods.sodium.client.world.WorldSlice
	Mod Version: 1.6.0-pre067
	Mod Issue URL: https://github.com/CreativeMD/LittleTiles/issues
	Exception message: java.lang.IncompatibleClassChangeError: class team.creative.littletiles.client.mod.rubidium.level.LittleWorldSlice cannot inherit from final class me.jellysquid.mods.sodium.client.world.WorldSlice
Stacktrace:
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {}
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:119) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at team.creative.littletiles.client.mod.rubidium.pipeline.LittleRenderPipelineTypeRubidium.<init>(LittleRenderPipelineTypeRubidium.java:8) ~[LittleTiles_ALPHA_v1.6.0-pre067_mc1.20.1.jar%23189!/:1.6.0-pre067] {re:classloading}
	at team.creative.littletiles.client.mod.rubidium.RubidiumInteractor.<clinit>(RubidiumInteractor.java:8) ~[LittleTiles_ALPHA_v1.6.0-pre067_mc1.20.1.jar%23189!/:1.6.0-pre067] {re:classloading}
	at team.creative.littletiles.client.mod.rubidium.RubidiumManager.init(RubidiumManager.java:24) ~[LittleTiles_ALPHA_v1.6.0-pre067_mc1.20.1.jar%23189!/:1.6.0-pre067] {re:classloading}
	at team.creative.littletiles.client.LittleTilesClient.setup(LittleTilesClient.java:245) ~[LittleTiles_ALPHA_v1.6.0-pre067_mc1.20.1.jar%23189!/:1.6.0-pre067] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%23109!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%23109!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23109!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23109!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.20.1-47.2.0.jar%23214!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:124) ~[fmlcore-1.20.1-47.2.0.jar%23213!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.6, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 516872872 bytes (492 MiB) / 1853882368 bytes (1768 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i7-12700K
	Identifier: Intel64 Family 6 Model 151 Stepping 2
	Microarchitecture: Alder Lake
	Frequency (GHz): 3.61
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 20
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2504
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3667
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 5.60
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 5.60
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 46373.54
	Virtual memory used (MB): 24232.98
	Swap memory total (MB): 13824.00
	Swap memory used (MB): 139.54
	JVM Flags: 21 total; -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx8192m
	Loaded Shaderpack: (off)
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |ENQUEUE_IM|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		SmartBrainLib-neoforge-1.20.1-1.12.jar            |SmartBrainLib                 |smartbrainlib                 |1.12                |ENQUEUE_IM|Manifest: NOSIGNATURE
		FarmersDelight-1.20.1-1.2.3.jar                   |Farmer's Delight              |farmersdelight                |1.20.1-1.2.3        |ENQUEUE_IM|Manifest: NOSIGNATURE
		LittleFrames_FORGE_v1.3.2_mc1.20.1.jar            |LittleFrames                  |littleframes                  |1.3.2               |ENQUEUE_IM|Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.20.1-17.0.8.jar   |EnchantmentDescriptions       |enchdesc                      |17.0.8              |ENQUEUE_IM|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		TerraBlender-forge-1.20.1-3.0.0.169.jar           |TerraBlender                  |terrablender                  |3.0.0.169           |ENQUEUE_IM|Manifest: NOSIGNATURE
		physics-mod-3.0.9-mc-1.20.1-forge.jar             |Physics Mod                   |physicsmod                    |3.0.9               |ENQUEUE_IM|Manifest: NOSIGNATURE
		mcdoom-neoforge-1.20-6.0.6.jar                    |MCDoom                        |doom                          |6.0.6               |ENQUEUE_IM|Manifest: NOSIGNATURE
		ImmersiveEngineering-1.20.1-10.0.0-169.jar        |Immersive Engineering         |immersiveengineering          |1.20.1-10.0.0-169   |ENQUEUE_IM|Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		customportalapi-0.0.1-forge-1.20.jar              |Custom Portal Api [Forge]     |customportalapi               |0.0.1-beta1-1.20    |ENQUEUE_IM|Manifest: NOSIGNATURE
		BiomesOPlenty-1.20.1-18.0.0.598.jar               |Biomes O' Plenty              |biomesoplenty                 |18.0.0.598          |ENQUEUE_IM|Manifest: NOSIGNATURE
		NoChatReports-FORGE-1.20.1-v2.2.2.jar             |No Chat Reports               |nochatreports                 |1.20.1-v2.2.2       |ENQUEUE_IM|Manifest: NOSIGNATURE
		watermedia-2.0.8.jar                              |WaterMedia                    |watermedia                    |2.0.8               |ENQUEUE_IM|Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.11.6_mc1.20.1.jar           |CreativeCore                  |creativecore                  |2.11.6              |ENQUEUE_IM|Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.2.0.27.jar                    |Just Enough Items             |jei                           |15.2.0.27           |ENQUEUE_IM|Manifest: NOSIGNATURE
		giacomos_hud_conf-1.20.1-1.0.2.jar                |Giacomo's HUD Overlays Configu|giacomos_hud_conf             |1.0.2               |ENQUEUE_IM|Manifest: NOSIGNATURE
		domum_ornamentum-1.20-1.0.138-BETA-universal.jar  |Domum Ornamentum              |domum_ornamentum              |1.20-1.0.138-BETA   |ENQUEUE_IM|Manifest: NOSIGNATURE
		Satako-7.0.14-1.20.1.jar                          |Satako                        |satako                        |7.0.14-1.20.1       |ENQUEUE_IM|Manifest: NOSIGNATURE
		car-1.20.1-1.0.8.jar                              |Ultimate Car Mod              |car                           |1.20.1-1.0.8        |ENQUEUE_IM|Manifest: NOSIGNATURE
		rubidium-mc1.20.1-0.7.1.jar                       |Rubidium                      |rubidium                      |0.7.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		curios-forge-5.3.5+1.20.1.jar                     |Curios API                    |curios                        |5.3.5+1.20.1        |ENQUEUE_IM|Manifest: NOSIGNATURE
		blockui-1.20.1-0.0.94-ALPHA.jar                   |UI Library Mod                |blockui                       |1.20.1-0.0.94-ALPHA |ENQUEUE_IM|Manifest: NOSIGNATURE
		Xaeros_Minimap_23.8.2_Forge_1.20.jar              |Xaero's Minimap               |xaerominimap                  |23.8.2              |ENQUEUE_IM|Manifest: NOSIGNATURE
		oculus-mc1.20.1-1.6.9.jar                         |Oculus                        |oculus                        |1.6.9               |ENQUEUE_IM|Manifest: NOSIGNATURE
		giacomos_speedometer-1.20.1-1.0.8-neoforge.jar    |Giacomos Speedometer Mod      |giacomos_speedometer          |1.0.8               |ENQUEUE_IM|Manifest: NOSIGNATURE
		XaerosWorldMap_1.34.1_Forge_1.20.jar              |Xaero's World Map             |xaeroworldmap                 |1.34.1              |ENQUEUE_IM|Manifest: NOSIGNATURE
		SereneSeasons-1.20.1-9.0.0.46.jar                 |Serene Seasons                |sereneseasons                 |9.0.0.46            |ENQUEUE_IM|Manifest: NOSIGNATURE
		mixinextras-forge-0.2.0-beta.6.jar                |MixinExtras                   |mixinextras                   |0.2.0-beta.6        |ENQUEUE_IM|Manifest: NOSIGNATURE
		structurize-1.20.1-1.0.653-BETA.jar               |Structurize                   |structurize                   |1.20.1-1.0.653-BETA |ENQUEUE_IM|Manifest: NOSIGNATURE
		multipiston-1.20-1.2.31-ALPHA.jar                 |Multi-Piston                  |multipiston                   |1.20-1.2.31-ALPHA   |ENQUEUE_IM|Manifest: NOSIGNATURE
		Shrink-1.20.1-1.4.4.jar                           |Shrink                        |shrink                        |1.4.4               |ENQUEUE_IM|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.20.1-20.0.5.jar                 |Bookshelf                     |bookshelf                     |20.0.5              |ENQUEUE_IM|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		WorldEditCUI-1.20+01.jar                          |WorldEditCUI                  |worldeditcui                  |1.20+01             |ENQUEUE_IM|Manifest: NOSIGNATURE
		worldedit-mod-7.2.15.jar                          |WorldEdit                     |worldedit                     |7.2.15+6463-5ca4dff |ENQUEUE_IM|Manifest: NOSIGNATURE
		minecolonies-1.20.1-1.1.240-RELEASE.jar           |MineColonies                  |minecolonies                  |1.20.1-1.1.240-RELEA|ENQUEUE_IM|Manifest: NOSIGNATURE
		architectury-9.1.12-forge.jar                     |Architectury                  |architectury                  |9.1.12              |ENQUEUE_IM|Manifest: NOSIGNATURE
		minecraft-comes-alive-7.5.8+1.20.1-universal.jar  |Minecraft Comes Alive         |mca                           |7.5.8+1.20.1        |ENQUEUE_IM|Manifest: NOSIGNATURE
		K-Turrets-3.0.10-1.20.1.jar                       |K-Turrets                     |k_turrets                     |3.0.10-1.20.1       |ENQUEUE_IM|Manifest: NOSIGNATURE
		carryon-forge-1.20.1-2.1.2.5.jar                  |Carry On                      |carryon                       |2.1.2.5             |ENQUEUE_IM|Manifest: NOSIGNATURE
		azurelib-forge-1.20.1-1.0.33.jar                  |AzureLib                      |azurelib                      |1.0.33              |ENQUEUE_IM|Manifest: NOSIGNATURE
		rubidium_extras-1.20.1_v1.4.3.jar                 |Rubidium Extras               |rubidium_extras               |1.20.1_v1.4.3       |ENQUEUE_IM|Manifest: NOSIGNATURE
		player_companions_1.20.1-6.7.0.jar                |Player Companions             |player_companions             |6.7.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		forge-1.20.1-47.2.0-universal.jar                 |Forge                         |forge                         |47.2.0              |ENQUEUE_IM|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		ServerTabInfo-1.20-1.3.8.jar                      |Server Tab Info               |servertabinfo                 |1.3.8               |ENQUEUE_IM|Manifest: NOSIGNATURE
		LittleTiles_ALPHA_v1.6.0-pre067_mc1.20.1.jar      |LittleTiles                   |littletiles                   |1.6.0-pre067        |ERROR     |Manifest: NOSIGNATURE
	Crash Report UUID: 57b11965-5319-4121-b1a0-66544e2a9ad3
	FML: 47.2
	Forge: net.minecraftforge:47.2.0
```

**Comment by CreativeMD** [comment]
Use Embeddium instead.
