### ISSUE TITLE
java.lang.NoSuchFieldError when placing in stencil mode on dedicated servers

### ISSUE THREAD

**Issue by shBLOCK** [CreativeMD/LittleTiles#925]
This only happens on dedicated servers.
Here it's trying to access a client-only field on server:
https://github.com/CreativeMD/LittleTiles/blob/2f60dd4ce6f7bc5e2c1c5d5f16005f5d71a53c1e/src/main/java/team/creative/littletiles/common/action/LittleActionPlace.java#L31-L32
https://github.com/CreativeMD/LittleTiles/blob/2f60dd4ce6f7bc5e2c1c5d5f16005f5d71a53c1e/src/main/java/team/creative/littletiles/common/action/LittleActionPlace.java#L150

```
[Server thread/ERROR] [creativecore/]: Executing a packet ran into an exception
java.lang.NoSuchFieldError: destroyed
        at team.creative.littletiles.common.action.LittleActionPlace.placeTile(LittleActionPlace.java:150) ~[LittleTiles_ALPHA_v1.6.0-pre080_mc1.20.1.jar%23950!/:1.6.0-pre080] {re:classloading,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A}
        at team.creative.littletiles.common.action.LittleActionPlace.action(LittleActionPlace.java:83) ~[LittleTiles_ALPHA_v1.6.0-pre080_mc1.20.1.jar%23950!/:1.6.0-pre080] {re:classloading,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A}
        at team.creative.littletiles.common.action.LittleActionPlace.action(LittleActionPlace.java:25) ~[LittleTiles_ALPHA_v1.6.0-pre080_mc1.20.1.jar%23950!/:1.6.0-pre080] {re:classloading,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A}
        at team.creative.littletiles.common.action.LittleAction.executeServer(LittleAction.java:108) ~[LittleTiles_ALPHA_v1.6.0-pre080_mc1.20.1.jar%23950!/:1.6.0-pre080] {re:classloading,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A}
        at team.creative.creativecore.common.network.CreativePacket.execute(CreativePacket.java:14) ~[CreativeCore_FORGE_v2.11.17_mc1.20.1.jar%23789!/:2.11.17] {re:classloading,pl:rei_plugin_compatibilities:B}
        at team.creative.creativecore.common.network.CreativeNetwork.lambda$registerType$4(CreativeNetwork.java:56) ~[CreativeCore_FORGE_v2.11.17_mc1.20.1.jar%23789!/:2.11.17] {re:classloading,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A}
```

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue!
