### ISSUE TITLE
GuiBag calling server method on client?

### ISSUE THREAD

**Issue by shBLOCK** [CreativeMD/LittleTiles#927]
`GuiBag` seems to be calling a server-only sync method? Very strange...
The call site:
https://github.com/CreativeMD/LittleTiles/blob/1.20/src/main/java/team/creative/littletiles/common/gui/tool/GuiBag.java#L50C20-L50C20
The method:
https://github.com/CreativeMD/CreativeCore/blob/1.20/src/main/java/team/creative/creativecore/common/util/inventory/ContainerSlotView.java#L55-L59

Error message:
```
[19:14:28] [Render thread/ERROR] [creativecore/]: Executing a packet ran into an exception
java.lang.ClassCastException: class net.minecraft.client.player.LocalPlayer cannot be cast to class net.minecraft.server.level.ServerPlayer (net.minecraft.client.player.LocalPlayer and net.minecraft.server.level.ServerPlayer are in module minecraft@1.20.1 of loader 'TRANSFORMER' @2387e60b)
	at team.creative.creativecore.common.util.inventory.ContainerSlotView.changed(ContainerSlotView.java:58) ~[CreativeCore_FORGE_v2.11.17_mc1.20.1.jar%23853!/:2.11.17] {re:classloading,pl:rei_plugin_compatibilities:B}
	at team.creative.littletiles.common.gui.tool.GuiBag.lambda$new$0(GuiBag.java:50) ~[LittleTiles_ALPHA_v1.6.0-pre080_mc1.20.1.jar%231016!/:1.6.0-pre080] {re:classloading,pl:rei_plugin_compatibilities:B}
	at team.creative.creativecore.common.gui.sync.GuiSyncLocal.receive(GuiSyncLocal.java:22) ~[CreativeCore_FORGE_v2.11.17_mc1.20.1.jar%23853!/:2.11.17] {re:classloading,pl:rei_plugin_compatibilities:B}
	at team.creative.creativecore.common.gui.sync.GuiSyncLocal.receive(GuiSyncLocal.java:11) ~[CreativeCore_FORGE_v2.11.17_mc1.20.1.jar%23853!/:2.11.17] {re:classloading,pl:rei_plugin_compatibilities:B}
	at team.creative.creativecore.common.gui.packet.ControlSyncPacket.execute(ControlSyncPacket.java:32) ~[CreativeCore_FORGE_v2.11.17_mc1.20.1.jar%23853!/:2.11.17] {re:classloading,pl:rei_plugin_compatibilities:B}
	at team.creative.creativecore.common.gui.packet.LayerPacket.executeClient(LayerPacket.java:16) ~[CreativeCore_FORGE_v2.11.17_mc1.20.1.jar%23853!/:2.11.17] {re:classloading,pl:rei_plugin_compatibilities:B}
	at team.creative.creativecore.common.network.CreativePacket.execute(CreativePacket.java:12) ~[CreativeCore_FORGE_v2.11.17_mc1.20.1.jar%23853!/:2.11.17] {re:classloading,pl:rei_plugin_compatibilities:B}
	at team.creative.creativecore.common.network.CreativeNetwork.lambda$registerType$4(CreativeNetwork.java:56) ~[CreativeCore_FORGE_v2.11.17_mc1.20.1.jar%23853!/:2.11.17] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:67) ~[client-1.20.1-20230612.114412-srg.jar%231282!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%231282!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%231282!/:?] {re:mixin,re:computing_frames,pl:rei_plugin_compatibilities:B,re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%231282!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.20.1-20230612.114412-srg.jar%231282!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106) ~[client-1.20.1-20230612.114412-srg.jar%231282!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%231282!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:APP:smoothboot.mixins.json:client.MainMixin,pl:mixin:APP:notenoughcrashes.forge.mixins.json:client.MixinMain,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.16.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.16.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.16.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:66) ~[?:?] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[?:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[?:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[?:?] {}
```

**Comment by CreativeMD** [comment]
Fixed in the newest version. Update CreativeCore and LittleTiles. Thanks for your detailed bug report, made it really easy for me to fix it!
