### ISSUE TITLE
Render error with little tiles

### ISSUE THREAD

**Issue by Tollainmear** [CreativeMD/LittleTiles#929]
Minecraft Forge: 47.2.17
creativeCore: v2.11.18
littletile: v1.6.0-pre083

Hi, I'm not sure what happened, the reason why I noticed this problem is that I got killed when no monster displayed around me, so I open my log file and found a tons of error message mentioning `LittleTilesClient.ANIMATION_HANDLER is null`.

the key error message I paste below, and the full log file was uploaded at the end of issue.
```
[061月2024 04:25:04.197] [Render thread/ERROR] [net.minecraft.util.thread.BlockableEventLoop/FATAL]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "team.creative.littletiles.client.level.LittleAnimationHandlerClient.pollEntityInTransition(net.minecraft.network.protocol.game.ClientboundAddEntityPacket)" because "team.creative.littletiles.client.LittleTilesClient.ANIMATION_HANDLER" is null
	at net.minecraft.client.multiplayer.ClientPacketListener.handler$fnj000$handleAddEntity(ClientPacketListener.java:11547) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_6771_(ClientPacketListener.java:447) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.network.protocol.game.ClientboundAddEntityPacket.m_5797_(ClientboundAddEntityPacket.java:99) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.network.protocol.game.ClientboundAddEntityPacket.m_5797_(ClientboundAddEntityPacket.java:15) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_264308_(ClientPacketListener.java:2305) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.network.protocol.game.ClientboundBundlePacket.m_5797_(ClientboundBundlePacket.java:13) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.network.protocol.game.ClientboundBundlePacket.m_5797_(ClientboundBundlePacket.java:6) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[Karoglan-TFC-Create.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.17.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.17.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.17.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) ~[?:?]
[061月2024 04:25:04.198] [Render thread/ERROR] [net.minecraft.util.thread.BlockableEventLoop/FATAL]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "team.creative.littletiles.client.level.LittleAnimationHandlerClient.pollEntityInTransition(net.minecraft.network.protocol.game.ClientboundAddEntityPacket)" because "team.creative.littletiles.client.LittleTilesClient.ANIMATION_HANDLER" is null
	at net.minecraft.client.multiplayer.ClientPacketListener.handler$fnj000$handleAddEntity(ClientPacketListener.java:11547) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_6771_(ClientPacketListener.java:447) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.network.protocol.game.ClientboundAddEntityPacket.m_5797_(ClientboundAddEntityPacket.java:99) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.network.protocol.game.ClientboundAddEntityPacket.m_5797_(ClientboundAddEntityPacket.java:15) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_264308_(ClientPacketListener.java:2305) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.network.protocol.game.ClientboundBundlePacket.m_5797_(ClientboundBundlePacket.java:13) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.network.protocol.game.ClientboundBundlePacket.m_5797_(ClientboundBundlePacket.java:6) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[Karoglan-TFC-Create.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.17.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.17.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.17.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) ~[?:?]
[061月2024 04:25:04.298] [Render thread/ERROR] [net.minecraft.util.thread.BlockableEventLoop/FATAL]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "team.creative.littletiles.client.level.LittleAnimationHandlerClient.pollEntityInTransition(net.minecraft.network.protocol.game.ClientboundAddEntityPacket)" because "team.creative.littletiles.client.LittleTilesClient.ANIMATION_HANDLER" is null
	at net.minecraft.client.multiplayer.ClientPacketListener.handler$fnj000$handleAddEntity(ClientPacketListener.java:11547) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_6771_(ClientPacketListener.java:447) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.network.protocol.game.ClientboundAddEntityPacket.m_5797_(ClientboundAddEntityPacket.java:99) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.network.protocol.game.ClientboundAddEntityPacket.m_5797_(ClientboundAddEntityPacket.java:15) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_264308_(ClientPacketListener.java:2305) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.network.protocol.game.ClientboundBundlePacket.m_5797_(ClientboundBundlePacket.java:13) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.network.protocol.game.ClientboundBundlePacket.m_5797_(ClientboundBundlePacket.java:6) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[Karoglan-TFC-Create.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.17.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.17.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.17.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) ~[?:?]
```

[latest.log](https://github.com/CreativeMD/LittleTiles/files/13846294/latest.log)

**Comment by Tollainmear** [comment]
Hi, I found that the same problem also orrcured with pre082, after throughing nether portal or acrossing any dimension, but I'm not sure is this a problem with littletile or a compability problem with other mod.

**Comment by Xplodin** [comment]
I was afraid invisible monsters had something to do with whatever mods do rendering stuff..
Dang. I hope this gets fixed! :)

**Comment by Tollainmear** [comment]
> I was afraid invisible monsters had something to do with whatever mods do rendering stuff.. Dang. I hope this gets fixed! :)

yeah, I think this [issue](https://github.com/CreativeMD/LittleTiles/issues/928) is point to the same problem

**Comment by Xplodin** [comment]
Do you have embeddium installed too?
I think this is a mix of both mods

**Comment by Tollainmear** [comment]
> Do you have embeddium installed too? I think this is a mix of both mods

yep, and I also installed several embeddium addons.

Here is the full mod list:
```
[Puzzles Lib/]: Loading 305 mods:
	- achiopt 1.0.2
	- additionalplacements 1.7.6
	- adfinders 9.1.1.0
	- advancementplaques 1.5.1
	- ae2 15.0.18
	- ae2additions 5.0.4
	- ae2things 1.2.1
	- aeinfinitybooster 1.20.1-1.0.0+21
	- amplifiednether 1.2.4
	- apexcore 10.0.0
	- apotheosis 7.2.0
	- apothiccurios 1.0.3
	- architectury 9.1.12
	- argentinas_delight 1.3
	- artifacts 9.2.0
	- astikorcarts 1.1.7
	- attributefix 21.0.4
	- attributeslib 1.2.1
	- azurelib 2.0.18
	- balancedflight 1.20.1_v2.2.0
	- balm 7.2.1
	- barrels_2012 2.1
	- bcc 4.0.8
	- bellsandwhistles 0.4.3-1.20.x
	- betterchunkloading 1.20.1-2.5
	- bettercombat 1.8.1+1.20.1
	- betterendisland 1.20-Forge-2.0.4
	- betterf3 7.0.2
	- betterfoliage 5.0.2
	- betterfortresses 1.20-Forge-2.0.5
	- betterfpsdist 1.20.1-4.1
	- bettertags 1.20.1-1.1
	- betterthirdperson 1.9.0
	- bfendcities 1.0
	- biomesoplenty 18.0.0.598
	- blockrunner 8.0.2
	- blur 3.1.1
	- bookshelf 20.1.8
	- born_in_chaos_v1 1.0.0
	- bosses_of_mass_destruction 1.1.0
	- bwncr 3.17.0
	- bygonenether 1.3.2
	- caelus 3.1.0+1.20
	- callablehorses 1.3.0.1
	- canary 0.2.10
	- cataclysm 1.0
	- cataclysmiccombat 1.2
	- catalogue 1.8.0
	- cerbons_api 1.0.0
	- chalk 1.6.3
	- chat_heads 0.10.27
	- cherishedworlds 6.1.4+1.20.1
	- citadel 2.4.9
	- cleanview 1.20-v1
	- clienttweaks 11.1.0
	- cloth_config 11.1.118
	- clumps 11.0.0.2
	- collective 7.30
	- commonality 7.0.0
	- controlling 12.0.2
	- cosmeticarmorreworked 1.20.1-v1a
	- craftingtweaks 18.2.2
	- crashutilities 8.1.4
	- create 0.5.1.f
	- create_jetpack 4.2.0
	- create_sa 2.0.4.
	- createaddition 1.20.1-1.2.1
	- createdieselgenerators 1.20.1-1.2f
	- createeditions 1.0.1
	- createoreexcavation 1.4.2
	- createutilities 0.1.4+1.20.1
	- creativecore 2.11.18
	- culllessleaves 1.20.1-1.0.5
	- cupboard 1.20.1-2.1
	- curios 5.4.7+1.20.1
	- customskinloader 14.19.1
	- deep_dark_regrowth 1.2.4.4
	- deeperdarker 1.2.1
	- design_decor 0.1.0
	- deuf 1.20.1-1.3
	- dimtpcmd 1.19.2-0.0.1
	- doapi 1.2.8
	- drawerstooltip 8.0.0
	- dsbg 1.0-1.20.1
	- dummmmmmy 1.20-1.8.13
	- dungeons_arise 2.1.58-1.20.x
	- dungeons_enhanced 5.2.1
	- elenaidodge2 1.1
	- embeddium 0.2.16+mc1.20.1
	- embeddiumplus 1.1.0
	- emojitype 2.2.3+1.20.4
	- enchdesc 17.0.11
	- endermanoverhaul 1.0.3
	- endersdelight 1.0.3
	- endlessbiomes 1.0.0
	- ends_delight 1.0.1
	- enhancedai 2.2.0
	- enlightened_end 5.0.14
	- entity_model_features 1.2.1
	- entity_texture_features 5.1.2
	- entityculling 1.6.2
	- epicsamurai 0.0.32-1.20.1-neo
	- equipmentcompare 1.3.7
	- euphoria_patcher 0.2.0-forge
	- everycomp 1.20-2.6.21
	- expandability 9.0.0
	- explorify 1.3.0-mc1.20
	- fallingleaves 2.1.0-beta.1
	- farmersdelight 1.20.1-1.2.3
	- farmersdelight_tfc 1.0.4
	- farsight_view 1.20.1-3.6
	- fastbench 8.0.2
	- fasterladderclimbing 0.2.10
	- fastfurnace 8.0.1
	- fastload 3.4.0
	- fastsuite 5.0.1
	- feathers 1.1
	- ferritecore 6.0.1
	- findme 3.2.0
	- firmaciv 0.1.10-alpha
	- firmalife 2.0.6-beta
	- flightlib 2.0.3
	- flywheel 0.6.10-7
	- forge 47.2.17
	- forgeendertech 11.1.0.1
	- fpsreducer 1.20-2.5
	- framedblocks 9.1.6
	- framedcompactdrawers 1.20-6.0.0
	- ftbchunks 2001.2.5
	- ftblibrary 2001.1.4
	- ftbqoptimizer 1.1.5-1.20.1
	- ftbquests 2001.3.0
	- ftbteams 2001.1.4
	- ftbxmodcompat 2.1.0
	- gamemenumodoption 2.2.1
	- gamemenuremovegfarb 2.1.2
	- geckolib 4.3.1
	- getittogetherdrops 1.3
	- getwebbed 1.0
	- globalgamerules 8.0.0.11
	- gpumemleakfix 1.20.1-1.8
	- handcrafted 3.0.5
	- hardrock_samples 1.0.0
	- highlighter 1.1.9
	- horseexpert 8.1.1
	- iceberg 1.1.18
	- immediatelyfast 1.2.8+1.20.4
	- incendium 5.3.4
	- incontrol 1.20-9.1.3
	- infernalmobs 1.20.1.1
	- infusedfoods 10.0.0
	- insanelib 1.12.1
	- inventoryhud 3.4.18
	- inventoryprofilesnext 1.10.9
	- iris 1.6.9
	- irisflw 1.20.1-0.2.0
	- irons_spellbooks 1.20.1-2.2.0
	- itemfilters 2001.1.0-build.59
	- itemphysic 1.7.0
	- itemproductionlib 1.0.0a
	- itlt 2.2.1
	- jade 11.7.1
	- jadeaddons 5.2.2
	- jecharacters 4.5.4
	- jeed 1.20-2.1.7
	- jei 15.2.0.27
	- jeresources 1.4.0.238
	- jmi 1.20.1-0.14-45
	- journeymap 5.9.18
	- jumpoverfences 1.3.1
	- keepcuriosinventory 1.20.1-0.0.1
	- kitchenkarrot 1.20.1-0.5.4
	- kleeslabs 15.0.0
	- kotlinforforge 4.8.0
	- kubejs 2001.6.4-build.114
	- kubejs_create 2001.2.5-build.2
	- kubejs_tfc 1.20.1-1.0.3
	- kubejsdelight 1.1.1
	- libipn 4.0.1
	- libx 1.20.1-5.0.12
	- lightmanscurrency 1.20.1-2.2.0.0g
	- littletiles 1.6.0-pre083
	- lootbeams 1.20.1
	- lootjs 1.20.1-2.10.4
	- lootr 0.7.29.68
	- mafglib 0.1.3-mc1.20.1
	- maxhealthfix 12.0.2
	- mcwbridges 2.1.1
	- mcwfences 1.0.7
	- memoryleakfix 1.1.2
	- memorysettings 1.20.1-5.4
	- memorysweep 1.0.0
	- mes 1.3-1.20-forge
	- minecraft 1.20.1
	- minemention 1.20.1-3.0.1
	- mixinextras 0.2.0
	- mixinsquared 0.1.1
	- modelfix 1.14
	- moderately_enough_effect_desc 1.0.0
	- modernfix 5.11.1+mc1.20.1
	- modernui 3.9.0.4
	- moonlight 1.20-2.8.79
	- mousetweaks 2.25
	- mr_irradium_begone 1.1.0
	- multimine 1.20.1.3
	- mutil 6.1.1
	- nbt_ac 1.1.7
	- nckey 1.0.0
	- nebs 0.0NONE
	- nerb 0.3
	- neruina 1.3.0
	- nethersdelight 1.20.1-4.0
	- nethervinery 2.0.2
	- notenoughcrashes 4.4.6+1.20.1
	- nourished_nether 0.2.5
	- nullscape 1.2.4
	- obscure_tooltips 2.2
	- observable 4.4.0
	- octolib 0.1
	- oculus 1.6.9
	- oculusparticlefix 1.0
	- parcool 1.20.1-3.1.0.6-R
	- patchouli 1.20.1-83-FORGE
	- paxi 1.20-Forge-4.0
	- pickupnotifier 8.0.0
	- pingwheel 1.7.1
	- placebo 8.6.0
	- playeranimator 1.0.2-rc1+1.20
	- playertrade 1.20.1-a
	- polylib 2000.0.3-build.97
	- probejs 5.7.0
	- progressivebosses 3.9.5-mc1.20.1
	- puzzlesaccessapi 8.0.7
	- puzzlesapi 8.1.4
	- puzzleslib 8.1.11
	- quicktakeoff 1.0.0
	- redirector 1.20.1-4.4.0
	- reeses_sodium_options 1.0.4
	- relics 0.5.2.1
	- resourcefulconfig 2.1.1
	- resourcefullib 2.1.20
	- rhino 2001.2.2-build.18
	- rubidium 0.7.1
	- rubidium_extra 0.5.3.1+mc1.20.1-build.110
	- salju_ladders 2.4.3
	- satin 1.20.1+1.15.0-SNAPSHOT
	- saturn 0.1.1
	- searchables 1.0.2
	- servertabinfo 1.3.8
	- sewingkit 1.8.0
	- shouldersurfing 1.20.1-2.8.1
	- showcaseitem 1.20.1-1.0
	- simplebackups 1.20.1-3.1.3
	- simplehats 1.20.1-0.2.2
	- simplemusket 1.3.2
	- skilltree 0.6.3a
	- skinlayers3d 1.5.4
	- smoothboot 0.0.3
	- smoothchunk 1.20.1-3.5
	- sophisticatedbackpacks 3.19.5.988
	- sophisticatedcore 0.5.113.524
	- sound_physics_remastered 1.20.1-1.3.1
	- spark 1.10.53
	- spidersproducewebs 3.2
	- stalwart_dungeons 1.2.8
	- storagedrawers 12.0.2
	- strawstatues 8.0.2
	- structure_gel 2.16.0
	- structureessentials 1.20.1-3.2
	- tabstats 1.0.5
	- terrablender 3.0.1.2
	- terraform 7.0.1
	- tetra 6.1.0
	- tetracelium 1.0.1
	- tetraextrassro 0.1.1-1.20
	- tetranomicon 1.4.4-1.20.1
	- textrues_embeddium_options 0.1.3+mc1.20.1
	- tfc 3.1.4-beta
	- tfcambiental 1.20.1-3.2.0
	- tfcastikorcarts 1.1.7.2
	- tfcvesseltooltip 1.0
	- tfmg 0.6.0e
	- tipsmod 12.0.4
	- trashslot 15.1.0
	- travelerstitles 1.20-Forge-4.0.1
	- treechop 0.18.3
	- tslatentitystatus 1.4.4
	- tweakerge 0.1.1-mc1.20.1
	- v_slab_compat 1.20-2.2
	- vinery 1.4.7
	- visuality 2.0.2
	- visualworkbench 8.0.0
	- voicechat 1.20.1-2.4.32
	- waterdripsound 0.3.2
	- waterflasks 3.0.2
	- waterframes 2.0.0-beta5.1
	- watermedia 2.0.25
	- weaponmaster_ydm 4.1.0
	- whats_that_slot 1.3.4
	- worldedit 7.2.15+6463-5ca4dff
	- worldeditcui 1.20+01
	- worldhandler 1.20.1-3.5
	- yeetusexperimentus 2.3.1-build.6+mc1.20.1
	- yungsapi 1.20-Forge-4.0.2
	- yungsmenutweaks 1.20.1-Forge-1.0.1
```

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for pointing out switching the dimension being the problem, that helped a lot to figure out what is going wrong.
