### ISSUE TITLE
crash with latest version

### ISSUE THREAD

**Issue by charliez0** [CreativeMD/LittleTiles#940]
```plain
[20:14:13] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "me.jellysquid.mods.sodium.client.gl.shader.GlProgram.getInterface()" because the return value of "net.coderbot.iris.compat.sodium.impl.shader_overrides.ShaderChunkRendererExt.iris$getOverride()" is null
	at team.creative.littletiles.client.mod.oculus.OculusInteractor.getShader(OculusInteractor.java:46) ~[LittleTiles_ALPHA_v1.6.0-pre091_mc1.20.1.jar%23509!/:1.6.0-pre091]
	at me.jellysquid.mods.sodium.client.render.chunk.DefaultChunkRenderer.handler$fki000$littletiles$render(DefaultChunkRenderer.java:2082) ~[%5Bclient%5Dembeddium-0.3.1+mc1.20.1.jar%23385!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.DefaultChunkRenderer.render(DefaultChunkRenderer.java:87) ~[%5Bclient%5Dembeddium-0.3.1+mc1.20.1.jar%23385!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:277) ~[%5Bclient%5Dembeddium-0.3.1+mc1.20.1.jar%23385!/:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:246) ~[%5Bclient%5Dembeddium-0.3.1+mc1.20.1.jar%23385!/:?]
	at net.minecraft.client.renderer.LevelRenderer.m_172993_(LevelRenderer.java:8696) ~[client-1.20.1-20230612.114412-srg.jar%23590!/:?]
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1166) ~[client-1.20.1-20230612.114412-srg.jar%23590!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1126) ~[client-1.20.1-20230612.114412-srg.jar%23590!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:909) ~[client-1.20.1-20230612.114412-srg.jar%23590!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23590!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23590!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.20.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.20.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.20.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
```

**Comment by CreativeMD** [comment]
Fixed in the newest version, which should be available in a few minutes.
