### ISSUE TITLE
When you click on any animated door, it does nothing and displays an error in the log (1.20.1)

### ISSUE THREAD

**Issue by 151chit** [CreativeMD/LittleTiles#966]
[latest.log](https://github.com/CreativeMD/LittleTiles/files/15021013/latest.log)
[debug.log](https://github.com/CreativeMD/LittleTiles/files/15021018/debug.log)
When I click on the animated door I get the error 

Cannot assign field "currentPrimedTnt" because "this.spigotConfig" is null

Most likely this is due to the use of the Mohist server core, because there is no spigot on the forge kernel, but is it possible to somehow fix this without replacing the server kernel with another one?

However this works great in single player

**Comment by CreativeMD** [comment]
Does this issue still occur? Sorry for not responding earlier.

**Comment by SynteticX** [comment]
Yes, still occur

**Comment by CreativeMD** [comment]
@SynteticX can you send a log file or crash-report of it?

**Comment by 151chit** [comment]
[latest.log](https://github.com/user-attachments/files/17450310/latest.log)
This still happens on the latest versions of forge, mohist, littletiles and creativeCore. It only happens on the server, and when the server is on the mohist core, when it receives a network packet about opening the little tiles door, some method is executed with the this.spigotConfig field which is null:
[15:51:54] [Server thread/ERROR] [net.minecraft.network.protocol.PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket@31717212, suppressing error
java.lang.NullPointerException: Cannot assign field "currentPrimedTnt" because "this.spigotConfig" is null
at net.minecraft.world.level.Level.m_46463_(Level.java:649) ~[server-1.20.1-20230612.114412-srg.jar%23202!/:?] at team.creative.littletiles.common.entity.animation.LittleAnimationLevel.initialTick(LittleAnimationLevel.java:260) ~[LittleTiles_BETA_v1.6.0-pre131_mc1.2 0.1.jar%23200!/:1.6.0-pre131]

**Comment by 151chit** [comment]
![animTick](https://github.com/user-attachments/assets/1f6e6163-aaeb-4906-b272-74ecacbb2aa7)
![level](https://github.com/user-attachments/assets/8e89acc4-dfcf-486d-b82c-68bef4c0f445)

**Comment by AiharaYuriko** [comment]
Same problem, with the latest versions of forge(47.3.12), mohist(1.20.1-906), littletiles(1.6.0-pre135) and creativeCore(2.12.22).
Here is the log [log.txt](https://github.com/user-attachments/files/17840640/log.txt)

The server and client won't crash, but animated door is also not working

**Comment by CreativeMD** [comment]
Has anyone reported this issue to mohist? Might be easy to fix for them if they check if spigotConfig is null.

**Comment by AiharaYuriko** [comment]
> Has anyone reported this issue to mohist? Might be easy to fix for them if they check if spigotConfig is null.

I've reported the issue to mohist author few days ago, but there's no reply for now. Is this problem can only be fixed by mohist? It would be great if you can do something about it.

**Comment by AiharaYuriko** [comment]
> > Has anyone reported this issue to mohist? Might be easy to fix for them if they check if spigotConfig is null.
> 
> I've reported the issue to mohist author few days ago, but there's no reply for now. Is this problem can only be fixed by mohist? It would be great if you can do something about it.

Now someone from the comment found a way to fix this problem, here's the link of my issue:
https://github.com/MohistMC/Mohist/issues/3451
And here's the link how he fix it:
https://github.com/MohistMC/Mohist/pull/3461/commits/f01cad0c0937775924953776b92e4f32e9e5f320

And this is his comment: "LittleTiles' inheritance of Level is an unreasonable way of writing (if only accessing Level, why inherit?). A fix has been found, but it is still recommended that the development team change the method of using Level." (machine translation)
I don't know how to code, maybe there's something to do to improve this mod?

**Comment by CreativeMD** [comment]
Glad it is fixed now. Unfortunately there is no way to change it.
