### ISSUE TITLE
Little tiles crashes minecraft when I open custom doors?

### ISSUE THREAD

**Issue by porky231** [CreativeMD/LittleTiles#992]
It works just fine if I use 2 block sized doors, but when i do like a block taller it freaks out and crashes!
Maybe my laptop can't handle it, i'm not sure haha

I'm using 1.20.1!

Here's the crash report.
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2024-07-10 03:12:22
Description: Unexpected error

java.nio.BufferOverflowException: null
	at java.nio.ByteBuffer.put(ByteBuffer.java:1007) ~[?:?] {re:mixin}
	at team.creative.littletiles.client.mod.rubidium.buffer.RenderedBufferRubidium.upload(RenderedBufferRubidium.java:37) ~[LittleTiles_BETA_v1.6.0-pre109_mc1.20.1.jar%23185!/:1.6.0-pre109] {re:classloading}
	at team.creative.littletiles.client.render.cache.buffer.BufferHolder.upload(BufferHolder.java:64) ~[LittleTiles_BETA_v1.6.0-pre109_mc1.20.1.jar%23185!/:1.6.0-pre109] {re:classloading}
	at team.creative.littletiles.client.mod.rubidium.buffer.RubidiumBufferCache.upload(RubidiumBufferCache.java:191) ~[LittleTiles_BETA_v1.6.0-pre109_mc1.20.1.jar%23185!/:1.6.0-pre109] {re:classloading}
	at team.creative.littletiles.client.mod.rubidium.buffer.RenderedBufferRubidium.<init>(RenderedBufferRubidium.java:26) ~[LittleTiles_BETA_v1.6.0-pre109_mc1.20.1.jar%23185!/:1.6.0-pre109] {re:classloading}
	at team.creative.littletiles.client.mod.rubidium.entity.LittleAnimationRenderManagerRubidium$RebuildTask.compile(LittleAnimationRenderManagerRubidium.java:215) ~[LittleTiles_BETA_v1.6.0-pre109_mc1.20.1.jar%23185!/:1.6.0-pre109] {re:classloading}
	at team.creative.littletiles.client.mod.rubidium.entity.LittleAnimationRenderManagerRubidium.compileChunks(LittleAnimationRenderManagerRubidium.java:80) ~[LittleTiles_BETA_v1.6.0-pre109_mc1.20.1.jar%23185!/:1.6.0-pre109] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at team.creative.littletiles.client.level.LittleAnimationHandlerClient.compileChunks(LittleAnimationHandlerClient.java:329) ~[LittleTiles_BETA_v1.6.0-pre109_mc1.20.1.jar%23185!/:1.6.0-pre109] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.handler$zll000$compileChunks(LevelRenderer.java:6637) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddium.mixins.json:features.render.world.clouds.WorldRendererMixin,pl:mixin:APP:littletiles.mixins.json:client.render.LevelRendererAccessor,pl:mixin:APP:scena.mixins.json:client.LevelRendererBeforeDebugRenderingHookMixin,pl:mixin:APP:embeddium.mixins.json:features.options.weather.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.render.gui.outlines.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.render.world.sky.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:core.render.world.WorldRendererMixin,pl:mixin:APP:littletiles.mixins.json:client.render.LevelRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_194370_(LevelRenderer.java:2112) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddium.mixins.json:features.render.world.clouds.WorldRendererMixin,pl:mixin:APP:littletiles.mixins.json:client.render.LevelRendererAccessor,pl:mixin:APP:scena.mixins.json:client.LevelRendererBeforeDebugRenderingHookMixin,pl:mixin:APP:embeddium.mixins.json:features.options.weather.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.render.gui.outlines.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.render.world.sky.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:core.render.world.WorldRendererMixin,pl:mixin:APP:littletiles.mixins.json:client.render.LevelRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1164) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddium.mixins.json:features.render.world.clouds.WorldRendererMixin,pl:mixin:APP:littletiles.mixins.json:client.render.LevelRendererAccessor,pl:mixin:APP:scena.mixins.json:client.LevelRendererBeforeDebugRenderingHookMixin,pl:mixin:APP:embeddium.mixins.json:features.options.weather.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.render.gui.outlines.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.render.world.sky.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:core.render.world.WorldRendererMixin,pl:mixin:APP:littletiles.mixins.json:client.render.LevelRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1126) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fastload.mixins.json:client.GameRendererMixin,pl:mixin:APP:exposure-common.mixins.json:DrawViewfinderOverlayMixin,pl:mixin:APP:littletiles.mixins.json:client.render.GameRendererAccessor,pl:mixin:APP:littletiles.mixins.json:client.render.GameRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:909) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fastload.mixins.json:client.GameRendererMixin,pl:mixin:APP:exposure-common.mixins.json:DrawViewfinderOverlayMixin,pl:mixin:APP:littletiles.mixins.json:client.render.GameRendererAccessor,pl:mixin:APP:littletiles.mixins.json:client.render.GameRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.2.23.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.23.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.23.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.23.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod: 
	LittleTiles (littletiles), Version: 1.6.0-pre109
		Issue tracker URL: https://github.com/CreativeMD/LittleTiles/issues
		at TRANSFORMER/littletiles@1.6.0-pre109/team.creative.littletiles.client.mod.rubidium.buffer.RenderedBufferRubidium.upload(RenderedBufferRubidium.java:37)
Stacktrace:
	at java.nio.ByteBuffer.put(ByteBuffer.java:1007) ~[?:?] {re:mixin}
	at team.creative.littletiles.client.mod.rubidium.buffer.RenderedBufferRubidium.upload(RenderedBufferRubidium.java:37) ~[LittleTiles_BETA_v1.6.0-pre109_mc1.20.1.jar%23185!/:1.6.0-pre109] {re:classloading}
	at team.creative.littletiles.client.render.cache.buffer.BufferHolder.upload(BufferHolder.java:64) ~[LittleTiles_BETA_v1.6.0-pre109_mc1.20.1.jar%23185!/:1.6.0-pre109] {re:classloading}
	at team.creative.littletiles.client.mod.rubidium.buffer.RubidiumBufferCache.upload(RubidiumBufferCache.java:191) ~[LittleTiles_BETA_v1.6.0-pre109_mc1.20.1.jar%23185!/:1.6.0-pre109] {re:classloading}
	at team.creative.littletiles.client.mod.rubidium.buffer.RenderedBufferRubidium.<init>(RenderedBufferRubidium.java:26) ~[LittleTiles_BETA_v1.6.0-pre109_mc1.20.1.jar%23185!/:1.6.0-pre109] {re:classloading}
	at team.creative.littletiles.client.mod.rubidium.entity.LittleAnimationRenderManagerRubidium$RebuildTask.compile(LittleAnimationRenderManagerRubidium.java:215) ~[LittleTiles_BETA_v1.6.0-pre109_mc1.20.1.jar%23185!/:1.6.0-pre109] {re:classloading}
	at team.creative.littletiles.client.mod.rubidium.entity.LittleAnimationRenderManagerRubidium.compileChunks(LittleAnimationRenderManagerRubidium.java:80) ~[LittleTiles_BETA_v1.6.0-pre109_mc1.20.1.jar%23185!/:1.6.0-pre109] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at team.creative.littletiles.client.level.LittleAnimationHandlerClient.compileChunks(LittleAnimationHandlerClient.java:329) ~[LittleTiles_BETA_v1.6.0-pre109_mc1.20.1.jar%23185!/:1.6.0-pre109] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.handler$zll000$compileChunks(LevelRenderer.java:6637) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddium.mixins.json:features.render.world.clouds.WorldRendererMixin,pl:mixin:APP:littletiles.mixins.json:client.render.LevelRendererAccessor,pl:mixin:APP:scena.mixins.json:client.LevelRendererBeforeDebugRenderingHookMixin,pl:mixin:APP:embeddium.mixins.json:features.options.weather.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.render.gui.outlines.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.render.world.sky.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:core.render.world.WorldRendererMixin,pl:mixin:APP:littletiles.mixins.json:client.render.LevelRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_194370_(LevelRenderer.java:2112) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddium.mixins.json:features.render.world.clouds.WorldRendererMixin,pl:mixin:APP:littletiles.mixins.json:client.render.LevelRendererAccessor,pl:mixin:APP:scena.mixins.json:client.LevelRendererBeforeDebugRenderingHookMixin,pl:mixin:APP:embeddium.mixins.json:features.options.weather.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.render.gui.outlines.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.render.world.sky.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:core.render.world.WorldRendererMixin,pl:mixin:APP:littletiles.mixins.json:client.render.LevelRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1164) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddium.mixins.json:features.render.world.clouds.WorldRendererMixin,pl:mixin:APP:littletiles.mixins.json:client.render.LevelRendererAccessor,pl:mixin:APP:scena.mixins.json:client.LevelRendererBeforeDebugRenderingHookMixin,pl:mixin:APP:embeddium.mixins.json:features.options.weather.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.render.gui.outlines.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.render.world.sky.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:core.render.world.WorldRendererMixin,pl:mixin:APP:littletiles.mixins.json:client.render.LevelRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1126) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fastload.mixins.json:client.GameRendererMixin,pl:mixin:APP:exposure-common.mixins.json:DrawViewfinderOverlayMixin,pl:mixin:APP:littletiles.mixins.json:client.render.GameRendererAccessor,pl:mixin:APP:littletiles.mixins.json:client.render.GameRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['porkyfriedrice'/13, l='ClientLevel', x=18.25, y=31.00, z=44.14]]
	Chunk stats: 121, 45
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,33,109), Section: (at 8,1,13 in 0,2,6; chunk contains blocks 0,-64,96 to 15,319,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 724486 game time, 9444 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:455) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddium.mixins.json:features.render.world.ClientLevelMixin,pl:mixin:APP:littletiles.mixins.json:client.level.ClientLevelMixin,pl:mixin:APP:embeddium.mixins.json:core.world.biome.ClientWorldMixin,pl:mixin:APP:embeddium.mixins.json:core.world.map.ClientWorldMixin,pl:mixin:APP:embeddium.mixins.json:features.render.world.sky.ClientWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2319) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:740) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.2.23.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.23.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.23.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.23.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, mod_resources, file/Better Leaves Add-on V3.0-1.20.zip, file/Borderless Glass V1.0.1 (1.20-1.20.1).zip

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1321808344 bytes (1260 MiB) / 2936012800 bytes (2800 MiB) up to 4175429632 bytes (3982 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: 13th Gen Intel(R) Core(TM) i7-1355U
	Identifier: Intel64 Family 6 Model 186 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 2.61
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 12
	Graphics card #0 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 128.00
	Graphics card #0 deviceId: 0xa7a1
	Graphics card #0 versionInfo: DriverVersion=31.0.101.5449
	Memory slot #0 capacity (MB): 2048.00
	Memory slot #0 clockSpeed (GHz): 4.27
	Memory slot #0 type: LPDDR4
	Memory slot #1 capacity (MB): 2048.00
	Memory slot #1 clockSpeed (GHz): 4.27
	Memory slot #1 type: LPDDR4
	Memory slot #2 capacity (MB): 2048.00
	Memory slot #2 clockSpeed (GHz): 4.27
	Memory slot #2 type: LPDDR4
	Memory slot #3 capacity (MB): 2048.00
	Memory slot #3 clockSpeed (GHz): 4.27
	Memory slot #3 type: LPDDR4
	Memory slot #4 capacity (MB): 2048.00
	Memory slot #4 clockSpeed (GHz): 4.27
	Memory slot #4 type: LPDDR4
	Memory slot #5 capacity (MB): 2048.00
	Memory slot #5 clockSpeed (GHz): 4.27
	Memory slot #5 type: LPDDR4
	Memory slot #6 capacity (MB): 2048.00
	Memory slot #6 clockSpeed (GHz): 4.27
	Memory slot #6 type: LPDDR4
	Memory slot #7 capacity (MB): 2048.00
	Memory slot #7 clockSpeed (GHz): 4.27
	Memory slot #7 type: LPDDR4
	Virtual memory max (MB): 22071.78
	Virtual memory used (MB): 16888.50
	Swap memory total (MB): 6144.00
	Swap memory used (MB): 380.48
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=125
	Launched Version: 1.20.1-forge-47.2.23
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: Intel(R) Iris(R) Xe Graphics GL version 4.6.0 - Build 31.0.101.5449, Intel
	Window size: 1920x1200
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources, file/Better Leaves Add-on V3.0-1.20.zip, file/Borderless Glass V1.0.1 (1.20-1.20.1).zip
	Current Language: en_us
	CPU: 12x 13th Gen Intel(R) Core(TM) i7-1355U
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['porkyfriedrice'/13, l='ServerLevel[PACOVILLE - Map]', x=18.25, y=31.00, z=44.14]]
	Data Packs: vanilla, mod:forge, mod:scena (incompatible), mod:chiselsandbits (incompatible), mod:easy_npc, mod:mixinextras (incompatible), mod:fastload, mod:itemzoom, mod:worldedit (incompatible), mod:ferritecore (incompatible), mod:memoryleakfix (incompatible), mod:exposure, mod:modernfix (incompatible), mod:jei, mod:moa_decor_science, mod:moa_decor_garden_, mod:trafficcraft, mod:moa_decor_cookery, mod:moa_decor_bath, mod:moa_decor_art, mod:moa_decor_electronics, mod:embeddium, mod:creativecore, mod:littletiles
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.2.23.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.23.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.2.23.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.2.23.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.23.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		easy_npc-forge-1.20.1-5.1.0.jar                   |Easy NPC                      |easy_npc                      |5.1.0               |DONE      |Manifest: NOSIGNATURE
		Fastload-Reforged-mc1.20.1-3.4.0.jar              |Fastload-Reforged             |fastload                      |3.4.0               |DONE      |Manifest: NOSIGNATURE
		MOAdecor GARDEN 1.20.1.jar                        |MOA DECOR: GARDEN             |moa_decor_garden_             |1.20.1              |DONE      |Manifest: NOSIGNATURE
		scena-forge-1.0.103.jar                           |Scena                         |scena                         |1.0.103             |DONE      |Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.11.31_mc1.20.1.jar          |CreativeCore                  |creativecore                  |2.11.31             |DONE      |Manifest: NOSIGNATURE
		MOAdecor COOKERY 1.20.2.jar                       |MOA DECOR: COOKERY            |moa_decor_cookery             |1.20.1              |DONE      |Manifest: NOSIGNATURE
		modernfix-forge-5.18.6+mc1.20.1.jar               |ModernFix                     |modernfix                     |5.18.6+mc1.20.1     |DONE      |Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.3.0.8.jar                     |Just Enough Items             |jei                           |15.3.0.8            |DONE      |Manifest: NOSIGNATURE
		mixinextras-forge-0.3.5.jar                       |MixinExtras                   |mixinextras                   |0.3.5               |DONE      |Manifest: NOSIGNATURE
		MOAdecor SCIENCE 1.20.1.jar                       |MOA DECOR: SCIENCE            |moa_decor_science             |1.20.1              |DONE      |Manifest: NOSIGNATURE
		itemzoom-1.20.1-2.9.0.jar                         |Item Zoom                     |itemzoom                      |2.9.0               |DONE      |Manifest: NOSIGNATURE
		worldedit-mod-7.2.15.jar                          |WorldEdit                     |worldedit                     |7.2.15+6463-5ca4dff |DONE      |Manifest: NOSIGNATURE
		ferritecore-6.0.1-forge.jar                       |Ferrite Core                  |ferritecore                   |6.0.1               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		trafficcraft-1.0.4-1.20.1.jar                     |TrafficCraft                  |trafficcraft                  |1.0.4-1.20.1        |DONE      |Manifest: NOSIGNATURE
		memoryleakfix-forge-1.17+-1.1.5.jar               |Memory Leak Fix               |memoryleakfix                 |1.1.5               |DONE      |Manifest: NOSIGNATURE
		exposure-1.20.1-1.7.2-forge.jar                   |Exposure                      |exposure                      |1.7.2               |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.2.23-universal.jar                |Forge                         |forge                         |47.2.23             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		MOAdecor BATH 1.20.1.jar                          |MOA DECOR: BATH               |moa_decor_bath                |1.20.1              |DONE      |Manifest: NOSIGNATURE
		MOAdecor ART 1.20.1.jar                           |MOA DECOR: ART                |moa_decor_art                 |1.20.1              |DONE      |Manifest: NOSIGNATURE
		MOAdecor ELECTRONICS 1.20.1.A.jar                 |MOA: ELECTRONICS              |moa_decor_electronics         |1.20.1.             |DONE      |Manifest: NOSIGNATURE
		chisels-and-bits-forge-1.4.148.jar                |chisels-and-bits              |chiselsandbits                |1.4.148             |DONE      |Manifest: NOSIGNATURE
		embeddium-0.3.24+mc1.20.1.jar                     |Embeddium                     |embeddium                     |0.3.24+mc1.20.1     |DONE      |Manifest: NOSIGNATURE
		LittleTiles_BETA_v1.6.0-pre109_mc1.20.1.jar       |LittleTiles                   |littletiles                   |1.6.0-pre109        |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: c051cee4-f32f-49d7-b272-0b03f164c6e3
	FML: 47.2
	Forge: net.minecraftforge:47.2.23

**Comment by CreativeMD** [comment]
Newest version fixes it. Thanks for reporting this issue!
